- src/buffer_ops/buffer_ops.h
- src/client/pmix_client.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
This error was noticed when running with
```export OMPI_MCA_opal_pmix_base_async_modex=1```
In this case it is possible that dmdx requests will arrive before the data is available. This means that the following codepath was enabled:
https://github.com/pmix/releases/blob/v1.1/src/server/pmix_server_ops.c#L187:L213
The error occurs because data was free()'d twice, here:
https://github.com/pmix/releases/blob/v1.1/src/server/pmix_server_ops.c#L200
and here:
https://github.com/pmix/releases/blob/v1.1/src/server/pmix_server_ops.c#L207.
> Fix double-free error in pmix_server_commit.

- src/server/pmix_server.c
If not found, then don't pass any topology info down to the client as it won't know how to unpack it anyway.
Fixes #20
> Provide a check for hwloc support

- config/pmix.m4
Build out of top of source dir uses not actual config.h file
in case src/include/ folder has config.h created during a previous
build at the same place as source.
> config: Fix wrong usage of config.h

- include/pmix/pmix_common.h
- src/buffer_ops/copy.c
- src/buffer_ops/pack.c
- src/buffer_ops/print.c
- src/buffer_ops/unpack.c
Add a "required" flag to the pmix_info_t structure so users can indicate that a specific info_t is required vs optional. We need atomicity at the individual key level, and making both "reqd" and "optional" versions of every key isn't really practical.
> Add a "required" flag to the pmix_info_t structure

- test/pmix_client.c
We need this in case we test direct modex: if some process will
exit before others will request it's blob we will get an error.
Application developer is responsible for keeping all processes
running until all the data is retrieved from it. Here we achieve
this using PMIx_Fence.
> Put the barrier at the end of the pmix_client.c test.

- examples/client.c
- examples/dmodex.c
- include/pmix/pmix_common.h
- include/private/hash_string.h
- src/buffer_ops/buffer_ops.h
- src/buffer_ops/internal.h
- src/class/pmix_list.h
- src/class/pmix_object.h
- src/include/pmix_globals.h
- src/server/pmix_server.c
- src/server/pmix_server_ops.h
- src/usock/usock.h
- src/util/error.h
- test/test_fence.c
Remove extra semicolon from the end of do/while loops throughout
code, fix whitespace before and after the while keyword.
Fix an example which was not correctly providing a semicolon.
Signed-off-by: Ashley Pittman <ashley.m.pittman@intel.com>
> Correct use of do/while loops to consume semicolon.

- src/client/pmix_client.c
The reference counting was broken which led PMIx_Finalize
to release resources early. This fixes the "use after free" scenarios
that I encountered.
> Increment the reference count in PMIx_Init

- include/pmix.h
- include/pmix/pmix_common.h
- src/buffer_ops/copy.c
- src/buffer_ops/unpack.c
- src/client/pmix_client_get.c
C++ mandates that we provide a name to each struct - i.e., it doesn't like:
typedef struct {
...
} foo_t;
Instead, it requires:
typedef struct foo {
...
} foo_t;
So make it happy and let C++ apps use PMIx
> Fix C++ usage of PMIx

- src/server/pmix_server.c
- src/server/pmix_server_listener.c
If the tmpdir name is too long, then return an error so the host RM can know we couldn't setup the rendezvous point. Also, minor cleanup of some debug output
@artpol84 Can you please take a look? I think I captured everything from Rainer's original PR
> Backport the relevant changes from OMPI

- src/client/pmi1.c
- test/utils.c
Several PMI1 functions returned success without setting their parameter when `PMIx_Get()` failed.  Fix the logic in those functions to return the (PMI1-converted) error code of `PMIx_Get()` when it fails.  Also define PMIX_JOB_SIZE and PMIX_APPNUM in the `pmix_test` namespace so the `pmi_client` test no longer fails as reported in #83.
Note: `PMI2_Init()` returns PMIX_UNIV_SIZE for its `size` parameter.  Perhaps `PMI1_Get_size()` should use that instead of PMIX_JOB_SIZE?  I wasn't too sure about that one so I left it as is.
> Return sensible errors from PMI1 when RM registers incomplete namespace

- include/pmix/pmix_common.h
- src/sec/pmix_munge.c
- src/sec/pmix_native.c
- src/sec/pmix_sec.c
- src/server/pmix_server.c
- src/server/pmix_server_listener.c
- src/server/pmix_server_ops.h
- test/Makefile.am
- test/pmix_client_otheruser.sh
- test/pmix_test.c
This PR changes the way that the "native" security module works, as proposed in #91.  Instead of checking a client-supplied credential against the uid/gid registered by the server, send a NULL credential and validate a `struct ucred` from SO_PEERCRED against the uid/gid registered by the server.
This also closes a vulnerability where a client could bypass a security module's `validate_cred` method by sending a NULL cred.
Finally,  munge is removed from the list of security modules, since only UNIX domain socket connections are supported by PMIx presently, and it adds latency to the synchronous connect handshake of clients without improving security over SO_PEERCRED.
Testing:
* The fact that the "native" module no longer has a `create_cred` method means the client sends an empty cred; so …
> security: validate connections with SO_PEERCRED + misc fixes

- include/pmix/pmix_common.h
pmix cannot be built on alpine linux because of some missing includes.
uid_t and gid_t are defined in unistd.h or sys/types.h, and unistd.h
is not indirectly pulled under alpine linux, so do it manually.
Thanks N.L.K Nguyen for the report
> add missing include files

- config/pmix.m4
Define additional integral variants of major and minor components
of PMIX_VERSION. This provides ability to use integral preprocessing
expressions like the following:
```C
#ifndef PMIX_VERSION_MAJOR
#define PMIX_VERSION_MAJOR 1L
#endif
#if (PMIX_VERSION_MAJOR > 1L)
...
#endif
```
> pmix/version: integral components

- include/pmix/pmix_common.h
- src/client/pmix_client.c
- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
The object will be returned in one of the info structures (in fact, it is the last info struct in the array, though that is not a requirement).
Fixes #120
> Provide a key by which users can register a callback object to be returned whenever the registered event handler is invoked

- src/client/pmix_client.c
In case the buffer unpack failed, we have a hang in [waiting status](https://github.com/pmix/master/blob/d8def6b020dd392ed937962dcc6f4d2eb6fdb2c1/src/client/pmix_client.c#L419).
> Fix buffer unpack hang

- include/pmix_common.h
- src/buffer_ops/copy.c
- src/buffer_ops/pack.c
- src/buffer_ops/print.c
- src/buffer_ops/unpack.c
- src/client/pmix_client_get.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Convert the larger objects in pmix_value_t to pointers to those objects, thus reducing the overall size of pmix_value_t to roughly 8 bytes.
Refs #129
> First pass on reducing memory footprint

- src/dstore/pmix_esh.c
- src/dstore/pmix_esh.h
Recent dstore code causes a bus error on sparc64 because sparc64 needs 64-bit alignment when accessing 64-bit value but elements in dstore initial segments and data segments are not (necessarily) aligned.
Could someone review? I ran a simple MPI program to confirm the fix.
For initial segments, I changed the type of `full` to `size_t` from `int`. Another solution is to use `PMIX_ALIGN`. If you prefer `PMIX_ALIGN`, I'll update this PR.
> Fix dstore bus error on sparc64

- config/pmix.m4
- configure.ac
- src/mca/pdl/configure.m4
the LT_* macros do overwrite the enable_dlopen variable,
so it must be tested and saved before invoking LT_INIT.
delay the invokation of the LT_* macros and use the
PMIX_ENABLE_DLOPEN_SUPPORT variable to figure out whether
--disable-dlopen was invoked
> configury: correctly handle --disable-dlopen

- src/server/pmix_server_ops.c
and get PMIx build on OpenBSD 6.0
initially from open-mpi/ompi@5479c6cca703ec743102af7c5b87aab90ff42ce7
> server/pmix_server_ops: add a missing #include

- src/client/pmix_client.c
pmix_progress_thread_finalize() invokes libevent event_base_free,
so all libevent stuff cannot be used after.
Hence, pmix_client_globals.myserver must be PMIX_DESTRUCT'ed
before invoking pmix_progress_thread_finalize()
> client: fix PMIx_Finalize() sequence

- src/dstore/pmix_dstore.c
- src/dstore/pmix_dstore.h
- src/dstore/pmix_esh.c
- src/dstore/pmix_esh.h
- src/server/pmix_server.c
Fixed the problem introduced in https://github.com/open-mpi/ompi/issues/1998. 
- DSTOR rework for use support multiple nspaces
- Added use of dynamically extending arrays of nspaces
> Fix dstore nspace

- src/dstore/pmix_esh.c
Fixed problem discovered with `loop_spawn` test in PR #141
> pmix/dstore: fix the extention of the initial segment

- src/dstore/pmix_esh.c
When added new sm segment the counter was not reset. It was
cause of error in logic operations on data elements in a segment
with incorrect counter. This fix is resets the counter of elements
for new segment.
> dstore: fix the extention of the initial segment

- examples/dynamic.c
- test/utils.c
- MAXHOSTNAMELEN is defined in <netdb.h> on Solaris
- stdout cannot be assigned, so use freopen instead
> misc fixes to get pmix build on Solaris

- src/dstore/pmix_esh.c
So it'll be consistent with pmix_common.h
> dstore: fix PMIX_DSTPATH info-key type

- src/client/pmix_client.c
pmix_progress_thread_init() is already (indirectly) invoked
(by pmix_rte_init()) so there is no need to call it again
> client: invoke pmix_progress_thread_init() once

- config/pmix.m4
* This commit enables the shared memory datastore by default
- This makes it match the `master` branch
* No clear commit to pick from `master` so manually applied change.
> pmix/config: Enable dstore by default

- src/client/pmix_client_get.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
This is a re-organization and rebase of the previous pull request for get changes:
Support a client (likely a tool) to call PMIx_Get on a namespace other than
its own and in particular:
1) call PMIx_Get on a namespace that is not located locally
2) call PMIx_Get on either a specific rank or PMIX_RANK_WILDCARD
In the later case, we expect job_info data to be collected
To fully support this, the RM code for dmodex get has to be able
to handle the case where we request a rank PMIX_RANK_WILDCARD and
has to know to figure out which host to send that request to to
get the job_info data.
> Daves new get changes 

- src/server/pmix_server.c
Fixed the pmix build fail with `--dstore-enable` which introduced after the commit 333efe5.
@rhc54 please review
> dstore: fixed pmix build fails with dstore

- src/server/pmix_server_ops.c
Force local data to deposit directly to the dstore at PMIx_Commit.
Before this patch local keys wasn't published in the dstore causing
first access to local key to go through a long path by sending a
message to server and asking to publish the data.
This was causing performance issues.
> dstore: Fix PMIx_Commit

- src/client/pmix_client.c
- src/client/pmix_client_connect.c
- src/client/pmix_client_get.c
- src/client/pmix_client_ops.h
- src/client/pmix_client_spawn.c
- src/common/Makefile.include
- src/common/pmix_jobdata.c
- src/dstore/pmix_esh.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/include/pmix_jobdata.h
- src/server/pmix_server.c
Reduction of memory usage on pmix-client's side by to not duplicate
the job data for each client's:
- Job info will not be sent to clients when connecting to the server.
- The server will provide the job information into `dstore`.
- The client will use the `dstore` for access to job info.
Fixes #144
> dstore: keeping job info in the dstor

- src/client/pmix_client_get.c
> Silence an error log - it is perfectly okay for a key not to be found

- src/client/pmix_client_get.c
- src/dstore/pmix_esh.c
Currently in dstor the key names are stored in the arrays of 512 bytes.
This causes memory loss because real key names usually less
than 16 bytes.This commit reduces the memory footprint by using
only requested amount memory size to store the key name.
Beside memory footprint, the key access performance was also
significantly improved on PPC (Power8).
Average amount of L1-dcache-load-misses was decreased by 30%,
amount of LLC-load-misses was decreased by 59%.
> dstor: reduce storage space for the key name

- src/include/Makefile.am
> Add missing header to Makefile.am so it is included in the tarball

- include/pmix_common.h
- src/client/pmix_client.c
- src/client/pmix_client_get.c
- src/event/pmix_event_registration.c
Add some memory profiling attributes. Do not "put" keys that start with "pmix" as that will overwrite data provided by the RM.
> Fix a couple of minor bugs in the event registration process. 

- .gitignore
- config/pmix_check_psm2.m4
- config/pmix_check_withdir.m4
- examples/Makefile.am
- examples/server.c
- include/pmix_common.h
- include/pmix_server.h
- src/mca/pnet/Makefile.am
- src/mca/pnet/base/Makefile.include
- src/mca/pnet/base/base.h
- src/mca/pnet/base/pnet_base_fns.c
- src/mca/pnet/base/pnet_base_frame.c
- src/mca/pnet/base/pnet_base_select.c
- src/mca/pnet/opa/Makefile.am
- src/mca/pnet/opa/configure.m4
- src/mca/pnet/opa/pnet_opa.c
- src/mca/pnet/opa/pnet_opa.h
- src/mca/pnet/opa/pnet_opa_component.c
- src/mca/pnet/pnet.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/util/Makefile.include
- src/util/alfg.c
- src/util/alfg.h
Add a new network support framework so that the RM can:
* precondition an application (e.g., adding a security token to the app's environment)
* setup the local network driver to support an application (e.g., for "instant on" address resolution)
* pass directives in the environment of client procs prior to forking
* cleanup after each child terminates
* cleanup after all local children for a given application have terminated
> Add network support APIs

- src/buffer_ops/internal.h
- src/buffer_ops/internal_functions.c
- src/buffer_ops/open_close.c
Thanks to @hjelmn for the contribution!
> Backport changes from OMPI scaling tests to improve performance by reducing the number of realloc operations.

- src/dstore/pmix_esh.c
Data corruption was observed when a key was stored second time (forcing
data overwrite). In case of overwrite, the old record is invalidated
with "INVALIDATED" string written into its key name field. The problem
was observed when space insufficient for storing "INVALIDATED" string
was reserved for the key name field at the original key submission.
The fix provides minor refactoring of the dtore record formats to
flexibly address this issue.
(cherry picked from commit f6808239e91f4308eb93d9e0562f00d234e81c12)
Conflicts:
src/dstore/pmix_esh.c
> dstore: Fixed dstor bug case of key overwrite.

- src/common/pmix_jobdata.c
Accidentally loop that was submitting jobinfo data was duplicated
in two nested functions. As the result computational complexity
rised from O(n) to O(n^2) which caused significant performance
hit at 8k node level (thanks to @hjelmn for noticing and doing
initial analysis!)
This bug wasn't visible at dstore data level because if for the key
being replaced the size of the data was the same - key was simply
rewritten.
> dstore: Fix significant performance degradation.

- config/pmix.m4
- src/sm/pmix_mmap.c
if the filesystem is full, both ftruncate() and mmap() success, but
a crash occurs when accessing the mmap'ed memory.
unlike ftruncate(), posix_fallocate() does fail when the filesystem
is full
> sm: use posix_fallocate() before mmap'ing it

- test/Makefile.am
- test/pmix_client.c
- test/test_common.c
- test/test_common.h
- test/test_fence.c
- test/test_internal.c
- test/test_internal.h
- test/test_replace.c
- test/test_replace.h
- test/utils.c
- Add the key replacement test.
The option to activate test of replacement: `./pmix_test --test-replace`
- Add the key internal store test: `./pmix_test --test-internal`
> pmix/test: add key replacement and internal store

- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
use a local variable name different than the one passed into the function
> Cleanup a typo that can cause a segfault

- config/Makefile.am
- config/pmix.m4
- config/pmix_check_lock.m4
- src/dstore/pmix_esh.c
- src/dstore/pmix_esh.h
Added alternative locking by `pthread` with use shared memory region
for the lock. The code path of old locking by `flock` has been saved
for evaluate performance against locking by `pthread` and other purposes.
To change the locking type needs to enable the code paths by macro:
```C  
#define PTHREAD_LOCK_ENABLE  1
#define FCNTL_LOCK_ENABLE    1
```
In priority uses the locking by `pthread`
Thanks to @artpol84 for this proof of concept.
- The  results of locking by `pthread` here: https://github.com/pmix/master/pull/260#issuecomment-273945190
- Code base of concept: https://github.com/artpol84/poc/tree/master/benchmarks/shmem_locking
> dstore: Added locking by pthread.

- src/util/compress.c
It's possible that we can have `zlib.h` but still not have zlib support.  Use the correct macro to protect the usage of calling zlib functions.
> pmix: fix zlib protection macro usage

- src/client/pmi1.c
- src/client/pmi2.c
- src/dstore/pmix_esh.c
With set of changes I was able to can run [MPICH 3.2](http://www.mpich.org/static/downloads/3.2/mpich-3.2.tar.gz) with SLURM 16.05 (branch from github + the fix with "volatile" as in Issue #279 ).
> Set of fixes targeting restoration of PMI1/PMI2 support

- config/pmix_check_lock.m4
* Typo in the variable check prevents the check for the pthread locking mechanism.
> config: Fix pthread locking variable

- src/dstore/pmix_esh.c
- src/dstore/pmix_esh.h
This PR changes the access rights to locking in case when PMIx server
was started as root user and clients from normal user.
> dstore: Fix access rights for pthread-based locking

- src/dstore/pmix_esh.c
rinfo may point to the shared memory region or be allocated using
malloc. Release it only if it was malloc'ed.
This needs refactoring to make rinfo always point to the shared
memory ares. This will be done after v1.2.1 release.
(cherry picked from commit b2b5373901cb9561683045cc3d461aa380f1bf45)
> dstore: Fix illegal memory free

- src/mca/ptl/tcp/ptl_tcp_component.c
> Make tcp be the default transport

- src/server/pmix_server.c
- src/server/pmix_server_ops.c
> Cleanup an error path that Coverity identified as dereferencing a NULL pointer

- config/pmix.m4
- include/Makefile.am
Fix configure logic to install the primary API headers when we are not in embedded mode, or when the user has configured us --with-devel-headers. Update the tests/examples configure option so it doesn't build those by default unless the primary API headers have been installed, and errors out if someone explicitly asks for the tests and/or examples but the primary headers are not being installed as the tests and examples will fail without those.
> Fix configure logic

- src/server/pmix_server.c
> Provide a user-friendly error message when the usock path length is too long

- src/client/pmix_client.c
- src/runtime/pmix_finalize.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/tool/pmix_tool.c
> Fix a race condition resulting in segfault during PMIx finalize by stopping the PMIx progress thread prior to tearing down any infrastructure

- src/client/pmix_client.c
- src/runtime/pmix_finalize.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Instead of completely free'ing the event base, pause the PMIx progress thread before tearing down the infrastructure, and then release the event base at the end of the procedure. This allows any infrastructure objects holding events to delete them prior to free'ing the event base.
> Cleanup shutdown

- config/pmix_check_compiler_version.m4
> Backport minor config change from master: remove stale file reference that cases the compiler check to always fail

- src/client/pmix_client_get.c
> Silence Coverity warning - the cb pointer cannot be NULL or else things would have failed from the very beginning.

- config/pmix_check_package.m4
- src/mca/ptl/base/ptl_base_frame.c
Thanks Paul Hargrove for bringing this to our attention
Refs open-mpi/ompi#2106
> misc OpenBSD 6 related fixes

- src/class/pmix_hotel.c
- src/class/pmix_hotel.h
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/include/types.h
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/mca/ptl/ptl_types.h
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/runtime/pmix_progress_threads.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.h
- test/simple/simpclient.c
Thanks to Nathan Hjelmn for pointing them out
> Fix a number of abstraction breaks relating to the assign, add, active, and del of events.

- include/pmix/pmix_common.h
- src/sm/pmix_mmap.c
- src/sm/pmix_sm.c
- src/sm/pmix_sm.h
Thanks to Paul Hargrove for pointing this out.
> Fix some missing includes and one #ifdef that shouldn't have been included

- src/sm/pmix_mmap.c
Thanks @PHHargrove for this fix.
refs [#3117](https://github.com/open-mpi/ompi/issues/3117)
> dstore/sm: added the check `posix_fallocate` return code

- include/pmix_common.h
- include/pmix_server.h
- src/util/error.h
> Reorder server callback struct and redefine error constants to support backward compatibility

- test/test_common.c
Fixed the string size calculate error in arguments parsing of test
> pmix/test: fix mem corruption

- src/server/pmix_server_ops.c
Fix a segv that can occur if `opcbfunc` is not initialized to NULL.
Seen in the wild in a segv at the end of the `PMIx_server_deregister_nspace` callback. It looks like this has been fixed on `master` already.
> server: init opcbfunc to NULL

- src/server/pmix_server.c
- src/server/pmix_server_ops.c
> Fix dmodex - eliminate race condition where data was being released while sent

- src/server/pmix_server.c
> server: fix a typo in the PMIx_server_dmodex_request() log message

- src/Makefile.am
> Minor correction to allow libpmix to be installed in embedded scenarios when --with-devel-headers is given

- src/mca/pdl/pdlopen/configure.m4
flags. This may work on some platforms, but on at least RHEL 7.3, it
does not (i.e., compiling MPI applications fails because it can't find
dlopen).
Backported from OMPI
> With this, libs (e.g., "-ldl") are not added to the wrapper LIBS

- .gitignore
- src/buffer_ops/pack.c
- src/buffer_ops/unpack.c
- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/runtime/pmix_params.c
- src/runtime/pmix_rte.h
- test/simple/Makefile.am
- test/simple/simpdie.c
Run the lost_connection events thru an aggregator window to damp out notification "ring" when the local RM kills the procs without deregistering them first. This causes the PMIx server to see every process lose its connection, but we only want one notification from it. Set a default window size of 3 seconds, controlled by an MCA parameter "pmix_event_caching_window"
> Run the lost_connection events thru an aggregator window

- src/event/pmix_event.h
- src/runtime/pmix_params.c
- test/simple/simpdie.c
Have the window be the time between events to allow for aggregation, instead of the total size of the window.
> Adjust the event aggregation window so there is less trial-and-error.

- config/pmix_setup_cc.m4
- configure.ac
This commit removes the invocation of AC_PROG_CC in the top
level configure.ac script and moves the AC_PROG_CC_C99 call
into _PMIX_PROG_CC to ensure that AC_PROG_CC is never called
after AM_PROG_CC_C_O. This allows pmix to build with the
autotools triple (automake: 1.13.4, autoconf: 2.69, libtool:
2.4.2).
Signed-off-by: Nathan Hjelm <hjelmn@lanl.gov>
> config: make config work with older autotools

- src/event/pmix_event_notification.c
- test/simple/simpft.c
- test/simple/simptest.c
Do not rely on known location for event handler name and object, but instead search for them. There won't be that many info keys and so the search should be short.
> Fix a segfault in client notification

- src/class/pmix_pointer_array.c
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/tcp/ptl_tcp.c
Fix a segfault caused in a race condition between messages being sent and clients departing
> Update the pointer array code per changes downstream. 

- src/atomics/sys/gcc_builtin/atomic.h
- src/client/pmix_client.c
- src/client/pmix_client_connect.c
- src/client/pmix_client_get.c
- src/client/pmix_client_pub.c
- src/client/pmix_client_spawn.c
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/include/pmix_globals.h
- src/mca/psensor/file/psensor_file.c
- src/mca/psensor/heartbeat/psensor_heartbeat.c
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/mca/ptl/ptl_types.h
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/threads/threads.h
Per discussion on https://github.com/pmix/pmix/pull/384, update all cases where we threadshift to use memory fences to ensure data sync. Define new PMIX_POST_OBJECT and PMIX_ACQUIRE_OBJECT macros that (for now) contain only the atomic memory fence commands so we can later, if we choose, use them to change the threading model.
> Update all cases where we threadshift to use memory fences to ensure data sync.

- src/atomics/sys/powerpc/atomic.h
* `lwsync` is a write memory barrier.
- `eieio` is really not meant for this type of operation.
* `lwsync` can also be used for the read memory barrier according to
my reading of the of the Power 8 ISA docs (v2.07)
- https://www-01.ibm.com/marketing/iwm/iwm/web/reg/download.do?source=swg-opower&S_PKG=dl&lang=en_US&cp=UTF-8
> atomics/powerpc: Fix WMB instruction

- config/pmix_functions.m4
> configury: use 'uname -n' when 'hostname' is unavailable

- include/pmix_common.h
- src/buffer_ops/copy.c
- src/client/pmix_client_get.c
- src/server/pmix_server.c
- src/util/hash.c
- test/simple/simpclient.c
If we are looking for all the data that we "put" ourselves, then it won't be in the dstore. It will be in our own hash table, so allow us to look there. Also fix a bug in the bfrops copy routines when copying a data array - need to look at the type stored in the data array, not the type of the value object (as that is already known to be data array).
> Fix a bug in the PMIx_Get logic

- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/include/pmix_globals.h
- src/server/pmix_server_ops.h
- test/simple/loop-exec.sh
- test/simple/simpclient.c
- test/simple/simptest.c
> Fix the self-notification procedure so it properly caches notifications issued prior to registration and activates them when registration occurs

- include/pmix_common.h
- src/buffer_ops/unpack.c
Add missing support for pmix_info_t objects in pmix_data_array_t as these are typically returned from calls to PMIx_Query
This needs to go over to the 2.x branch
> Protect the PMIX_INFO_FREE macro from NULL data arrays. 

- config/pmix_setup_libevent.m4
> configury: use default libevent headers unless specified otherwise

- src/mca/gds/ds12/gds_dstore.c
- src/server/pmix_server_get.c
Address:
CID 1375987: Time of check time of use (TOCTOU)
CID 1415599: Resource leaks  (RESOURCE_LEAK)
CID 1415602: Null pointer dereferences  (FORWARD_NULL)
CID 1415601: Resource leaks  (RESOURCE_LEAK)    
CID 1415600: Uninitialized variables  (UNINIT)
Was marked as ignored:
CID 1375986: Security best practices violations (TOCTOU)
> Silence coverity

- config/pmix.m4
- config/pmix_check_lock.m4
- config/pmix_setup_zlib.m4
equality is "=", not "==". Also, remove --enable-dstore configure option as it is now a component in a framework. It is best disabled by simply setting an MCA param.
> Fix incorrect syntax in several places where "test" is used in .m4 files

- include/pmix_common.h
(cherry picked from commit c431c5900caba96524ba60c54f49a1d2fcf5644e)
> Add a few hwloc attributes

- config/pmix.m4
- config/pmix_check_lock.m4
- config/pmix_setup_zlib.m4
(cherry picked from commit aa15a87855209961cc6926f8699a7d8750eda29d)
> Fix incorrect syntax in several places where "test" is used in .m4 files - equality is "=", not "=="

- src/mca/base/pmix_mca_base_open.c
- src/util/output.c
from (https://github.com/open-mpi/ompi/pull/3775)
> Backport changes to mca base

- config/pmix.m4
- src/Makefile.am
> Accommodate the case where someone embedding PMIx code in their library needs to link libpmix against another library

- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/bfrops/base/bfrop_base_select.c
- src/mca/gds/base/gds_base_select.c
- src/mca/pdl/pdlopen/pdl_pdlopen_module.c
- src/mca/pinstalldirs/pinstalldirs.h
- src/mca/preg/base/preg_base_select.c
- src/mca/psec/base/psec_base_select.c
- src/mca/ptl/base/ptl_base_select.c
- src/runtime/help-pmix-runtime.txt
- src/runtime/pmix_init.c
Check for failure to find any usable components in frameworks that require at least one, print an informative error message, and return an error.
If the user provides us with a PMIX_INSTALL_PREFIX that points to an unusable location (either nonexistent or not available to us), or none of the default search locations exist (because the installation was moved), then provide a nice message so they know what is wrong and return an error.
> Check for incorrect install locations and no usable components

- test/Makefile.am
Now pmix utility functions like containers (lists) and opal-like OS functions
are exported to allow plugins to work. This means that tests are ok with
enabled visibility.
> Per 08/10/2017 telecon: enable test suite build when visibility is ON.

- config/pmix_check_visibility.m4
- include/pmi.h
- include/pmi2.h
- include/pmix.h
- include/pmix_common.h
- include/pmix_server.h
- include/pmix_tool.h
- src/class/pmix_object.h
- src/include/pmix_config_bottom.h
- src/mca/base/pmix_mca_base_component_repository.c
- src/util/alfg.h
- src/util/basename.h
- src/util/os_path.h
- src/util/printf.h
- src/util/show_help.h
Resolve the visibility problem by making the configury define a flag that gets used in pmix_common.h to set the attribute. Thus, use of pmix.h in an application will result in the attribute being defined to nothing, while use in building the library lets the attribute be defined to the visibility flag if the compiler supports it.
> Resolve the visibility problem

- src/client/pmix_client_fence.c
The error status is not detected for clients when server
responded with error message for Fence request.
> Fixed provide the unpacked status of fence

- test/Makefile.am
Now pmix utility functions like containers (lists) and opal-like OS functions
are exported to allow plugins to work. This means that tests are ok with
enabled visibility.
(cherry picked from commit 7d55b080230c39d06df882fad629e96e0bd21c94)
> v2.0: Per 08/10/2017 telecon: enable test suite build when visibility is ON.

- src/mca/gds/ds12/gds_dstore.c
*** CID 1416397:  Null pointer dereferences  (FORWARD_NULL)
*** CID 1416398:  Uninitialized variables  (UNINIT)
This one was noted as ignored:
*** CID 1375986:  Security best practices violations  (TOCTOU)
> Silence coverity CIDs 1416397, 1416398

- NEWS
- VERSION
> VERSION/NEWS: Prepare for v1.2.3rc1

- src/mca/ptl/tcp/ptl_tcp.c
> Correct size computation - missed one field in backport

- src/client/pmix_client.c
- src/client/pmix_client_connect.c
- src/client/pmix_client_fence.c
- src/client/pmix_client_get.c
- src/client/pmix_client_pub.c
- src/client/pmix_client_spawn.c
- src/common/pmix_control.c
- src/common/pmix_log.c
- src/common/pmix_query.c
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/include/pmix_globals.h
- src/mca/bfrops/base/bfrop_base_print.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/tool/pmix_tool.c
backwards compatibility support
> Always use the defined PMIX_COMMAND data type so we can correctly handle

- include/pmix_common.h
- src/event/pmix_event_registration.c
- src/mca/gds/ds12/gds_dstore.c
- src/mca/ptl/tcp/ptl_tcp.c
- src/tool/pmix_tool.c
This allows tools to use the internal PMIx storage for distributing data within themselves when they have alternative methods for connecting to a server, or simply want to operate in standalone mode.
> Allow tools to initialize without requiring they connect to a server.

- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/v12/bfrop_v12.c
- src/mca/bfrops/v12/unpack.c
- src/mca/bfrops/v20/Makefile.am
- src/mca/bfrops/v20/bfrop_pmix20.c
- src/mca/bfrops/v20/bfrop_pmix20.h
- src/mca/bfrops/v20/copy.c
- src/mca/bfrops/v20/internal.h
- src/mca/bfrops/v20/pack.c
- src/mca/bfrops/v20/print.c
- src/mca/bfrops/v20/unpack.c
- src/mca/gds/ds12/gds_dstore.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/server/pmix_server_get.c
This completes the basic level of cross-version support where the server is newer than the client. Still need to investigate the reverse scenario, and test the heck out of this code.
> Support v2.0 clients

- src/client/pmix_client.c
- src/mca/bfrops/v12/bfrop_v12.c
- src/mca/bfrops/v20/bfrop_pmix20.c
- src/mca/bfrops/v20/pack.c
- src/mca/gds/ds12/gds_dstore.c
- src/mca/gds/hash/gds_hash.c
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock.c
- src/server/pmix_server.c
Note that all work to-date is with dstore disabled on both sides.
> Get the reverse mode to work for v20 - i.e., let a v2.1 client connect to a v2.0 server.

- src/event/pmix_event_registration.c
- src/mca/bfrops/v12/pack.c
- src/mca/bfrops/v12/unpack.c
- src/mca/ptl/base/ptl_base_connect.c
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/mca/ptl/base/ptl_base_stubs.c
- src/mca/ptl/ptl_types.h
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/usock/ptl_usock.c
Again, dstore disabled on both sides
> Cleanup support for v2.1 client connecting to v1.2 server. 

- src/client/pmix_client.c
- src/mca/gds/base/gds_base_frame.c
- src/mca/gds/gds.h
- src/mca/ptl/tcp/ptl_tcp_component.c
> Do not lock v2.0 clients to the "hash" gds component. Add debug output

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/ds12/gds_dstore.c
- src/mca/gds/hash/gds_hash.c
This fix avoids double unpacking of the jobinfo array, which occurs in nspace register, and then when clients are connected. To provide job data to clients the local cache is used instead of unpacking data from jobinfo array. Since the jobinfo array is not needed now so it has been removed.
> jobinfo: avoid duplication of job information

- src/mca/bfrops/base/bfrop_base_fns.c
> Fix a memory corruption issue when transferring pmix_proc_t and pmix_rank_t values

- include/pmix_common.h
- src/mca/ptl/tcp/ptl_tcp.c
> Add attributes to fully support OMPI spawn options. Only retry connection if wait_to_connect param is non-zero

- src/mca/gds/ds12/gds_dstore.c
- src/server/pmix_server.c
- test/pmix_client.c
Closes #498 
PR is in progress. Don't merge. 
There are results of testing for v2.1 server with v2.0 clients:
```
/pmix/v2.1/test $ ./check.sh
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:3]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:;1:]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[0:]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[b | 0:]" -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --ns-dist 3:1 --fence "[d | 0:]" --noise [0:0,1] -e /home/user/pmix/v2.0/test/.libs/pmix_client
OK ./pmix_test -n 4 --job-fence -c -e /home/user/pmix/v2.0/test/.libs/pmix_client …
```
> Addressed the dstore compatibility between v2.1 and v.2.0

- .gitignore
- examples/Makefile.am
- examples/client2.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/bfrops/v12/pack.c
- src/mca/gds/ds12/gds_dstore.c
- src/mca/pshmem/mmap/pshmem_mmap.c
- src/server/pmix_server.c
Add an example that tests it. Cleanup a few warnings
> Implement missing support for data_array of pmix_value_t's. 

- .gitignore
- examples/Makefile.am
- examples/client2.c
- src/buffer_ops/unpack.c
Add example to test it
Thanks to Swen Boehm for reporting it.
> Provide missing implementation support for arrays of pmix_value_t's.

- src/mca/bfrops/v12/pack.c
> Oops - silence coverity warning by actually computing the size of the argv array

- src/mca/gds/ds12/gds_dstore.c
Closes https://github.com/open-mpi/ompi/issues/4296
> dstore: fixes a double destructor invoke

- VERSION
- configure.ac
- src/Makefile.am
- src/client/pmi1.c
- src/client/pmi2.c
Ensure we pass values back that are required for singleton operations
Some MPI libraries are hardcoded to look for libpmi and/or libpmi2, so if we are configured to support backward compatibility, go ahead and emit those libraries
(cherry picked from commit 08958fbb1409d9deb94b512a34f7052527673298)
> Support singleton operations under PMI-1 and PMI-2

- NEWS
Since 1.2.4 is likely/hopefully the last in that series. I thought it would be good to sync the NEWS file with master. Probably should push to this the v2.x release branch too.
bot:notest
> Sync NEWS from v1.2 series

- src/event/pmix_event_registration.c
(cherry picked from commit ac15fb23baf282718ce634cb170d0abbef7cfe7d)
> Fix event registration so OpenMP/MPI coordination sides can both get notification of model declarations

- src/mca/bfrops/v12/bfrop_v12.c
- src/mca/bfrops/v12/pack.c
- src/mca/bfrops/v12/unpack.c
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server.c
Fix errors uncovered when trying to execute OMPI v2.x apps (using PMIx v1.2) using a server from OMPI master (using PMIx v2.1). Get the packing/unpacking of pmix_info_array_t's and pmix_proc correct. Modex blobs are always provided based on the local peer since they were "fetched" locally. Avoid a segfault when a remote daemon fails to start its procs, thereby causing a collective to execute locally without any local callbacks.
> Fix errors uncovered by cross-version testing

- src/mca/base/pmix_mca_base_open.c
- src/util/output.c
Backport syslog protection from https://github.com/open-mpi/ompi/pull/4374 to support Mac High Sierra
> Backport syslog protection

- src/buffer_ops/unpack.c
- src/sec/pmix_sec.c
Fix an error uncovered when trying to execute OMPI v2.x apps (using PMIx v1.2) using a server from OMPI master (using PMIx v2.1). Note that the updated OMPI passes pmix_info_array_t values and has an additional security component not present in PMIx v1.2. Prior versions of OMPI didn't pass pmix_info_array_t values, and hence the bug in the unpacking routine wasn't exercised. Likewise, the presence of an unrecognized security component shouldn't cause the app to exit, so long as at least one common component is found
> Fix an error uncovered by cross-version tests

- include/pmi.h
- include/pmi2.h
It is possible for the test in the legacy PMI include files to get a different answer for PMIX_EXPORT when built in an embedded environment, leading to "redefined" warnings. So use the definition generated for pmix_common.h, even though we don't really need any of the rest of the definitions in there.
> Unify definition of PMIX_EXPORT

- src/mca/ptl/usock/ptl_usock.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/server/pmix_server_ops.c
Update the usock component to check for version and reject anything less than v1.2.5.
Allow usock to work with non-v1.2 clients - no reason to preclude v3 or v2.1 operations. Add compatibility handshake info to end of connection exchange so it can still work with v1.2/2.0 servers, but can do a better job with more modern ones.
> Update the usock component

- src/client/pmix_client.c
Update the client connection protocol to support cross-version operations.
Do not disturb the initial portion of the handshake used by the v1.2 series servers. Verified to work against v1.2.4.
Add the buffer type to the connection handshake
> Update client connection protocol to support cross-version ops

- src/server/pmix_server_ops.c
(cherry picked from commit 90e22e88503a27b773455a25906d5f0d0fb05da0)
> pack pointer to object (vs. pointer to pointer)

- .gitignore
- config/pmix.m4
- include/Makefile.am
- include/pmix_common.h.in
Make pmix_common.h be a generated header file so we actually take visibility into account. As things were, we ignored that directive because PMIX_HAVE_VISIBILITY wasn't defined in pmix_common.h and we don't want to include pmix_config.h in a user-facing file.
(cherry picked from commit 531a9f6ebfa62fb29fa2bd0532c66b20c4716ec5)
> Make pmix_common.h be a generated header file

- src/mca/gds/ds12/gds_dstore.c
- src/server/pmix_server_get.c
Fixed dstor compatibility issues between v1.2 and v2.x.
Fixes #563
Note: the `dstor` cannot support multi-clients case for nspace when clients in the same one nspace will be has different versions, i.e. in one nspace should be use clients v1.2 only, or v2.x only.
> dstor: addresses a dstor compatibility issues

- src/mca/gds/hash/gds_hash.c
(cherry picked from commit 3294061fe1bb7deaf24eb3ba6f1c048a7890d2e1)
> gds/hash: Fix the error handling paths for the jobinfo cache.

- src/atomics/sys/powerpc/atomic.h
* Fix typo in the `opal_atomic_wmb` declaration.
* Fix lingering `eieio` reference in the XL assembly to be `lwsync`
> ppc/asm: Fix opal_atomic_wmb definition

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- added the flag indicating the rank has invoked `commit`
- the request is moved to pending till the requested rank does not invoke `commit`
>  Fixed server-side get logic when there is no key in GDS

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- added the flag indicating the rank has invoked `commit`
- the request is moved to pending till the requested rank does not invoke `commit`
(cherry picked from commit c63b1528e9550c0c581f363c104db92eae2a4f94)
> Fixed server-side get logic when there is no key in GDS

- src/mca/psec/munge/Makefile.am
- src/mca/psec/munge/psec_munge.c
- Link psec/munge to munge library for `munge_decode` and `munge_encode`.
- Use C99 designated initializers for `pmix_psec_module_t`, just like the other modules.
> psec/munge: use munge configure.m4 vars; use C99 designated initializers

- src/mca/psec/none/psec_none.c
this is required by the PMIX_PSEC_CREATE_CRED macro,
so define a callback that simply returns PMIX_SUCCESS.
Refs pmix/pmix#620
> psec/none: add a create_cred callback

- src/mca/psec/native/psec_native.c
add missing bits from pmix/pmix@89b6251a7666d14ae60955a89ad96ddbd9b6e6d6
and fix build os OS (such as OS X) that have HAVE_GETPEEREID
> psec/native: fix usage of the socket descriptor

- src/Makefile.am
- src/client/Makefile.include
- src/runtime/Makefile.include
- src/threads/Makefile.include
- test/Makefile.am
Port the proposed patch in #617 from @pkovacs to master. It is not quite complete, however, as we shouldn't have PMI-1 or PMI-2 symbols in libpmix, nor should we have PMI-1 symbols in libpmi2 and vice versa. So fix all that and adjust the test linkages to match
> Cleanup separation of PMI-1/2 and PMIx symbols

- src/mca/psec/base/psec_base_select.c
- src/mca/psec/munge/psec_munge.c
- src/mca/psec/native/psec_native.c
- src/mca/psec/none/psec_none.c
Provide a chance for psec modules to init. Ensure that the credential byte object is always initialized, even when we return an error. Add thread protection to psec/munge module.
Fixes #620 
> Some cleanup for the psec framework

- src/Makefile.am
- src/client/Makefile.include
- src/mca/base/pmix_mca_base_var.h
- src/mca/psec/base/psec_base_select.c
- src/mca/psec/munge/Makefile.am
- src/mca/psec/munge/psec_munge.c
- src/mca/psec/none/psec_none.c
- src/runtime/Makefile.include
- src/threads/Makefile.include
- test/Makefile.am
Corrects operation of psec/munge, psec/none; provides separation of PMI/PMI2/PMIX
symbols in their respective libraries; ensures no unresolved internal symbols.
- PR #618: Cleanup separation of PMI-1/2 and PMIx symbols
- PR #619: psec/munge: use munge configure.m4 vars; use C99 designated initializers
- PR #621: psec/none: add a create_cred callback
- PR #623: Some cleanup for the psec framework
- from commit 0a5563ce3cef: src/mca/base/pmix_mca_base_var.h changes (PMIX_EXPORT)
>     v2.1 bugfix rollup

- src/Makefile.am
- src/client/Makefile.include
- src/mca/base/pmix_mca_base_var.h
- src/mca/psec/base/psec_base_select.c
- src/mca/psec/munge/Makefile.am
- src/mca/psec/munge/psec_munge.c
- src/mca/psec/none/psec_none.c
- src/runtime/Makefile.include
- src/threads/Makefile.include
- test/Makefile.am
Corrects operation of psec/munge, psec/none; provides separation of PMI/PMI2/PMIX
symbols in their respective libraries; ensures no unresolved internal symbols.
- PR #618: Cleanup separation of PMI-1/2 and PMIx symbols
- PR #619: psec/munge: use munge configure.m4 vars; use C99 designated initializers
- PR #621: psec/none: add a create_cred callback
- PR #623: Some cleanup for the psec framework
- from commit 0a5563ce3cef: src/mca/base/pmix_mca_base_var.h changes (PMIX_EXPORT)
> v2.0 bugfix rollup

- .gitignore
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- test/simple/Makefile.am
- test/simple/simptest.c
- test/simple/simptimeout.c
Check for PMIX_TIMEOUT directives in the fence, get, and connect operations. Have the local PMIx server enforce the timeout, notifying the requesting proc when timeout hits. If a proc terminates (either finalize or die) before a collective it participates in has completed, then notify all other participants as the collective will never complete.
NOTE: this still leaves a few "gaps":
* only local participants are informed of a collective failure due to a proc going away. Need to decide on a way of notifying remote participants, most likely via the event notification system
* if a proc terminates prior to the collective being defined (i.e., another participant having called it), then the server loses all knowledge that the terminating proc existed and the collective "succeeds". This -might- …
> Add support for "timeout" directives

- etc/pmix-mca-params.conf
Correct the comment in the default MCA param template - we do not support a param called "component_path". The correct syntax is "mca_base_component_path"
[skip ci]
bot:notest
> Correct the comment in the default MCA param template

- include/pmix_common.h.in
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/util/error.c
Application processes frequently need to create temporary files and directories (e.g., for shared memory backing) that need to be cleaned up upon termination. This RFC provides a mechanism by which the process can register a file or directory for post-termination cleanup by the PMIx server.
> Add registration for cleanup support (RFC0027)

- src/common/pmix_data.c
Ensure we set the buffer type when embedding user-level buffers into
PMIx internal buffers.
> Ensure the buffer type gets set

- src/tool/pmix_tool.c
of global namespaces.  We are a tool and the server didn't create our
namespace for us because they didn't know about us before we existed.  So
just create the namespace.
> In PMIx_tool_init, we can't expect to find our own namespace in the list

- src/mca/ptl/tcp/ptl_tcp.c
each connection method it is trying.
> When we connect with a tool, we don't want to see error messages about

- src/server/pmix_server_get.c
using a pointer to an array of pointers to the buffer, not a pointer
directly to the buffer.
> When we get job_info data from a remote namespace, we have to unpack it

- include/pmix_common.h.in
- src/client/pmix_client.c
- src/client/pmix_client_ops.h
- src/common/pmix_data.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/hash/gds_hash.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/tool/pmix_tool.c
Implement the changes described in RFC0028 by adding a pmix_proc_t
parameter to the PMIx_Data_pack and PMIx_Data_unpack signatures.
> Implement revised data operations APIs

- src/server/pmix_server.c
* Refs https://github.com/open-mpi/ompi/pull/4689
* Refs https://github.com/pmix/pmix/pull/657
> server_regex: correctly handle node names with multiple set of digits

- src/mca/preg/native/preg_native.c
Refs. open-mpi/ompi#4689
Refs. open-mpi/ompi#4748
> preg/native: correctly handle node names with multiple set of digits

- contrib/pmix_jenkins.sh
- src/mca/ptl/base/ptl_base_frame.c
- src/server/pmix_server_get.c
- src/tool/pmix_tool.c
- test/cli_stages.c
- test/cli_stages.h
When a process requests job-level info for a namespace unknown to the PMIx server, the server generates a dmodex request to its local host. The request specifies the target nspace, but with a WILDCARD rank since the data being requested is from the job-level info. At least one way the host can respond is to register the nspace using the PMIx server's register nspace API. However, this results in the data being "cached" in the server's GDS module, not in that of the requesting client.
I took a shot at transferring the data in pmix_server_get.c, but the buffer format created by PMIX_GDS_REGISTER_JOB_INFO doesn't match that returned in a regular dmodex request, and so this fails. Alternatively, we could have the host create a job-level dmodex response buffer and give it to us - I chose not …
> Resolve dmodex of job-level info

- config/pmix_check_package.m4
- config/pmix_setup_libevent.m4
Fix a typo that led to incorrect -L for standard locations. If using non-standard locations, then always check the given location first - before appending "/include", or "/lib", or "/lib64" as the user may have pointed us directly to the location
> Update check package

- src/mca/preg/native/preg_native.c
The object destructor tries to free the `nspace` name pointer when it not NULL:
https://github.com/pmix/pmix/blob/master/src/include/pmix_globals.c#L286-L287
But this pointer was not allocated, and instead it points to another data that
shouldn't free here.
> preg: fixed object destructor: free(): invalid pointer

- src/mca/ptl/base/ptl_base_sendrecv.c
It is needed for PMIX_REPORT_EVENT.
> ptl/base: Fix preliminary peer->info release

- src/mca/gds/ds12/gds_dstore.c
- src/mca/gds/ds12/gds_dstore.h
Use individual locks per process for clients.
Drawback: server has to lock them all now.
> dstore: Change locking scheme

- contrib/perf_tools/pmi_intra_perf.c
This ensures that service activity is not overlapped with the performance
measured region
> pmix_perf: Add the barrier at the end of measured key fetching

- test/server_callbacks.c
The spawn_wait variable is used as a bool, and declared as a bool, everywhere - but included as an "extern int" in server_callbacks.c. This causes a problem on strict alignment architectures such as ARM
Thanks to @brockpalen for the report
Fixes #682 
> Correct an extern statement

- config/pmix.m4
- include/pmix_version.h.in
* This would have been helpful in detecting one of the changes from the
2.0.2 to 2.0.3 build. A downstream project needed to change behavior
based upon the point release change.
* Note that the `pmix_version.h` symbol is `PMIX_VERSION_RELEASE` to make
it match the other version constants. The internal define is still
called `PMIX_RELEASE_VERSION` and does not have the `L` suffix. I
did that so that it does not break internal functionality.
> Add a `PMIX_VERSION_RELEASE` to the pmix_version.h

- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- test/simple/simptest.c
For consistency, always provide the PMIX_SPAWNED and PMIX_PARENT_ID keys
in the job-level info of procs started by PMIx_Spawn from a client. Do
not do so for procs started by a tool as the tool isn't part of the
resulting nspace.
> Provide spawned keys to resulting procs

- src/server/pmix_server_get.c
Fixed checking the commit counter which should be not checked for
server, otherwise clients have get error when direct modex.
> Fixed the direct modex request

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/hash/gds_hash.c
Upon first connection, the server transfers its cached nspace registration data to the gds being used by the client's nspace. Any data registered for a specific proc must go as well, even if the proc is remote. Otherwise, the client library won't find it, and won't ask the server for it because the key starts with "pmix", and must therefore have been provided at startup.
> Transfer all cached data to client gds

- src/include/pmix_globals.c
- src/mca/pnet/base/base.h
- src/mca/pnet/base/pnet_base_fns.c
- src/mca/pnet/opa/pnet_opa.c
- src/mca/pnet/pnet.h
- src/mca/pnet/tcp/pnet_tcp.c
- src/mca/pnet/test/pnet_test.c
- src/server/pmix_server.c
Resources are allocated prior to knowing the type of application being executed. If the app never calls PMIx_Init, then no connection is made to the server and no pmix_peer_t object is created for it. This also means that PMIx_Finalize will never be called.
Together, this caused the client_finalized and app_finalized routines to fail to be called, thus leaking resources. Move those calls to the deregister_client function as the host RM is _always_ required to call that upon process termination, regardless of the type of application.
> Properly ensure that resources are returned at child end

- src/mca/ptl/tcp/ptl_tcp_component.c
- src/server/pmix_server.c
Add missing assignment of info->peerid for tools. Check peer is not tool before calling child_finalized
> Do not cleanup resources for tools

- src/class/pmix_bitmap.c
Backport of https://github.com/open-mpi/ompi/pull/4670
> Backport patch for bitmap class

- src/server/pmix_server_ops.c
(cherry picked from commit d5e4523bae0bef898c38e82e11927c3d3fd3c53a)
Conflicts:
src/server/pmix_server_ops.c
Corresponds to #733
> v2.1: Fixed use of uninitialized value

- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/server/pmix_server_ops.c
When an event is registered, we always check the cached notifications to see if we should deliver something previously received. Add checks to see if there really is a match between the newly registered handler and the cached notification before delivering it.
Silence coverity warning
> Avoid sending unwanted notifications

- src/mca/pnet/opa/pnet_opa.c
> Protect opa component when no hwloc available

- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server.c
- test/simple/stability.c
@ggouaillardet Many thanks for the help!!! Looks like we are getting closer.
```shell
$ valgrind --track-fds=yes .libs/stability --reps 10
==188204== Memcheck, a memory error detector
==188204== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==188204== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==188204== Command: .libs/stability --reps 10
==188204== 
Testing version 3.0.0
Running cycle 0
Running cycle 1
Running cycle 2
Running cycle 3
Running cycle 4
Running cycle 5
Running cycle 6
Running cycle 7
Running cycle 8
Running cycle 9
Test finished OK!
==188204== 
==188204== FILE DESCRIPTORS: 3 open at exit.
==188204== Open file descriptor 2: /dev/pts/1
==188204==    <inherited from parent>
==188204== 
==188204== Open file descriptor 1: /dev/pts/1 …
```
> Continue cleanup of finalize

- examples/dynamic.c
- examples/server.c
- include/pmix.h
- include/pmix_common.h.in
- include/pmix_server.h
- src/client/pmi2.c
- src/client/pmix_client_connect.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- test/server_callbacks.c
- test/server_callbacks.h
- test/simple/gwtest.c
- test/simple/simpdyn.c
- test/simple/simptest.c
- test/simple/simptimeout.c
- test/simple/stability.c
- test/test_cd.c
- test/test_resolve_peers.c
Although we are unaware of anyone who has implemented the server-side backend for PMIx_Connect/Disconnect, we really need to begin enforcing the backward compatibility guarantee. We had changed these signatures to accommodate the work being done in the MPI sessions working group, burt we will instead meet that request by adding a set of new APIs (PMIx_Group_*) in the future v4 of the standard.
Note: this effectively "rejects" RFC https://github.com/pmix/RFCs/pull/3 - it will be so marked and replaced by a new RFC for PMIx_Group
> Revert connect/disconnect to v2 signatures

- src/event/pmix_event_notification.c
- src/mca/pnet/tcp/pnet_tcp.c
- src/mca/psec/native/psec_native.c
- src/server/pmix_server_get.c
- src/tool/pmix_tool.c
Don't try to allocate ports if ports_per_node is 0.
Silence various warnings, some of which don't make sense
> Minor cleanup

- src/mca/pnet/opa/configure.m4
- src/mca/pnet/opa/pnet_opa.c
> Fix typo in configure so include files are found

- src/mca/ptl/tcp/ptl_tcp_component.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.h
Allow someone to pass that attribute during server_init
> Implement support for PMIX_SYSTEM_TMPDIR on server

- bindings/python/Makefile.am
look for setup.py in the source directory instead of
the current directory
> bindings/python: fix make install when VPATH is in use

- src/server/pmix_server.c
Fix compiler warning about unused variable.
> pmix_server: minor compiler warning stomp

- include/pmix_version.h.in
Enable easier check of full version number. The numeric fields are:
bytes 0-3: major version number (hex)
bytes 4-5: minor version number (hex)
bytes 6-7: release number (hex)
> Provide a numeric version definition

- .gitignore
- bindings/python/Makefile.am
- bindings/python/client.py
- bindings/python/construct.py
- bindings/python/cpmix.pxd
- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- config/pmix.m4
- config/pmix_summary.m4
- configure.ac
- include/pmix_common.h.in
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/bfrops/v12/copy.c
- src/mca/bfrops/v12/pack.c
- src/mca/bfrops/v12/unpack.c
- src/mca/bfrops/v20/copy.c
- src/mca/bfrops/v20/pack.c
- src/mca/bfrops/v20/print.c
- src/mca/bfrops/v20/unpack.c
- src/mca/bfrops/v21/bfrop_pmix21.c
- src/mca/bfrops/v21/internal.h
- src/mca/bfrops/v3/bfrop_pmix3.c
- src/mca/gds/ds12/gds_dstore.c
Require Python 3 for bindings
Output configuration summary report. Show Python and Cython version info
Create a python script to automatically generate Cython input files from
PMIx headers. This gets executed during "make install" as part of
generating the bindings. The conversion routines to shift information
between C and Python need to be manually written for now. Fortunately,
these don't change as we move across PMIx versions and so they should
only be modified when something gets added, which is rare.
> Complete initial pass thru prototype Py bindings

- include/Makefile.am
- include/pmix_common.h.in
- include/pmix_extend.h
We need to separate out the PRI's unique extensions that aren't part of
the actual Standard. This includes macros that utilize any PRI internal
functions we exposed for "convenience" as they are
implementation-specific
> Add a new header file to contain extensions

- .gitignore
- include/pmix_common.h.in
- src/common/pmix_control.c
- src/mca/psensor/base/psensor_base_stubs.c
- src/mca/psensor/heartbeat/psensor_heartbeat.c
- src/mca/psensor/heartbeat/psensor_heartbeat.h
- src/mca/psensor/heartbeat/psensor_heartbeat_component.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- test/simple/Makefile.am
- test/simple/simpjctrl.c
- test/simple/simptest.c
Somehow, we missed fully implementing these APIs in the PMIx library.
Fix that by properly handling monitoring requests and by fixing the
heartbeat component. Also ensure that we have a way for a host to
indicate they atomically handled the request for those cases where they
cannot thread shift to call the callback function.
Fixes #806 
> Implement job control and sensor APIs

- include/pmix_extend.h
- src/client/pmix_client_get.c
- src/hwloc/hwloc.c
- test/test_common.h
Remove an extension that actually references an unexposed function -
good thing nobody ever used it. Remove deprecated defines per prior
discussion.
> Cleanup a few things

- src/server/pmix_server_ops.c
Return OPERATION_SUCCEEDED for cleanup registrations
> Update the job_ctrl return code

- src/mca/psensor/file/psensor_file.c
- src/mca/psensor/heartbeat/psensor_heartbeat.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
Ensure we cleanup any active sensors when a peer departs. Allow the
heartbeat monitor to "reset" if a process stops beating and subsequently
returns
Fixes #819
> Update sensor support

- src/util/path.c
> util/path: only include sys/mount.h once

- src/common/pmix_strings.c
Since the answer string is large enough, there is no need to
initialize it nor use strncpy().
This also silences warnings emitted by -Wformat-truncation
> common/pmix_strings: silence warnings

- include/pmix_common.h.in
- include/pmix_extend.h
- src/client/pmix_client.c
- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/server/pmix_server_ops.c
- src/tool/pmix_tool.c
- src/util/error.c
- test/simple/simptest.c
Fix a few bugs in the event notification system and provide some missing
implementation (support for specifying target procs to receive the
event).
> Fix event notification operations

- include/pmix_common.h.in
Change the value of PMIX_PROC_TERMINATED to put it in the v2 error
constant region
> Shift the PROC_TERMINATED constant into v2 region

- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/usock/ptl_usock.c
`EOPNOTSUPP` can be returned by `getsockopt()` when running on QEMU user-mode emulation, which [does not support](https://github.com/qemu/qemu/blob/b8f7ff1e10b4d03555d6a5da011c2aae10063ab8/linux-user/syscall.c#L3285) `getsockopt(..., SOL_SOCKET, SO_RCVTIMEO, ..., ...)`. I discovered this with OpenMPI 2.1.1 (PMIx 1.2.1) on Ubuntu 18.04, emulating armhf on amd64, but the issue seems to persist in newer versions.
Without this patch, the following error messages appear and initialization fails:
```
$ mpiexec -n 1 --mca pmix_base_verbose 100 ./helloworld
[...]
[0086e7d4ea41:26421] pmix: init called
[0086e7d4ea41:26421] posting notification recv on tag 0
[0086e7d4ea41:26421] Security SPC include: native
[0086e7d4ea41:26421] sec: native init
[0086e7d4ea41:26421] sec: SPC native active …
```
> Deal with EOPNOTSUPP returned from getsockopt()

- include/pmix.h
- include/pmix_common.h.in
- include/pmix_server.h
- src/client/pmix_client.c
- src/common/pmix_data.c
- src/event/pmix_event_registration.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/ds12/gds_dstore.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/tool/pmix_tool.c
Mostly small addition/deletion of constants and attributes. From a code base standpoint, the biggest change was globally renaming the internal pmix_nspace_t object to pmix_namespace_t to resolve the conflict with the new user-facing structure type.
> Sync to the formal PMIx v2 Standard doc

- include/pmix.h
- include/pmix_common.h.in
- include/pmix_server.h
- src/client/pmix_client.c
- src/common/pmix_data.c
- src/event/pmix_event_registration.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/ds12/gds_dstore.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/mca/pnet/base/base.h
- src/mca/pnet/base/pnet_base_fns.c
- src/mca/pnet/opa/pnet_opa.c
- src/mca/pnet/pnet.h
- src/mca/pnet/tcp/pnet_tcp.c
- src/mca/pnet/test/pnet_test.c
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/tool/pmix_tool.c
Mostly small addition/deletion of constants and attributes. From a code base standpoint, the biggest change was globally renaming the internal pmix_nspace_t object to pmix_namespace_t to resolve the conflict with the new user-facing structure type.
> Sync to formal PMIx v2 Standard doc

- include/pmix_common.h.in
- src/client/pmix_client.c
- src/include/pmix_config_bottom.h
- src/mca/pshmem/base/pshmem_base_frame.c
- test/utils.c
Replace some further use of strncpy with pmix_strncpy. Also add a little
more protection to PMIx_Init so that a failure to init in a prior call
will return an error on subsequent calls without going thru init again
as we don't completely cleanup on failure.
> Further cleanup use of strncpy

- src/event/pmix_event_notification.c
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/mca/ptl/ptl_types.h
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Debuggers can now launch prun, pass it directives, and then have it
launch its application.
Still need to resolve IOF from launcher thru debugger
> Complete indirect launch via debugger/tool

- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp.h
- src/mca/ptl/tcp/ptl_tcp_component.c
* Instead of retrying 2 times and waiting for 2 seconds, allow the user
to adjust these values via new MCA parameters
- `ptl_tcp_handshake_wait_time`
- `ptl_tcp_handshake_max_retries`
> ptl/tcp: Make try connect retry/timout MCA adjustable

- test/simple/simptest.c
- If we get 1 SIGCHLD for multiple children exiting at the same time,
then the `simtest` will hang because it called `return` instead of
`break`.
> Allow for multiple children in the waitpid loop

- src/mca/pinstalldirs/config/Makefile.am
> Backport fix from OMPI - correct typo

- .gitignore
- bindings/python/construct.py
- examples/Makefile.am
- examples/asyncgroup.c
- examples/group.c
- include/pmix.h
- include/pmix_common.h.in
- include/pmix_extend.h
- src/client/Makefile.include
- src/client/pmix_client_group.c
- src/common/pmix_strings.c
- src/event/pmix_event_notification.c
- src/include/pmix_globals.h
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/bfrops.h
- src/mca/bfrops/v12/copy.c
- src/mca/bfrops/v12/internal.h
- src/mca/bfrops/v20/copy.c
- src/mca/bfrops/v20/internal.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/tool/pmix_tool.c
- src/util/error.c
- test/simple/simptest.c
Implement PMIx_Group_construct and PMIx_Group destruct. Add tracking of
PMIx group members and substitute the real members for a group involved
in the Fence operation as a first example.
> Implement PMIx group collective APIs

- config/pmix_mca.m4
- src/mca/pshmem/base/pshmem_base_frame.c
Now that there are TWO dstore components, they are causing the pshmem
framework to be opened twice, thus crashing the code
(cherry picked from commit d070754b5cd529aa8dae329a105527f1a4c79aab)
> Ensure we only open the pshmem framework once

- config/pmix_mca.m4
(cherry picked from commit 065f19aaa3ad81dee6a52ec77e2d0b1040638ecf)
> Fix typo in configure logic

- examples/asyncgroup.c
- examples/group.c
- include/pmix.h
- include/pmix_common.h.in
- include/pmix_server.h
- src/client/pmix_client_group.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
Begin implementation to return an assigned context ID from PMIx_Group_construct. Cleanup some errors observed when executing multiple apps using same group name.
> Continue implementation of PMIx Groups

- examples/group.c
- include/pmix_common.h.in
- include/pmix_server.h
- src/client/pmix_client_group.c
- src/server/pmix_server_ops.c
Update the PMIx_Group_construct[_nb] APIs to allow return of a requested
context ID for the new group.
> Enable PMIx_Group_construct to return a context ID

- src/mca/plog/stdfd/plog_stdfd.c
Signed-off-by: Ralph H Castain <rhc@open-mpi.org>
> Correctly extract the timestamp from directives

- src/mca/ptl/usock/ptl_usock_component.c
This guards against corruption seen in https://github.com/pmix/pmix/issues/824.
This will need some more discussion as to whether we should bail out of the server here or not.
> ptl/usock: Guard against assumption that zero-length credential is NULL

- src/mca/common/dstore/dstore_base.c
- src/mca/common/dstore/dstore_common.h
- src/mca/gds/base/base.h
- src/mca/gds/base/gds_base_fns.c
- src/mca/gds/ds12/gds_ds12_base.c
- src/mca/gds/ds21/gds_ds21_base.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server.c
Move the GDS (in particular the dstore) locks up to avoid
the over head of locking and unlocking for each key
set in the modex data.
Signed-off-by: Scott Miller <scott.miller1@ibm.com>
> Pull gds locking of modex up to improve performance.

- src/mca/common/dstore/dstore_base.c
* Dstore needs an outer wrapper for the kv pair.
- Without this we corrupt memory on the modex operation.
* Bug introduced in PR #897
- The call was switched from `pmix_common_dstor_store`, which adds the
extra wrapping (seen in this PR), to `_dstore_store_nolock` which
expects the `kv` to already be wrapped.
> Wrap the inner dstore kv in an object.

- src/util/os_path.c
- src/util/os_path.h
- src/util/show_help.c
- src/util/show_help.h
According to clang on MacOS, passing a bool parameter -- which
undergoes default parameter promotion -- to va_start() results in
undefined behavior.  So just change these params to int and avoid the
issue.
> passing a bool to va_start() is undefined

- src/atomics/sys/gcc_builtin/atomic.h
(from: https://github.com/open-mpi/ompi/pull/6048)
I'm porting Nathan Hjelm's fix for OMPI Issue 6014
(https://github.com/open-mpi/ompi/issues/6014) to PMIx.
Signed-off-by: Geoffrey Paulsen <gpaulsen@us.ibm.com>
> fix potential memory barrier bug with __atomic builtin atomics

- src/mca/psensor/file/psensor_file.h
Add missing `PMIX_EXPORT` decoration on `mca_psensor_file_component` so that it can be resolved at runtime by `dlsym`. It was already added to master by af64c7d.
See open-mpi/ompi#6056.
> v2.1/psensor/file: add missing PMIX_EXPORT on mca_psensor_file_component

- src/mca/common/dstore/dstore_base.c
1. Make dstor modex to be more efficient.
Dstor _dstore_store_nolock function is able to receive multiple keys on input (packed in a buffer).
_dstor_store_modex_cb originally was feeding it with one key-value at a time, but when possible it is preferred to pass dstor with the whole set of keys (for performance reasons).
1. Avoid extra extension slots
Extra extension slots were placed when the key-values were passed individually. Examples are:
- direct modex 
- local keys at the commit time.
We need to place extension slots in order to make sure that
they are separating keys from different ranks (and thus can
provide the "next" link if new keys are to be appended).
This solution detects unneeded extension slot when keys from the same rank are being placed. These unneeded extension slots …
> Dstore: fix key publishing logic

- config/pmix.m4
- src/mca/common/dstore/dstore_segment.c
- src/mca/common/dstore/dstore_segment.h
- src/mca/gds/ds21/gds_ds21_lock_pthread.c
(cherry picked from commit c9a8bba66bae2ac02eb35f4f4392678e56539aaf)
Corresponds to #805
> v2.2/dstore: ds21 locks are aligned to the size of the cache line

- src/mca/ptl/tcp/ptl_tcp_component.c
(cherry picked from commit 59f3742ece02f619289c40b49a39bdcfa6894352)
> Use pmix_setenv instead of argv_append

- src/mca/ptl/tcp/ptl_tcp_component.c
> Default the v2.0 GDS to "ds12,hash"

- src/event/pmix_event_notification.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/mca/ptl/ptl.h
- src/mca/ptl/ptl_types.h
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
Ensure we mark that a proc has finalized. Check the finalized flag prior
to each message sent from server to client
> Avoid sending messages to procs that have finalized

- src/event/pmix_event.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
- test/simple/simpdie.c
- test/simple/simptest.c
Flag the event for non-default event handlers. Include the affected proc's ID.
> Report events only to members of the failed procs nspace

- src/event/pmix_event.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
> Ensure clients still receive a socket termination when the server dies

- autogen.sh
AFAIK, autogen.sh has never been used in PMIx (i.e., it's always been
autogen.pl in PMIx) -- this is just a holdover from its Open MPI
roots.  So remove this outdated sym link.
> autogen.sh: remove outdated sym link

- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- test/simple/simpdmodex.c
When a process that is participating in a tracked request (e.g., collectives or direct modex) fails, a race condition exists between the lost-connection procedure and the host callback. Resolve this by checking and removing the proc from the trackers, and check the lists upon host callback prior to removing them from the list.
> Fix race conditions in tracked requests

- include/pmix_common.h.in
- src/common/pmix_query.c
v2.1 of the PMIx Standard stipulates that the query API must cache any returned values so that subsequent queries can be locally resolved. It provides for a new attribute that indicates the cache should be refreshed for the specified values.
This implementation could be further optimized. It currently will refer the entire request to the host if _any_ included key in _qny_ query fails to locally resolve. Optimally, only the values that couldn't be resolved would be passed to the host, and the results of both the local and host requests then aggregated prior to return. Someone is welcome to implement!
> Complete Query update for v2.1 compliance

- examples/group.c
- include/pmix_server.h
- src/client/pmix_client_group.c
- src/server/pmix_server_ops.c
Avoid double-destruct of message. Break race condition when
operation-succeeded is returned
> Fix group construct/destruct

- src/common/pmix_query.c
(cherry picked from commit 58ac939d5b4e737495001bfbc82f4f12e9bf8a6f)
> Correct typo on proc assignment

- src/include/pmix_globals.c
> iof: plug a memory leak in the pmix_iof_req_t destructor

- src/event/pmix_event.h
> Ensure that lost-connection events get delivered to default evhandlers

- include/pmix_common.h.in
Release the pmix_proc_t array when the value is a PMIX_PROC
> plug a memory leak in pmix_value_destruct()

- include/pmix_common.h.in
- src/include/pmix_globals.h
- src/server/pmix_server_ops.c
Detect that a group construct operation involves only local procs and
optimize the operation - override it if a context ID must be assigned.
Allow user to force local-only operation.
Ensure that modex information is returned for non-local operations so
that group members can immediately communicate.
> Enhance group construct for local ops

- include/pmix_common.h.in
Remain compliant with the standard, but handling different max length
values requires a fairly significant change beyond what we have time to
implement at this point.
> Restore prior sizes for max nslen and keylen

- src/server/pmix_server.c
> server: have query_cbfunc invoke the release callback when available

- src/mca/gds/ds12/gds_ds12_lock_pthread.c
> gds/ds12: plug a memory leak in pmix_ds12_lock_finalize()

- src/mca/common/dstore/dstore_base.c
remove the tracker from the tracking array after being destructed.
> dstore/base: plug a memory leak in pmix_common_dstor_del_nspace()

- src/server/pmix_server_get.c
If the server is asked for a piece of information that isn't immediately
available, we create a request tracker and add the requesting peer to
it. The precise return status, however, must be carefully controlled to
ensure that the peer object gets released when it should, and doesn't
get release twice.
> Attempt to address the case where data isn't found

- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/runtime/pmix_params.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Events were being cached forever, leading to a flood hitting a newly
connected client that sometimes overwhelmed the system. There is likely
still something not quite right on the client side of the event
notification system as it shouldn't be getting overwhelmed. However,
cleaning up the system a bit won't hurt and we can then take a deeper
dive into the client side code.
Ensure that all cached objects (IOF requests, event registrations,
notifications) get purged when a proc finalizes or abruptly terminates,
and when nspaces are deregistered.
> Overhaul the event caching system

- include/pmix_common.h.in
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server_ops.c
- test/simple/simptest.c
If the event generator specified targets, then track how many targets we
are to notify. Once we have notified them, then evict the event from the
cache hotel to clear room for the next one.
> Remove events once all targets notified

- src/mca/ptl/tcp/ptl_tcp.c
Some TCP/IP stacks (such as Linux' old stack used in GNU/Hurd) have
getsockopt(SO_RCVTIMEO) return a zeroed tv, but setsockopt(SO_RCVTIMEO
return ENOPROTOOPT, so we need to make setsockopt error checking look for it
(and EOPNOTSUPP) just like is done for getsockopt.
Signed-off-by: Samuel Thibault <samuel.thibault@ens-lyon.org>
> handle setsockopt(SO_RCVTIMEO) not being supported

- include/pmix_common.h.in
- src/runtime/pmix_params.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/tool/pmix_tool.c
Evict the oldest cached output to make room for the newest. Provide an
MCA param for sizing the max iof cache - default it to 1M messages since
memory is only allocated on an as-needed basis. Add some debugging
output when pmix_server_iof_verbose is on so we can see the cache in
operation.
Fixes https://github.com/pmix/prrte/issues/183
> Properly cache IO for pending registrants

- src/include/pmix_globals.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
Run epilogs when deregistering clients and/or nspaces, and when a
process (e.g., tool) unexpectedly drops its connection.
> Ensure that epilogs get run

- examples/alloc.c
- examples/bad_exit.c
- examples/client.c
- examples/client2.c
- examples/dmodex.c
- examples/dynamic.c
- examples/examples.h
- examples/fault.c
- examples/hello.c
- examples/jctrl.c
- examples/launcher.c
- examples/log.c
- examples/tool.c
- src/common/pmix_query.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
The client first checks to see if it has the requested info and then
passes the request up to the server. Have the server check its own cache
before passing it along to the host.
Update the examples
> Extend the server's support for query and update examples

- src/include/pmix_globals.c
> epilog: fix a typo in pmix_execute_epilog()

- src/common/pmix_control.c
explicitly release 'results' if there is no callback present.
> pmix_control: plug a memory leak in query_cbfunc()

- VERSION
> Fix the greek version (make it 'a1')

- config/pmix.m4
- config/pmix_check_os_flavors.m4
- include/pmix_common.h.in
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
Ensure the server knows what the tool's cmd line was so that it can provide it in response to queries. Modify the returned data type for the PMIX_QUERY_NAMESPACES attribute so we can return more than just a simple list of namespaces - e.g., to include the cmd line executing in the namespace.
> Pass the tool's cmd line to the server

- src/mca/gds/ds21/gds_ds21_file.c
make the ESH_REGION_EXTENSION_FLG, ESH_REGION_INVALIDATED_FLG
and ESH_REGION_SIZE_MASK macros 32bits on these arch.
Refs. pmix/pmix#1032
> gds/ds21: fix support for 32 bits arch

- src/mca/common/dstore/dstore_base.c
free the dstore context at the end
> common/dstore: plug a memory leak in pmix_common_dstor_finalize()

- src/event/pmix_event_notification.c
do release the event evicted from the cache.
> event: plug a memory leak in _notify_client_event()

- config/pmix_setup_hwloc.m4
- config/pmix_setup_libevent.m4
- src/hwloc/hwloc-internal.h
Mimic the way we handle libevent for environments that embed a copy of
PMIx in themselves.
Fixes #1045 
> Update our handling of hwloc configure

- src/mca/preg/base/preg_base_frame.c
- src/mca/preg/native/preg_native.c
- src/mca/preg/preg_types.h
* The problem is that `PMIx_generate_regex` must preserve ordering of the
list passed into it. This allows for a proper mapping of nodes-to-ranks
to occur inside of PMIx (which is then exposed to the application).
- If the hostnames contain multiple sets of digits then the list
can be reordered causing the mapping to be incorrect.
* This patch prevents the regex from 'matching' an earlier prefix/suffix
if that would mean skipping over another match just before it.
* Fixes #1049
> Fixes PMIx_generate_regex ordering

- include/pmix_common.h.in
- src/client/pmix_client_spawn.c
- src/common/pmix_query.c
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/mca/pnet/base/pnet_base_fns.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Add a macro to check for end of pmix_info_t array marker.
Check input to spawn and query functions to ensure the number of app
directives and qualifiers is set.
Ensure launchers pickup PMIx MCA params to forward to their child jobs.
> Use affected procs for filtering notifications

- config/pmix_setup_cc.m4
clang 5.0 on trusty is busted with respect to C11 atomics
This can be evidenced with the simple program below.
This test was added into OPAL_PROG_CC_C11_HELPER() and disable
C11 atomics if it fails.
_Atomic uint32_t a;
uint32_t b;
atomic_fetch_xor_explicit(&a, b, memory_order_relaxed);
Refs. open-mpi/ompi#6264
(back-ported from commit open-mpi/ompi@d1fadebc65a7a7bcfce14641e389f02307f580e2)
> configury: enhance C11 detection

- examples/tool.c
- src/common/pmix_query.c
- src/include/pmix_globals.h
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/runtime/pmix_init.c
- src/server/pmix_server_ops.c
Allow user to request information about a different node.
(cherry picked from commit 6edaab91463e56d2d634309e4af411046772042d)
> Save hostname for use in responding to queries

- include/pmix_common.h.in
Based on a line-by-line comparison between the standard doc and pmix_common.h.in.
> Sync some missing attributes from v2.2 standard

- src/server/pmix_server_ops.c
When registering a default event handler, we have to return "operation
succeeded" as we have atomically completed the registration and won't be
executing a callback function.
> Ensure we return the correct status

- include/pmix_common.h.in
> Fix typo in PMIX_SYSTEM_EVENT macro

- include/pmix_extend.h
- test/test_common.h
We moved the non-standard macros out of pmix_common.h so that the
public-facing header would fully comply with the standard. However, this
meant that the Slurm plugin no longer compiled as they use those macros
there. Shifting them back to pmix_extend.h preserves the "standard only"
nature of pmix_common.h, but still exposes the non-standard macros for
now. We will remove them in later major releases after the Slurm plugin
has been updated.
Fixes #1082 
> Shift the non-standard macros to pmix_extend.h

- test/test_server.c
- test/test_server.h
* Fixed the barrier lock active flag.
* Removed wait time for barrier due to uselessness.
* Moved list object destructors before finalizing PMIx.
> test: multiserver fixes

- test/test_server.c
- test/test_server.h
* Fixed the barrier lock active flag.
* Removed wait time for barrier due to uselessness.
* Moved list object destructors before finalizing PMIx.
(cherry picked from commit ea6e47d722f9b2279542b70909667641a47c9437)
Corresponds to #1084
> v2.2/test: multiserver fixes

- test/test_server.c
- test/test_server.h
* Fixed the barrier lock active flag.
* Removed wait time for barrier due to uselessness.
* Moved list object destructors before finalizing PMIx.
(cherry picked from commit ea6e47d722f9b2279542b70909667641a47c9437)
Corresponds to #1084
> v3.1/test: multiserver fixes

- src/threads/thread_usage.h
> Require that the thread_usage macros always be inlined

- config/pmix.m4
- config/pmix_search_libs.m4
- src/server/pmix_server_ops.c
Port some configure changes from upstream. Protect the one place where
we call clock_gettime from systems where it isn't available.
> Update configure logic for clock_gettime

- config/pmix_setup_hwloc.m4
- config/pmix_setup_libevent.m4
Remove the --enable-embedded-libevent and --enable-embedded-hwloc flags as they are confusing users. Instead, we will use the --enable-embedded-mode to handle both of these options.
> Update configure logic

- config/pmix.m4
- include/pmix_version.h.in
Refs. pmix/pmix#1101
(back-ported from commit pmix/pmix@ccb76fd4a5745ee8591ff9655a54c2ca9adcdbba)
> configury: automatically generate PMIX_NUMERIC_VERSION

- config/pmix.m4
fix a typo from pmix/pmix@ccb76fd4a5745ee8591ff9655a54c2ca9adcdbba
> configury: fix PMIX_NUMERIC_VERSION

- include/pmix_common.h.in
> Remove the "restrict" keyword to avoid requiring C99 for apps

- include/pmix_common.h.in
Ensure we only use "restrict" key word for C99 and above compilers
> Use "restrict", but protect it

- .gitignore
- include/pmix_common.h.in
- src/common/pmix_iof.c
- src/common/pmix_iof.h
- src/event/pmix_event_notification.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/util/error.c
- test/simple/Makefile.am
- test/simple/makedata.pl
- test/simple/simpio.c
Forward stdin upon request, reading from the proc's stdin until it is
closed and returns zero bytes. Forward read data to server for relay to
host for delivery. Add simple test plus script to make a data file.
> Complete implementation of stdin forwarding

- test/test_server.c
but uses PMIx "wrappers" pmix_event_{add,del}() instead
of directly calling libevent event_{add,del}()
> test/test_server: do not invoke libevent directly

- src/include/types.h
- src/runtime/pmix_progress_threads.c
in order to avoid deadlocks, simply queue event_{add,del,active}()
when using libev in a multi-threaded context.
> libev: fix libev support

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/common/dstore/dstore_base.c
- src/mca/common/dstore/dstore_common.h
- src/mca/gds/base/base.h
- src/mca/gds/base/gds_base_fns.c
- src/mca/gds/ds12/gds_ds12_base.c
- src/mca/gds/ds21/gds_ds21_base.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
Packing the nspace string with each proc is redundant and not need for unpacker side. This commit avoids packing `nspace:rank` tuples into the modex blob, instead of that all ranks are renumbered throughtout procs involved in Modex and packed as integers.
Example procs paking:
```
{ "nspace1", 0} : 0
{ "nspace1", 1} : 1 => procs = { {0}, {1}, {2} }
{ "nspace2", 0} : 2
```
Refs https://github.com/pmix/pmix/issues/681
> modex: optimization of rank identification size reduction

- src/event/pmix_event_notification.c
Delay the checkout/release of the cached event object to ensure the
object remains valid until we are done with it.
> Avoid segfault in event notification

- src/mca/ptl/tcp/ptl_tcp_component.c
If this is a tool that we already established info for, then
info variable is not set locally, but is in the peer structure.
Signed-off-by: David Solt <dsolt@us.ibm.com>
> Fix access to uninitialized info

- bindings/python/construct.py
- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/server.py
Fix detection of error constants - not all constants have PMIX_ERR in their name!
Begin implementation of server module functions by adding skeletons.
Deal with Python unhappiness with types such as "bool".
> Continue working on the Python bindings

- contrib/pmix.spec
Since PMIx requires _libevent_ the spec file should ensure that _libevent-devel_ is installed.
Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>
> Add BuildRequires: libevent-devel to spec file

- src/atomics/sys/atomic_impl.h
https://github.com/open-mpi/ompi/pull/6500
(cherry picked from commit 4ee4fe51712eed872c61fee8b45bcb67b0db6114)
> Backport https://github.com/open-mpi/ompi/pull/6500

- src/mca/gds/ds21/gds_ds21_lock_pthread.c
When re-attaching the lock-segment, the `seg_hdr` pointer was not
updated, which caused to reference on incorrect data and damage.
> gds/ds21: update the pointer of `seg_hdr` when segment re-attached

- src/mca/bfrops/base/bfrop_base_unpack.c
> bfrops/base: fix a typo in pmix_bfrops_base_unpack_app()

- src/mca/gds/ds21/gds_ds21_lock_pthread.c
When re-attaching the lock-segment, the `seg_hdr` pointer was not
updated, which caused to reference on incorrect data and damage.
(cherry picked from commit ef2575f3ac21a3261da16d827fe2efd27b46151c)
Corresponds to #1156
> v3.1/gds/ds21: update the pointer of `seg_hdr` when segment re-attached

- src/atomics/sys/powerpc/atomic.h
Tracks https://github.com/open-mpi/ompi/pull/6453
(cherry picked from commit 8025f845b1ccb42ba9bae60c422f31b1a54f3b73)
> Atomics: fix a compiler warning on POWER arch

- src/mca/common/dstore/dstore_base.c
- src/mca/gds/base/base.h
- src/mca/gds/base/gds_base_fns.c
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server_ops.c
- src/util/argv.c
- src/util/argv.h
This commit optimizes the modex size, avoiding duplication of key-names for key-value pairs. It generates the key-map with the unique names and packs key indexes instead of key-name strings. The key-map packaged separately and allows the remote side to determine the key-name by index when unpacking.
>  modex: reduce modex size by replacing key names with indexes

- src/mca/gds/ds21/gds_ds21_lock_pthread.c
When re-attaching the lock-segment, the `seg_hdr` pointer was not
updated, which caused to reference on incorrect data and damage.
(cherry picked from commit ef2575f3ac21a3261da16d827fe2efd27b46151c)
Corresponds to #1156
> v2.2/gds/ds21: update the pointer of `seg_hdr` when segment re-attached

- src/server/pmix_server_ops.c
This was identified by Coverity with CID 337282
> server: plug a memory leak in _collect_data()

- include/pmix_common.h.in
- include/pmix_extend.h
- src/mca/base/pmix_mca_base_var.c
- src/mca/gds/base/gds_base_fns.c
- src/server/pmix_server_ops.c
- src/util/argv.c
- src/util/argv.h
Remove the unused and useless 'overwrite' parameter from
pmix_status_t pmix_argv_append_unique_idx() and
pmix_argv_append_unique_nosize()
In order to maintain backward compatibility, the 'overwrite' parameter
was not removed from the public PMIX_ARGV_APPEND_UNIQUE() macro
but is now ignored.
Note pmix_argv_append_unique_nosize() was updated accordingly in pmix_extend.h
> util/argv: remove the useless 'overwrite' parameter

- src/mca/psquash/flex128/psquash_flex128.c
The `master` branch will not build on my Mac because of the conflicting function signatures.
```
$$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.10.44.4)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
```
psquash_flex128.c:316:15: error: conflicting types for 'flex_pack_integer'
static size_t flex_pack_integer(size_t val,
^
psquash_flex128.c:220:15: note: previous declaration is here
static size_t flex_pack_integer(uint64_t val,
^
psquash_flex128.c:342:15: error: conflicting types for 'flex_unpack_integer'
static size_t flex_unpack_integer(const uint8_t in_buf[], size_t buf_size,
^ …
```
> psquash/flex128: Fix mismatch prototype

- src/mca/bfrops/base/base.h
CID 1444191
CID 1444190
CID 1444187
CID 1444185
CID 1444180
CID 1444178
CID 1444175
CID 1444173
> bfrops: fixed coverity: `Using uninitialized value "*tmpbuf"`

- include/pmix_common.h.in
- src/server/pmix_server.c
- src/util/error.c
Add attribute to request notification when launch completes
Add error constant for registering to get launch complete notifications
Delete timeout timer when op completes. There is still a timeout timer execution, so delete it when the modex completes
Add missing error constant string
> Complete indirect launch under debugger

- config/distscript.sh
- config/pmix.m4
test the existence of .git in the top source tree
in order to
- support VPATH
- support git worktrees (.git is a file and not
a directory)
> configury: fix git source tree is detected

- config/pmix.m4
- src/mca/pdl/configure.m4
The $enable_dlopen variable might be set to "unknown" by libtool.m4.
In order to cope with that, use $PMIX_ENABLE_DLOPEN_SUPPORT that is
set before $enable_dlopen might be overwritten.
Also add a test to make sure PMIX_ENABLE_DLOPEN_SUPPORT was not set
after $enable_dlopen was overwritten.
Refs. pmix/pmix#1121
> configury: use PMIX_ENABLE_DLOPEN_SUPPORT instead of enable_dlopen

- src/event/pmix_event_registration.c
- src/server/pmix_server_ops.c
We want the register_events callback function to be executed prior to
delivery of any corresponding events. Ensure that happens by injecting
the registration into an event that won't fire until after the server
has notified the client of completion of the registration.
> Ensure any cached notifications arrive after reg completes

- .travis.yml
- README.md
Draft for adding travis-ci for memory checks: #1025 https://github.com/open-mpi/ompi/issues/6242
> Travis CI Script

- LICENSE
- Makefile.am
- contrib/make_dist_tarball
"make check" can only succeed if the plugins have been installed or
"--disable-dlopen" has been passed to configure.  The first can't
happen in "make distcheck", so force the second for all invocations
of "make distcheck" by setting AM_DISTCHECK_CONFIGURE_FLAGS in
Makefile.am.
Clean up the handling of AM_DISTCHECK_CONFIGURE_FLAGS and
DISTCHECK_CONFIGURE_FLAGS in make_dist_tarball.  First, with the
above fix, passing --disable-dlopen is no longer required.  Second,
users (and scripts) should set DISTCHECK_CONFIGURE_FLAGS, not
AM_DISTCHECK_CONFIGURE_FLAGS.  Automake will combine the two options
when running "make distcheck", so the right things will happen with
this configuration.
> dist: Clean up handling of --disable-dlopen in dist process

- src/mca/bfrops/v12/Makefile.am
- src/mca/bfrops/v20/Makefile.am
- src/mca/bfrops/v21/Makefile.am
- src/mca/bfrops/v3/Makefile.am
- src/mca/bfrops/v4/Makefile.am
- src/mca/gds/ds12/Makefile.am
- src/mca/gds/ds21/Makefile.am
- src/mca/gds/hash/Makefile.am
- src/mca/pcompress/zlib/Makefile.am
- src/mca/plog/default/Makefile.am
- src/mca/plog/stdfd/Makefile.am
- src/mca/plog/syslog/Makefile.am
- src/mca/pnet/opa/Makefile.am
- src/mca/pnet/tcp/Makefile.am
- src/mca/pnet/test/Makefile.am
- src/mca/preg/native/Makefile.am
- src/mca/psec/munge/Makefile.am
- src/mca/psec/native/Makefile.am
- src/mca/psec/none/Makefile.am
- src/mca/psensor/file/Makefile.am
- src/mca/psensor/heartbeat/Makefile.am
- src/mca/pshmem/mmap/Makefile.am
- src/mca/psquash/flex128/Makefile.am
- src/mca/psquash/native/Makefile.am
- src/mca/ptl/tcp/Makefile.am
- src/mca/ptl/usock/Makefile.am
They don't appear to be necessary for Python bindings support and are messing up OMPI
> Remove the link-backs to libpmix

- config/pmix.m4
- src/mca/bfrops/v12/Makefile.am
- src/mca/bfrops/v20/Makefile.am
- src/mca/bfrops/v21/Makefile.am
- src/mca/bfrops/v3/Makefile.am
- src/mca/bfrops/v4/Makefile.am
- src/mca/gds/ds12/Makefile.am
- src/mca/gds/ds21/Makefile.am
- src/mca/gds/hash/Makefile.am
- src/mca/pcompress/bzip/Makefile.am
- src/mca/pcompress/gzip/Makefile.am
- src/mca/pcompress/zlib/Makefile.am
- src/mca/plog/default/Makefile.am
- src/mca/plog/smtp/Makefile.am
- src/mca/plog/stdfd/Makefile.am
- src/mca/plog/syslog/Makefile.am
- src/mca/pnet/opa/Makefile.am
- src/mca/pnet/tcp/Makefile.am
- src/mca/pnet/test/Makefile.am
- src/mca/preg/native/Makefile.am
- src/mca/psec/munge/Makefile.am
- src/mca/psec/native/Makefile.am
- src/mca/psec/none/Makefile.am
- src/mca/psensor/file/Makefile.am
- src/mca/psensor/heartbeat/Makefile.am
- src/mca/pshmem/mmap/Makefile.am
- src/mca/psquash/flex128/Makefile.am
- src/mca/psquash/native/Makefile.am
- src/mca/ptl/tcp/Makefile.am
- src/mca/ptl/usock/Makefile.am
Add --enable-nonglobal-dlopen to control adding libpmix to every MCA component. Default it to enabled.
> Add a new configure option specifically to enable non-global dlopen

- config/pmix.m4
Refs https://github.com/pmix/pmix/pull/1215#issuecomment-484771286
> Default to disable-nonglobal-dlopen in embedded mode

- src/include/pmix_globals.h
- src/mca/psec/native/psec_native.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/tool/pmix_tool.c
When a launcher is invoked multiple times in a job script, each
invocation will have the same "client". The job-level info and tracking
objects are released after each invocation, so we have to recreate them.
Fixes #1211
> Fix case of multiple launcher calls in job script

- config/pmix.m4
This fixes pmix/pmix@886724a5889f61608b07a5defcdbf64650d6aa7d
Refs. pmix/pmix#1215
Refs. pmix/pmix#1217
Also use 'test ... -eq ...' when comparing a variable with an integer.
> configury: fix a typo in embedded mode handling

- test/cli_stages.c
- test/cli_stages.h
- test/pmix_test.c
- test/server_callbacks.c
- test/test_common.c
- test/test_common.h
- test/test_fence.c
- test/test_resolve_peers.c
- test/test_server.c
- test/utils.c
- test/utils.h
This PR fixes the test suite problems with GDS HASH component.
Details:
```bash
user@cn1 ~/pmix/v2.2/test $ export PMIX_MCA_gds=ds21,hash
user@cn1 ~/pmix/v2.2/test $ ./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:3]"
pmix_test.c:main: Test finished OK!
```
```bash
user@cn1 ~/pmix/v2.2/test $ export PMIX_MCA_gds=hash
user@cn1 ~/pmix/v2.2/test $ ./pmix_test -n 4 --ns-dist 3:1 --fence "[db | 0:0-2;1:3]"
[cn1:05920] PMIX ERROR: PROC-ENTRY-NOT-FOUND in file gds_hash.c at line 648
[cn1:05920] PMIX ERROR: PROC-ENTRY-NOT-FOUND in file gds_hash.c at line 766
[cn1:05920] PMIX ERROR: PROC-ENTRY-NOT-FOUND in file server/pmix_server.c at line 2697
[cn1:05940] PMIX bfrop:unpack: got type 20 when expecting type 3
[cn1:05940] PMIX ERROR: PACK-MISMATCH in file client/pmix_client.c at line 224
ERROR …
```
> v2.2/Fix the test suite with GDS hash component

- src/server/pmix_server_ops.c
If the host executes the fence, connect, or disconnect operation atomically, or there is an error when processing a particular participant's request, then we need to ensure that all prior participants are released from their locks.
Refs #1236 
> Fix atomic and error code paths

- src/runtime/pmix_progress_threads.c
The hang was quite rare and appears as the result of the race condition
between PMIx progress thread and main thread calling
PMIx_Server_finalize.
The following sequence is possible:
```
| main thread  | Progress thread   |
|              | while(ev_active){ |
|ev_active=0   |                   |
|ev_break_loop |                   |
|              | ev_loop()         |
```
According to libevent manual, in this situation, libevent will
ignore ev_break_loop as it wasn't in the loop at the time
ev_break_loop() was called (see (b) in the libevent excerpt below)
So the progress thread will enter the loop and hang.
To fix this use event_base_loopexit that have desired behavior
(See section (a) of the excerpt below)
**excerpt from the libevent manual**:
```
...
Note also that …
```
> server: Fix PMIx_Server_Finalize hang

- src/runtime/pmix_progress_threads.c
> v3.1/server: Fix PMIx_Server_Finalize hang

- configure.ac
Autotools expect to perform compiler tests without additional CFLAGS. If
the user provides CFLAGS, this can interfere - e.g., providing -Werror
will cause autotools to abort every time it tests for some
functionality. So capture the user-provided flags and restore them after
configure is done running tests.
> Preserve user-provided CFLAGS to protect autotools

- .travis.yml
- configure.ac
- src/common/pmix_iof.h
- src/mca/ptl/tcp/ptl_tcp.c
- src/tools/pattrs/pattrs.c
Adds Clang compile routines and `-fsantize=undefined` checks to Travis-CI.
Fix small warnings in sign compare and sometimes uninitialized variables.
Over the next development steps, we should try to remove the amount of `-Wno-...` flags provided to CI by fixing the warnings.
> Travis: Clang and Undefined Behavior Sanitizer

- src/mca/ptl/ptl_types.h
Use fixed 32-bit field to represent the message size as opposed to
floating `size_t` type.
Preserve backward compatibility by adding a padding.
> ptl: Fix message header `nbytes` field ambiguity

- examples/dmodex.c
Do not load the key into the proc nspace (duh).
Thanks to @krempel-pt for pointing it out.
Fixes #1247
> Correct dmodex example

- src/mca/ptl/usock/ptl_usock_component.c
Port this portion from 6bbbb4bf0 in master.
> PTL/usock: `usock` doesn't support Tools, fail query for this case.

- src/mca/pif/linux_ipv6/pif_linux_ipv6.c
Fix a buffer overflow on some systems on which `IF_NAMESIZE` is defined to 10 but we read 20 chars in `fscanf`.
First seen in #1265.
Note: it's probably better to modify the `fscanf` line instead, e.g. by pre-processor math and pre-processor stringification.
> IPv6 IF Read: Buffer Overflow

- examples/asyncgroup.c
- examples/fault.c
- examples/tool.c
since they show up near the end of the build, they are kind
of noticeable.
> examples: swat compiler warnings

- include/pmix_rename.h.in
- src/util/output.c
- src/util/output.h
Don't render the output if the verbosity is below the trigger level and
nothing will be output
> Avoid output_verbose overhead when it won't print

- src/tool/pmix_tool.c
If no nspace/rank is given, then can still register attributes and satisy some simple requests
> Tools that don't connect do not need to provide ID

- src/mca/pif/linux_ipv6/pif_linux_ipv6.c
Seams to commonly be defined to 16 in glibc and musl.
Thanks to @orivej for catching this!
Follow-up to #1275
> Fix comment: IPv6 IF_NAMESIZE

- src/mca/gds/base/gds_base_fns.c
- src/mca/pnet/base/pnet_base_fns.c
- src/server/pmix_server.c
Servers are not required to pass a function pointer module.
> Allow servers to pass NULL module

- src/mca/gds/hash/gds_hash.c
There is no requirement that a job specify proc-level info just in
order to run. So don't error out if none is available
> Allow jobs to not specify proc-level info

- src/mca/gds/hash/gds_hash.c
If values are not explicitly given but can be computed from
provided data, then do so as a convenience to the host
environment - and helpful to libraries looking for those
specific values.
> Add some more values that can be computed

- src/mca/preg/native/preg_native.c
Backport of https://github.com/open-mpi/ompi/pull/6739
> Fix potential integer overflow in regex

- bindings/python/sched.py.in
The setup_application call only requires two arguments, and was
being passed three. This fix removes the appinfo from the call,
and stores the returned list from setup_application in appinfo.
> Fix schedular example in python bindings

- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/ptl_types.h
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp.h
- src/mca/ptl/tcp/ptl_tcp_component.c
The tool connection protocol was updated in v3.1 and v2.2 series, but
not v3.0. This PR syncs v3.0 with those branches so we don't have a
breakage in the middle.
> Update the tool handshake procedure to match v3.1 series

- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_unpack.c
Although the number of argvs is technically an int32, we have
to pack/unpack it as a generic int due to a typo in earlier
release series. This preserves the ordering of bytes in the
packed buffer as it includes a tag indicating the actual size
of the value. No harm is done as generic int is equivalent to
int32 on all current systems - just something to watch out
for in the future should someone someday change the size of "int"
> Fix xversion spawn test

- src/include/types.h
- src/runtime/pmix_progress_threads.c
When libev is used, wrap pmix_event_base_loopexit() in order to support multithreading.
Since pmix_event_base_loopbreak() is not used anymore,
simply rename it into pmix_event_base_loopexit().
This fixes pmix/pmix@f652ae1d607b15ea89a0cb085c92275939499fd6 when libev is used
instead of libevent.
> libev: wrap pmix_event_base_loopexit()

- configure.ac
For static builds, we need -fPIC so PRRTE and friends can correctly
absorb it.
> Add -fPIC to static builds

- test/cli_stages.c
- test/cli_stages.h
- test/pmix_test.c
- test/server_callbacks.c
- test/test_common.c
- test/test_resolve_peers.c
- test/utils.c
- test/utils.h
Corresponds to 83b3d0dccd932a3bf40adf11df87d5e1cf4c9abf
> v1.2/test: eliminated the usage of through ranking for namespaces

- configure.ac
Werror CFLAGS cause problems for autoconf's tests, so scan the incoming
CFLAGS to discover any the user might have set and cache them prior to
executing AC tests. Restore them at the conclusion of configure so the
compiler will see them when building.
Refs #1332 
> Fix support for 32-bit builds

- src/mca/bfrops/base/bfrop_base_stubs.c
Users of PMIx_Data_type_string prior to PMIx_Init receive "not initialized"
which isn't helpful. Instead, provide a base string capability for
use prior to init.
> Provide data type string support prior to Init

- src/mca/ptl/tcp/ptl_tcp.c
Get messages transmitted quickly and trap a SIGPIPE seen occasionally on
BSD/OSX systems
> Add some appropriate socket options

- config/pmix_setup_hwloc.m4
- src/Makefile.am
- src/atomics/sys/atomic.h
- src/include/Makefile.include
- src/mca/pif/Makefile.am
- src/mca/psec/Makefile.am
- src/threads/Makefile.include
- src/threads/thread_usage.h
Ensure we get _all_ the headers exposed and in the correct place
> Correctly handle with-devel-headers

- NEWS
- config/pmix.m4
- configure.ac
- contrib/whitespace-purge.sh
- src/mca/pnet/opa/configure.m4
Thanks to Stephane Goujet for the report
(cherry picked from commit a6c1f8e6e7841c76ac7e16ded5cde4854db96bf1)
> Do not use '==' in m4 test statements

- src/mca/pif/linux_ipv6/pif_linux_ipv6.c
`if_linux_ipv6_open` should add interfaces with global scope to use them to reach any network host.
This ports the fix from https://github.com/open-mpi/ompi/pull/4930
> Fix if_linux_ipv6_open interface filter

- src/mca/base/pmix_mca_base_component_find.c
- src/mca/base/pmix_mca_base_open.c
- src/mca/pnet/opa/pnet_opa.c
- src/mca/pnet/tcp/pnet_tcp.c
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/runtime/pmix_init.c
- src/tool/pmix_tool.c
- src/util/output.c
Ensure there is always enough space and that it is NULL terminated
> Fix use of gethostname

- .gitignore
- include/pmix_common.h.in
- include/pmix_sched.h
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/gds/hash/gds_hash.c
- src/mca/pnet/base/pnet_base_fns.c
- src/mca/pnet/pnet.h
- src/mca/pnet/test/pnet_test.c
- src/server/pmix_sched.c
- test/simple/Makefile.am
- test/simple/simpclient.c
- test/simple/simpcoord.c
- test/simple/simpsched.c
- test/simple/simptest.c
Provide a more flexible definition for pmix_coord_t that supports
arbitrary dimensionality and offers multiple points-of-view for the
fabric. Implement the pnet/test component to provide coordinates based
on an MCA parameter definition for planes, switches, and nodes. Update
the simple tests to exercise it and display the result.
> Complete implementation of network coord support

- config/pmix.m4
- src/util/pmix_environ.c
setenv() is more friendly than putenv() with respect to
valgrind that does not report a memory leak with the former.
> util/environ: use setenv() if available

- src/include/pmix_globals.c
> plug a misc memory leak in the pmix_query_caddy_t destructor

- src/util/pmix_environ.c
Try an approach to resolving the "tainted value" warning by checking the
envar string for NULL-termination. Protect setenv against a NULL input.
> Silence Coverity warning

- NEWS
- src/client/pmix_client_get.c
- src/common/pmix_query.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server_ops.c
- test/simple/simptest.c
The updated PMIx v3.1 Standard defines new attributes for passing arrays
of data for the various levels (job, app, node). This was done in order
to simplify the data being passed to register_nspace, and to support
passing of data that used the same attribute key for each level - e.g.,
the PMIX_NODE_SIZE for multiple nodes. This PR implements at least the
job and app arrays - the node array support remains TBD.
> Implement support for class-based info arrays

- bindings/python/setup.py
> Remove useless requirement for pandoc in Python bindings

- src/client/pmi1.c
- src/client/pmix_client_fence.c
- src/client/pmix_client_get.c
- src/event/pmix_event_notification.c
- src/include/pmix_globals.h
- src/mca/gds/hash/gds_hash.c
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/mca/pnet/base/pnet_base_fns.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- src/tool/pmix_tool.c
- src/util/name_fns.c
- test/pmi_client.c
- test/simple/Makefile.am
- test/simple/simplegacy.c
Legacy interfaces cannot pass the proc whose data they are requesting.
Instead, legacy apps publish keys that have the proc's rank embedded in
them, thus making them globally unique. When requesting the data, the
requestor can only pass PMIX_RANK_UNDEF to PMIx_Get since it has no
other information.
In that scenario, we have to search data from all ranks (since it will
have been stored by rank when it was published) to find the unique key.
Since the datastore components cannot handle PMIX_RANK_UNDEF, we must
also ensure that all data operations involving PMIX_RANK_UNDEF flow
thru the GDS hash component
Also, fix the pmi_client test program - any keys "put" by a process must
be globally unique
> Fix legacy support for PMI-1

- src/client/pmix_client_get.c
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server_get.c
If data is being requested for a different nspace, then correctly direct
it to the right place.
> Cleanup handling of data requests for different nspaces

- examples/client.c
- examples/dynamic.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
The current code focused solely on retrieving modex info for procs where
the "get" request goes up to the PMIx server as there was an assumption
that job-level information would already be available. However, when
asking for information on a different nspace, the job-level info may be
available at the server, but not to the requesting process.
We had a code path to return the job-level info from the other nspace,
but that didn't include the proc-specific portion of the job-level info.
In other words, we returned things like PMIX_UNIV_SIZE but did not
return PMIX_HOSTNAME for each proc in the other nspace. This change
fixes that gap.
As a note for the future: it would be simpler if we just provided a
"hook" to the other proc's shmem region. However, that would require
some additional code …
> Resolve get of proc-specific job-level info from another nspace

- src/mca/pif/bsdx_ipv4/pif_bsdx.c
- src/mca/pif/bsdx_ipv6/pif_bsdx_ipv6.c
- src/mca/pif/linux_ipv6/pif_linux_ipv6.c
- src/mca/pif/pif.h
- src/mca/pif/solaris_ipv6/pif_solaris_ipv6.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/util/pif.h
Avoid confusion over the precise setting of IF_NAMESIZE by the system
and set it to something large enough to cover anything we encounter
> Change IF_NAMESIZE to PMIX_IF_NAMESIZE

- bindings/python/pmix.pyx
- bindings/python/sched.py.in
Check for NULL callback function before executing it.
Correctly pass the node regex in sched.py example
> Minor cleanups in the Python bindings

- bindings/python/pmix.pyx
The key value was being sent to pmix_load_value in
setup_local_support, where pmix_load_value expects
a tuple of value, val_type
> Send value and value type tuple to pmix_load_value

- config/c_get_alignment.m4
- config/pmix_check_compiler_version.m4
- config/pmix_check_icc.m4
and have 'configure CFLAGS=-fsanitize=address' successes
Refs. pmix/pmix#1265
> configury: plug misc memory leaks

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
Currently the python bindings use exceptions,
and these changes update them to return PMIX
error codes instead. This was the newly agreed
upon method going forward.
> Update python bindings to use error codes

- src/mca/common/dstore/dstore_base.c
The key name length was determined incorrectly, which led to truncation when copying the name.
Fixes #1375
>  dstore: fixed truncate key-names while restoring

- bindings/python/client.py.in
- bindings/python/pmix.pyx
Allows PMIx_Get to be called through the
Python bindings interface.
> Add PMIx_Get wrapper in Python bindings

- .travis.yml
- use python 3.5
- install cython
- pass the --enable-python-bindings option to configure
> travis: test python bindings

- .gitignore
- bindings/python/Makefile.am
- bindings/python/client.py
- bindings/python/construct.py
- bindings/python/sched.py
- bindings/python/server.py
- config/pmix.m4
- configure.ac
- test/Makefile.am
- test/python/Makefile.am
- test/python/client.py
- test/python/run_sched.sh.in
- test/python/run_server.sh.in
- test/python/sched.py
- test/python/server.py
- test/simple/Makefile.am
Force use of Python 3. Add the simple binding tests to "make check" when
Python bindings are built.
> Extend the Python binding support

- bindings/python/client.py
- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
The python bindings now represent a
pmix_value_t in python as a dict with
keys of value and val_type, where they
were previously represented as tuples.
> Update value type in Python bindings

- src/client/pmix_client_get.c
- src/server/pmix_server_get.c
- src/util/name_fns.c
- src/util/name_fns.h
When we perform a direct modex request for information on a different
nspace, we need to store that info in the hash table. Otherwise, dstore
will simply ignore it. Add some helpful verbose debug as well.
> Fix xnspace dmodex and add verbose debug

- src/client/pmix_client_get.c
- src/server/pmix_server_get.c
When requesting a piece of job-level data for a namespace not known on
this node, flag that we are only seeking job-level data in the dmodex
request so we don't hang waiting for the remote proc to post its modex
info.
Fixes #1401 
> Resolve request for job-level data

- src/client/pmix_client_get.c
- src/mca/gds/hash/gds_hash.c
Fixing the last problem reintroduced the problem of not getting
job-level data for specific procs when doing dmodex operations across
nspaces. Ensure we return it again. Note, however, that this means we
may be returning significantly more info on a dmodex request than we
used to do.
> Fix xnspace get yet again

- bindings/python/pmix.pxi
- bindings/python/server.py
Updates python darray to use a dictionary
where it was previously a tuple.
> Update python darray type to use dictionary

- bindings/python/sched.py
Use the dictionary type defined in the sched.py
test.
> Fix sched.py to use correct darray type

- src/mca/gds/hash/gds_hash.c
- src/mca/pnet/test/pnet_test.c
- src/mca/pnet/test/pnet_test.h
- src/mca/pnet/test/pnet_test_component.c
- test/simple/simpcoord.c
- test/simple/simptest.c
Use allocated nodes instead of fake ones. Update the MCA param to only
specify the fabric topology and not include #nodes. Update tests to
track changes.
> Cleanup pnet/test component

- bindings/python/client.py
- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/sched.py
- bindings/python/server.py
Update proc type in the python bindings to use
a dictionary with keys of nspace and rank, instead
of tuple.
> Update proc tuple of nspace and rank to use dict

- bindings/python/client.py
- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/server.py
Bring the server module "fence" function into compliance with the
standard. Update the load/unload functions to fix a couple of places
dealing with pmix_info_t. Add check of unsupported attributes to the
tests.
> Cleanup some Python bindings and update test

- config/pmix.m4
First check to see if it was installed as a Python package. If not, then
look to see if the compiler is present - i.e., it was installed via rpm.
> Provide a backup method for finding cython

- bindings/python/client.py
- bindings/python/pmix.pyx
Add python wrapper for PMIx_Publish. I am currently getting an error when calling PMIx_Lookup inside of the PMIx_Lookup python wrapper I am currently working on, so I want to get this one submitted and make sure it is correct. When running the python tests the lookup wrapper for python isn't returning a visible error. 
> Add Python wrapper for PMIx_Publish

- include/pmix_common.h.in
- src/mca/gds/hash/gds_hash.c
- src/mca/pmdl/Makefile.am
- src/mca/pmdl/base/Makefile.include
- src/mca/pmdl/base/base.h
- src/mca/pmdl/base/pmdl_base_frame.c
- src/mca/pmdl/base/pmdl_base_select.c
- src/mca/pmdl/base/pmdl_base_stubs.c
- src/mca/pmdl/ompi/Makefile.am
- src/mca/pmdl/ompi/pmdl_ompi.c
- src/mca/pmdl/ompi/pmdl_ompi.h
- src/mca/pmdl/ompi/pmdl_ompi_component.c
- src/mca/pmdl/pmdl.h
- src/server/pmix_server.c
- test/simple/simptest.c
Programming models often like to provide their applications with custom
environmental variables to help guide their execution. Making every
resource manager wishing to support direct launch of such apps write
their own code to provide those envars is burdensome, which means users
cannot rely on their presence.
Provide a mechanism by which programming models that want to can
contribute a plugin that allows any PMIx-enabled RM to supply the custom
environment without generating their own code, and can forward
model-specific envars from frontend to backend.
> Add ability to provide custom environments

- bindings/python/pmix.pyx
- bindings/python/sched.py
The python generate regex function was calcuating the
length of the returned regex from PMIx_generate_regex
incorrectly. It was also indexing into regex with the
incorrect values. This was caused by the recent changes
to what is returned by the PMIx_generate_regex function.
Also, code was never entering this block:
```c
if "pmix" == regex[:4]:
```
Even when it should have, so I think the second commit should fix that, where I convert
the byte literal to ascii. 
> Fix python generate_regex function

- include/pmix.h
- include/pmix_common.h.in
- src/common/pmix_iof.c
- src/common/pmix_security.c
- src/event/pmix_event_registration.c
Update the Job/Monitor blocking signatures. Update the event registration
signatures to return a status. Update behavior of IOF and credentials
functions to return status.
> Update blocking APIs to match standard

- bindings/python/client.py
- bindings/python/pmix.pyx
- bindings/python/sched.py
- bindings/python/server.py
- src/mca/gds/hash/gds_hash.c
Need to use "def" instead of "cdef" on Python class function
definitions. If we don't have a new object, then don't update the list
in gds_hash.
Fixes https://github.com/pmix/prrte/issues/252
> Fix some Python bindings and avoid double-ref of list item

- src/common/pmix_iof.c
- src/event/pmix_event_registration.c
Some of the new blocking fn forms use a shortcut to resolve the thread
lock. Ensure the lock object doesn't get released too soon.
> Fix some double-free errors

- bindings/python/client.py
- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/sched.py
- bindings/python/server.py
Server and client functions for publish, unpublish, and lookup. Also uses the thread shift example to call the lookup callback, but I think that maybe needs some work in terms of how to generalize it for the rest of the callback functions. 
- Add client and server module functions
publish, unpublish, and lookup
- Add initial thread shifting with timer
based on example in PR #1457 using
lookup callback function
- Add load and unload functions for pdata
struct
> add python wrappers and server host functions

- config/pmix.m4
> Check for the new required functions

- bindings/python/client.py
- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/sched.py
- bindings/python/server.py
Add query client wrapper, and server
module function. This also adds NULL
terminator to pmix_load_argv, and
the alloc_info function was removed.
> add python query_info client wrapper

- src/server/pmix_server_ops.c
This can cause a hang in a Fence call since the trk->local
is not properly initialized. Default trk->local to false,
and set it to true if after looping through all the procs
they are accounted for.
> Initialize nlocal and local in the tracker.

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
This change got reverted because we believed it to be the source of the memory corruption we were seeing. Turns out that was in the pmix_load_argv function. I rebuilt the python bindings and ran ./server.py and ./sched.py successfully. So, I believe it to be working. 
Created pmix_alloc_info since most of the info struct
memory allocation and error checking code was the same
in every wrapper. This reduces the amount of code in
each wrapper.
> Add helper function for allocating info structs

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/tests/client.py
- bindings/python/tests/server.py
- bindings/python/tests/server_upcalls.py
- src/event/pmix_event_registration.c
- test/simple/simpclient.c
- test/simple/simptest.c
The GIL was causing the pyeventhandler to lock up. Occasionally on some test runs the user event handler is not invoked, or the Register_event_handler (blocking) call from the C API returns a -1. So I'm still working on what is going on there.
> Pyeventhandler

- src/client/pmix_client.c
- src/client/pmix_client_get.c
- src/event/pmix_event_registration.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/common/dstore/dstore_base.c
- src/mca/gds/hash/gds_hash.c
- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_stubs.c
- src/mca/ptl/ptl_types.h
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- test/pmix_test.c
- test/run_tests.pl.in
- test/test_common.c
- test/test_common.h
- test/test_fence.c
- test/test_resolve_peers.c
- test/test_server.c
- test/test_server.h
**Provide some handy definitions for comparing release versions.** 
Update the dbase store_job_info function to check for an earlier version and translate the node info array, extracting and storing just the local peers for each node.
**Try to fix the "test" area**
The tests do not correctly compute the node and proc maps when running
with multiple servers - they only compute those values for the local
server. This wasn't detected in the past because we weren't using that
info. However, now that we are correctly tracking info by node, this
causes the tests to become confused and fail.
I was unable to get the tests to correctly compute the pattern of proc
assignments for multiple servers, so just tell the tests to only run one
server until someone with more knowledge of this code can fix …
> Cache local peers in deprecated form for older versions, try to fix the "tests", continue workaround of dstore

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
There can be a race condition between registration and recording the
event handler in the myevhdlr list. If we lose that race, then just
cache the event in a timeshift and try again.
> Python: Cache events if evhdlr not found

- bindings/python/pmix.pyx
- bindings/python/tests/client.py
- bindings/python/tests/server.py
The client.py program was finalizing before the event handler had a
chance to actually be invoked. A better solution would be to "hold"
client.py until the handler was invoked and had returned using the
available handshake protocols in the event handler callback, but this
suffices to illustrate the situation
> Clarify tests to show that Python evhdlrs are being invoked

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
Add correct return to directmodex server module function,
and allocate memory for strings in caddy objects for both
directmodex and fencenb.
> python: add correct return from directmodex

- src/client/pmix_client_get.c
- src/common/pmix_log.c
- src/mca/gds/hash/gds_hash.c
- src/mca/preg/native/preg_native.c
- src/mca/ptl/base/ptl_base_stubs.c
- src/server/pmix_server_ops.c
- test/simple/simpclient.c
- test/simple/simptest.c
Deal with earlier versions and their expectations for node-level info
Tested against v2.2 and v3.1
(cherry picked from commit cbf3da75def731cc5770c794ccc237f59d5cde98)
> Further cleanups for xversion support

- README.md
Name of the repo changed from pmix to openpmix, so the
Travis links to the build status were incorrect.
> update README links so build status shows

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/setup.py
- merged all pyshift structs into one with all
of the fields needed to invoke callback functions
created so far
- moved callback function wrappers to pmix.pxi
- added flag to setup.py file in order to see pyx
file line numbers when warnings and errors are
printed
> python: cleaup pyshift structs

- src/client/pmix_client_get.c
- test/simple/simpclient.c
Ensure we only look at rank=wildcard locations for node-level data when
dealing with older servers. Update simpclient to exit with errors.
> Fix support for older servers

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
1. Add toolconnected and allocate callbacks, invocations,
and return correct data from their servermodule functions
2. Add client wrapper for PMIx_Process_monitor
3. Add client wrapper for PMIx_Get_credential and server cb to server module function
4. Add client wrapper for PMIx_Validate_credential and server cb to server module function
> python: add callbacks and client wrappers

- test/cli_stages.c
- test/cli_stages.h
- test/pmix_client.c
- test/pmix_test.c
- test/test_server.c
Use SIGCHLD detection to determine that a child has exited as it is more reliable. Track the returned exit codes to help determine success or failure of the overall tests. Minor cleanup of the exit status for pmix_client.
> Update the "make check" tests

- test/cli_stages.c
- test/cli_stages.h
- test/pmix_client.c
- test/pmix_test.c
- test/run_tests.pl.in
- test/test_cd.c
- test/test_fence.c
- test/test_internal.c
- test/test_publish.c
- test/test_replace.c
- test/test_resolve_peers.c
- test/test_server.c
- test/test_spawn.c
Update the "make check" tests
Use SIGCHLD detection to determine that a child has exited as it is more reliable. Track the returned exit codes to help determine success or failure of the overall tests. Minor cleanup of the exit status for pmix_client.
Add timeout capability to make check
Take a pass thru tests ensuring they exit with error
> Update "make check" tests

- test/cli_stages.c
- test/pmix_client.c
- test/test_common.h
The event handler wasn't implemented correctly - it has to thread shift and issue the callback per the standard.
(cherry picked from commit 0cc0c4877aafe80e7d43c83b445af5ed789fa7eb)
> Remove event handler registration from tests

- .github/actions/mlnx/Dockerfile
- .github/actions/mlnx/action.yml
- .github/actions/mlnx/entrypoint.sh
- .github/workflows/main.yml
Original testing string was here:
https://github.com/mellanox-hpc/jenkins_scripts/blob/master/jenkins/pmix/pmix_jenkins.sh
This scipt became an `entrypoint.sh` for MLNX Actions with the following
key differences:
1. Removed COverity related code. PMIx uses official scan for that.
2. Removed Jenkins specific code. Variables with `jenkins` in name were
not renamed to keep files comparable.
3. `make check` is now part of the build
> CI: enable MLNX CI using Github Actions

- test/test_common.h
- test/test_server.c
When performing xversion tests, earlier versions don't understand that a
fake node name is in use.
>  Remove fake nodenames as it confuses earlier versions

- test/pmix_test.c
- test/test_common.h
- test/test_resolve_peers.c
- test/utils.c
When performing xversion tests, earlier versions don't understand that a
fake node name is in use.
> Remove fake nodenames as it confuses earlier versions

- src/mca/common/dstore/dstore_base.c
Earlier clients are looking for node info as a data array with the name of the node as the key.
> Correctly xfer node-level data arrays for pre-v3.1.5 clients

- src/client/pmix_client.c
- test/test_resolve_peers.c
Servers prior to v3.1.5 don't properly track information such as
local_peers on a per-node basis. So ensure we try to access peer info in
a manner consistent with the server's version.
Also, the test servers in older versions just return "not found" for
direct modex requests. This means that resolve_peers is guaranteed to
fail for requests of information about other namespaces, so don't
include such tests in that situation.
> Deal with servers using older versions

- src/mca/common/dstore/dstore_base.c
- test/pmix_test.c
Ensure that earlier versions get the full set of node-level info
properly transferred to the dstore. Minor fixes of the tests
> Continue repairs of xversion make check tests

- .gitignore
- src/client/pmix_client.c
- src/client/pmix_client_fence.c
- src/client/pmix_client_ops.h
- test/simple/Makefile.am
- test/simple/pmitest.c
Allow singleton operations, at least for simple functions such as init,
put, commit, fence, and get. Add a simple PMI-1 test code for some of
the features.
> Fix singleton initialization

- include/pmix.h
- include/pmix_common.h.in
- include/pmix_server.h
- src/client/pmix_client.c
- src/common/pmix_iof.c
- src/common/pmix_iof.h
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/tool/pmix_tool.c
Also cleanup the IOF tracking code to ensure we accurately track the
evhandler ID. Implement the ability to return the IO to a specified
cbfunc instead of just printing it to stdout/err
> Add missing IOF_deregister function

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
1. uncomment iof_deregister wrapper
2. fix/update type of payload input parameter to pyiofhandler
> python: add iof_deregiter and update pyiofhandler

- .github/actions/mlnx/Dockerfile
- .github/actions/mlnx/action.yml
- .github/actions/mlnx/entrypoint.sh
- .github/workflows/main.yml
Original testing string was here:
https://github.com/mellanox-hpc/jenkins_scripts/blob/master/jenkins/pmix/pmix_jenkins.sh
This scipt became an `entrypoint.sh` for MLNX Actions with the following
key differences:
1. Removed COverity related code. PMIx uses official scan for that.
2. Removed Jenkins specific code. Variables with `jenkins` in name were
not renamed to keep files comparable.
3. `make check` is now part of the build
Signed-off-by: Andrey Maslennikov <andreyma@mellanox.com>
(cherry picked from commit 809e58f666a9b1b907c41ab38d145f9d80c23760)
> CI: enable MLNX CI using Githaub Actions — v3.1

- src/mca/common/dstore/dstore_base.c
Signed-off-by: David Solt (dsolt@us.ibm.com)
Conflicts:
src/mca/common/dstore/dstore_base.c
(cherry picked from commit ffa96007a4a629723f3779034e60fe8d1deddc35)
> Fix memory leak as explained in issue 1548

- src/common/pmix_iof.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/tool/pmix_tool.c
We need to track both the local and remote reference IDs on IOF requests
to avoid causing the pointer array to allocate excessive space. Ensure
we always create the default registration request at the tool to match
what the server is doing.
Fixes https://github.com/openpmix/prrte/issues/259
> Cleanup IOF registration

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/tests/cython/cython_test_functions.pyx
- bindings/python/tests/cython/test_cython.py
This adds initial cython test structure, and adds tests for pmix_load_value, and pmix_alloc_info. The pmix_load_value functions tests all datatypes. I found two bugs with this test in that function so far. 
Note: I wasn't sure the best way to build the .pyx file with the cython test functions, because they test functions in the .pxi file I couldn't compile it as a separate module and have access to those functions. Not sure if you have any better ideas of how to incorporate/build these tests. 
Also, REGEX type is missing from the type conversion table of the v4 API documentation for Python. And in the sched.py test the regex is generated with an API call, then passed into the PMIX_NODE_MAP as a PMIX_STRING. So, I'm not sure if it is a string now or a separate type?
> python: add initial cython test structure

- config/pmix_functions.m4
- src/tools/pmix_info/Makefile.am
Allow to override build date+host+user with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
Also switch to UTC to be independent of timezone.
Also use ISO 8601 date format to be easier to parse.
Note: This date call is designed to work with different flavors
of date (GNU, BSD and others).
If only GNU (Linux) support is needed, the patch can be simplified.
This PR was done while working on reproducible builds for openSUSE.
For reproducible builds, it would also be a good solution to just drop one or both of these date+user+host to avoid the added complexity.
> configury: Allow to override build date+host+user

- src/server/pmix_server_ops.c
After reviewing #1471 I think that there is no need in `ns_local` anymore.
The whole point behind it was to verify that in case of a wildcard all processes in the namespace are located on the local node (on the per namespace basis).
What the code does now - it is filtering all the local ranks from the fence signature, and then this value is compared to the total process count.
I agree this is a cleaner way, so let's get rid of `ns_local`.
> Simplify tracker initialization

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/tests/cython/cython_test_functions.pyx
- bindings/python/tests/cython/test_cython.py
- src/mca/bfrops/base/bfrop_base_stubs.c
- add missing data conversion function for PMIX_REGEX
- add tests for pmix_value_unload on all type values
> python: add missing data conversions for types

- examples/alloc.c
- examples/asyncgroup.c
- examples/client.c
- examples/dmodex.c
- examples/dynamic.c
- examples/fault.c
- examples/group.c
- examples/jctrl.c
- examples/pub.c
- examples/pubi.c
* Fixes #1133
* Remove `pmix_value_t *val = &value` where not meaningful.
* Cleanup a few places where `val` was not released, and a couple
of other minor memory leaks.
> Cleanup example use of pmix_value_t

- bindings/python/pmix.pxi
- bindings/python/tests/cython/cython_test_functions.pyx
- Add missing functionality for unloading data arrays
in Python
- Add support for PMIX_BOOL and PMIX_BYTE in
pmix_load_darray
- Fix bugs in pmix_load_darray
- Add tests for more darray types
> python: add pmix_unload_darray function

- src/mca/gds/ds12/gds_ds12_lock_pthread.c
- src/mca/gds/ds21/gds_ds21_lock_pthread.c
Do not try to set pthread_rwlockattr_setpshared with PTHREAD_PROCESS_SHARED when it is not available.
Do not try to use pthread_mutexattr_setpshared() when it is not available
Thanks to @geowiwi for the report and the patch
Fixes #1577
(cherry picked from commit 164e8041106e8fe2174efacaac23749331192633)
> Protect pthread setpshared calls

- config/pmix.m4
- config/pmix_check_lock.m4
- config/pmix_config_pthreads.m4
- src/mca/gds/ds12/configure.m4
- src/mca/gds/ds12/gds_ds12_lock_pthread.c
- src/mca/gds/ds21/configure.m4
- src/mca/gds/ds21/gds_ds21_lock_pthread.c
After digging deeper into two reports of error log outputs from dstore
components that were built but could not run, it turned out that there
were a few compensating errors in the dstore configure code. First, the
use of AC_EGREP_HEADER was incorrect as it always failed - that function
looks for an exact match of the output from "egrep" and the provided
pattern. Instead, egrep was outputting the entire line that contained
the provided string, resulting in it always failing.
Someone clearly realized things were failing as the result of that test
was never being used. This led to error logs being emitted by ds21 when
attempting to run on systems that actually didn't support that specific
option.
What needed to happen was to correctly test for the existence of the
option and the …
> Correct the gds/dstore configure logic

- src/mca/gds/ds12/gds_ds12_lock_pthread.c
Don't output an error log if the server has already removed a lock
> Silence error log

- src/mca/gds/hash/gds_hash.c
- src/mca/preg/native/preg_native.c
- test/simple/simpclient.c
Ensure we capture the number of procs in the nspace tracker when
registering an nspace so we don't lose proc-specific data.
Check the proc/node map types for string vs regex
Ensure the "pmix" regex string retains the NULL terminator
> Fix bugs in gds/hash and preg/native

- src/mca/pnet/simptest/Makefile.am
- src/mca/pnet/simptest/pnet_simptest.c
- src/mca/pnet/simptest/pnet_simptest.h
- src/mca/pnet/simptest/pnet_simptest_component.c
- test/simple/netconfig.txt
- test/simple/simpcoord.c
- test/simple/simptest.c
Add a simple pnet component that reads a config file to define
coordinates for each node. Update the simpcoord test to not error out if
endpts are not found as they may not be assigned
> Add pnet/simptest component

- HACKING
- contrib/Makefile.am
- contrib/platform/optimized
It wasn't actually optimizing the code other than to set the
--disable-debug flag. If you truly want to optimize, you also need to
set the appropriate -O compiler flags, so this was just misleading
people.
> Remove the "optimized" platform file

- include/pmix_common.h.in
- src/include/pmix_globals.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
There are several problems needing to be addressed. First, there exists a very small race condition window between registration of nspaces and/or clients and receipt of a collective operation request from a local client. We were trying to do too much in the register_client area, resulting in some potential area to miscount the number of local participants. Sadly, we weren't looking for this race condition at all in the register_nspace code. It could be that this race shouldn't happen, but I decided to protect against it just to be safe.
Second, the code in the "new_tracker" area wasn't correct. Cleanly separating out the various possible scenarios helps clarify the logic and avoid some of the problems.
I added quite a few comments to the code to help people understand the flow. …
> Re-address the collective tracker problem

- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
There remain some issues about detecting local vs non-local procs when
setting up the tracker. I've resolved the ones surfaced by multi-node
testing using PRRTE with both simple PMIx clients and the "double-get"
test case. This is a subset of those changes as the broader ones failed
to pass CI - hopefully, this minimum subset does and then I'll try again
with the remainder.
For this subset, we use the fact that we are being told both the number
of local procs and the total number of procs in a namespace upon call to
"register_nspace". If we are in a collective and have not yet received
the "register_nspace" call, then we defer processing of the collective
until we do.
> Complete debugging of the collective tracker

- include/pmix_common.h.in
- src/client/pmix_client_get.c
- src/server/pmix_server_get.c
Define a new PMIX_GET_REFRESH_CACHE attribute by which a user can direct
PMIx to perform a dmodex operation, thereby obtaining a new copy of the
remote data. Anything that has been added or changed will be included.
Note that there is no current mechanism for _deleting_ information once
a process has put/commit it.
> Allow user to request cache refresh

- include/pmix_common.h.in
Restore the PMIX_DEBUG_TARGET attributes that somehow was mistakenly
removed. Add two new attributes for dealing with PMIx_Get requests:
PMIX_GET_REFRESH_CACHE: refresh the local datastore with information
posted by the remote proc. Noop for local procs.
PMIX_REQUIRED_KEY: used to pass the key being requested from the PMIx
server library to its host via the dmodex interface.
> Add some attributes

- src/client/pmix_client_get.c
- src/mca/common/dstore/dstore_base.c
- src/mca/gds/hash/gds_hash.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- test/server_callbacks.c
- test/simple/simpclient.c
- test/simple/simptest.c
- test/simple/simptest.h
- test/test_fence.c
A dmodex operation is triggered whenever the key being requested is not
found in the local cache. Include the specified key in the request
passed from the client to the local server. Have the server check for
that key in its own storage - if it isn't present, then pass the request
to the host thru the dmodex interface with the key being identified by
including the PMIX_REQUIRED_KEY attribute in the info array.
The rest of this fix is in the PRRTE PR that cannot be filed until this
one has been committed due to the new attribute definition.
> Properly support dmodex requests

- .github/actions/mlnx/entrypoint.sh
- .gitignore
- config/pmix.m4
- src/client/pmix_client_get.c
- src/server/pmix_server_get.c
- test/Makefile.am
- test/run_tests.pl.in
- test/simple/Makefile.am
- test/simple/doubleget.c
Protect against double-free of the pmix_info_t array in the
pmix_server_caddy object.
Add doubleget test and remove stale code
> Ensure the switchyard doesn't prematurely release the server caddy

- src/mca/common/dstore/dstore_base.c
- src/server/pmix_server_get.c
- test/test_fence.c
Better differentiate when we want the switchyard to release the server
caddy.
> Correct return status when trackers are created

- src/mca/common/dstore/dstore_segment.c
The bug was discovered in #1605. The previous version was returning an
unsigned representation of `-1` which resulted in 0-size mmap argument.
(see #1605 for the details)
> dstore: Fix cache size calculation

- config/pmix.m4
- config/pmix_check_curl.m4
- config/pmix_check_jansson.m4
- detect/add libjansson for JSON parsing
- detect/add libcurl for http connections
This only detects the availability of these libraries - future work will
utilize them but only when configured to do so. Note that PMIx is not
going to act as a REST server - this is intended to allow a PMIx server
to request services from a system-level REST server.
> Add configury to support REST interface interactions

- src/client/pmix_client_get.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
When the "fastpath" code was added, it was put in the PMIx_Get call.
This broke the model of PMIx_Get acting as a wrapper for PMIx_Get_nb,
resulting in calls to PMIx_Get_nb behaving differently than its
non-blocking form. Furthering the problem, the code to detect and
resolve requests for node and app-level info also went into PMIx_Get as
it was intended to protect the call to "fastpath".
Realigning the two "get" functions requires moving the "fastpath" and
node/app info code down into PMIx_Get_nb. The "fastpath" code still
avoids the threadshift, which was the original intent. However, now the
two APIs behave the same again.
> Realign behavior of PMIx_Get and PMIx_Get_nb

- src/tool/pmix_tool.c
Don't complain and drop it on the floor - just print it out
(cherry picked from commit abe0e35a6c6e29e7a6609cf2d88ed1d1499fbd4e)
> Properly handle forwarded output when no handler registered

- include/pmix_common.h.in
- src/client/pmix_client_spawn.c
- src/mca/pfexec/base/base.h
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/mca/pfexec/base/pfexec_base_frame.c
- src/mca/pfexec/linux/pfexec_linux.c
- src/mca/pfexec/pfexec.h
- src/mca/ptl/tcp/ptl_tcp.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/tool/pmix_tool.c
- src/util/os_dirpath.h
Fix the internal fork/exec support so it can return the nspace of the
spawned child job. Ensure we give each child job a unique nspace.
Separate rendezvous file generation from attachment to allow for
chaining of connections (e.g., debugger -> launcher -> DVM)
Ensure we cleanup completely upon terminating a tool/server that has
dropped rendezvous files
> Fix fork/exec and provide better tool support

- src/common/pmix_iof.c
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/mca/pfexec/base/pfexec_base_frame.c
- src/mca/pfexec/linux/pfexec_linux.c
Only remove the child object once from the tracker list
> Fix race condition between pfexec and iof

- src/common/pmix_iof.c
- src/common/pmix_iof.h
- src/mca/pfexec/base/pfexec_base_frame.c
libevent can get upset if you delete an event that is not active
Fix IOF race condition
Ensure we only call "check_complete" once both stdout **and** stderr read
events have terminated.
> Check for active event before deleting

- src/client/pmix_client_get.c
Try another method for determining if we need to skip the dstore when
looking for node/app-level info.
> Another approach to resolve fast/slow get path

- include/pmix_common.h.in
Allow tools to request diagnostic info when a job times out
> Add attributes to support tool-requested timeout

- src/common/pmix_iof.c
> Turn off useless error log

- include/pmix_common.h.in
- src/include/pmix_globals.h
- src/mca/gds/hash/gds_hash.c
- src/mca/pmdl/ompi/pmdl_ompi.c
Ensure the programming models get updated with client and nspace info.
Add attribute for passing the original cmd line for an app.
> Pass additional required values

- src/mca/ptl/tcp/ptl_tcp_component.c
Use the "remove" function instead of "unlink" as it is more reliable
> Ensure cleanup of rendezvous files

- src/mca/pfexec/base/pfexec_base_frame.c
- src/mca/ptl/tcp/ptl_tcp.c
- src/tool/pmix_tool.c
Ensure the sigchld event has been stopped prior to dismantling the list
of pfexec children
Take a shot at fixing the prun-prte connection creation
Give prte a little more time to create the rendezvous file. Resolve a
race condition where the file may have been created, but prte hasn't yet
had a chance to write its rendezvous info into it.
> Fix a race condition during finalize

- .gitignore
- Makefile.am
- config/pmix_setup_libev.m4
- configure.ac
- maint/pmix.pc.in
This PR adds the generation and installation of a pmix.pc file which would allow the PMIx libs and cflags (as well as its dependencies) to be found by pkg-config.
At the moment the generated pmix.pc file contains hard-coded dependencies to hwloc and libevent, so it is appropriate for use only when PMIx is installed with hwloc and libevent support. These dependencies are hard-coded in configure.ac (lines 262 to 279).
The next step would be to make these variables depend on what is actually needed (i.e. not add hwloc if it's not enabled, add the libev libraries instead of libevent if PMIx is compiled with libev, etc.)
> WIP: Generating a pkg-config file

- include/pmix_common.h.in
- src/mca/common/dstore/dstore_base.c
- src/mca/gds/hash/gds_hash.c
Remote nodes may know themselves by a name different than the one known
to the launcher. Provide an attribute for communicating the known
aliases and ensure that the local node info can be identified.
> Check hostname aliases to ensure xfer of job-level info

- include/pmix_common.h.in
- src/client/pmix_client.c
- src/mca/gds/hash/gds_hash.c
- src/mca/ptl/tcp/ptl_tcp_component.c
Ensure we check cached notifications upon tool or client connection.
Properly return UNREACH error status from PMIx_Init when no server is
detected so the caller can decide if they want to proceed or terminate.
Silence a Coverity warning in gds/hash.
> Ensure notification upon connect and fix PMIx_Init return code

- config/pmix.m4
- src/mca/pcompress/zlib/configure.m4
Need to add required libs to the PMIX_EMBEDDED_xxx values so that OMPI
can extract them for adding to the wrapper flags
> Update embedded flags for extraction by OMPI

- src/event/pmix_event_notification.c
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
Pass nspace/rank to the fork/exec'd child, taking into account it could
be a server. Add lots of verbose debugging output to the event
notification code for debugging purposes
> Pass nspace/rank on fork/exec and cleanup notify

- config/pmix_check_vendor.m4
Tracks https://github.com/open-mpi/ompi/pull/7385
(cherry picked from commit 3d67fda95700bcaef3a81dd4c41d7ded6df4da43)
> v2.2: Update "check_vendor" for PGI problem

- src/client/pmix_client_spawn.c
- src/mca/base/pmix_mca_base_open.c
- src/mca/base/pmix_mca_base_var.c
- src/mca/pmdl/base/base.h
- src/mca/pmdl/base/pmdl_base_stubs.c
- src/mca/pmdl/ompi4/pmdl_ompi4.c
- src/mca/pmdl/ompi4/pmdl_ompi4.h
- src/mca/pmdl/ompi5/pmdl_ompi5_component.c
- src/mca/pmdl/oshmem/Makefile.am
- src/mca/pmdl/oshmem/pmdl_oshmem.c
- src/mca/pmdl/oshmem/pmdl_oshmem.h
- src/mca/pmdl/oshmem/pmdl_oshmem_component.c
- src/mca/pmdl/pmdl.h
- src/mca/pnet/base/pnet_base_fns.c
- src/mca/pnet/opa/pnet_opa.c
- src/mca/pnet/tcp/pnet_tcp.c
- src/util/pmix_environ.c
- src/util/pmix_environ.h
Pickup the user-defined default parameter file values for forwarding.
This assists in scalability by allowing user-default values without
every proc referring back to the home directory. Add component to
support OSHMEM.
> Enhance harvesting of envars for OMPI/OSHMEM

- config/pmix_setup_wrappers.m4
When running on a Mac, Apple's libtool does not support the "--config"
option. This leads to configure generating an error that can be
misleading. We _could_ use "glibtool" to perform the check, but we are
actually using Apple's libtool to do the build, so best to just silently
return the error
> Silence errors coming out of libtool config check

- test/test_v2/Makefile
- test/test_v2/cli_stages.c
- test/test_v2/cli_stages.h
- test/test_v2/pmix_regex.c
- test/test_v2/pmix_test.c
- test/test_v2/server_callbacks.c
- test/test_v2/server_callbacks.h
- test/test_v2/test_common.c
- test/test_v2/test_common.h
- test/test_v2/test_server.c
- test/test_v2/test_server.h
- test/test_v2/utils.c
- test/test_v2/utils.h
This is the start of the new PMIx test suite per @artpol84 's guidance. 
This initial version only includes pmix_test.c and all its dependencies, and nothing else, in a new subdirectory of test called test_v2. 
For now it is built using a custom Makefile and is not touched by configure, so it will not be part of the regular build process, nor enabled, for now. The idea is that for a period of time it will be run independent of/in parallel to the existing test suite.
> Added test_v2 directory for new version of test suite (#2)

- src/mca/common/dstore/dstore_base.c
- src/mca/pmdl/base/pmdl_base_stubs.c
- src/mca/pmdl/ompi4/pmdl_ompi4.c
- src/mca/pmdl/ompi5/pmdl_ompi5.c
- src/mca/pmdl/pmdl.h
- src/mca/pshmem/mmap/pshmem_mmap.c
OMPI expects to see some envars. The ompi4 component already knows to
set them, but OMPI5 did not as it was expecting them to be set in PRRTE.
However, we are going to move all that across anyway, so have it done in
PMIx now.
> Cleanup a bit and ensure ompi5 sets envars

- src/client/pmix_client_spawn.c
Blocking call cannot return OPERATION_SUCCEEDED
> Correct return code from PMIx_Spawn

- src/mca/common/dstore/dstore_base.c
- src/mca/common/dstore/dstore_common.h
- src/mca/gds/ds12/gds_ds12_base.c
- src/mca/gds/ds21/gds_ds21_base.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server.c
Following the issue: https://github.com/openpmix/prrte/issues/505
This commit provides `nlocalprocs`, obtained from
`PMIx_server_register_nspace` to the GDS `add_nspace` handler.
> Fixes propagation of the number of local processes to GDS

- src/client/pmix_client_spawn.c
- src/mca/common/dstore/dstore_base.c
- src/mca/common/dstore/dstore_common.h
- src/mca/gds/ds12/gds_ds12_base.c
- src/mca/gds/ds21/gds_ds21_base.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server.c
Fixes propagation of the number of local processes to GDS
This commit provides `nlocalprocs`, obtained from
`PMIx_server_register_nspace` to the GDS `add_nspace` handler.
(cherry picked from commit 1bd9899)
Correct return code from PMIx_Spawn
Blocking call cannot return OPERATION_SUCCEEDED
(cherry picked from commit 30d3dda)
> Backport updates

- src/mca/ptl/usock/ptl_usock.c
Issue was found by coverity.
pmix-2.2.3/src/mca/ptl/usock/ptl_usock.c:164: alloc_fn: Storage is returned from allocation function "strdup".
pmix-2.2.3/src/mca/ptl/usock/ptl_usock.c:164: var_assign: Assigning: "nspace" = storage returned from "strdup(pmix_client_globals.myserver->nptr->nspace)".
pmix-2.2.3/src/mca/ptl/usock/ptl_usock.c:177: leaked_storage: Variable "nspace" going out of scope leaks the storage it points to.
|#  175|           pmix_argv_free(uri);
|#  176|           PMIX_ERROR_LOG(PMIX_ERR_NOT_FOUND);
|#  177|->         return PMIX_ERR_NOT_FOUND;
|#  178|       }
|#  179|       pmix_argv_free(uri);
Error: RESOURCE_LEAK (CWE-772):
pmix-2.2.3/src/mca/ptl/usock/ptl_usock.c:166: alloc_fn: Storage is returned from allocation function "strdup". …
> ptl_usock.c: Fix RESOURCE_LEAK issues

- src/server/pmix_server_get.c
Satisfied requests have already invoked `cbfunc` and must be destructed. Otherwise they keep alive and subject to timer event (if the timer has been enabled), which causes them to try to invoke `cbfunc` again, that leads to segfault.
> Fixes cleanup the dmdx satisfied request list

- src/include/Makefile.include
- src/mca/pmdl/ompi5/pmdl_ompi5.c
Exclude pmix_config.h from tarball
Protect against zero local procs
Don't generate an error if the local size for the node isn't found as it
may not have any local procs
>  Exclude pmix_config.h from tarball and Protect against zero local procs

- src/mca/pnet/base/pnet_base_fns.c
Unless there is a real error, return success
> Correct the returned status from pnet/allocate

- src/mca/pinstalldirs/base/base.h
- src/mca/pinstalldirs/base/pinstalldirs_base_components.c
- src/mca/pinstalldirs/env/pmix_pinstalldirs_env.c
- src/mca/pinstalldirs/pinstalldirs.h
- src/runtime/pmix_init.c
Tools need to be able to pass an install prefix for the PMIx they want
to use, but cannot always pass it in the environment - e.g., if they are
going to fork/exec a PMIx-based application/launcher that uses a
different PMIx library. Provide a code path that lets them pass the
PMIX_PREFIX attribute down into the installdirs framework where it can
set the PMIX_INSTALL_PREFIX field.
> Allow passing of PMIX_PREFIX to PMIx_tool_init

- test/test_v2/Makefile
- test/test_v2/test_init_fin.c
This PR adds a simple Init/Finalize test to the new test_v2 suite.
-The test makes use of the new infrastructure functions.
See issue for test description and expected results for server and client:
https://github.com/openpmix/pmix-tests/issues/60
> Added first test to new test_v2 suite

- config/pmix.m4
- config/pmix_setup_hwloc.m4
- config/pmix_setup_libev.m4
- config/pmix_setup_libevent.m4
The HWLOC, libevent, and libev libraries are all external
dependencies. However, we need to delay adding any required CPPFLAGS,
LDFLAGS, and LIBS until we are done with configure so we don't interfere
with any configure tests.
> Avoid adding external libs until done with configure

- config/pmix_setup_libev.m4
A user might try to configure --with-libev but accidentally provide a
path to libevent. Since some symbols are common between the two
libraries, pick a function to look for that only is in libev, and error
out if they specifically asked for libev and we don't find it.
> Protect against user error

- config/pmix_setup_libevent.m4
* We only need the functionality in `-levent_core`
* We can avoid a potential conflict with other software (e.g., LSF) that
also ship a `libevent` that is unrelated.
> Move from -levent to -levent_core

- include/pmix_common.h.in
- src/mca/pnet/simptest/pnet_simptest.c
- src/util/hash.c
- test/simple/simpcoord.c
Endpts are returned as an array since they can contain multiple endpt
assignments if there are multiple NICs available to the proc. Ensure
that the pnet/simptest component returns at least one endpt since the
simpcoord test/example is looking for it.
> Correctly handle endpt simulation

- config/pmix.m4
- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/pdl/pdlopen/pdl_pdlopen_module.c
- src/mca/pdl/plibltdl/pdl_libltdl_module.c
When doing a dlopen, we apparently strip the extension from the actual
filename to identify the component it relates to, and then add accepted
extensions back to the filename when checking for file existence prior
to loading. Unfortunately, some 3rd party packages (e.g., debuggers)
take our libraries, do a little magic, and then output a copy of the
results into our lib directory - only with a new suffix. So we might get
something like "ourcomponent.so.dbg". We then strip the ".dbg" and add
".so" to it again - and complain that "ourcomponent.so is not found".
Fix the error message so it reports the name of the file it actually
couldn't find, not the name of the component, so it doesn't totally
confuse people.
> Point to the correct file that wasn't found

- config/pmix.m4
- config/pmix_setup_man_pages.m4
- configure.ac
Developers don't typically refer to man pages, and requiring pandoc on
every developer's machine is proving rather controversial. So if we
detect we are building from within a git clone, only require pandoc and
build the manpages if the developer requests it. Otherwise, build the
manpages if there is an adequate pandoc available, but don't if not.
> Don't require pandoc on developer builds

- src/mca/gds/ds21/gds_ds21_lock_pthread.c
A check was added to avoid locks finalization in the error case
when the dstore segment was not created and its pointer is NULL.
> ds21: fixed crash of dstor locks destructor

- src/mca/gds/ds21/gds_ds21_lock_pthread.c
A check was added to avoid locks finalization in the error case
when the dstore segment was not created and its pointer is NULL.
(cherry picked from commit beddd8859e6723153893c9de2a2e014de18adc59)
Corresponds to #1765
> v3.2/ds21: fixed crash of dstor locks destructor

- src/mca/gds/ds21/gds_ds21_lock_pthread.c
A check was added to avoid locks finalization in the error case
when the dstore segment was not created and its pointer is NULL.
(cherry picked from commit beddd8859e6723153893c9de2a2e014de18adc59)
Corresponds to #1765
> v3.1/ds21: fixed crash of dstor locks destructor

- src/mca/gds/ds21/gds_ds21_lock_pthread.c
A check was added to avoid locks finalization in the error case
when the dstore segment was not created and its pointer is NULL.
(cherry picked from commit beddd8859e6723153893c9de2a2e014de18adc59)
Corresponds to #1765
> v2.2/ds21: fixed crash of dstor locks destructor

- config/pmix_setup_man_pages.m4
- src/tools/pmix_info/pmix_info.c
- src/tools/pmix_info/support.c
Indicate whether or not manpages are being built in the configure
summary and in pmix_info
> Add manpage build decision to config summary and pmix_info

- src/client/pmix_client_get.c
- src/common/pmix_data.c
- src/mca/pnet/simptest/pnet_simptest.c
If job-level info isn't found for our own nspace, then we return an
error. If the user wants us to recheck with the server, then they need
to tell us to "refresh cache".
Fix a bug in parsing of the pnet/simptest config file
> Fix a bug in client/get and in pnet/simptest

- config/pmix.m4
- config/pmix_setup_wrappers.m4
The final wrapper setup needs the "libtool" executable to be available
to check for rpath kinds of things.  So make sure we call LT_OUTPUT to
ensure that it exists before we do the final wrapper compiler setup.
> configury: fix final wrapper setup

- config/pmix_check_jansson.m4
We don't support earlier versions than that one.
Fixes #1794 
> Check for libjansson version > 2.11

- src/tools/pattrs/pattrs.c
- src/tools/pevent/pevent.c
- src/tools/plookup/plookup.c
- src/tools/pps/pps.c
- src/tools/pquery/help-pquery.txt
- src/tools/pquery/pquery.c
Need to call pmix_pinstall_dirs_base_init before initializing show_help
to ensure all values are filled in.
> Initialize pinstall info

- src/server/pmix_server.c
Seeing increasing demand for the server to provide info based on the
topology. Need to advise RM's to pass their local topology pointer down
to the server so it doesn't do its own discovery.
> Ensure the PMIx server knows the local topology

- include/pmix_common.h.in
- src/mca/pnet/base/pnet_base_fns.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/util/error.c
Remove a few error codes that are somewhat duplicative or getting too
detailed. Silence a few Coverity warnings. Cleanup a few errors in the
pnet base.
> Cleanup a few error codes and silence coverity warns

- src/event/pmix_event_registration.c
Should support both an array of procs AND a single proc pointer
Fixes https://github.com/openpmix/openpmix/issues/1768
> Fix registration of custom range

- src/tools/wrapper/Makefile.am
* No longer requires `--with-devel-headers` to get the wrapper compiler
> Make `pmixcc` a default binary

- examples/server.c
Signed-off-by: Thomas Naughton <naughtont@ornl.gov>
> examples: initialize var to avoid SEGV

- src/runtime/pmix_params.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
* If all processes participating in the fence are local to the node
then there is an optimization that allows the PMIx Server side
library to complete the call internally without the upcall into
the RM. For RMs that need to monitor the fence calls this poses a
problem as they do not see the upcall.
- This really only became an issue when a RM is trying to support
a protocol like MPIR where they are taking advantage of a
global fence in, in this case, MPI_Init to hold the processes
in that fence operation by preventing it from completing until
the debugger is attached and ready.
- If this optimization is enabled and the fence participants are
all local then the RM does not get the opportunity to hold that
fence since they never receive the upcall.
* This commit adds the …
> Add option to bypass local-only fence optimization

- src/client/pmix_client_get.c
We hadn't really planned on releasing anything beyond rel=5 in the 3.1.x
series, so we hard-coded a check for 3.1.5 in client get. This must be
updated to allow 3.1.6 (plus any future releases in the v3.1.x series)
to pass cross-version tests when the v3.1.x release is acting as the
server.
> Fix cross-version for v3.1.6+

- .gitignore
- config/pmix.m4
- configure.ac
- include/pmix_common.h.in
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/util/error.h
- Remove some leftover references to the wrapper compiler, jansson, curl
- Move `PMIX_INTERNAL_ERR_BASE` back to `pmix_common.h.in` to make it match
the v3.1 branch - just in case anyone was trying to use it.
- Add back the `PMIX_EXTERNAL_ERR_BASE` that was mistakenly taken out
- Remove a couple of leftover references to `pstrg`
> Cleanup a few leftovers from v3.2 sync with master

- config/pmix_setup_cc.m4
equivalent to OMPI PR https://github.com/open-mpi/ompi/pull/8015
suppress 100s of the following messages from icc:
icc: command line warning #10148: option '-Wno-long-double' not supported
Signed-off-by: Howard Pritchard <hppritcha@gmail.com>
> icc: suppress no_long_double

- src/mca/pstrg/lustre/pstrg_lustre.c
The static availsys array is initialized with doubles where the underlying
struct type uses uint64_t resulting in compiler warnings.
Removing all related code using this availsys array as it is only used in
a single path that has no side effect to any other part in the code base.
Signed-off-by: Christoph Niethammer <niethammer@hlrs.de>
> Delete dead code

- include/Makefile.am
- include/pmix_common.h.in
- include/pmix_deprecated.h
- include/pmix_tool.h
> Move deprecated APIs, constants, and attributes to separate header

- config/pmix_check_tm.m4
I encountered a problem when passing `--with-tm=<pbs-dir>` to OMPI, and traced it back to this file: looks like `pmix_check_tm_libdir` was used but never assigned.
For reference, here's what I've been getting before:
```
…
--- MCA component prm:tm (m4 configuration macro)
checking for MCA component prm:tm compile mode... dso
checking --with-tm value... sanity check ok (/opt/x86_64/pbs/)
checking for pbs-config... not found
looking for header in /opt/x86_64/pbs
checking tm.h usability... no
checking tm.h presence... no
checking for tm.h... no
looking for header in /opt/x86_64/pbs/include
checking tm.h usability... yes
checking tm.h presence... yes
checking for tm.h... yes
looking for library without search path
checking for library containing tm_init... no
looking for library in …
```
> Fix TM detection (Torque / PBS Pro)

- src/client/pmix_client_topology.c
- src/mca/ploc/base/ploc_base_stubs.c
- src/mca/ploc/hwloc/ploc_hwloc.c
- src/util/error.h
- test/simple/simpfabric.c
Finally identify the source of the problems and ensure we set the name
of the source when copying the topology. Allocate the bitmap prior to
getting the cpuset. Avoid raising a request to compute distances to the
host if we already tried but can't.
> Cleanup topology support a bit

- contrib/pmix.spec
This proposition adds *-devel RPMs containing headers and shared objects symbolic links when `build_all_in_one_rpm == 0`
With the libpmi split there is therefore 4 package in this situation: `pmix, pmix-devel, pmix-libpmi, pmix-libpmi-devel`
pmix-devel provides:
```
./opt/pmix/3.1.6/include
./opt/pmix/3.1.6/include/pmix.h
./opt/pmix/3.1.6/include/pmix_common.h
./opt/pmix/3.1.6/include/pmix_extend.h
./opt/pmix/3.1.6/include/pmix_rename.h
./opt/pmix/3.1.6/include/pmix_server.h
./opt/pmix/3.1.6/include/pmix_tool.h
./opt/pmix/3.1.6/include/pmix_version.h
./opt/pmix/3.1.6/lib/libmca_common_dstore.la
./opt/pmix/3.1.6/lib/libmca_common_dstore.so
./opt/pmix/3.1.6/lib/libpmix.la
./opt/pmix/3.1.6/lib/libpmix.so
```
In the same way
pmix provides only libpmix.so.* and libmca_common_dstore.so.* and no …
> SPEC add RPM *-devel packages

- src/server/pmix_server_get.c
Eliminate confusion over return status from the "defer" function between
when the "immediate" flag was given versus creation of a new tracker.
Fixes https://github.com/openpmix/openpmix/issues/1803
> Fix "immediate" flag behavior at the server

- contrib/pmix.spec
> Update the rpm spec to remove all references to PMI-1 and PMI-2 libs

- src/client/pmix_client.c
- src/client/pmix_client_get.c
- src/include/pmix_globals.h
- src/mca/common/dstore/dstore_base.c
- src/mca/gds/hash/gds_hash.c
- test/simple/simpclient.c
PMIx_Get was calling its cbfunc from within the API, which is not allowed by the Standard. Also, update realm recognition for app and node, and add session realm detection
> Update realm checks and fix pmix_get for v4

- contrib/perf_tools/pmi2_utils.c
This code doesn't appear to be utilized under normal build conditions in the master branch, but possibly the function is used elsewhere in other branches? 
I discussed it briefly with Artem and Howard, maybe we can talk about it on the weekly call to see if it is still used somewhere.
> Fixed uninitialized data bug in pmi_base64_encode_block

- NEWS
- VERSION
* `.so` version already incremented in PR #1890 so no need to do so here
> VERSION/NEWS: Prepare for v3.2.1rc1

- .github/actions/mlnx/Dockerfile
- config/pmix.m4
We just need Python in some cases (e.g., developer git clones where we
don't have directory.h).  If you have Python, it's probably modern
enough.  So roll back the Mellanox CI that updates to Python 3, and
let's make sure that even older Python works fine.
To be clear: if you're building the Python bindings, you still need
Python >= v3.4 -- that requirement has not changed.  This commit is
more about when you're *not* building the Python bindings.
> Sometimes we just need any version of Python

- contrib/construct_dictionary.py
- src/Makefile.am
- src/include/Makefile.am
Tested with:
```
git clean -dfx ; \
./autogen.pl && \
./configure --prefix=$bogus --with-libevent=$libevent --with-hwloc=$hwloc |& tee config.out && \
make distcheck DISTCHECK_MAKE_FLAGS=-j32 AM_MAKEFLAGS=-j32 AM_DISTCHECK_CONFIGURE_FLAGS="--with-libevent=$libevent --with-hwloc=$hwloc"|& tee distcheck.out
```
> More fixes to dist / construct_dictionary

- config/Makefile.am
- config/pmix_functions.m4
- configure.ac
- Ensure getdate.sh is included in the dist tarball
- Ensure $top_srcdir is set properly
- Use $top_srcdir to find getdate.sh, not $srcdir
Thanks to @tonycurtis for the heads up.  Refs https://github.com/open-mpi/ompi/issues/8182.
> configury: fix getdate.sh woes

- src/client/pmix_client_get.c
Eliminate an unnecessary malloc operation that caused a minor memory
leak every time we went thru PMIx_Get/fastpath
Thanks to @ekeever1 for finding it!
Refs https://github.com/open-mpi/ompi/issues/8166
> Plug a memory leak and optimize a bit

- src/client/pmix_client.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Detect if someone has set an MCA param directing selection of ptl
components. If only usock is permitted, error out with an explanation
since we cannot support that option. Otherwise, silently remove the
restriction.
> Silence usock component warning message

- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/client/ptl_client.c
- src/mca/ptl/client/ptl_client_component.c
- src/mca/ptl/tool/ptl_tool.c
- src/tool/pmix_tool.c
Completely separate tools from clients, pushing the detection of server
URI envars into the ptl/base as that code is common to the two cases.
Ensure that tool_attach_to_server sets up the necessary infrastructure
prior to attempting to connect to the new server.
> Clean up PTL refactoring

- contrib/pmix.spec
Cherry pick of PR #1864 from v3.1 on v3.2.
Creates *-devel RPMs when `build_all_in_one_rpm == 0`. This is usefull for us as we move to v3.2.
> .spec: add *-devel packages

- config/pmix_setup_libevent.m4
- configure.ac
Take hwloc as a dependency ONLY when hwloc is
NOT in embeded mode.
Signed-off-by: Jie Zhang <zhngaj@amazon.com>
> Fix dependency issue with hwloc

- configure.ac
Take hwloc as a dependency ONLY when hwloc is
NOT in embedded mode.
Signed-off-by: Jie Zhang <zhngaj@amazon.com>
> [v3.2] Fix dependency issue with hwloc

- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- test/python/client.py
The comment was correct that we need to threadshift before accessing the
library's event handler chain, but for some reason that wasn't actually
implemented!
> Fix thread conflict in event notification

- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- test/python/client.py
Fix thread conflict in event notification
The comment was correct that we need to threadshift before accessing the
library's event handler chain, but for some reason that wasn't actually
implemented!
(cherry picked from commit dd4d930)
Protect the chain object thru event timeout
(cherry picked from commit 96ea178)
Ensure all processing of event chain occurs in event
(cherry picked from commit a6d6434)
> Event notification updates from master

- src/event/pmix_event_registration.c
Need to copy the event info, not the registration values
> Fix typo in checking cached events

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- test/python/client.py
Use the Python "queue" class to shift the response from an event handler
to meet PMIx Standard requirements instead of a timer - greatly speeds
up the response.
> Fix Python event notification

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- include/pmix_common.h.in
- src/mca/gds/hash/gds_hash.c
- test/pmix_client.c
- test/python/sched.py
- test/python/server.py
Use the queue class to threadshift all server-level responses instead of
doing a timer delay
-----------------------
Let hash search for node/app info on specified proc
If the process has been specified in a PMIx_Get and its node or app
information is requested, then search the proc-level data to get it.
Fixes #1965
-----------------------
Ensure Python progress thread doesn't return early
-----------------------
> Complete revision of Python bindings

- src/client/pmix_client_get.c
- test/pmix_client.c
If the process rank is specified and node/app info is requested, then if
they didn't provide the hostname or appnum, assume they are looking for
info on the node/app to which that proc belongs
(cherry picked from commit 4343a1af90e6ded279bbbbd8b73828d1eb6ac9ac)
> Update the client get per v4.0 Standard

- NEWS
- src/mca/gds/hash/gds_hash.c
- src/mca/ptl/base/ptl_base_listener.c
- src/server/pmix_server_get.c
- test/test_fence.c
When performing a get operation that goes up to the server, check to see
if the key exists in some other scope and return the correct error if it
does. Check for that error and don't "wait" for the data to appear as it
will never do so if it is already posted to a scope outside the range of
the caller.
Protect the socket/bind call when running on Mac.
Update test_job_fence so only one proc tries one time to find a
nonexistent key - helps reduce the runtime of the test
> Protect the socket/bind call and avoid unnecessary key waits

- VERSION
- src/class/pmix_object.h
- src/client/pmix_client.c
- src/client/pmix_client_get.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/tool/pmix_tool.c
Update client_get function and the gds/hash component to support v4. Fix
a few miscellaneous issues.
Add malloc option to support getting memory from the OS as well as from
an alternate memory pool. We will use this later for the new shmem
component.
> Step 2: update client_get and hash component

- src/runtime/pmix_finalize.c
otherwise applications that try to init/finalize pmix multiple times segfault
in second call to pmix_rte_finalize.
> finalize: set hostname in global to NULL

- README
- bindings/python/Makefile.am
- bindings/python/construct.py
- bindings/python/setup.py
- config/pmix.m4
* We need to include both the autogenerated include directory
(in the VPATH) and the static include directory (in src/include)
when building the python bindings.
* Fixes #2003
> Fix Python binding build for VPATH

- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_listener.c
We are getting errors from the "bind" function on ARM machines due to IPv6 interfaces. We don't normally see those, and typically we disable them by default - but PMIx didn't set that default for some reason. Correct that here.
If someone cares about IPv6 support, they will need/want to further debug this behavior
> Disable IPv6 by default

- README
- bindings/python/Makefile.am
- bindings/python/construct.py
- bindings/python/setup.py
- config/pmix.m4
* We need to include both the autogenerated include directory
(in the VPATH) and the static include directory (in src/include)
when building the python bindings.
* Fixes #2003
> v4: Fix Python binding build for VPATH

- config/pmix.m4
- config/pmix_check_ofi.m4
- config/pmix_check_psm2.m4
- src/mca/pnet/base/base.h
- src/mca/pnet/base/pnet_base_fns.c
- src/mca/pnet/base/pnet_base_frame.c
- src/mca/pnet/opa/configure.m4
- src/mca/pnet/opa/pnet_opa.c
Pass the envars to the backend and let the plugin apply them. This provides a generic method that doesn't rely on PRRTE to apply the envars itself.
Cleanup the pnet base
Don't use memory to track all that stuff - let the components decide if they need it
> Update the pnet/opa component to current architecture

- config/pmix_check_ofi.m4
do set libdir-prefix when invoking PMIX_CHECK_PACKAGE()
> configury: fix --with-ofi=DIR handling

- test/test_v2/Makefile
- test/test_v2/base64_enc_dec.c
- test/test_v2/pmix_test.c
- test/test_v2/server_callbacks.c
- test/test_v2/test_clientapp_funcs.c
- test/test_v2/test_common.c
- test/test_v2/test_common.h
- test/test_v2/test_get_basic.c
- test/test_v2/test_get_peers.c
- test/test_v2/test_helloworld.c
- test/test_v2/test_init_fin.c
- test/test_v2/test_server.c
- test/test_v2/test_server.h
This PR is the implementation of https://github.com/openpmix/pmix-tests/issues/66.
It includes a new client test to get job information for all ranks, plus the ability to place ranks on servers (nodes) in a user-specified configuration.
Also included is a commit with bug fixes to prior tests.
> Test to get job info for other ranks + custom rank placement

- config/pmix.m4
- config/pmix_check_ofi.m4
- config/pmix_check_package.m4
- include/pmix_common.h.in
If OFI isn't installed, don't abort unless the user specifically asked for it.
> Cleanup the OFI detection m4

- config/pmix_check_ofi.m4
- src/mca/ploc/hwloc/ploc_hwloc.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.h
- test/simple/simptest.c
Provide an envar version of the HWLOC shmem rndvz info
Allow lower-level libs to attach to the HWLOC shmem region without requiring them to link against PMIx.
-----------------------
Fix bugs in OFI configure and HWLOC component
Protect against --with-ofi being "yes". Add missing function call to hwloc component to get shared memory size
-----------------------
> Various HWLOC support changes plus one OFI config fix

- .gitignore
- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/runtime/pmix_progress_threads.c
- test/simple/Makefile.am
- test/simple/hybrid.c
If someone specifies a first or last overall event and then registers an event relative to them, we need to correctly handle that both during registration and notification.
> Correctly handle precedence for first/last overall events

- config/pmix_setup_cc.m4
- src/atomics/sys/atomic_stdc.h
Clang uses its own fancy builtin c11 atomics. These functions
don't like casting away the volatile pointer, while the gcc
and pgi versions don't take a volatile. Add some configury logic
to detect what to do here.
> Silence PGI atomics warnings, while not breaking clang.

- config/pmix.m4
(cherry picked from commit fcb79a6)
> v3.2: Fix configury so PMIx is compiled with -O3 by default.

- config/pmix.m4
(cherry picked from commit fcb79a6)
> v3.1: Fix configury so PMIx is compiled with -O3 by default.

- src/atomics/sys/atomic_stdc.h
Make special exception for Clang built-in C11 atomics.
Fixes #2050.
Regression caused by #2049.
> Fix clang compliler regression.

- config/pmix_check_vendor.m4
- src/atomics/sys/powerpc/atomic.h
- src/include/pmix_portable_platform.h
By default newer xlc compilers only define __ibmxl__ now.
https://www.ibm.com/support/knowledgecenter/en/SSXVZZ_13.1.6/com.ibm.xlcpp1316.lelinux.doc/compiler_ref/xlmacros.html
> Fix check for IBM xl compilers for v13.1 and later.

- src/client/pmix_client.c
- src/client/pmix_client_topology.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/ploc/hwloc/ploc_hwloc.c
- src/server/pmix_server.c
- test/simple/simpclient.c
Clients are pointed to use PMIx_Load_topology, which must first
check all possible methods by which the server could have shared
it to avoid duplicating topology trees. Discovery is purely a
last resort.
Servers and tools internally setup the topology during "init".
Will share the topology if so directed.
NOTE: all PMIx process types support having an external topology
passed into them at "init".
> Ensure the topology support matches the Standard

- src/mca/ploc/hwloc/ploc_hwloc.c
Ancient versions don't expose it
> Protect HWLOC_VERSION

- include/pmix.h
- include/pmix_common.h.in
- src/common/pmix_data.c
Add an API for embedding a byte object into a buffer.
Add a macro for transferring pmix_value_t data without
allocating a new pmix_value_t
> Extend data buffer support a little bit

- config/pmix_check_package.m4
use the correct name for the cached variable
(so it can be properly un-cached)
This is a backport from open-mpi/ompi@7da50433f799c98de82e2963d2fb5ea5d21663fb
> configury: fix _PMIX_CHECK_PACKAGE_LIB() macro

- src/atomics/sys/atomic_impl.h
Track https://github.com/open-mpi/ompi/pull/8456
> Fix stale definition for PMIX_HAVE_ATOMIC_LLSC_PTR

- config/pmix_setup_cc.m4
With '-g' and '-finline-functions' xlc will throw:
'warning: "-qinline" is not compatible with "-g". "-qnoinline" is being set.'
> Silence -qinline xlc compiler warning.

- src/server/pmix_server_ops.c
Retains transfer of the peer object to the callback function
Fixes #2072 
> Use the provided caddy instead of creating a new one

- config/Makefile.am
- config/pmix_check_cflags.m4
- config/pmix_setup_cc.m4
- Came across this when trying to debug other xlc compiler
issues. The old configury logic would only set certain flags
if the compiler vendor was labeled as 'gnu'. Ie - any non-gcc
build would have far fewer CFLAGS compared to a gcc build.
This change cropped up due to this commit:
a2b2712d368c258782cbcf083742822ffe0dbc35
which changed the way vendors are labeled. Before pretty much
all vendors were labeled as gnu,
Now, however, the vendor may be labeled as 'gnu'/'ibm'/
'portland group'/ect. This change will validate and set CFLAGS
for any compiler instead of assuming they are only valid for gcc.
> Validate CFLAGS individually.

- src/mca/bfrops/bfrops_types.h
Refs https://github.com/open-mpi/ompi/pull/8492#issuecomment-781436490
> Extend check for empty buffer

- include/pmix_common.h.in
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/pstat/linux/pstat_linux_module.c
- src/mca/pstat/test/pstat_test.c
Replace array of char in pmix_proc_stats_t with a single
character as that is all that is actually required.
Fixes https://github.com/openpmix/openpmix/issues/2079
> Fix Python binding build

- src/server/pmix_server.c
The call to PMIx_tool_set_server near line 692 in src/server/pmix_server.c failed with return code -25, PMIX_ERR_UNREACH because the myproc structure passed in this call was uninitialized.
I initialized the myproc structure, which solves the problem.
Signed-off-by: David Wootton <dwootton@us.ibm.com>
> Initialize myproc structure before calling PMIx_tool_set_server

- src/client/pmix_client.c
- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/client/ptl_client.c
- src/server/pmix_server.c
Have the server "self-register" the singleton nspace/proc
so it doesn't reject the subsequent connection attempt.
Enable the client to connect to a specified server when
PMIx_Init is called again. Provide a mechanism by which
the PTL listener can output the connection info to a
provided pipe.
> Enable singleton "comm_spawn" operations

- src/util/argv.c
Tracks https://github.com/open-mpi/ompi/pull/8581
> Avoid zero byte malloc in argv_join_range

- src/mca/pcompress/base/Makefile.am
- src/mca/pcompress/base/base.h
- src/mca/pcompress/base/help-pcompress.txt
- src/mca/pcompress/base/pcompress_base_frame.c
Only emit it once. Add param to silence even that warning.
> Add runtime warning that compression isn't active

- .clang-format
- contrib/clang-format-pmix.sh
This file works with clang-format --style=file to reformat code to match the
style used in PMIx. This type includes:
No tabs. They are not recommended for PMIx and can often screw up the
formatting.
Tab depth: 4. This is what is used throughout the PMIx code base.
Max column width: 100. There currently is no standard for PMIx but we
should aim to use something reasonable.
Braces following function definitions occur un-indented on the following
line.
Braces following other control statements occur on the same line as the
control statement.
Spaces always before open parentheses for control statements (if, while, do,
etc). This is common across the code base but not consistent. No spaces
after function names, and function or macro calls.
Align consecutive macro definitions.
Tracks …
> Add clang format support

- src/event/pmix_event_notification.c
- src/util/name_fns.c
Make the name print format more closely mirror that of PRRTE.
Don't identify the source as the target by default.
> Slight touchups on event notification and name print

- include/pmix_common.h.in
- src/mca/bfrops/v4/Makefile.am
- src/mca/bfrops/v4/bfrop_pmix4.c
- src/mca/bfrops/v4/bfrop_pmix4.h
- src/mca/bfrops/v4/bfrop_pmix4_component.c
- src/mca/bfrops/v401/Makefile.am
- src/mca/bfrops/v401/bfrop_pmix401.c
- src/mca/bfrops/v401/bfrop_pmix401.h
- src/mca/bfrops/v401/bfrop_pmix401_component.c
- src/mca/pcompress/base/help-pcompress.txt
- src/mca/pcompress/base/pcompress_base_frame.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_listener.c
- src/runtime/pmix_init.c
Also restrict compression warning to non-clients
> Update the v4 bfrops for the new types

- src/common/pmix_iof.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
Sometimes the server needs to receive IO forwarded by someone
else or even itself. Allow a server to register for IO, and
enable processes to send messages to themselves.
> Allow servers to receive IOF

- src/common/pmix_iof.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
Pass the correct cbdata to the server response function. Create
a separate response function just to keep things clearer. Init
server to point at itself as its own server.
Fixes https://github.com/openpmix/prrte/issues/744
> Fix IOF dereg
