openpmix/openpmix

include/pmix/pmix_common.h, man/pmix_constants.7.md, src/client/pmix_client.c
* PMIx_Init(NULL) is supported
* Incomplete PMIx_constants man page had some lingering cruft
* Missing prototype for pmix_value_load
Fixes #11
Fixes #12
Fixes #13
=> Fix several issues identified by Paul Hargrove:

src/client/pmix_client_get.c
@rhc54 @jladd-mlnx 
Hello,
I'm seeing frequent crashes when launching latest OMPI with **mpirun**. Here is what I'm getting on stderr:
```
[cn-xxx:26242] *** Process received signal ***
[cn-xxx:26242] Signal: Segmentation fault (11)
[cn-xxx:26242] Signal code: Address not mapped (1)
[cn-xxx:26242] Failing at address: 0x30
[cn-xxx:26242] [ 0] /lib64/libpthread.so.0[0x3d7560f710]
[cn-xxx:26242] [ 1] /tmp/artemp-ompi/lib/libpmix.so.0(+0x23833)[0x7ffff6396833]
[cn-xxx:26242] [ 2] /tmp/artemp-ompi/lib/libpmix.so.0(OPAL_PMIX_PMIX1XX_PMIx_Finalize+0x3af)[0x7ffff63981cf]
[cn-xxx:26242] [ 3] /tmp/artemp-ompi/lib/openmpi/mca_pmix_pmix1xx.so(pmix1_client_finalize+0x46)[0x7ffff65cb636]
[cn-xxx:26242] [ 4] /tmp/artemp-ompi/lib/openmpi/mca_ess_pmi.so(+0x45c8)[0x7ffff67df5c8]
[cn-xxx:26242] [ 5] …
```
=> Fix race condition in PMIx_Get/PMIx_Get_nb

config/Makefile.am, config/pmix_check_icc.m4
Thanks Paul Hargrove for the report
=> configury: add missing PMIX_CHECK_ICC_VARARGS function

src/server/pmix_server.c, src/util/hash.c
Remove code that makes logic hard to understanding.
There is no needs in special processing here. Just use negative
values for special rank values.
@rhc54 could you review
=> Code logic improvement

test/test_fence.c
Fixes https://github.com/pmix/master/issues/38
=> test: Fix hardcoded value

include/pmix/pmix_common.h, src/buffer_ops/buffer_ops.h, src/buffer_ops/copy.c, src/buffer_ops/internal.h, src/buffer_ops/open_close.c, src/buffer_ops/pack.c, src/buffer_ops/print.c, src/buffer_ops/unpack.c, src/class/Makefile.am, src/class/pmix_hotel.c, src/class/pmix_hotel.h, src/class/pmix_ring_buffer.c, src/class/pmix_ring_buffer.h, src/client/pmix_client.c, src/client/pmix_client_get.c, src/common/pmix_common.c, src/include/pmix_globals.c, src/include/pmix_globals.h, src/server/pmix_server.c, src/server/pmix_server_ops.c, src/server/pmix_server_ops.h, src/usock/usock.h, src/usock/usock_sendrecv.c, src/util/error.c, src/util/error.h
Note that some functions are not completely implemented in files:
src/server/pmix_server.c
src/server/pmix_server_ops.c
=> Initial transfer of the notification code from the OMPI master. 

src/buffer_ops/pack.c
=> Fix typo in packing of pmix_app_t - thanks to Gilles for pointing it out

src/buffer_ops/copy.c, src/buffer_ops/internal.h, src/buffer_ops/internal_functions.c, src/buffer_ops/open_close.c, src/buffer_ops/pack.c, src/buffer_ops/print.c, src/buffer_ops/unpack.c, src/class/pmix_hash_table.c, src/class/pmix_hash_table.h, src/client/pmix_client.c, src/client/pmix_client_connect.c, src/client/pmix_client_fence.c, src/client/pmix_client_get.c, src/client/pmix_client_pub.c, src/client/pmix_client_spawn.c, src/sec/pmix_native.c, src/server/pmix_server.c, src/server/pmix_server_ops.h, src/usock/usock.c, src/usock/usock.h, src/util/hash.c, src/util/pmix_environ.c, src/util/pmix_environ.h, test/server_callbacks.c, test/simple/simptest.c
* Related to this PR on the release branch
https://github.com/pmix/releases/pull/11
=> Fix some inconsistencies in pmix_status_t vs int declarations

config/pmix.m4, include/pmix/autogen/config.h.in
* Also sets the PMIX_VERSION string for easy access
=> config: Set the Major/Minor/Release in the config.h file

examples/dynamic.c, include/pmix/autogen/pmix_config_bottom.h, src/util/output.c, test/simple/simpdyn.c, test/simple/simptest.c
Thanks to Karol Mroz for the contribution.
=> Standardize the size of arrays we use for getting hostnames.

src/server/pmix_server.c
=> Attempt to resolve race condition

examples/client.c, examples/dmodex.c, examples/dynamic.c, src/buffer_ops/pack.c, src/buffer_ops/print.c, src/client/pmi1.c, src/client/pmi2.c, src/server/pmix_server.c, src/server/pmix_server_listener.c, src/server/pmix_server_regex.c, src/util/output.c, src/util/pmix_environ.c, src/util/progress_threads.c
Fixes #97 
@garlick Please see if this resolves these as I can't replicate with gcc 6.0.0 on my machine
=> Cleanup some of the compiler complaints about not checking return codes

include/pmix_server.h, src/server/pmix_server.c, src/server/pmix_server_listener.c, src/server/pmix_server_ops.c, src/server/pmix_server_ops.h
required for handling tool connections as well as multi-version communication protocols
=> Add the ability to support multiple listener rendezvous points

Makefile.am
=> do not install man pages when configure'd with --enable-embedded-mode

src/server/pmix_server.c
In particular, this fixes initialization of the 'mytmpdir'.
=> Fetch some info from the info array before initializing server base.

config/pmix.m4, include/Makefile.am, include/pmix_common.h, include/pmix_version.h.in
=> pmix/version: rework define of PMIx versions

test/test_fence.c
Fixed problem introduced in #146
=> test: fixed fence test

src/client/pmix_client.c
Сhery-picked from commit d8def6b (PR #125)
=> Fix buffer unpack hang

src/dstore/pmix_esh.c
In case not set the `TMPDIR` env variable then called the `strdup` with `NULL` pointer argument it causes an segmentation fault in dstore init. 
This fix to avoid use the strdup with `NULL` argument.
=> dstore: fixed segfault with use strdup(NULL)

src/dstore/pmix_esh.c, src/dstore/pmix_esh.h
=> dstore: added check the return code of lock fcntl

test/pmix_test.c, test/server_callbacks.c, test/test_fence.c
- Fixed spawn test
- Fixed fence test
=> pmix/test: fixed tests

src/dstore/pmix_esh.c
This PR corresponds to #59
Waits for #164 to be merged. Once merged we need to rebase this one.
=> V1.2 dstor pr3 (depends on #164)

src/dstore/pmix_esh.c
This PR corresponds to #135
Once #166 is merged this one must be rebased and merged as well.
Represents relevant commits from #135
=> V1.2 dstor pr4 (depends on #166)

src/dstore/pmix_esh.c
This PR has no corresponding `master` PR.
Should go after #167, need rebase after #167 is merged.
=> V1.2 dstor pr5 (depends on #167)

src/dstore/pmix_esh.c, src/dstore/pmix_esh.h
This PR corresponds to PR #140
Once #168 is merged, this one has to be rebased.
=> V1.2 dstor pr6 (depends on #168)

src/class/Makefile.am, src/class/pmix_value_array.c, src/class/pmix_value_array.h
This PR portion of #123 (pmix value array, in particular)
=> Add pmix value array class

src/dstore/pmix_dstore.c, src/dstore/pmix_dstore.h, src/dstore/pmix_esh.c, src/dstore/pmix_esh.h, src/server/pmix_server.c
This PR corresponds to #141
Depends on #173. Needs to be rebased after #173 is merged.
=> V1.2 dstor pr8 (depends on #173)

src/dstore/pmix_esh.c
This PR corresponds to #158.
Once #178 is merged, rebase this one.
=> V1.2 dstor pr9 (depends on #178)

src/dstore/pmix_esh.c
Corresponds to PR #163.
Needs rebase once #179 is merged
=> V1.2 dstor pr10 (depends on #179)

src/dstore/pmix_esh.c, src/dstore/pmix_esh.h
cherry-picked from commit 7e530bf (PR #162)
=> v1.2/dstore: added check the return code of lock fcntl

src/client/pmix_client_get.c, src/dstore/pmix_dstore.h, src/dstore/pmix_esh.c
This PR corresponds to PR #182
=> v1.2: dstor: pmix_esh: fix error handling.

src/client/pmi1.c, src/client/pmi2.c, src/client/pmix_client.c, src/client/pmix_client_get.c
=> v1.2: Fix backward compatibility

contrib/perf_tools/pmi.h, contrib/perf_tools/pmi2.c, contrib/perf_tools/pmi2_pmap_parser.c, contrib/perf_tools/pmi2_pmap_parser.h, contrib/perf_tools/pmi2_utils.c, contrib/perf_tools/pmi2_utils.h, contrib/perf_tools/pmi_intra_perf.c, contrib/perf_tools/pmix.c, contrib/perf_tools/run.sh
The following process is considered:
- each process put's defined number (param) of keys of some size (param)
- each process does commit and fence
- each process fetches the keys for each other process.
=> Add the pmix performance measurement tool.

contrib/perf_tools/Makefile
=> Add missing Makefile

src/server/pmix_server_ops.c
Force local data to deposit directly to the dstore at PMIx_Commit.
Before this patch local keys wasn't published in the dstore causing
first access to local key to go through a long path by sending a
message to server and asking to publish the data.
This was causing performance issues.
=> dstore: Fix PMIx_Commit

contrib/perf_tools/pmi_intra_perf.c
Added init time and total time measuring.
Changed the view of results as follows:
```
init: 0.003989 ; put: 0.000131 ; commit: 0.000066 ; fence: 0.419088 ; get: 0.085229 ; total: 0.511531
init:          max 0.012452 min 0.001733
put:           loc 0.000065 rem 0.000065
get:           loc 0.000067 rem 0.000067 all 0.000067
get:           min loc 0.000065 rem 0.000066 (loc: 1, rem: 1)
get:           max loc 0.000072 rem 0.000067 (loc: 116, rem: 0)
total:         max 0.672792 min 0.341711
```
=> perf: Added measurement points for the perf tool

src/common/pmix_common.c, src/util/error.c
will be restored in subsequent release series
=> Disable the errhandler support as it is broken

contrib/perf_tools/pmi_intra_perf.c
Added measuring of memory usage by the ["proportional set size" (PSS)](https://www.kernel.org/doc/Documentation/filesystems/proc.txt) (from `/proc/<pid>/smaps`)
```
The "proportional set size" (PSS) of a process is the count of pages it has
in memory, where each page is divided by the number of processes sharing it.
So if a process has 1000 pages all to itself, and 1000 shared with one other
process, its PSS will be 1500.
Note that even a page which is part of a MAP_SHARED mapping, but has only
a single pte mapped, i.e.  is currently used by only one process, is accounted
as private and not as shared.
```
=> Perf: Added memory measurement for the perf tool

src/client/pmix_client.c, src/client/pmix_client_get.c, src/common/pmix_jobdata.c
- Fix get some data from the internal hash in dstor case.
- Silence a warning
=> dstor: fix PMIx_Get

src/mca/pif/base/pif_base_components.c, src/runtime/pmix_finalize.c, src/runtime/pmix_init.c, src/util/pif.c
=> Cleanup the PIF usage per Gilles commit to OMPI

src/client/pmix_client_spawn.c, src/server/pmix_server_get.c, src/server/pmix_server_ops.c
=> Remove trailing whitespace

src/include/pmix_globals.c, src/include/pmix_globals.h, src/tool/pmix_tool.c
=> Cleanup two unused functions, fix segfault in tool support

src/client/pmix_client.c, src/client/pmix_client_connect.c, src/client/pmix_client_get.c, src/client/pmix_client_ops.h, src/client/pmix_client_spawn.c, src/common/Makefile.am, src/common/pmix_jobdata.c, src/dstore/pmix_esh.c, src/include/pmix_globals.c, src/include/pmix_globals.h, src/include/pmix_jobdata.h, src/server/pmix_server.c
Corresponds to PR #217
(cherry-picked from dcb6967da20b76ad357c3176f1fcfaa8807c8d2b)
(cherry-picked from 32c93e2bfddd23bc12cb098b56eb4859aedd6310)
=> dstore: keeping job info in the dstor

config/pmix.m4
=> Update the header tests to support Open BSD

src/dstore/pmix_esh.c
Currently in dstor the key names are stored in the arrays of 512 bytes.
This causes memory loss because real key names usually less
than 16 bytes.This commit reduces the memory footprint by using
only requested amount memory size to store the key name.
=> dstor: reduce storage space for the key name

src/class/pmix_object.c, src/class/pmix_object.h
=> class: correctly handle concurrent class initialization

src/class/pmix_hash_table.h, src/class/pmix_hotel.h, src/class/pmix_object.h, src/class/pmix_pointer_array.h, src/class/pmix_ring_buffer.h, src/class/pmix_value_array.h, src/client/pmix_client_ops.h, src/include/pmix_globals.c, src/mca/base/pmix_mca_base_var.h, src/mca/ptl/base/base.h, src/mca/ptl/base/ptl_base_frame.c, src/mca/ptl/tcp/ptl_tcp_component.c, src/mca/ptl/usock/ptl_usock_component.c, src/server/pmix_server_ops.c, src/server/pmix_server_ops.h, src/util/argv.h, src/util/fd.h, src/util/os_path.h, src/util/show_help.h
=> Fix visibility issues so that OMPI built against external PMIx master can work

src/dstore/pmix_esh.c
dstore: Fixed dstor bug case of key overwrite. 
Data corruption was observed when a key was stored second time (forcing 
data overwrite). In case of overwrite, the old record is invalidated 
with "INVALIDATED" string written into its key name field. The problem 
was observed when space insufficient for storing "INVALIDATED" string 
was reserved for the key name field at the original key submission.
The fix provides minor refactoring of the dtore record formats to 
flexibly address this issue.
=> dstor: fixed key overwrite

src/client/pmix_client.c, src/common/pmix_jobdata.c, src/include/pmix_globals.h, src/util/compress.h
=> Correctly handle NULL strings

src/mca/ptl/usock/ptl_usock_component.c
=> Adjust the usock priority higher than tcp for now

include/pmix_common.h
=> Backport some attribute definitions from the OMPI master

src/client/pmix_client.c, src/common/pmix_jobdata.c, src/server/pmix_server.c
=> Minor cleanups to fix Coverity issues

src/mca/ptl/base/ptl_base_sendrecv.c
on Linux, sending the header and then the message data does severely
impact performances of ptl/tcp :
on the receiver, reading the data can often result in an PMIX_ERR_RESOURCE_BUSY
or PMIX_ERR_WOULD_BLOCK, which ends up degrading performances)
this commit send both header and message data at the same time via writev()
and makes ptl/tcp virtually as efficient as ptl/usock.
Short writev generally occur when the kernel buffer is full, so there is no
point for retrying in this case.
fwiw, no such degradation was observed on OSX.
Refs open-mpi/ompi#2657
=> pmix2x: ptl/base: send header and message data together via writev()

src/mca/ptl/base/ptl_base_sendrecv.c
=> Silence Coverity CID 1398541 (from OMPI)

src/buffer_ops/copy.c, src/common/pmix_jobdata.c, src/mca/base/pmix_mca_base_var.c, src/mca/pnet/opa/pnet_opa.c, src/mca/psec/native/psec_native.c, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c, src/server/pmix_server_get.c, src/util/net.h, src/util/show_help.c, test/pmi_client.c
=> Silence a bunch of Coverity warnings

src/dstore/pmix_esh.c
Restored the part of PR #260
Thanks to @hjelmn for the contribution!
=> dstor: Removed unnecessary pack/unpack operation

src/include/pmix_globals.h
=> Add missing symbol export

src/dstore/pmix_esh.c, src/mca/base/pmix_mca_base_var.c, src/mca/base/pmix_mca_base_var.h, src/mca/ptl/tcp/ptl_tcp.c, test/pmi2_client.c, test/pmi_client.c
=> Cleanup Coverity warnings

include/pmix_common.h
Defined the key name to set session id
=> dstore: Introduce session supports

src/client/pmix_client_get.c
The `PMIx_Get` is hanging if key was stored in local hash and
key name not equal `pmix.*`. Bug reproduced with `--disable-dstore`.
This PR is fixes the get internal keys in non dstore case.
=> Fixed PMIx_Get

src/client/pmi1.c, src/client/pmi2.c, src/dstore/pmix_esh.c
=> Set of fixes targeting restoration of PMI1/PMI2 support

config/pmix_check_lock.m4
=> config: Fix pthread locking variable

src/dstore/pmix_esh.c
=> dstore: Fix extension slot allocation

src/client/pmix_client_get.c
=> Refactor PMIx_Get fixing `PMIX_store_internal` case

src/mca/pnet/opa/Makefile.am
=> pnet/opa: fix a typo in Makefile.am

config/pmix_check_lock.m4, src/dstore/pmix_esh.c
Thanks Siegmar Gross for the report
=> make Oracle compilers happy panda again

config/pmix.m4, src/mca/pdl/configure.m4, src/mca/pdl/pdlopen/configure.m4
=> Correct some typos in configure support for disable-dlopen

config/pmix_check_lock.m4, src/dstore/pmix_esh.c
Ref PR https://github.com/pmix/master/pull/309
=> make Oracle compilers happy

include/pmix_common.h
Add PMIX_TIME_REMAINING key
Refs https://github.com/pmix/RFCs/pull/13
=> Prototype for RFC00013

.gitignore, examples/Makefile.am, examples/alloc.c, include/pmix.h, include/pmix_common.h, include/pmix_server.h, src/buffer_ops/copy.c, src/buffer_ops/internal.h, src/buffer_ops/open_close.c, src/buffer_ops/pack.c, src/buffer_ops/print.c, src/buffer_ops/unpack.c, src/common/pmix_query.c, src/common/pmix_strings.c, src/include/pmix_globals.c, src/include/pmix_globals.h, src/server/pmix_server.c, src/server/pmix_server_ops.c, src/server/pmix_server_ops.h, src/util/error.c
=> Implement the PMIx_Allocate_request_nb support

src/dstore/pmix_esh.c
=> Silence unnecessary error log

src/sm/pmix_mmap.c
=> dstore/sm: added the check `posix_fallocate` return code

NEWS
Synchronize the `NEWS` file with the `v1.2` branch.
=> NEWS: Sync with the v1.2 branch

config/pmix_functions.m4
=> configury: allow repeated arguments with -XCClinker

config/pmix_functions.m4
=> configury: allow repeated arguments with -Xg

src/client/pmix_client_get.c
=> Fixed get logic for local keys

include/pmix_common.h, src/event/pmix_event.h, src/event/pmix_event_notification.c, src/event/pmix_event_registration.c, src/server/pmix_server_ops.c
Refs https://github.com/pmix/RFCs/pull/18
=> Implement the event notification extension RFC

src/event/pmix_event_registration.c
=> Fix event registration - need to increment the event index and record the number of codes in the event handler

src/class/pmix_pointer_array.c, src/class/pmix_pointer_array.h
=> Port the pointer_array class optimizations provided by @bosilca to PMIx

src/server/pmix_server.c, src/server/pmix_server_get.c, src/server/pmix_server_ops.c
=> Backport modifications to support background modex operation

config/pmix_config_asm.m4, include/pmix_common.h, src/atomics/sys/architecture.h, src/atomics/sys/cma.h, src/client/pmix_client.c, src/event/pmix_event.h, src/event/pmix_event_notification.c, src/event/pmix_event_registration.c, src/include/pmix_globals.h, src/server/pmix_server.c, src/server/pmix_server_ops.c, src/server/pmix_server_ops.h, src/util/error.c, test/simple/simptest.c
Refs https://github.com/pmix/RFCs/pull/17
Refs https://github.com/open-mpi/ompi/pull/3448
=> Implement the notification changes required to support the cross-library integration

src/buffer_ops/open_close.c, src/include/pmix_globals.c
=> Add some missing PMIX_EXPORTs

autogen.pl
=> Check for the correct levels of autotools

src/client/pmix_client.c, src/dstore/pmix_esh.c, src/include/pmix_globals.c, src/include/pmix_globals.h, src/mca/ptl/base/ptl_base_sendrecv.c, src/server/pmix_server.c
=> Do not close the lockfd if we didn't set it.

src/atomics/sys/arm/atomic.h, src/atomics/sys/arm64/atomic.h, src/atomics/sys/gcc_builtin/atomic.h, src/atomics/sys/ia32/atomic.h, src/atomics/sys/ia64/atomic.h, src/atomics/sys/mips/atomic.h, src/atomics/sys/powerpc/atomic.h, src/atomics/sys/sparcv9/atomic.h, src/atomics/sys/x86_64/atomic.h
=> Backport fixes to avoid conflicts when embedded

src/threads/wait_sync.c, src/threads/wait_sync.h
=> Protect against multiple definition issues when embedded

src/runtime/pmix_finalize.c, src/runtime/pmix_init.c, src/server/pmix_server.c
=> Fix initialization of notification ring buffer

src/mca/pdl/pdlopen/configure.m4
=> Minor cleanup of configure for pdlopen

src/event/pmix_event_notification.c
=> Silence Coverity warnings

autogen.pl, configure.ac
=> Roll back the required autotool levels - will update the web site to track

include/pmix_common.h, src/common/Makefile.include, src/common/pmix_data.c
=> Add new PMIx_Data_xxx APIs to expose the bfrops support as potentially useful utilities for host RMs

src/server/pmix_server.c, src/server/pmix_server_ops.c
=> Fix dmodex - eliminate race condition where data was being released while sent

src/mca/ptl/tcp/ptl_tcp_component.c
=> Minor cleanups

AUTHORS, HACKING, INSTALL, NEWS, VERSION
@jjhursey Please review for rc1 release
=> Update info files for 2.0rc1

src/server/pmix_server.c
=> Silence a couple of Coverity warnings

include/pmix_common.h, src/event/pmix_event_registration.c, src/util/output.c, test/simple/loop-exec.sh
=> Silence some Coverity warnings. Add new test program

src/event/pmix_event_registration.c
=> Silence coverity

VERSION
=> Roll the version number to 2.0.1

AUTHORS, INSTALL, NEWS
=> Backport the authors etc updates

autogen.pl, include/pmix_common.h
=> Silence a coverity warning. Provide ordering of directory processing in autogen

test/test_common.c
(cherry picked from commit eb44c18493a66d4459d8d7e89a3f26adacf7261d)
=> test: fixed the client rank determine for testing under SLURM

src/client/pmix_client_connect.c, src/client/pmix_client_pub.c, src/mca/gds/hash/gds_hash.c, src/server/pmix_server_get.c, src/tool/pmix_tool.c, src/util/pif.c
=> Silence more Coverity warnings

src/mca/preg/native/preg_native.c
=> Fix an error in regex generation

src/atomics/sys/sync_builtin/atomic.h, src/buffer_ops/internal_functions.c, src/dstore/pmix_esh.c
=> Upstream a few fixes from OMPI

VERSION, src/mca/bfrops/base/base.h, src/mca/bfrops/base/bfrop_base_frame.c, src/mca/bfrops/bfrops_types.h, src/mca/pnet/base/base.h, src/mca/preg/Makefile.am, src/mca/preg/base/base.h, src/mca/preg/base/preg_base_frame.c, src/mca/preg/preg.h, src/mca/preg/preg_types.h, src/mca/psec/base/base.h, src/mca/pshmem/base/base.h, src/mca/ptl/base/base.h
=> Update VERSION to 2.1 as there have been no API changes thus far. Fix visibility issues

src/client/pmix_client.c
The client's 'PMIx_Commit' works correctly only when client has
local and remote keys at the same time. If client has only one
type of keys this leads to fail.
=> Fixes the 'PMIx_Commit' failure.

src/mca/gds/ds12/gds_dstore.c
=> Silence error log of "success"

include/pmix_common.h
=> Add a few hwloc attributes

include/pmix_common.h, src/class/pmix_hash_table.h, src/class/pmix_list.h, src/class/pmix_value_array.h, src/mca/base/pmix_mca_base_framework.h, src/mca/bfrops/base/base.h, src/mca/bfrops/bfrops_types.h, src/mca/pnet/base/base.h, src/mca/preg/preg_types.h, src/runtime/pmix_init.c, src/util/basename.h, src/util/getid.h, src/util/hash.h, src/util/output.h, src/util/path.h, src/util/pmix_environ.h, src/util/printf.h, src/util/show_help.h, src/util/timings.h
=> Upstream visibility fixes from OMPI

test/test_common.h, test/test_fence.c
(cherry picked from commit d81a28d1300000af3a59cef3ca875f38ff281b66)
=> test: Fix pmix_client/job-fence test checks

config/pmix_check_visibility.m4, include/pmi.h, include/pmi2.h, include/pmix.h, include/pmix/autogen/pmix_config_bottom.h, include/pmix/pmix_common.h, include/pmix_server.h, src/class/pmix_object.h, src/client/pmix_client.c, src/common/pmix_common.c, src/server/pmix_server.c, src/util/basename.h, src/util/crc.h, src/util/os_path.h, src/util/printf.h
=> Resolve visibility issues for public APIs

src/class/pmix_hash_table.c, src/class/pmix_list.c, src/class/pmix_pointer_array.c, src/class/pmix_ring_buffer.c, src/class/pmix_value_array.c
=> Export the class instances

src/dstore/pmix_esh.c
** CID 1375987: Time of check time of use (TOCTOU)
(cherry picked from commit 4568a4f4af7760dabcb6b6e132f96190db8815a1)
=> v2.0: Silence coverity CID 1375987

NEWS, VERSION
=> Update NEWS and VERSION for v2.0.1rc1

src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c
=> Final cleanups: silence coverity warnings

src/include/pmix_globals.h, src/mca/ptl/tcp/ptl_tcp.c
=> Capture a couple of missing updates

src/client/pmix_client_get.c
Properly deal with compressed strings returned by the query
=> Ensure the query actually gets sent so the client doesn't hang.

VERSION
=> VERSION: Bump to v1.2.4a1

src/mca/bfrops/pmix1/Makefile.am
=> Add missing file to tarball

src/dstore/pmix_esh.c
** CID 1375987: Time of check time of use (TOCTOU)
(cherry picked from commit 4568a4f4af7760dabcb6b6e132f96190db8815a1)
=> v1.2: Silence coverity CID 1375987

src/mca/bfrops/pmix1/bfrop_pmix1.c, src/mca/bfrops/pmix1/pack.c, src/mca/gds/hash/gds_hash.c, src/server/pmix_server.c, src/server/pmix_server_get.c
The simpclient test now passes
=> Complete the (basic) support for v1 client working with a v2 server.

config/pmix.m4, config/pmix_setup_cc.m4
Refs https://github.com/open-mpi/ompi/pull/4181
=> Resolve the configure ordering problem presented by AM_PROG_CC_C_O

examples/debugger.c, src/event/pmix_event_notification.c, src/event/pmix_event_registration.c, src/mca/base/pmix_mca_base_framework.c, src/mca/base/pmix_mca_base_open.c, src/mca/base/pmix_mca_base_var.c, src/mca/bfrops/base/bfrop_base_pack.c, src/mca/bfrops/base/bfrop_base_print.c, src/mca/gds/ds12/gds_dstore.c, src/mca/pdl/pdlopen/pdl_pdlopen_module.c, src/mca/pinstalldirs/base/pinstalldirs_base_expand.c, src/mca/pnet/opa/pnet_opa.c, src/mca/ptl/tcp/ptl_tcp_component.c, src/server/pmix_server_get.c, src/util/path.c, src/util/show_help.c, test/test_common.c, test/utils.c
=> Silence a bunch of warnings that show when building rpm's

include/pmix_common.h, src/client/pmix_client.c, src/client/pmix_client_connect.c, src/client/pmix_client_fence.c, src/client/pmix_client_get.c, src/client/pmix_client_pub.c, src/client/pmix_client_spawn.c, src/common/pmix_control.c, src/mca/bfrops/bfrops_types.h, src/mca/ptl/base/ptl_base_connect.c, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/usock/ptl_usock.c, src/server/pmix_server_ops.c, src/tool/pmix_tool.c, src/util/error.c, src/util/error.h
=> Cleanup a few tool-related issues (backport from reference server)

include/pmix_common.h, src/include/pmix_globals.c, src/runtime/pmix_init.c, src/runtime/pmix_rte.h, src/server/pmix_server.c
=> Capture some missed changes from reference server

config/pmix.m4, config/pmix_setup_cc.m4, configure.ac
Refs https://github.com/open-mpi/ompi/issues/4109
=> Update the configury to resolve problems with automake 1.13.

src/mca/ptl/tcp/ptl_tcp_component.c
=> Check for NULL in places

include/pmix_common.h, src/event/pmix_event_notification.c
=> Cleanup a few things relative to notifying used by tools

src/mca/ptl/tcp/ptl_tcp_component.c
=> Minor cleanup - use the same version string as the client is expecting

examples/client.c
=> Fix the client example

src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp.h, src/mca/ptl/tcp/ptl_tcp_component.c
=> Fix tool connection logic so we properly search for default session server, perform specified number of retries, etc.

Makefile.am, config/pmix.m4, contrib/pmix.spec, etc/Makefile.am, etc/pmix-mca-params.conf
=> Add the default MCA parameter file template

config/pmix.m4
=> configury: fix small typo

config/distscript.sh, src/class/pmix_value_array.c, src/mca/base/pmix_mca_base_component_compare.c, src/mca/pinstalldirs/config/configure.m4, src/mca/pinstalldirs/env/configure.m4, src/util/pmix_environ.c, src/util/strnlen.h
=> Cleanup whitespace

.gitignore, test/simple/Makefile.am, test/simple/simplegacy.c
=> Add a legacy test that does multiple commit/fence cycles with legacy-style keys

src/mca/gds/gds.h
=> Add some debug output

include/pmix_common.h, src/client/pmix_client.c, src/client/pmix_client_get.c, src/event/pmix_event_notification.c, src/event/pmix_event_registration.c, src/mca/psensor/file/psensor_file.c, src/mca/ptl/base/ptl_base_listener.c, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp.h, src/mca/ptl/tcp/ptl_tcp_component.c, src/mca/ptl/usock/ptl_usock_component.c, src/server/pmix_server_get.c, src/server/pmix_server_ops.c, src/tool/pmix_tool.c
=> Enable reporting of URI to stdout, stderr, or file so that remote connections can be found.

Makefile.am, VERSION, configure.ac, src/client/pmi1.c, src/client/pmi2.c
(cherry picked from commit d52fb9d738665db4fc2bae079b5ec6dc2bca66c3)
=> Support singleton operations under PMI-1 and PMI-2

src/client/pmix_client.c, src/event/pmix_event_notification.c, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp.h, src/mca/ptl/tcp/ptl_tcp_component.c, src/tool/pmix_tool.c
=> Enable support for remote tool connections

config/pmix_setup_libevent.m4, src/client/pmi2.c, src/client/pmix_client.c, src/mca/bfrops/base/bfrop_base_copy.c, src/mca/bfrops/v20/copy.c, src/tool/pmix_tool.c
=> Cleanup the libevent configure logic to support default install paths

src/mca/ptl/tcp/ptl_tcp.c
=> Fix cmd line passing of URI

src/event/pmix_event_notification.c, src/mca/ptl/base/ptl_base_sendrecv.c
=> Debounce "unreachable" notifications for tools when they disconnect

src/mca/gds/ds12/gds_dstore.c, src/mca/ptl/ptl_types.h, src/mca/ptl/tcp/ptl_tcp_component.c, src/server/pmix_server.c
=> Update the proc types to cover v3.0

NEWS, VERSION
=> Prep NEWS and VERSION for release

VERSION
=> Add the rc1 designator

src/event/pmix_event_registration.c
=> Fix event registration so OpenMP/MPI coordination sides can both get notification of model declarations

src/include/Makefile.include
=> Include missing file

VERSION
=> Roll to v2.0.3

src/mca/base/pmix_mca_base_var.c, src/mca/gds/hash/gds_hash.c, src/tools/pinfo/pinfo.c, src/tools/pinfo/support.c
=> Silence cov warnings

src/common/pmix_strings.c, src/event/pmix_event_notification.c
=> Add a missing range string

src/tools/pinfo/support.c
=> tools/pinfo: fix misc memory leaks

src/server/pmix_server.c
=> Do not block when asked for dmodex info

VERSION, examples/dynamic.c, examples/server.c, include/pmix.h, include/pmix_common.h, include/pmix_server.h, src/client/pmi2.c, src/client/pmix_client_connect.c, src/include/pmix_globals.h, src/server/pmix_server.c, src/server/pmix_server_ops.c, src/server/pmix_server_ops.h, test/server_callbacks.c, test/server_callbacks.h, test/simple/simpdyn.c, test/simple/simptest.c, test/test_cd.c, test/test_cd.h, test/test_resolve_peers.c
Refs https://github.com/pmix/RFCs/pull/3
=> Modification of connect/disconnect APIs

config/pmix.m4
=> Provide the means to force-off the binary tools

config/pmix_setup_zlib.m4
=> Backport zlib configury changes from OMPI

src/mca/ptl/base/base.h, src/mca/ptl/base/ptl_base_frame.c, src/mca/ptl/base/ptl_base_sendrecv.c, src/runtime/help-pmix-runtime.txt, src/util/path.c, src/util/pif.c
=> Silence some coverity warnings

examples/debugger.c, src/client/pmix_client_ops.h, src/event/pmix_event_notification.c, src/runtime/pmix_init.c, src/runtime/pmix_params.c, src/server/pmix_server.c, src/server/pmix_server_ops.c, src/server/pmix_server_ops.h
=> Continue breaking down the verbosity settings to aid in debugging

src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c, src/server/pmix_server_ops.c
=> Minor cleanups of tool services

src/server/pmix_server_ops.c
=> pack pointer to object (vs. pointer to pointer)

src/mca/ptl/usock/ptl_usock.c
There is still something wrong with usock support, but it is internal to v2.0 and not associated with cross-version ops.
Note that cross-version works fine with the default tcp transport.
=> Update the usock component to support cross-version. 

src/mca/gds/ds12/Makefile.am, src/mca/gds/ds12/gds_dstore.c, src/mca/gds/ds12/gds_dstore.h, src/mca/gds/ds12/gds_dstore_v12.c, src/mca/gds/ds12/gds_dstore_v20.c
=> dstor: rework dstor compatibility

include/pmix.h, include/pmix_common.h.in, include/pmix_server.h, src/common/Makefile.include, src/common/pmix_security.c, src/include/pmix_globals.c, src/include/pmix_globals.h, src/mca/psec/munge/psec_munge.c, src/mca/psec/native/psec_native.c, src/mca/psec/none/psec_none.c, src/mca/psec/none/psec_none_component.c, src/mca/psec/psec.h, src/mca/ptl/ptl_types.h, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c, src/mca/ptl/usock/ptl_usock.c, src/mca/ptl/usock/ptl_usock_component.c, src/server/pmix_server.c, src/server/pmix_server_ops.c, src/server/pmix_server_ops.h, test/simple/simptest.c
Refs https://github.com/pmix/RFCs/pull/24
=> Prototype implementation of v3.0 Security APIs

config/pmix_check_attributes.m4, src/include/pmix_config_bottom.h, src/mca/gds/ds12/gds_dstore.c
Use pmix-prefixed attributes, add extension and optnone to the attribute list
=> Update attribute checking code

src/mca/base/pmix_mca_base_cmd_line.c
=> Check return code of asprintf

src/mca/gds/ds12/gds_dstore.c
Fixed dstor compatibility issues between v1.2 and v2.x
(cherry picked from commit dab23fe4a4002f48485f26cc5682a40d0051f3c7)
=> dstor: addresses a dstor compatibility issues

test/pmi2_client.c, test/pmi_client.c
- test/pmix_test -e test/pmi_client works again.
- test/pmix_test -e test/pmi2_client works again.
- Probably closes dregs of Issue #107.
=> Fix segfaults in test/pmi_client and test/pmi2_clients.

NEWS, VERSION
=> Update NEWS and VERSION for release

VERSION, etc/pmix-mca-params.conf, test/pmi2_client.c, test/pmi_client.c
Cherry-pick a couple of minor cleanups. Update VERSION to rc2
=> Prep for v2.1.0rc2

src/mca/base/pmix_mca_base_var.c
Refs https://github.com/open-mpi/ompi/pull/4328
=> Backport of changes to path separator

src/tool/pmix_tool.c
of these are being put with rank=0 for tools instead of using
PMIX_RANK_WILDCARD.
=> Probably need someone to review these more carefully, but at least some

include/pmix_rename.h.in, src/tool/pmix_tool.c
=> Remove unsued var, fix file permissions

src/tool/pmix_tool.c
Save the tool nspace/rank in the peer object
Refs #638 
=> Capture the tool nspace/rank

examples/client.c
=> Update the client example to properly account for local vs remote peers

include/pmix_common.h, src/common/pmix_data.c
=> Update data pack/unpack APIs to match RFC

NEWS, include/pmix_rename.h.in, src/mca/ptl/base/base.h, src/mca/ptl/base/ptl_base_frame.c, src/mca/ptl/base/ptl_base_sendrecv.c, src/mca/ptl/usock/ptl_usock.c, src/runtime/help-pmix-runtime.txt
=> Protect against overly-large messages

src/common/pmix_jobdata.c
The hash store function does a "retain" on the incoming pmix_kval_t object and then appends it to a list. This object must, therefore, have been allocated and cannot be a statically declared variable.
=> Do not destruct object on list

src/server/pmix_server_get.c
=> Fix dmodex when receiving new nspace

src/mca/base/pmix_mca_base_var_group.c
https://github.com/open-mpi/ompi/commit/2b08028567f63309f8bd0931739dd9a2afc6c0d6
=> Backport fix for group registration

NEWS, VERSION, config/pmix_check_attributes.m4, contrib/pmix_jenkins.sh, examples/pmi1client.c, include/pmix_common.h.in, src/client/pmix_client_pub.c, src/include/pmix_globals.h, src/mca/base/pmix_mca_base_var_group.c, src/mca/gds/ds12/gds_dstore.c, src/server/pmix_server.c, src/server/pmix_server_get.c, src/tool/pmix_tool.c, test/cli_stages.c, test/cli_stages.h, test/simple/test_pmix.c
Rollup of commits to bring v2.1 branch up to v2.1.1rc1
@artpol84 @jjhursey I just need one of you to review, but both are welcome to comment.
=> Update in preparation for v2.1.1 release

include/pmix_common.h.in, src/mca/bfrops/base/base.h, src/mca/bfrops/base/bfrop_base_copy.c, src/mca/bfrops/base/bfrop_base_fns.c, src/mca/bfrops/base/bfrop_base_pack.c, src/mca/bfrops/base/bfrop_base_print.c, src/mca/bfrops/base/bfrop_base_unpack.c, src/mca/bfrops/v3/bfrop_pmix3.c, src/mca/preg/native/preg_native.c, src/server/pmix_server.c
Must be committed after https://github.com/pmix/pmix/pull/612
=> Prototype implementation of RFC0022

include/pmix_common.h.in
Add some coordination attributes and status codes
=> OpenMP/MPI Coordination

test/pmi2_client.c, test/pmi_client.c
=> Fixed faulty compares in PMI/PMI2 tests

test/pmi2_client.c, test/pmi_client.c
(cherry picked from commit 4118eed8a9acaa6948e0069fb65fb411ffa3d94f)
=> v2.0 Fixed faulty compares in PMI/PMI2 tests

src/server/pmix_server.c
=> Silence Coverity warning

config/pmix.m4, config/pmix_setup_hwloc.m4, include/pmix_common.h.in, src/Makefile.am, src/hwloc/Makefile.include, src/hwloc/hwloc-internal.h, src/hwloc/hwloc.c, src/mca/pif/posix_ipv4/pif_posix.c, src/mca/pnet/base/base.h, src/mca/pnet/base/pnet_base_fns.c, src/mca/pnet/opa/pnet_opa.c, src/mca/pnet/pnet.h, src/mca/pnet/tcp/pnet_tcp.c, src/mca/pnet/test/pnet_test.c, src/mca/ptl/tcp/ptl_tcp_component.c, src/server/pmix_server.c, src/server/pmix_server_ops.c, src/server/pmix_server_ops.h, src/tool/pmix_tool.c, test/simple/simptest.c
Topology is now created and cleaned up
Complete collection of inventory
Enable OPA and TCP collection
=> Setup HWLOC integration, if available, and collect inventory

src/include/pmix_globals.c, src/include/pmix_globals.h, src/mca/pnet/base/base.h, src/mca/pnet/base/pnet_base_fns.c, src/mca/pnet/opa/pnet_opa.c, src/mca/pnet/pnet.h, src/mca/pnet/tcp/pnet_tcp.c, src/server/pmix_server.c
=> Cleanup finalize and local_app_finalize

src/runtime/pmix_finalize.c
=> Ensure we cleanup the class definitions

include/pmix_common.h.in, src/class/Makefile.include, src/class/pmix_bitmap.c, src/class/pmix_bitmap.h
=> Add pmix_bitmap class and clarify attribute def

.gitignore, Makefile.am, bindings/Makefile.am, bindings/README, bindings/python/Makefile.am, bindings/python/README, bindings/python/client.py, bindings/python/cpmix.pxd, bindings/python/pmix.pyx, bindings/python/server.py, bindings/python/setup.py, config/pmix.m4, src/mca/pnet/base/pnet_base_fns.c, src/util/name_fns.c, test/simple/gwclient.c, test/simple/simptest.c, test/test_fence.c
=> First prototype for Python wrappers

config/pmix.m4, config/pmix_check_cython.py
=> Add check for Cython

include/pmix_common.h.in, src/mca/bfrops/base/bfrop_base_fns.c, src/mca/bfrops/bfrops.h, src/mca/plog/base/plog_base_stubs.c, src/mca/plog/default/plog_default.c, src/mca/pnet/base/pnet_base_fns.c, src/util/error.c, src/util/error.h
=> Few minor cleanups

src/mca/pnet/base/pnet_base_fns.c, src/mca/pnet/pnet.h
=> Fix typo: PMIX_ERR_OPERATION_IN_PROGRESS -> PMIX_OPERATION_IN_PROGRESS

src/mca/pnet/base/base.h, src/mca/pnet/base/pnet_base_fns.c, src/mca/pnet/base/pnet_base_frame.c, src/mca/pnet/test/pnet_test.c
Will eventually be moved into revised shared memory segment
=> Add temporary ability to cache proc/node maps

src/server/pmix_server.c
=> v2.1: Fix deadlock in PMIx_Server_init in the error case

include/pmix_common.h.in, src/common/pmix_data.c, src/mca/bfrops/base/bfrop_base_pack.c, src/mca/pnet/tcp/pnet_tcp.c, src/mca/pnet/test/pnet_test.c
=> Minor cleanups for PRRTE

examples/pub.c, src/mca/pnet/base/base.h, src/mca/pnet/base/pnet_base_fns.c, src/mca/pnet/base/pnet_base_frame.c, src/mca/pnet/tcp/pnet_tcp.c
=> Begin tracking inventory

.gitignore, examples/Makefile.am, examples/pubi.c, src/tool/pmix_tool.c
=> Ensure tools cleanup and add another example

src/server/pmix_server_ops.c
=> Fixed use of uninitialized value

NEWS, VERSION
=> Update NEWS and VERSION

src/client/pmix_client.c, src/runtime/pmix_finalize.c, src/server/pmix_server.c, src/tool/pmix_tool.c, test/simple/stability.c
=> Some minor cleanups

src/mca/pnet/opa/pnet_opa.c, src/mca/pnet/opa/pnet_opa.h, src/mca/pnet/tcp/pnet_tcp.c, test/simple/gwtest.c
=> Build out the OPA inventory collection

VERSION, contrib/pmix.spec, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c
=> PMIx master is now targeting v4.0.0

src/mca/pnet/opa/pnet_opa.c, src/mca/ptl/tcp/ptl_tcp_component.c
=> Cleanup connection check and add missing include

src/common/pmix_data.c
=> Remove stale code

.gitignore, test/simple/Makefile.am, test/simple/quietclient.c, test/simple/simptest.h, test/simple/stability.c
=> Add the stability test for ease of use

src/mca/ptl/tcp/ptl_tcp_component.c, src/tool/pmix_tool.c
=> Tools need to init tmpdirs too

config/pmix.m4, config/pmix_check_cython.py
Thanks to @ggouaillardet for the suggestion!
=> Simplify cython detection

src/mca/gds/ds12/gds_dstore.c
=> dstore: fixed the logic of unmaping dstore segments

src/mca/gds/ds12/gds_dstore.c
Fixes a crash described at #777
=> dstor: added the check of the dstore tracker is existed

src/mca/gds/ds12/gds_dstore.c
(cherry picked from commit d95a1419a3f61bb52516807131a28e341f11d45c)
=> v3.0 dstore: fixed the logic of unmaping dstore segments

src/mca/gds/ds12/gds_dstore.c
(cherry picked from commit d95a1419a3f61bb52516807131a28e341f11d45c)
=> v2.1 dstore: fixed the logic of unmaping dstore segments

src/dstore/pmix_esh.c
=> v2.0 dstore: fixed the logic of unmaping dstore segments

bindings/python/cpmix.pxd
Complete definition of the pmix_common.h and pmix_server.h
APIs/attributes
=> Continue working on Python bindings

contrib/pmix.spec, include/pmix_version.h.in
=> Add numeric version field

test/simple/simptest.c
Check for correct handling of nondefault designation
=> Minor mod to simptest

src/mca/common/dstore/dstore_base.c
=> Transfer all cached data to client dstore gds

VERSION, config/pmix_mca.m4, configure.ac, src/mca/common/dstore/Makefile.am, src/mca/gds/ds12/Makefile.am, src/mca/gds/ds21/Makefile.am, src/mca/pnet/opa/pnet_opa.c
Common component libraries must be versioned.
=> Fix the common framework integration

src/server/pmix_server_ops.c
=> Missed one spot where we need to avoid the cbfunc

.gitignore, include/pmix_common.h.in, src/common/pmix_control.c, src/mca/psensor/base/psensor_base_stubs.c, src/mca/psensor/heartbeat/psensor_heartbeat.c, src/mca/psensor/heartbeat/psensor_heartbeat.h, src/mca/psensor/heartbeat/psensor_heartbeat_component.c, src/server/pmix_server.c, src/server/pmix_server_ops.c, test/simple/Makefile.am, test/simple/simpjctrl.c, test/simple/simptest.c
Thanks to @wessle for reporting the problem.
=> Implement job control and sensor APIs

config/pmix_setup_cc.m4
Revamp PMIX_PROG_CC_C11 macro in order to define macros only once.
Otherwise, macros get redefined during the configure process and
issue a bunch of warning in config.log. That would also cause
PMIx fail to build if compiled with "-Werror"
(back-ported from upstream commit open-mpi/ompi@c9d3c81cbf97df97ebe0de8e4761e8c7a9278f48)
Signed-off-by: Gilles Gouaillardet <gilles@rist.or.jp>`
(cherry picked from commit ca510b3bf15975b848ee4b65c0565a89f085dabc)
=> configury: define C11 macros once

config/pmix.m4, src/mca/common/dstore/dstore_segment.c, src/mca/common/dstore/dstore_segment.h, src/mca/gds/ds21/gds_ds21_lock_pthread.c
=> dstore: ds21 locks are aligned to the size of the cache line

src/mca/psensor/heartbeat/psensor_heartbeat.c
=> Remove stale return call

src/client/pmix_client_get.c
=> Fixed verbose output for get operation

Makefile.am
=> Add missing file to dist

src/mca/pnet/base/pnet_base_fns.c, src/mca/pnet/opa/pnet_opa.c, src/mca/pnet/opa/pnet_opa.h, src/mca/pnet/opa/pnet_opa_component.c, src/mca/pnet/tcp/pnet_tcp.c, src/mca/pnet/tcp/pnet_tcp.h, src/mca/pnet/tcp/pnet_tcp_component.c
=> Add debugging output to pnet components

src/mca/pnet/opa/pnet_opa.c, src/mca/pnet/tcp/pnet_tcp.c
Also update to use new PMIX_CHECK_KEY macro
=> Add a little more debugging

config/pmix.m4, config/pmix_setup_cli.m4, src/tools/pevent/Makefile.am, src/tools/plookup/Makefile.am, src/tools/pmix_info/Makefile.am, src/tools/pps/Makefile.am
Provide a mechanism to link libtool archives
=> Backport changes to expose tools when embedded

src/mca/pif/bsdx_ipv4/pif_bsdx.c, src/mca/pif/bsdx_ipv6/pif_bsdx_ipv6.c, src/mca/pif/linux_ipv6/pif_linux_ipv6.c, src/mca/pif/pif.h, src/mca/pif/posix_ipv4/pif_posix.c, src/util/net.c, src/util/pif.c
=> Remove stale MacOSX protections

include/pmix_common.h.in, src/client/pmix_client.c, src/client/pmix_client_get.c, src/client/pmix_client_spawn.c, src/server/pmix_server.c
=> Bring the APIs into compliance with std

src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp.h, src/mca/ptl/tcp/ptl_tcp_component.c
=> ptl/tcp: Make try connect retry/timout MCA adjustable

test/simple/simptest.c
(cherry picked from commit d0a90016a5ebd83a7e6ea957002143aa21b3a77d)
=> Update simptest to return client status

include/pmix_common.h.in, src/mca/gds/ds12/gds_ds12_base.c, src/mca/gds/ds21/gds_ds21_base.c, test/simple/simptest.c, test/test_fence.c
=> Cleanup after last PR added ds21 component

VERSION, include/Makefile.am, include/pmix_extend.h, src/server/pmix_server.c
=> Roll to rc1, cleanup some minor typos

src/mca/common/dstore/dstore_base.c
* Dstore needs an outer wrapper for the kv pair.
- Without this we corrupt memory on the modex operation.
* Bug introduced in PR #897
- The call was switched from `pmix_common_dstor_store`, which adds the
extra wrapping (seen in this PR), to `_dstore_store_nolock` which
expects the `kv` to already be wrapped.
(cherry picked from commit c9d0632b61ec450c7661fd6a80a63033134a4242)
=> Wrap the inner dstore kv in an object.

config/pmix_config_asm.m4, src/atomics/sys/Makefile.include, src/atomics/sys/architecture.h, src/atomics/sys/arm/atomic.h, src/atomics/sys/arm64/atomic.h, src/atomics/sys/atomic.h, src/atomics/sys/atomic_impl.h, src/atomics/sys/atomic_stdc.h, src/atomics/sys/cma.h, src/atomics/sys/gcc_builtin/atomic.h, src/atomics/sys/ia32/atomic.h, src/atomics/sys/powerpc/atomic.h, src/atomics/sys/sparcv9/atomic.h, src/atomics/sys/sync_builtin/atomic.h, src/atomics/sys/timer.h, src/atomics/sys/x86_64/atomic.h, src/atomics/sys/x86_64/timer.h, src/atomics/sys/x86_64/update.sh, src/class/pmix_list.h, src/class/pmix_object.h, src/include/Makefile.include, src/include/pmix_stdatomic.h, src/include/pmix_stdint.h, src/threads/mutex_unix.h, src/threads/thread_usage.h, src/threads/wait_sync.h
=> Sync with OPAL atomics

examples/debuggerd.c, examples/group.c, src/mca/gds/ds21/gds_ds21_lock_pthread.c, test/simple/gwclient.c
=> Silence warnings and fix ds21 for new atomics

config/pmix.m4, src/mca/common/dstore/dstore_segment.c, src/mca/common/dstore/dstore_segment.h, src/mca/gds/ds21/gds_ds21_lock_pthread.c
(cherry picked from commit c9a8bba66bae2ac02eb35f4f4392678e56539aaf)
Corresponds to #805
=> v3.1/dstore: ds21 locks are aligned to the size of the cache line

test/simple/simptest.c
=> Ensure SIGCHLD is unblocked in simptest

src/server/pmix_server_ops.c, src/tools/pevent/pevent.c
=> v3.1: Fix event registration when not supported by host 

include/pmix_common.h.in, src/common/pmix_query.c, src/event/pmix_event_registration.c, src/include/pmix_globals.h, src/mca/ptl/tcp/ptl_tcp_component.c, src/mca/ptl/usock/ptl_usock_component.c, src/server/pmix_server.c, src/server/pmix_server_ops.c, test/simple/simpclient.c, test/simple/simptest.c, test/simple/simptool.c
=> First pass at bringing the library into compliance with v2.1 of the standard

src/client/pmix_client.c, src/common/pmix_query.c, src/server/pmix_server.c, src/server/pmix_server_ops.c, src/tool/pmix_tool.c
=> Cleanup tool operations and remove debug

bindings/python/setup.py, src/server/pmix_server.c
=> Resolve thread shift issue and silence Cython warning

include/pmix_common.h.in
=> Add process set name key

src/common/pmix_query.c
=> Correctly handle refresh_cache for queries

include/pmix_common.h.in, src/common/pmix_query.c, src/include/pmix_globals.h, src/mca/ptl/base/ptl_base_sendrecv.c, src/server/pmix_server.c, src/server/pmix_server_get.c, src/server/pmix_server_ops.c, test/simple/simpdmodex.c
Updates for compliance and to fix race conditions in collective trackers
=> Catch v3.1 up with changes

src/mca/common/dstore/dstore_file.h, src/mca/gds/ds12/gds_ds12_file.c, src/mca/gds/ds12/gds_ds20_file.c, src/mca/gds/ds21/gds_ds21_file.c
=> v3.1/dstor: fix detection of invalidated key

src/client/pmix_client_get.c
=> v3.1: Fixed verbose output for get operation.

src/mca/ptl/tcp/ptl_tcp.c
=> Silence error logs on rejected connections

src/common/pmix_query.c
=> Correct typo on proc assignment

src/mca/ptl/tcp/ptl_tcp_component.c
=> Silence unnecessary warning message

include/pmix_common.h.in, src/mca/ptl/tcp/ptl_tcp.c
=> Pass the tool's pid to the server

src/mca/ptl/ptl_types.h, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c, src/server/pmix_server.c
=> Correctly handle client tools

include/pmix_common.h.in
=> Add attribute to mark that a job consists of tool

src/server/pmix_server_ops.c
=> plug a memory leak in the spcbfunc() callback

src/mca/pnet/base/pnet_base_fns.c
release the pmix_pnet_node_t and pmix_pnet_local_procs_t objects in
pmix_pnet_base_deregister_nspace()
=> pnet/base: plug misc memory leaks

src/mca/common/dstore/dstore_file.h, src/mca/gds/ds12/gds_ds12_file.c, src/mca/gds/ds12/gds_ds20_file.c, src/mca/gds/ds21/gds_ds21_file.c
=> v2.2/dstor: fix detection of invalidated key

include/pmix_common.h.in, src/client/pmix_client_get.c, src/client/pmix_client_ops.h, src/mca/common/dstore/dstore_base.c, src/mca/common/dstore/dstore_base.h, src/mca/gds/ds12/gds_ds12_base.c, src/mca/gds/ds21/gds_ds21_base.c, src/mca/gds/gds.h, src/mca/gds/hash/gds_hash.c, src/runtime/pmix_params.c
=> Use fastpath to get keys without thread shifting, if supported by GDS

src/server/pmix_server_ops.c
=> Expand the local procs/peers wildcards for group construct

src/server/pmix_server_ops.c
=> Ensure we expand wildcard even if only one local proc

src/event/pmix_event_notification.c
=> Bump the oldest notification to make room, if needed

src/mca/gds/base/gds_base_fns.c
OBJ_{CONSTRUCT,DESTRUCT} the temporary pmix_buffer_t bkt.
=> gds/base: plug a memory leak in pmix_gds_base_store_modex()

src/mca/common/dstore/dstore_base.c
Closes: https://github.com/pmix/pmix/issues/1005
=> dstor/base: Address COV issue 168766

src/mca/ptl/tcp/ptl_tcp.c
=> Modify the connection order so we do system-first if requested

examples/Makefile.am, include/pmix_common.h.in
=> Add missing file to tarball and missing attributes

src/server/pmix_server_ops.c
=> Construct the list before use

include/pmix_common.h.in
=> Eliminate counter confusion across macros

src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c
=> Have a server store its internal URI for retrieval

src/mca/ptl/tcp/ptl_tcp_component.c
=> Remove envar indicating v3 protocol support

examples/tool.c, src/common/pmix_query.c, src/include/pmix_globals.h, src/mca/ptl/tcp/ptl_tcp_component.c, src/runtime/pmix_init.c, src/server/pmix_server_ops.c
Allow user to request information about a different node.
=> Save hostname for use in responding to queries

src/tool/pmix_tool.c
=> Forward PMIx MCA params by launchers

HACKING, INSTALL, LICENSE, NEWS, VERSION
=> Update docs for release

HACKING, INSTALL, LICENSE, NEWS, README, VERSION
=> Update all doc files for release

include/pmix_common.h.in
=> Restore PMIX_NUM_SLOTS

config/pmix.m4, include/pmix_version.h.in
=> configury: automatically generate PMIX_NUMERIC_VERSION

include/pmix_common.h.in
Courtesy of @jdinan - many thanks!
=> Improve performance and hardness of pmix_strncpy

include/pmix_common.h.in, src/common/pmix_iof.c, src/mca/bfrops/base/base.h, src/mca/bfrops/base/bfrop_base_copy.c, src/mca/bfrops/base/bfrop_base_fns.c, src/mca/bfrops/base/bfrop_base_pack.c, src/mca/bfrops/base/bfrop_base_print.c, src/mca/bfrops/base/bfrop_base_unpack.c, src/mca/bfrops/v4/Makefile.am, src/mca/bfrops/v4/bfrop_pmix4.c, src/mca/bfrops/v4/bfrop_pmix4.h, src/mca/bfrops/v4/bfrop_pmix4_component.c, src/mca/pnet/base/pnet_base_fns.c, src/mca/pnet/opa/pnet_opa.c, src/mca/pnet/opa/pnet_opa.h, src/mca/pnet/opa/pnet_opa_component.c, src/mca/pnet/pnet.h, src/mca/pnet/tcp/pnet_tcp.c, src/mca/pnet/test/pnet_test.c, src/mca/ptl/tcp/ptl_tcp.c, src/server/pmix_server_ops.c
=> Simulate assigning network coordinates for OPA

src/atomics/sys/powerpc/atomic.h
Tracks https://github.com/open-mpi/ompi/pull/6453
=> Atomics: fix a compiler warning on POWER arch

include/pmix_common.h.in, src/mca/bfrops/base/base.h, src/mca/bfrops/base/bfrop_base_fns.c, src/mca/bfrops/base/bfrop_base_pack.c, src/mca/bfrops/base/bfrop_base_unpack.c, src/mca/bfrops/v12/bfrop_v12.c, src/mca/bfrops/v12/internal.h, src/mca/bfrops/v12/pack.c, src/mca/bfrops/v12/unpack.c, src/mca/bfrops/v20/bfrop_pmix20.c, src/mca/bfrops/v20/internal.h, src/mca/bfrops/v20/pack.c, src/mca/bfrops/v20/unpack.c, src/mca/bfrops/v21/bfrop_pmix21.c, src/mca/bfrops/v3/bfrop_pmix3.c, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c
According to https://github.com/pmix/pmix/pull/1130#issuecomment-471073856, this PR re-opens #1126 (Used new PR since the original cannot be reopened).
Closes #1099
=> bfrops: redefinition regtypes for internal usage

NEWS, VERSION
=> Update header files

src/mca/bfrops/bfrops_types.h, src/mca/gds/base/gds_base_fns.c, src/server/pmix_server.c, src/server/pmix_server_ops.c
=> modex: avoid exchange unnecessary buffer when collect flag is not set

config/pmix.m4
=> Only check for Flex if we are in a git clone

src/mca/bfrops/v12/Makefile.am, src/mca/bfrops/v20/Makefile.am, src/mca/bfrops/v21/Makefile.am, src/mca/bfrops/v3/Makefile.am, src/mca/bfrops/v4/Makefile.am, src/mca/gds/ds12/Makefile.am, src/mca/gds/ds21/Makefile.am, src/mca/gds/hash/Makefile.am, src/mca/pcompress/zlib/Makefile.am, src/mca/plog/default/Makefile.am, src/mca/plog/smtp/Makefile.am, src/mca/plog/stdfd/Makefile.am, src/mca/plog/syslog/Makefile.am, src/mca/pnet/opa/Makefile.am, src/mca/pnet/tcp/Makefile.am, src/mca/pnet/test/Makefile.am, src/mca/preg/native/Makefile.am, src/mca/psec/munge/Makefile.am, src/mca/psec/native/Makefile.am, src/mca/psec/none/Makefile.am, src/mca/psensor/file/Makefile.am, src/mca/psensor/heartbeat/Makefile.am, src/mca/pshmem/mmap/Makefile.am, src/mca/psquash/flex128/Makefile.am, src/mca/psquash/native/Makefile.am, src/mca/ptl/tcp/Makefile.am, src/mca/ptl/usock/Makefile.am
=>  Add missing links for static builds

test/Makefile.am, test/run_tests.pl
Add a script that runs the Jenkins tests and returns a non-zero status
if any of them fail.
=> Implement "make check" in the tests subdir

test/run_tests.pl
Scan the output of the Jenkins run to get the list of tests
=> Replicate the tests in current Mellanox Jenkins

src/mca/pfexec/linux/pfexec_linux.h
=> Export missing symbols

contrib/pmix.spec
Introduces modification in the SPEC file to allow separate packaging of backward-compatibility PMI-1 and PMI-2 libraries and header files. 
This has been discussed in https://bugs.schedmd.com/show_bug.cgi?id=4511 and the idea is to allow sites to install a combination of PMIx (libpmix.so) and backward-compatibility PMI-1 (libpmi.so) and PMI2 (libpmi2.so) from either the PMIx project or Slurm, without conflicting with each other.
Right now, the PMIx 3.x RPM installs:
* `libpmi.so -> libpmi.so.1`
* `libpm2.so -> libpm2.so.1`
* `libpmix.so ->  libpmix.so.2`
and the `slurm-libpmi` RPM installs:
* `libpmi.so -> libpmi.so.0`
* `libpm2.so -> libpm2.so.0`
So the symlinks conflict but point to different versions of the same libraries. Meaning the the PMIx RPM cannot be installed in conjunction …
=> SPEC: allow splitting RPM in pmix and pmix-compat packages

contrib/pmix.spec
to allow separate packaging of backward-compatiblility PMI-1 and PMI-2 libs
Signed-off-by: Kilian Cavalotti <kilian@stanford.edu>
(cherry picked from commit 6e75a472b2cc348ac03895502059c823c157569d)
=> SPEC: allow splitting RPM in pmix and pmix-libpmi packages

src/include/types.h, src/mca/ptl/base/ptl_base_sendrecv.c, src/mca/ptl/ptl_types.h, src/mca/ptl/usock/ptl_usock.c
Use the appropriate size for the given configuration
Fixes #1238 
=> Define host/network conversion for size_t

test/pmix_test.c, test/server_callbacks.c, test/test_common.c, test/test_common.h, test/test_resolve_peers.c, test/test_server.c, test/test_server.h
* Fix error code propagation
* Fix "success" report for failing cases
* Minor improvements with debugging output
=> Fixes in the PMIx test suite

src/server/pmix_server_ops.c
=> Avoid double-free of tracker

test/cli_stages.c, test/cli_stages.h, test/pmix_test.c, test/server_callbacks.c, test/test_common.c, test/test_common.h, test/test_fence.c, test/test_resolve_peers.c, test/utils.c, test/utils.h
=> v3.0/Fix the test suite with GDS hash component

test/cli_stages.c, test/cli_stages.h, test/pmix_test.c, test/server_callbacks.c, test/test_common.c, test/test_common.h, test/test_fence.c, test/test_resolve_peers.c, test/utils.c, test/utils.h
=> v2.1/Fix the test suite with GDS hash component 

src/runtime/pmix_progress_threads.c
=> v2.2/server: Fix PMIx_Server_Finalize hang

src/runtime/pmix_progress_threads.c
=> v2.0/server: Fix PMIx_Server_Finalize hang

src/runtime/pmix_progress_threads.c
=> v2.1/server: Fix PMIx_Server_Finalize hang

src/runtime/pmix_progress_threads.c
=> v3.0/server: Fix PMIx_Server_Finalize hang

src/mca/pfexec/linux/pfexec_linux.c
=> Silence another Coverity warning

src/atomics/sys/atomic_stdc.h, src/class/pmix_hotel.c, src/class/pmix_list.h, src/event/pmix_event_notification.c, src/mca/base/pmix_mca_base_component_repository.c, src/mca/base/pmix_mca_base_var.c, src/mca/base/pmix_mca_base_var_enum.c, src/mca/bfrops/base/bfrop_base_copy.c, src/mca/bfrops/base/bfrop_base_frame.c, src/mca/bfrops/base/bfrop_base_pack.c, src/mca/bfrops/base/bfrop_base_print.c, src/mca/bfrops/base/bfrop_base_unpack.c, src/mca/gds/base/gds_base_fns.c, src/mca/pcompress/base/pcompress_base_frame.c, src/mca/pfexec/base/pfexec_base_default_fns.c, src/mca/pfexec/base/pfexec_base_frame.c, src/mca/pif/base/pif_base_components.c, src/mca/plog/base/plog_base_frame.c, src/mca/psensor/base/psensor_base_frame.c, src/mca/ptl/base/ptl_base_frame.c, src/mca/ptl/base/ptl_base_listener.c, src/mca/ptl/base/ptl_base_sendrecv.c, src/mca/ptl/base/ptl_base_stubs.c
Silence a selection of unused parameters (`-Wunused-parameter`).
=> Warning: Unused Parameters

src/mca/bfrops/base/bfrop_base_pack.c, src/mca/bfrops/base/bfrop_base_unpack.c
=> Add unsigned types to generic type check

src/mca/psec/psec.h, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c, src/mca/ptl/usock/ptl_usock_component.c
Avoid sending extra message in the client connection case.
Is an alternative to:
https://github.com/pmix/pmix/pull/1240
=> PTL: Fix the connection establishment protocol (minimalistic)

NEWS, VERSION
=> Update NEWS/VERSION for rc3

bindings/python/construct.py, bindings/python/pmix.pyx, include/pmix_sched.h
=> Add scheduler interfaces to Python bindings

src/mca/pnet/pnet.h, src/server/pmix_sched.c
=> Add missing scheduler function

.gitignore, bindings/python/Makefile.am, bindings/python/client.py.in, bindings/python/server.py.in, config/pmix.m4
=> Detect Python path and use that in the Py examples

src/server/pmix_server.c, test/test_server.c
If the caller doesn't provide a cbfunc for PMIx_server_register_nspace
and friends, then don't just return and let the processing of the
request be done without pause as they could get into race conditions.
=> Provide blocking ability to the register/deregister fns

config/pmix.m4, src/mca/psec/dummy_handshake/Makefile.am, src/mca/psec/dummy_handshake/psec_dummy_handshake.c, src/mca/psec/dummy_handshake/psec_dummy_handshake.h, src/mca/psec/dummy_handshake/psec_dummy_handshake_component.c
=> v2.0/psec: add dummy handshake component

config/pmix.m4, src/mca/psec/dummy_handshake/Makefile.am, src/mca/psec/dummy_handshake/psec_dummy_handshake.c, src/mca/psec/dummy_handshake/psec_dummy_handshake.h, src/mca/psec/dummy_handshake/psec_dummy_handshake_component.c
=> v2.1/psec: add dummy handshake component

config/pmix.m4, src/mca/psec/dummy_handshake/Makefile.am, src/mca/psec/dummy_handshake/psec_dummy_handshake.c, src/mca/psec/dummy_handshake/psec_dummy_handshake.h, src/mca/psec/dummy_handshake/psec_dummy_handshake_component.c
=> v2.2/psec: add dummy handshake component

config/pmix.m4, src/mca/psec/dummy_handshake/Makefile.am, src/mca/psec/dummy_handshake/psec_dummy_handshake.c, src/mca/psec/dummy_handshake/psec_dummy_handshake.h, src/mca/psec/dummy_handshake/psec_dummy_handshake_component.c
=> v3.0/psec: add dummy handshake component

config/pmix.m4, src/mca/psec/dummy_handshake/Makefile.am, src/mca/psec/dummy_handshake/psec_dummy_handshake.c, src/mca/psec/dummy_handshake/psec_dummy_handshake.h, src/mca/psec/dummy_handshake/psec_dummy_handshake_component.c
=> v3.1/psec: add dummy handshake component

.gitignore, include/pmix_common.h.in, src/mca/gds/hash/gds_hash.c, src/mca/pnet/base/base.h, src/mca/pnet/base/pnet_base_frame.c, src/mca/pnet/pnet.h, src/mca/pnet/tcp/pnet_tcp.h, src/mca/pnet/test/pnet_test.c, src/mca/pnet/test/pnet_test.h, src/mca/pnet/test/pnet_test_component.c, src/server/pmix_sched.c, test/simple/Makefile.am, test/simple/simpsched.c, test/simple/simptest.c
Provide a simple test component for the scheduler interfaces
along with a simpsched test that exercises them.
=> Implement pnet/test sched support

src/mca/ptl/tcp/ptl_tcp.h, src/mca/ptl/tcp/ptl_tcp_component.c
Should be a session-level rendezvous file whose name is just
pmix.host.tool
=> Add missing tool rendezvous file

include/pmix_common.h.in, src/mca/gds/hash/gds_hash.c, src/mca/pnet/base/pnet_base_fns.c, src/mca/pnet/test/pnet_test.c, src/mca/ptl/ptl_types.h, src/server/pmix_server.c, test/simple/simpsched.c
=> Prep tutorial and complete pnet/test component

.gitignore, bindings/python/pmix.pxi, bindings/python/pmix.pyx, bindings/python/sched.py.in, config/pmix.m4, src/mca/pnet/test/pnet_test.c
=> Implement Python bindings for setup_app and setup_local

include/pmix_common.h.in, src/mca/pnet/tcp/pnet_tcp.c
=> Prototype inline implementation of convenience macros

bindings/python/pmix.pxi
=> Correctly load byte object in Python

bindings/python/pmix.pxi, bindings/python/pmix.pyx
=> Add some more debugging to Python bindings

bindings/python/sched.py.in
=> Must provide the node and proc maps to register nspace

test/cli_stages.c, test/cli_stages.h, test/pmix_test.c, test/server_callbacks.c, test/test_common.c, test/test_resolve_peers.c, test/utils.c, test/utils.h
=> v2.0/test: eliminated the usage of through ranking for namespaces

NEWS, configure.ac, include/pmix_common.h.in, include/pmix_rename.h.in, src/atomics/sys/atomic_stdc.h, src/mca/gds/base/gds_base_fns.c, src/mca/gds/hash/gds_hash.c, src/mca/pnet/base/pnet_base_fns.c, src/mca/preg/native/preg_native.c, src/mca/ptl/tcp/ptl_tcp.h, src/mca/ptl/tcp/ptl_tcp_component.c, src/server/pmix_server.c, src/util/output.c, src/util/output.h, test/test_server.c
Add some fixes since the last rc - these are mostly minor corrections to reported problems.
=> Bring branch up-to-date

configure.ac
=> Cache only -W CFLAG entries to fix 32-bit builds

config/pmix.m4, configure.ac, contrib/whitespace-purge.sh, src/mca/pnet/opa/configure.m4
Thanks to Stephane Goujet for the report
=> Do not use '==' in m4 test statements

src/mca/base/pmix_mca_base_component_find.c, src/mca/base/pmix_mca_base_open.c, src/mca/pnet/opa/pnet_opa.c, src/mca/pnet/tcp/pnet_tcp.c, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/tcp/ptl_tcp_component.c, src/runtime/pmix_init.c, src/tool/pmix_tool.c, src/util/output.c
=> Reserve that last space for the NULL

test/test_server.c
fix incorrect pointer casts (major); 
adjust test timeout code (minor);
correct english (trivial)
=> fix incorrect pointer casts/deref

test/test_server.c
=> fix another pointer cast/deref in test suite

src/mca/gds/hash/gds_hash.c
Fixes #1360
Thanks to @tonycurtis for the report
=> Remove debug

bindings/python/pmix.pyx
=> Fix Python bindings

src/mca/pnet/test/pnet_test.c, test/simple/simpcoord.c
Some minor cleanups and added debug
=> Cleanup pnet/test component and associated test

src/mca/ptl/tcp/ptl_tcp_component.c
The next tool might be looking for it too
=> Don't whack the rendezvous file if you are a tool

.gitignore, config/pmix.m4, config/pmix_setup_libev.m4, config/pmix_setup_libevent.m4, src/client/pmix_client.c, src/include/pmix_globals.c, src/include/types.h, src/mca/common/dstore/dstore_segment.c, src/mca/ptl/tcp/ptl_tcp.c, src/mca/ptl/usock/ptl_usock.c, src/runtime/pmix_init.c, src/runtime/pmix_progress_threads.c, src/server/pmix_server.c, src/tool/pmix_tool.c, test/cli_stages.c, test/cli_stages.h, test/simple/gwtest.c, test/simple/simptest.c, test/simple/stability.c, test/test_server.c
=> Backport support for libev

src/client/pmix_client_get.c
=> Remove unnecessary error log

config/pmix.m4
The Autoconf test searches the system for a Python of at least the
specified version. However, that does NOT mean that the active version
of Python met that requirement - it only means that the specified
version is somewhere on the system. We actually require that the active
version meet the minimums, so test that more directly.
=> Be more restrictive on the minimum Python requirement

src/common/pmix_log.c, src/mca/plog/base/plog_base_stubs.c, src/mca/plog/stdfd/plog_stdfd.c, test/simple/quietclient.c, test/simple/simpclient.c, test/simple/simpcoord.c, test/simple/simpdie.c, test/simple/simpdmodex.c, test/simple/simpdyn.c, test/simple/simpft.c, test/simple/simpjctrl.c, test/simple/simppub.c, test/simple/simptimeout.c, test/simple/stability.c
=> Update simple tests to use job size instead of universe, fix Log code path

src/client/pmix_client_get.c
=> Skip fastpath/dstore for NULL keys

bindings/python/client.py.in, bindings/python/pmix.pxi, bindings/python/pmix.pyx, bindings/python/sched.py.in, bindings/python/server.py.in
This updates the info type to use a list of dictionaries
where each dictionary defines a key, value, and value type:
[{key:y, value:val, val_type:ty}, … ]
=> update info type to use list of dictionaries

src/mca/pshmem/mmap/pshmem_mmap.c
Fixes #1384
Thanks to Aurelien Larcher for the report
=> Check for EINVAL return from posix_fallocate

.travis.yml
=> Update travis - remove gfortran

src/server/pmix_server_ops.c
=> Minor cleanup

include/pmix.h, src/common/pmix_query.c
Refs https://github.com/pmix/pmix-standard/pull/209
=> Add blocking form of PMIx_Query_info

include/pmix_common.h.in, src/mca/bfrops/base/bfrop_base_copy.c, src/mca/bfrops/base/bfrop_base_pack.c, src/mca/bfrops/base/bfrop_base_print.c, src/mca/bfrops/base/bfrop_base_unpack.c, src/mca/pnet/test/pnet_test.c
Refs https://github.com/pmix/pmix-standard/pull/212
=> Update pmix_coord_t to track Standard

include/pmix_common.h.in
=> Cleanup a couple of attribute definitions

src/mca/preg/compress/preg_compress.c, src/mca/preg/native/preg_native.c
=> Remove debug error logs

src/client/pmix_client_pub.c
Fixes #1431 
Thanks to @dsikich, @artpol84, and @ariebs for all independently reporting this problem! Must have been a good week for PMIx_Publish.
=> Return the correct status from PMIx_Publish

examples/dmodex.c, src/server/pmix_server_get.c
=> Cleanup example and remove debug

NEWS
=> Update the NEWS from the release branches

bindings/python/pmix.pxi, bindings/python/pmix.pyx, include/pmix.h, src/common/pmix_control.c, test/python/sched.py
Add Tool class and fill in more client functions 
Add missing parameters to blocking APIs
Missing parameters to return results of PMIx_Job_control and
PMIx_Process_monitor. Need to update Standard to match
=> Add Tool class and missing parameters to blocking APIs

bindings/python/pmix.pyx
=> Continue prototyping Python bindings

bindings/python/pmix.pyx, src/client/pmix_client_group.c
Add some more Python bindings and mark where more work needs to be done
to complete implementation. Add missing PMIx_Group functions
=> Complete the Python binding prototypes and add missing functions

bindings/python/pmix.pyx, test/simple/simpcoord.c
=> Minor touchup to the python bindings

src/mca/bfrops/base/bfrop_base_fns.c
Refs https://github.com/open-mpi/ompi/pull/6993
=> Silence miscellaneous compiler warnins

bindings/python/client.py, bindings/python/pmix.pxi, bindings/python/pmix.pyx, bindings/python/server.py
=> Example of how to threadshift in Python bindings

bindings/python/pmix.pxi, bindings/python/pmix.pyx
Created pmix_alloc_info since most of the info struct
memory allocation and error checking code was the same
in every wrapper. This reduces the amount of code in
each wrapper.
=> Add helper function for allocating info structs

.gitignore, Makefile.am, Makefile.pmix-rules, config/pmix.m4, config/pmix_setup_cc.m4, config/pmix_setup_hwloc.m4, config/pmix_setup_libev.m4, config/pmix_setup_libevent.m4, config/pmix_setup_wrappers.m4, configure.ac, contrib/Makefile.am, contrib/make_manpage.pl, src/mca/pinstalldirs/pinstalldirs.h, src/tools/Makefile.include, src/tools/wrapper/Makefile.am, src/tools/wrapper/generic_wrapper.1in, src/tools/wrapper/help-pmix-wrapper.txt, src/tools/wrapper/pmix.pc.in, src/tools/wrapper/pmix_wrapper.1in, src/tools/wrapper/pmix_wrapper.c, src/tools/wrapper/pmixcc-wrapper-data.txt.in, src/util/Makefile.include, src/util/few.c, src/util/few.h
Helps when building unit tests, but also useful for anyone just writing
a PMIx-based tool or app.
=> Add a wrapper compiler for building PMIx-only apps

bindings/python/Makefile.am
=> Include missing binding files in tarball

NEWS, VERSION, examples/dmodex.c, include/pmix.h, include/pmix_common.h.in, src/client/pmix_client.c, src/client/pmix_client_get.c, src/common/pmix_query.c, src/include/pmix_globals.c, src/include/pmix_globals.h, src/mca/common/dstore/dstore_base.c, src/mca/gds/hash/gds_hash.c, src/server/pmix_server.c, src/server/pmix_server_get.c, src/server/pmix_server_ops.c, src/util/compress.c, src/util/name_fns.c, src/util/name_fns.h
@dsolt Please check to see if I caught everything needed for support of unknown nspaces.
=> Bring v3.1.5 up to date

src/mca/bfrops/v12/unpack.c, src/mca/gds/hash/gds_hash.c
=> Silence spurious error logs

src/mca/bfrops/v12/unpack.c, src/mca/gds/hash/gds_hash.c
=> Remove spurious error logs

src/mca/bfrops/v12/unpack.c
=> Silence spurious error log

test/simple/simptool.c
=> Test blocking form of PMIx_Query_info

bindings/python/pmix.pyx, bindings/python/tests/client.py
Add a function to test the register event handler wrapper
=> cleanup register event handler test in client

bindings/python/pmix.pyx, bindings/python/tests/client.py, bindings/python/tests/server_upcalls.py
The fence server module function was not invoking
its callback function
=> Python: add callback function invocation in fence

test/simple/simpclient.c, test/simple/simptest.c
We were incorrectly dealing with assignment of procs to nodes when
dealing with the simulation of multi-node ops.
=> Correct the simple tests

test/simple/simptest.c
=> Minor cleanup of simptest

bindings/python/pmix.pxi, bindings/python/pmix.pyx, bindings/python/setup.py
This PR depends on #1494 being merged first. 
Adds callback invocation for spawn, and correct return value from server module function according to v4 standard draft.
=> python: add callback and invocation for spawn 

src/common/pmix_log.c, src/mca/common/dstore/dstore_base.c, src/mca/preg/native/preg_native.c, src/mca/ptl/base/ptl_base_stubs.c, test/pmix_client.c, test/test_common.h, test/test_fence.c
Bring forward changes made to the v3.1 branch. Correctly transfer info to dstore for older versions.
=> Further cleanups for xversion

src/mca/common/dstore/dstore_base.c
(cherry picked from commit 97d234465b11143a0512cc6e4a194bac64864455)
=> Correctly transfer info to dstore for older versions

test/simple/simpclient.c
=> Ensure simpclient exits with error

test/simple/simpclient.c
=> Ensure simpclient exits upon error

src/mca/ptl/base/ptl_base_stubs.c, src/mca/ptl/tcp/ptl_tcp.c, src/server/pmix_server.c
=> Communicate the server's version to its clients

test/run_tests.pl.in
=> Add timeout capability to make check

test/test_cd.c, test/test_fence.c, test/test_internal.c, test/test_publish.c, test/test_replace.c, test/test_resolve_peers.c, test/test_spawn.c
=> Take a pass thru tests ensuring they exit with error

.gitignore, src/mca/ptl/tcp/ptl_tcp_component.c, test/simple/simptest.c
=> Fix tool and query support tests

test/cli_stages.c, test/cli_stages.h, test/pmi2_client.c, test/pmi_client.c, test/pmix_client.c, test/pmix_regex.c, test/pmix_test.c, test/server_callbacks.c, test/server_callbacks.h, test/simple/simpclient.c, test/test_cd.c, test/test_cd.h, test/test_common.c, test/test_common.h, test/test_error.c, test/test_fence.c, test/test_internal.c, test/test_publish.c, test/test_replace.c, test/test_resolve_peers.c, test/test_spawn.c, test/utils.c, test/utils.h
=> Ensure "make check" tests exit upon error

test/cli_stages.c, test/cli_stages.h, test/pmi_client.c, test/pmix_client.c, test/pmix_regex.c, test/pmix_test.c, test/server_callbacks.c, test/server_callbacks.h, test/simple/simpclient.c, test/simple/simptest.c, test/test_cd.c, test/test_cd.h, test/test_common.c, test/test_common.h, test/test_error.c, test/test_fence.c, test/test_internal.c, test/test_publish.c, test/test_replace.c, test/test_resolve_peers.c, test/test_spawn.c, test/utils.c, test/utils.h
Carry across the modifications to ensure proper report of errors.
=> Update "make check" tests for xversion

test/cli_stages.c, test/pmix_test.c, test/test_common.h, test/utils.c
=> Mark newly started procs as "alive"

src/mca/common/dstore/dstore_base.c
Properly support older clients
=> Update transfer from hash to dstore

test/test_fence.c
No such thing as "remote" procs as all the testing is done on a single
node.
=> Repair job-fence tests

bindings/python/pmix.pxi, bindings/python/pmix.pyx
- add tool iof_deliver function
- add server collect_inventory function
- add server deliver_inventory function
- move iof functions to tool class
- add pyiofhandler function for iof_pull
=> python: add missing wrappers and iof hdler

bindings/python/pmix.pyx
This adds the store_internal function wrapper to the client class.
=> python: store_internal client wrapper

.github/workflows/main.yml
Signed-off-by: Andrey Maslennikov <andreyma@mellanox.com>
(cherry picked from commit c10eef9bb51930f94e26b6a89de13d2a66d52c9c)
=> CI: make sure to run Actions on PR — v3.1

test/test_resolve_peers.c
=> Test: fixes resolve hostname to support backward compatibility with next versions

src/mca/common/dstore/dstore_base.c
Conflicts:
src/mca/common/dstore/dstore_base.c
=> Fix memory leak as explained in issue 1548

src/util/path.c
Signed-off-by: Geoffroy Vallee <geoffroy.vallee@gmail.com>
=> Fix typo in comment: contiaing -> containing

include/pmix_common.h.in, src/class/pmix_list.c, src/util/argv.h, src/util/cmd_line.c, src/util/pmix_environ.h
Signed-off-by: Geoffroy Vallee <geoffroy.vallee@gmail.com>
=> Fix a typo in comments: insertted -> inserted

src/mca/gds/hash/gds_hash.c, test/test_common.h, test/test_fence.c, test/test_server.c
- Fixes `nodeid` condition while finding nodeinfo item (see description in commit message)
- Fixes multiserver test mode
=> Fixes multiserver test mode

config/pmix.m4
=> configury: replace opal_show_subtitle with pmix_show_subtitle

bindings/python/pmix.pxi, bindings/python/tests/cython/cython_test_functions.pyx
Fix for most bugs in pmix_load_value that were uncovered
with the cython tests.
=> python: bug fixes for pmix_load_value

test/run_tests.pl.in
=> Enable multi-server tests

bindings/python/pmix.pxi, bindings/python/tests/cython/cython_test_functions.pyx
=> python: fix more type conversions in load_value

include/pmix_common.h.in
=> Add a PMIX_OUTPUT_TO_DIRECTORY attribute

.github/actions/mlnx/entrypoint.sh
=> Fix the mlnx CI - cannot use ds21 if --disable-pthlk

src/server/pmix_server_ops.c
=> Initialize the local flag to true

include/pmix_common.h.in
=> Add reincarnation tracker attribute

include/pmix_common.h.in, src/client/pmix_client_spawn.c, src/common/pmix_strings.c, src/mca/bfrops/base/base.h, src/mca/bfrops/base/bfrop_base_copy.c, src/mca/bfrops/base/bfrop_base_pack.c, src/mca/bfrops/base/bfrop_base_print.c, src/mca/bfrops/base/bfrop_base_unpack.c, src/mca/bfrops/v4/bfrop_pmix4.c, src/util/error.c
We missed this earlier, though we did add support for PMIx process
states. Add the corresponding job states and error constants
=> Add definition of PMIx job states

src/class/pmix_hotel.c, src/class/pmix_hotel.h
(cherry picked from commit 0cbcac76b676744c8842b7a7ac91f7394d1442e9)
=> Adjust hotel timeout to be in whole seconds

test/test_server.c
=> tests: Fix multiple occurrences of unaligned access
