openpmix/openpmix

- VERSION
> Correct library version triplet

- src/server/pmix_server.c
Protect against NULL nspace returns due to a failed launch
> Add a little protection against failed spawn requests

- config/pmix_check_vendor.m4
Tracks https://github.com/open-mpi/ompi/pull/7385
> Update "check_vendor" for PGI problem

- src/client/pmix_client_get.c
The callback object used to release PMIx_Get doesn't need to be
dynamically allocated - it can stay on the stack as we block in that
function until complete.
> Avoid an unnecessary malloc in a critical path

- src/server/pmix_server_get.c
Do not set a timeout on a dmodex request that gets passed up to the host
as they might also have one, resulting in a race condition that can
cause segfault.
> Remove a potential race condition

- config/pmix_load_platform.m4
- contrib/Makefile.am
- contrib/platform/intel/bend/linux
- contrib/platform/intel/bend/linux.conf
- contrib/platform/intel/bend/mac
- contrib/platform/intel/bend/mac.conf
- etc/Makefile.am
Ensure we provide the defaults if a platform is not specified.
Add some platform files for Intel/Bend
> Correctly transfer default param and hostfile files

- src/mca/base/pmix_mca_base_open.c
Tracks https://github.com/open-mpi/ompi/pull/7416
> Protect against NULL home directory

- NEWS
- VERSION
> Roll to rc4

- config/pmix_config_asm.m4
- src/atomics/sys/architecture.h
- src/atomics/sys/atomic.h
- src/atomics/sys/cma.h
> Remove MIPS atomics

- config/pmix_config_asm.m4
- src/atomics/sys/architecture.h
- src/atomics/sys/cma.h
> Remove stale s390 atomics

- src/atomics/sys/atomic.h
> Cleanup nit

- src/server/pmix_server_get.c
> Flag a local proc as being "local"

- src/tool/pmix_tool.c
Even when they pass us a namespace/rank
> Pass back the tool's ID

- src/client/pmix_client_spawn.c
- src/tool/pmix_tool.c
Need the pmdl and pnet frameworks
> Ensure that launchers open all required frameworks

- src/mca/pfexec/base/pfexec_base_default_fns.c
We only use fork/exec inside PMIx for tools and servers. Let them choose
their own nspace/rank and components.
> Do not transfer settings to fork/exec'd child

- src/client/pmix_client_spawn.c
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/tool/pmix_tool.c
Also cleanup any directories we create
> Ensure cleanup of fork/exec children

- config/pmix.m4
- src/mca/pmdl/ompi4/pmdl_ompi4.c
> Add support for missing include

- src/mca/gds/ds12/gds_ds12_lock_pthread.c
> Silence unnecessary error logs

- src/mca/ptl/tcp/ptl_tcp_component.c
> Little more cleanup on rndz file cleanup

- include/pmix_common.h.in
- src/client/pmix_client_get.c
- src/mca/gds/hash/gds_hash.c
> Silence some warnings and update an attribute's value

- src/common/pmix_control.c
> Protect job control from NULL results param

- include/pmix_common.h.in
- src/mca/gds/hash/gds_hash.c
> Alert user to FQDN status

- src/class/pmix_object.h
- src/threads/mutex_unix.h
> Silence warnings about static mutex init

- src/event/pmix_event.h
- src/hwloc/hwloc-internal.h
- src/runtime/pmix_rte.h
- src/server/pmix_server_ops.h
- src/tool/pmix_tool.c
> Play it safe - export all functions/vars

- src/mca/gds/hash/gds_hash.c
Hash component also needs to check for node/app keys and assume the
procs own host/appnum if not given. Also add a bunch of verbose debug to
help track down such problems.
> Assume our host/appnum if not given

- src/client/pmix_client.c
- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/mca/ptl/ptl.h
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/server/pmix_server_ops.c
- src/tool/pmix_tool.c
Deal with a variety of race conditions related to tool reconnection to a
different server.
> Update event notification for tool support

- src/mca/pmdl/ompi4/pmdl_ompi4.c
- src/mca/pmdl/ompi5/pmdl_ompi5.c
...so that OMPI knows and doesn't do it anyway
> Flag that user-level params were forwarded

- contrib/Makefile.am
- contrib/symbol-hiding.pl
- src/util/show_help_lex.h
> Export missing variables

- config/pmix_setup_wrappers.m4
- include/pmix_rename.h.in
> Remove more symbols and fix a wrapper

- config/pmix_config_asm.m4
> Silence unnecessary error msg in configure

- src/common/pmix_iof.c
- src/mca/pmdl/base/pmdl_base_stubs.c
- src/server/pmix_server_ops.c
> Silence a few Coverity warnings

- include/pmix_common.h.in
> Add PMIX_NUMA_RANK attribute key

- src/server/pmix_server_get.c
This commit avoids creating a local tracker for existing keys.
A local client may send a get request concurrently with a commit
request from another client, but the server may have processed the
commit request earlyer than the get request. In this case, we create
a local tracker for possibly existing keys that are added with the
completed commit request. Thus, the get request will be pended in
tracker and will be deffered. This scenario is possible when the
non-fence commit-get scheme is used and when the peer GDS
component is `dstore`.
> pmix_server_get: avoid creating a local tracker for existing keys

- test/test_v2/pmix_test.c
- test/test_v2/test_common.c
- test/test_v2/test_common.h
- test/test_v2/utils.c
- test/test_v2/utils.h
Modifications to the new PMIx test suite in test/test_v2 per @artpol84 's guidance. 
This commit includes:
-Removal of command-line options and associated functionality not necessary for the new suite;
-Addition of some support functions necessary to the new suite.
> Created support functions for test infrastructure

- src/client/pmix_client_get.c
> Don't return next_option when not found

- src/include/Makefile.include
> Add missing include to tarball

- src/server/pmix_server_get.c
- src/server/pmix_server_ops.h
Put a big comment explaining why we are doing it this way.
> Spruce up the dmodex fix

- src/mca/pmdl/ompi5/pmdl_ompi5.c
Grab all the data needed for setting OMPI envars during register_nspace
> Ensure we collect all data needed for setup_fork

- src/common/pmix_query.c
- src/mca/pstrg/lustre/pstrg_lustre.c
Pending getting the implementation added
Fixes https://github.com/openpmix/prrte/issues/515
> Default the pstrg/lustre query to return not found

- src/mca/base/pmix_mca_base_vari.h
> Export some missing functions

- include/pmix_common.h.in
Replace PMIX_NUMA_RANK with PMIX_PACKAGE_RANK
Add PMIX_FIRST_ENVAR to indicate the value you wish to have put first in
the indicated envar
> Add two attributes

- config/pmix_check_lustre.m4
- src/common/pmix_log.c
- src/mca/pnet/sshot/Makefile.am
- src/mca/pnet/sshot/pnet_sshot.c
- src/mca/pnet/sshot/pnet_sshot.h
- src/mca/pnet/sshot/pnet_sshot_component.c
Update lustre config logic
Tracks OMPI equivalent code
Silence Coverity warning
Add a new slingshot prototype component
To be completed - ignored for now.
> Update Lustre config logic plus add a new component prototype

- src/mca/pmdl/base/Makefile.include
- src/mca/pmdl/base/help-pmdl.txt
- src/mca/pmdl/ompi5/pmdl_ompi5.c
> Pickup the OMPI system-default params

- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/pdl/plibltdl/pdl_libltdl_module.c
> Minor cleanups - typo plus a missing part of a prior commit

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
Update the PMIx_Register_attributes function signature. Note that there
are still some warnings coming out from different areas of the bindings
not related to this patch that need investigation.
Fixes https://github.com/openpmix/openpmix/issues/1782
> Fix Python binding compilation

- src/server/pmix_server_get.c
> v3.2/Fixes cleanup the dmdx satisfied request list

- NEWS
- VERSION
- src/mca/pnet/base/pnet_base_fns.c
Fixes https://github.com/openpmix/openpmix/issues/1762
> Silence unnecessary error logs and prep for release

- config/pmix_setup_libev.m4
Choose a better function to check against
> Fix libev configury

- NEWS
> Update NEWS from v2.2.4 release

- src/mca/prm/tm/prm_tm.h
Fix header guard, was checking twice instead of check + define
> Fix header guard

- include/pmix_common.h.in
- src/tool/pmix_tool.c
- src/util/error.c
Fixes https://github.com/openpmix/openpmix/issues/1801
> Fix trivial spelling error

- src/client/pmix_client.c
- src/tool/pmix_tool.c
Put the server nspace/rank in our internal cache so it can easily be
retrieved via PMIx_Get
Refs https://github.com/openpmix/openpmix/issues/1801
> Cache the server ID for later retrieval

- src/mca/pstrg/vfs/Makefile.am
- src/mca/pstrg/vfs/pstrg_vfs.c
- src/mca/pstrg/vfs/pstrg_vfs.h
- src/mca/pstrg/vfs/pstrg_vfs_component.c
> Add VFS storage component

- src/tool/pmix_tool.c
> Few cleanups in tool reconnect

- src/mca/ptl/usock/ptl_usock_component.c
- src/server/pmix_server_ops.c
> Cleanup a couple of minor issues

- src/client/pmix_client_get.c
When passed an invalid rank in the ID along with PMIX_RANK as the key,
return the caller's own rank
Fixes #1795 
> Allow retrieval of the caller's own rank

- src/util/error.c
> Add missing error code strings

- maint/pmix.pc.in
Thanks to @tonycurtis for the report
Fixes https://github.com/openpmix/openpmix/issues/1826
> Fix typo in pmix.pc.in

- test/run_tests.pl.in
Fixes https://github.com/openpmix/openpmix/issues/1828
> Up the timeout as some tests are running on the edge

- config/pmix_setup_hwloc.m4
- config/pmix_setup_libevent.m4
Add ability for PMIx to find hwloc and libevent packages which are
built at the same time as PMIx, such as third party dependencies
in an MPI package.  This is a slight change on the existing
embedded PMIx support, in that it does not assume that PMIx itself
is being built embedded in another library, only that some of its
dependencies may be built at the same time as PMIx.
> build: Support hwloc and libevent cobuild

- test/test_v2/Makefile
- test/test_v2/pmix_test.c
- test/test_v2/test_common.c
- test/test_v2/test_common.h
- test/test_v2/test_get_basic.c
- test/test_v2/test_server.c
Also added ability to validate values returned by basic PMIx_get calls.
This PR is the implementation for issue 64 in openpmix/pmix-tests: https://github.com/openpmix/pmix-tests/issues/64.
> Created basic PMIx_Get() test case for rank positioning info

- src/mca/ptl/tcp/ptl_tcp.c
- src/tool/pmix_tool.c
Make it possible for tools to be connected to multiple servers at the
same time.
> Implement the new tools APIs

- .gitignore
- VERSION
- config/pmix.m4
- config/pmix_check_curl.m4
- configure.ac
- src/include/pmix_globals.h
- src/mca/common/sse/Makefile.am
- src/mca/common/sse/configure.m4
- src/mca/common/sse/sse.c
- src/mca/common/sse/sse.h
- src/mca/common/sse/sse_internal.h
- src/mca/common/sse/sse_lex.l
- src/mca/prm/hpesmf/configure.m4
- src/mca/psensor/hpesmf/Makefile.am
- src/mca/psensor/hpesmf/configure.m4
- src/mca/psensor/hpesmf/help-pmix-psensor-hpe.txt
- src/mca/psensor/hpesmf/psensor_hpe.c
- src/mca/psensor/hpesmf/psensor_hpe.h
- src/mca/psensor/hpesmf/psensor_hpe_component.c
- src/server/pmix_server_ops.c
- test/simple/simpsched.c
Provide some prototype support
> Continue work on REST support

- Makefile.am
- config/pmix.m4
- contrib/construct_dictionary.py
- include/pmix.h
- include/pmix_common.h.in
- src/include/dictionary.h
- src/util/error.c
> Auto-construct the dictionary whenever "make install"

- include/pmix_common.h.in
- src/client/pmix_client_fabric.c
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/bfrops/v4/bfrop_pmix4.c
- src/mca/ploc/base/base.h
- src/mca/ploc/base/ploc_base_frame.c
- src/mca/ploc/base/ploc_base_stubs.c
- src/mca/ploc/ploc.h
- src/runtime/pmix_init.c
- src/server/pmix_server.c
Some cleanup of PMIx_server_init included
> Add missing support for PMIX_TOPO data type

- contrib/Makefile.am
- examples/client.c
- src/mca/ploc/hwloc/ploc_hwloc.c
> Debug and cleanup the ploc/hwloc component

- include/pmix_common.h.in
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/bfrops/v4/bfrop_pmix4.c
- src/mca/ploc/hwloc/ploc_hwloc.c
- src/server/pmix_server.c
- test/simple/simptest.c
Need to add them to the pmix_value_t as pointers and adjust all the
xfer, copy, etc routines.
> Cleanup handling of new data types

- src/mca/ploc/hwloc/ploc_hwloc.c
> Add some debug for PRRTE - to be removed later

- include/pmix_common.h.in
> Minor adjustments to match Standard

- include/pmix_common.h.in
> Remove non-standard attribute

- config/pmix_load_platform.m4
- config/pmix_summary.m4
- src/mca/bfrops/base/bfrop_base_copy.c
> Change --with-platform option to --with-pmix-platform

- include/pmix.h
- src/client/pmix_client_topology.c
- src/mca/ploc/base/base.h
- src/mca/ploc/base/ploc_base_stubs.c
- src/mca/ploc/hwloc/ploc_hwloc.c
- src/mca/ploc/hwloc/ploc_hwloc.h
- src/mca/ploc/hwloc/ploc_hwloc_component.c
- src/mca/ploc/ploc.h
- test/simple/simpfabric.c
Change signature to take array of pmix_info_t
> Update compute_distances APIs

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/tests/cython/cython_test_functions.pyx
- contrib/construct_dictionary.py
- include/pmix.h
- include/pmix_common.h.in
- include/pmix_deprecated.h
- include/pmix_server.h
- src/client/pmix_client.c
- src/include/dictionary.h
- src/include/pmix_globals.h
- src/mca/ptl/tcp/ptl_tcp_component.c
- src/mca/ptl/usock/ptl_usock_component.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/runtime/pmix_progress_threads.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Initial work on Python bindings.
Provide a PMIx_Progress entry point for externally progressing the event
library.
> Continue work on updating to v4 Standard

- bindings/python/pmix.pyx
- include/pmix_tool.h
> Cleanup of Python bindings

- src/mca/ptl/tcp/ptl_tcp.c
> Ensure the peer objects are always initialized

- include/pmix_common.h.in
- src/include/dictionary.h
> Add new attributes and macro to track Standard

- src/mca/pnet/sshot/pnet_sshot.c
Allow host to access those values
> Locally cache VNI and traffic class

- src/mca/ploc/hwloc/configure.m4
- src/mca/ploc/hwloc/ploc_hwloc.c
Use different method for declaring that hwloc_topology_dup is available.
Implement workaround for when it isn't
> Fix some OMPI integration issues

- src/server/pmix_server_ops.c
- src/util/keyval_parse.c
> Silence Coverity and extend keyval buffer

- .gitignore
- src/mca/pnet/sshot/pnet_sshot.c
- test/simple/Makefile.am
- test/simple/get_put_example.c
- test/simple/simptest.c
Protect sshot from incomplete input
> Add new test code

- src/mca/ploc/hwloc/ploc_hwloc.c
> Cast a void*

- src/mca/preg/compress/preg_compress.c
> Per telecon, add to compress preg metadata

- src/mca/ploc/hwloc/ploc_hwloc.c
> Protect against stone age HWLOC version

- src/mca/preg/compress/preg_compress.c
(cherry picked from commit 53492d703f598217bb02fa83393664f574e58634)
> v3.2: Per telecon, add to compress preg metadata

- src/util/keyval_parse.c
Track https://github.com/open-mpi/ompi/pull/8144
> Touchup keyval buffer extension

- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Ensure we have the necessary frameworks opened
> Fix the direct-launch debugger example

- config/pmix_get_version.sh
Refs https://github.com/open-mpi/ompi/issues/8182
> pmix_get_version.sh: fix one more getdate.sh instance

- src/client/pmix_client_spawn.c
- src/mca/pfexec/base/base.h
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/mca/pfexec/base/pfexec_base_frame.c
- src/mca/pfexec/linux/pfexec_linux.c
- src/mca/pfexec/pfexec.h
- src/server/pmix_server.c
Prep it to handle the indirect tool launch case
> Update the pfexec framework

- config/pmix_setup_man_pages.m4
> Fix check to disable pandoc requirement

- autogen.pl
- config/ltmain_nag_pthread.diff
- config/ltmain_pgi_tp.diff
Port of https://github.com/open-mpi/ompi/pull/8222
> Patch libtool for Mac BigSur OS

- config/pmix_get_version.sh
Track https://github.com/open-mpi/ompi/pull/8239
> Fix pmix_get_version

- NEWS
- VERSION
> Update NEWS and VERSION for rc

- contrib/construct_dictionary.py
- include/pmix_common.h.in
- include/pmix_extend.h
- src/client/pmix_client.c
- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/pfexec/base/base.h
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/mca/pfexec/base/pfexec_base_frame.c
- src/mca/pfexec/linux/pfexec_linux.c
- src/mca/pnet/tcp/pnet_tcp.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/mca/ptl/tool/ptl_tool.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/tool/Makefile.include
- src/tool/pmix_tool.c
- src/tool/pmix_tool_ops.c
- src/tool/pmix_tool_ops.h
- src/util/error.c
- src/util/name_fns.c
Provide a simplified method for indirect launch by tools, pushing much
of the interconnect handshake down into the library.
> Update to utilize new tools functions

- bindings/python/pmix.pyx
* Tracking fixes related to https://github.com/pmix/pmix-standard/issues/313
* Added the following:
- `parse_cpuset_string` for `PMIx_Parse_cpuset_string`
- `generate_cpuset_string` for `PMIx_server_generate_cpuset_string`
- `generate_locality_string` for `PMIx_server_generate_locality_string`
* Modified API for:
- `set_server` to better match `PMIx_tool_set_server`
> Adjust Python bindings to match C

- src/server/pmix_server.c
Allow servers to also be controlled by an external tool
> Update server to track tool changes

- NEWS
- README
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/mca/ptl/base/ptl_base_fns.c
- src/tool/pmix_tool_ops.c
Correct a bunch of PMIx -> OpenPMIx changes, including updates to web
site names. Bring over the NEWS from the v3.x branches
> Silence Coverity warnings and update NEWS/README

- src/mca/ptl/base/ptl_base_listener.c
> Add more debug to error message

- include/pmix_common.h.in
- src/util/error.c
> Sync with v4 Standard

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- src/server/pmix_server.c
- test/python/sched.py
> Work on fixing Python bindings

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- src/server/pmix_server.c
- test/python/sched.py
(cherry picked from commit df8cad17762d7156e223c26e5e600b76b492ff43)
> Work on fixing Python binding for spawn

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- test/python/tool.py
> Fix Python "spawn" command and remove debug prints

- bindings/python/construct.py
Ensure that all written info is flushed to the files
> Close the Cython-constructed files

- test/test_v2/Makefile
- test/test_v2/pmix_test.c
- test/test_v2/test_get_basic.c
- test/test_v2/test_init_fin.c
Enables tests to build correctly.
> Bug fixes to Makefile, pmix_test.c, and all client tests.

- include/pmix_common.h.in
> Update info directives to track v4 Standard

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- include/pmix_common.h.in
- src/mca/gds/hash/gds_hash.c
- test/pmix_client.c
- test/python/sched.py
- test/python/server.py
Complete revision of Python bindings
Use the queue class to threadshift all server-level responses instead of
doing a timer delay
-------------------
Let hash search for node/app info on specified proc
If the process has been specified in a PMIx_Get and its node or app
information is requested, then search the proc-level data to get it.
-------------------
Ensure Python progress thread doesn't return early 
-------------------
> Update to track master branch

- VERSION
> Up version to rc2

- bindings/python/pmix.pyx
Thanks to @amckinstry for reporting it
> Remove unnecessary include

- src/client/pmix_client_get.c
- test/pmix_client.c
> Revert the changes to client_get

- VERSION
> Roll to rc3

- src/mca/ptl/base/ptl_base_listener.c
> Add a touch more output to error msg

- NEWS
> Update NEWS to track v4.0 release

- src/class/pmix_object.h
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/hash/gds_hash.c
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/runtime/pmix_init.c
> Add support for realloc to memory allocator

- src/server/pmix_server_get.c
The client/get function does not pass the requested key to the server in pre-v3.2 versions. This means that the server in those versions doesn't know what key it needs to respond with. Currently, it only provided job-level info for procs in a different namespace, and provided no mechanism for retrieving proc-posted data from the other namespace.
It's a trivial fix that is required to provide forward-compatibility - i.e., so that clients of v3.2 and above can get proc-posted data from different namespaces when only the gds/hash is enabled. This is an edge case, but it becomes the default (and only) case when working with clients from v4.1 and above, so let's fix it in each series.
> Fix server/get for gds=hash

- src/client/pmix_client_get.c
> Remove incorrect special case

- src/mca/gds/hash/Makefile.am
- src/mca/gds/hash/gds_fetch.c
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/gds_hash.h
- src/mca/gds/hash/gds_hash_component.c
- src/mca/gds/hash/gds_utils.c
- src/mca/gds/hash/process_arrays.c
> Refactor the gds/hash code for ease of editing

- config/pmix_check_cython.py
Thanks to @amckinstry for the report/suggestion
> Specify Python 3 for the configure check

- .github/actions/mlnx/entrypoint.sh
- VERSION
- config/pmix.m4
- config/pmix_get_version.sh
- config/pmix_summary.m4
- src/client/pmix_client.c
* PMIx Standard version can be adjusted in the VERSION file
* `OpenPMIx 4.1.0a1 (PMIx Standard: 4.0)`
> Add the PMIx Standard version level to the version string

- test/simple/doubleget.c
- test/sshot/testcoord.c
> Silence warnings

- .gitignore
- src/tools/pattrs/Makefile.am
- src/tools/pattrs/pattrs.1.md
- src/tools/pevent/Makefile.am
- src/tools/pevent/help-pevent.txt
- src/tools/pevent/pevent.1.md
- src/tools/pevent/pevent.c
- src/tools/plookup/Makefile.am
- src/tools/plookup/help-plookup.txt
- src/tools/plookup/plookup.1.md
- src/tools/plookup/plookup.c
- src/tools/pps/Makefile.am
- src/tools/pps/help-pps.txt
- src/tools/pps/pps.1.md
- src/tools/pps/pps.c
- src/tools/pquery/Makefile.am
- src/tools/pquery/pquery.1.md
Closes #1755
Closes #1754
Closes #1753
> Add man pages for PMIx tools

- src/event/pmix_event_notification.c
If a client sees a "lost connection" error, there is no point in trying to send it to the server as the connection to the server is what has been lost! Also protect against the case where the connection is lost in mid-communication - we flag that by returning a zero-byte message, so don't try to unpack it.
Fixes #2017 
> Silence unnecessary warning

- src/mca/pnet/opa/Makefile.am
- src/mca/pnet/opa/configure.m4
- src/mca/pnet/opa/pnet_opa.c
- src/mca/pnet/opa/pnet_opa.h
- src/mca/pnet/opa/pnet_opa_component.c
- src/tool/pmix_tool.c
Refs https://github.com/open-mpi/ompi/pull/8359
> Restore the pnet/opa component

- src/client/pmix_client.c
- src/util/error.c
Update a constant name and add missing string equivalent
> Touch of cleanup

- include/pmix_common.h.in
> Ensure the data array always gets initialized in PMIX_INFO_LIST_CONVERT

- src/mca/pnet/opa/pnet_opa.c
> Temporarily make the OPA envar OMPI-compliant

- src/mca/pnet/opa/configure.m4
- src/mca/pnet/opa/pnet_opa.c
- src/mca/pnet/sshot/pnet_sshot.c
- src/util/pmix_environ.c
> Update pnet/opa component to current architecture

- src/mca/pnet/opa/pnet_opa.c
> Correct name of PSM2 envar

- include/pmix_common.h.in
> Add a couple of useful macros

- test/test_v2/Makefile
- test/test_v2/test_clientapp_funcs.c
- test/test_v2/test_common.c
- test/test_v2/test_init_fin.c
- test/test_v2/test_server.c
Last set of changes required to permit new test suite to run with more than 2 servers, plus a few other updates.
> Added multiserver (> 2) capability to test suite

- src/common/pmix_iof.c
Refs https://github.com/openpmix/openpmix/issues/2010
> Add the local reference ID to iof/pull request

- test/simple/hybrid.c
> Update the new hybrid test a bit

- src/common/pmix_iof.c
Simplify it to ensure correct handling of the response.
Refs #2010 
> Cleanup the IOF register/dereg response code path

- src/mca/ploc/hwloc/ploc_hwloc.c
Fixes https://github.com/openpmix/openpmix/issues/2057
> Missed a spot - check for HWLOC_VERSION defined

- include/pmix_common.h.in
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_stubs.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/bfrops/v41/Makefile.am
- src/mca/bfrops/v41/bfrop_pmix41.c
- src/mca/bfrops/v41/bfrop_pmix41.h
- src/mca/bfrops/v41/bfrop_pmix41_component.c
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/ptl_types.h
> Add datatype support for new types

- include/pmix_common.h.in
- include/pmix_deprecated.h
- src/client/pmix_client.c
> Remove PMIX_BUFFER datatype and extend macro definition

- src/server/pmix_server_ops.c
Handle the case where the host returns OPERATION_SUCCEEDED
Refs #2010 
> Ensure proper handling of IOF pull requests

- NEWS
> Update NEWS to track release branches

- NEWS
- VERSION
> Update headers for release

- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/pnet/base/pnet_base_fns.c
- src/server/pmix_server.c
> Cleanup several places based on testing with PRRTE

- include/pmix.h
- src/common/pmix_data.c
> Add compress/decompress APIs

- include/pmix.h
- src/common/pmix_data.c
> Fix signature of new compression APIs

- src/server/pmix_server_ops.c
Fixes https://github.com/openpmix/prrte/issues/744
> Correct miscast of object type

- src/server/pmix_server_ops.c
The iof deregister callback function wants a pmix_server_caddy_t
in its callback data. However, we need to pass the host a
pmix_setup_caddy_t to hold all the info that needs to be retained
until the host calls us back. Insert an intermediary cbfunc to
untangle things and ensure everyone gets what they need.
Fixes https://github.com/openpmix/openpmix/issues/2072
> Correctly pass the right object to dereg cbfunc

- bindings/python/construct.py
> Py: Open files as UTF-8 while processing

- config/pmix_check_tm.m4
Signed-off-by: Michael Karo <mike0042@gmail.com>
> Link against libz when testing for TM

- config/pmix_setup_man_pages.m4
- configure.ac
Correctly identify the repo location
Add --disable-man-page help message
> Minor configure cleanups

- config/pmix_setup_libevent.m4
Get the headers in the right place
> Minor fix to libevent configury

- src/mca/pcompress/zlib/configure.m4
> Add warning for zlib not found

- src/mca/pcompress/zlib/compress_zlib.c
> Do not compress unless over limit

- src/mca/pcompress/base/Makefile.am
- src/mca/pcompress/base/base.h
- src/mca/pcompress/base/help-pcompress.txt
- src/mca/pcompress/base/pcompress_base_frame.c
- src/mca/pcompress/zlib/compress_zlib.c
- src/mca/pcompress/zlib/configure.m4
> Add zlib warning and compression checks

- examples/debugger.c
- examples/debuggerd.c
- examples/tool.c
- src/mca/common/sse/sse.c
- src/tools/pattrs/pattrs.c
- src/tools/pmix_info/pmix_info.c
- src/tools/pmix_info/support.c
- src/tools/pmix_info/support.h
- src/tools/pquery/pquery.c
- src/tools/wrapper/pmixcc.c
- test/pmix_test.c
- test/simple/hybrid.c
- test/simple/simpclient.c
- test/test_common.c
- test/test_common.h
- test/test_server.c
> Eliminate shadow variables

- src/common/pmix_iof.c
> Properly handle stdin forwarding

- .clang-format
- contrib/clang-format-pmix.sh
- examples/debugger.c
- examples/debuggerd.c
- examples/tool.c
- src/common/pmix_iof.c
- src/include/pmix_globals.c
- src/mca/common/sse/sse.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- src/tools/pattrs/pattrs.c
- src/tools/pmix_info/pmix_info.c
- src/tools/pmix_info/support.c
- src/tools/pmix_info/support.h
- src/tools/pquery/pquery.c
- src/tools/wrapper/pmixcc.c
- test/pmix_test.c
- test/simple/hybrid.c
- test/simple/simpclient.c
- test/test_common.c
- test/test_common.h
- test/test_server.c
Includes leak fixes, elimination of shadow variables, and stdin forwarding fixes
> Update v4.0 branch

- .clang-format
- include/pmix.h
- include/pmix_common.h.in
- src/common/pmix_data.c
- src/event/pmix_event_notification.c
- src/util/name_fns.c
Only need to do something about all the shadow variable warnings in the dstore code
> Update to pre-release status

- src/mca/bfrops/v401/Makefile.am
- src/mca/bfrops/v401/bfrop_pmix401.c
- src/mca/bfrops/v401/bfrop_pmix401.h
- src/mca/bfrops/v401/bfrop_pmix401_component.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_listener.c
> Add bfrops support for v401

- src/client/pmix_client_fabric.c
> Remove stale variable

- src/server/pmix_server.c
> Minor simplification

- test/test_spawn.c
> You have to at least spawn SOMETHING

- src/mca/ptl/base/ptl_base_connect.c
> Fix compile error in ptl_base_connect.c

- config/pmix_check_attributes.m4
- config/pmix_check_compiler_version.m4
Found a couple of broken configure tests while cleaning up other issues.
> Fix compiler behavior tests

- src/event/pmix_event_registration.c
- src/mca/ploc/hwloc/ploc_hwloc.c
> Silence warning and add a touch of debug output

- include/pmix_extend.h
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/pnet/base/pnet_base_frame.c
- test/simple/hybrid.c
> Silence some gcc warnings

- src/client/pmix_client_get.c
- src/server/pmix_server.c
- test/server_callbacks.c
Thanks to @tonycurtis for the patient assistance in chasing these down.
> Cleanup few lingering gcc11 warnings

- contrib/make_dist_tarball
Signed-off-by: Michael Karo <mike0042@gmail.com>
> Remove unnecessary shift in make_dist_tarball script

- include/pmix.h
- include/pmix_common.h.in
- src/common/pmix_data.c
- src/mca/pcompress/base/pcompress_base_frame.c
- src/mca/pcompress/pcompress.h
- src/mca/pcompress/zlib/compress_zlib.c
> Minor updates based on Standards review

- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_listener.c
Signed-off-by: Michael Karo <mike0042@gmail.com>
> Correct references to help-ptl-tool.txt

- include/pmix_common.h.in
> Add attribute to indicate copy/nocopy of output directed to files

- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_unpack.c
> Add missing osname endpt elements to bfrops

- src/common/pmix_iof.c
> Ensure tool output of IOF

- src/tool/pmix_tool.c
> Default tools to outputting their IOF

- src/client/pmix_client.c
- test/simple/simptest.c
PMIx_Abort is supposed to call exit after notifying
the server. Ensure we do so.
Fixes https://github.com/open-mpi/ompi/issues/8925
> Properly exit upon PMIx_Abort

- test/test_v2/test_fence_basic.c
Signed-off-by: Charles Shereda <cpshereda@lanl.gov>
> Added erroneously excluded test_fence_basic.c test case

- src/tool/pmix_tool.c
- src/tools/wrapper/pmixcc.c
> Remove cruft and let tools request job-level info during init

- src/tool/pmix_tool.c
Let anything from the host augment what we already know.
> Self-generate as much info as the tool can do

- .github/actions/mlnx/Dockerfile
- NEWS
- VERSION
- src/mca/pinstalldirs/env/pmix_pinstalldirs_env.c
- src/mca/ploc/base/help-ploc.txt
- src/mca/ploc/base/ploc_base_frame.c
- src/mca/ploc/base/ploc_base_select.c
- src/mca/ploc/hwloc/configure.m4
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
- src/tools/wrapper/pmixcc-wrapper-data.txt.in
- src/tools/wrapper/pmixcc.c
Carry across all master branch changes and update VERSION and NEWS files
> Update v4.1 to rc2

- test/test_v2/cli_stages.c
Done to match recent change in original test repo and fix apparent bug.
> Replaced PMIx_Notify_Event with cbfunc call in errhandler

- src/mca/ptl/base/ptl_base_connection_hdlr.c
> Cleanup Coverity warning

- config/pmix_setup_libevent.m4
Require a minimum of v2.0.21
Refs https://github.com/openpmix/prrte/issues/1065
> Check for libevent minimum 2.0.21

- src/runtime/pmix_progress_threads.c
> Restore the thread join in progress thread "stop"

- src/hwloc/pmix_hwloc.c
> Cleanup compiler warnings for ancient hwloc versions

- contrib/construct_dictionary.py
- include/pmix_common.h.in
- src/common/pmix_iof.c
- src/mca/pstrg/lustre/pstrg_lustre.c
> Update storage attrs to track Standard

- EXCEPTIONS
- Makefile.am
> Complete exceptions file

- config/pmix_setup_man_pages.m4
(cherry picked from commit d04d5998553024530e795c488a4cbf697b8aef27)
> man: Fix path check to see if pandoc is required

- EXCEPTIONS
Include attribute definitions, meaning of constants, etc. Add
entry for master branch
> Provide more info on exceptions

- src/mca/pmdl/mpich/Makefile.am
- src/mca/pmdl/mpich/pmdl_mpich.c
- src/mca/pmdl/mpich/pmdl_mpich.h
- src/mca/pmdl/mpich/pmdl_mpich_component.c
- src/mca/pmdl/ompi/pmdl_ompi.c
Harvest some envars, set a few on fork
> Add prelim support for MPICH

- test/pmix_client.c
- test/server_callbacks.c
- test/simple/gwclient.c
- test/simple/gwtest.c
- test/simple/quietclient.c
- test/simple/simpclient.c
- test/simple/simpcoord.c
- test/simple/simpcycle.c
- test/simple/simpdie.c
- test/simple/simpdmodex.c
- test/simple/simpdyn.c
- test/simple/simpft.c
- test/simple/simpio.c
- test/simple/simpjctrl.c
- test/simple/simppub.c
- test/simple/simptest.c
- test/simple/simptimeout.c
- test/simple/stability.c
- test/test_cd.c
- test/test_common.c
- test/test_common.h
- test/test_error.c
- test/test_fence.c
- test/test_internal.c
- test/test_publish.c
- test/test_replace.c
- test/test_resolve_peers.c
- test/test_v2/server_callbacks.c
- test/test_v2/test_common.h
Use pmix_strncpy instead of strncpy
> Silence compile warnings

- Makefile.pmix-rules
- config/pmix_setup_man_pages.m4
If someone doesn't want to build the man pages, then
don't force them to do so.
> Don't require pandoc to "make tarball"

- NEWS
> Update NEWS to include EXCEPTIONS file

- src/mca/ptl/base/ptl_base_connect.c
> Fix resource leak

- src/include/pmix_globals.c
- src/mca/pdl/pdlopen/pdl_pdlopen_module.c
- src/mca/psensor/file/psensor_file.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_listener.c
- src/util/fd.c
- src/util/os_dirpath.c
- src/util/path.c
> Try using TOCTOU instead of lower-case version

- test/simple/Makefile.am
Thanks to Orion Poplawski for reporting it
> Get the simptest.h file into the tarball

- src/event/pmix_event_notification.c
- src/tool/pmix_tool.c
- src/tool/pmix_tool_ops.c
- src/util/name_fns.h
Automatically stop in init if a rendezvous URI
is provided.
> Stop in init if rndz URI given

- EXCEPTIONS
> Update EXCEPTIONS file

- config/pmix_functions.m4
> Fix copy/paste typo

- NEWS
> Add NEWS for 4.1.1lz1

- test/test_v2/test_init_fin.c
- test/test_v2/test_server.c
Signed-off-by: Charles Shereda <cpshereda@lanl.gov>
> V2 suite test case for multiple inits and finalizes

- configure.ac
> Remove cobuild remnants from configure

- src/mca/ptl/base/ptl_base_fns.c
Use the correct argv API to avoid a bunch of duplicate
code. Silence Coverity warning of memory leaks
> Silence Coverity warning and cleanup code

- config/pmix_check_curl.m4
- config/pmix_check_jansson.m4
- configure.ac
- maint/pmix.pc.in
* Fix dependency declaration in pkg-config file
* Fix ability to use system-installed curl/jansson on ARM Ubuntu (and others)
* Clean up cobuild cruft
> Backport 3 build-related fixes from master

- config/pmix_check_cuda.m4
- config/pmix_check_ofi.m4
- config/pmix_check_psm2.m4
- src/mca/common/sse/configure.m4
- src/mca/pstrg/lustre/configure.m4
> Final minor diddles of configure summary categories

- README
> Add static library note to README

- src/client/pmix_client_spawn.c
- src/common/pmix_iof.c
- src/common/pmix_iof.h
Get it to work correctly for all use-cases
> Finish cleaning up nocopy behavior

- config/pmix_setup_wrappers.m4
> build: Fix escaping issue in pkg-config file

- configure.ac
Thanks to Marco Atzeri for the patch
> Add libtool tweak for Cygwin

- .github/workflows/run-xversion.yml
- Move the following cross-version CI tests to GitHub Actions
- `IBM CI (Cross-version: Client)`
- `IBM CI (Cross-version: Tool)`
- `IBM CI (Cross-version: make check)`
> GitHub Action for xversion testing

- config/pmix_setup_hwloc.m4
Exclude 2.5.0-2.7.0, inclusive
> Update the hwloc version checking

- NEWS
> Sync NEWS with v4.1.1 release

- config/pmix.m4
- src/tools/pmix_info/support.c
Remove things we don't actually use anywhere in the code
> Begin stripping configure of unnecessary checks

- .github/actions/mlnx/Dockerfile
- .gitignore
- config/pmix_setup_hwloc.m4
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/util/pmix_environ.c
- src/util/pmix_environ.h
- test/Makefile.am
- test/pmix_environ.c
Address https://github.com/openpmix/openpmix/issues/2450 by being more robust about environ handling when merging environments for application launch.
> Handle string literals in environ to unblock hwloc versions

- examples/debugger.c
- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/base/pmix_mca_base_open.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/v12/print.c
- src/mca/bfrops/v20/print.c
- src/mca/gds/hash/gds_utils.c
- src/mca/preg/native/preg_native.c
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/runtime/pmix_progress_threads.c
- src/tools/pmix_info/support.c
- src/util/pmix_cmd_line.c
- src/util/pmix_show_help.c
- test/test_v2/test_server.c
> Don't search home component path if not present

- src/mca/base/pmix_mca_base_component_repository.c
- src/util/pmix_cmd_line.c
- src/util/pmix_printf.c
- src/util/pmix_printf.h
> Add missing vsnprintf function

- src/util/pmix_printf.h
> Add missing include

- src/class/pmix_hotel.h
- src/class/pmix_list.h
> Fix visibility issues

- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/util/pmix_context_fns.c
- src/util/pmix_context_fns.h
Need to change the signature to allow for reuse by PRRTE
> Prep context_fns for reuse

- src/mca/base/pmix_mca_base_parse_paramfile.c
- src/tools/wrapper/pmixcc.c
- src/util/pmix_keyval_parse.c
- src/util/pmix_keyval_parse.h
> Prep keyval_parse functions for reuse by PRRTE

- src/include/pmix_globals.h
- src/util/pmix_name_fns.h
> Adjust include path on name_fns.h

- src/util/Makefile.am
- src/util/pmix_shmem.c
- src/util/pmix_shmem.h
> Add shared-memory segment utility functions.

- src/class/pmix_object.h
For PMIX_NEW(), one argument means the caller does not want a custom memory
allocator, namely the common case.  Two arguments means caller wants a
custom (TMA) memory allocator.
Similarly, PMIX_CONSTRUCT() now takes a maximum of three arguments: two
arguments means caller does not want a custom memory allocator---the
common case. Three arguments means the caller wants a custom (TMA) memory
allocator.
> Add macros for variadic PMIX_NEW, PMIX_CONSTRUCT.

- src/client/pmix_client_get.c
> Add a little extra protection

- src/mca/gds/base/gds_base_select.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/gds_hash_component.c
- src/mca/gds/shmem/Makefile.am
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/util/pmix_shmem.c
- src/util/pmix_shmem.h
Prep for the new shared memory support
> Add the gds/shmem skeleton

- .gitignore
- include/pmix.h
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/server/pmix_server_ops.c
- src/tools/pquery/pquery.c
I'm tired of writing pretty-print code in every app, so
create two new APIs:
PMIx_Info_string - prints a pmix_info_t
PMIx_Value_string - prints a pmix_value_t
Update pquery to print out the results using the new
APIs. Also update ignores
> Add a couple of print APIs and update pquery to use one

- src/mca/bfrops/base/bfrop_base_print.c
- src/tools/pquery/pquery.c
> Minor cleanups for picky compiler settings

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/util/pmix_shmem.c
- src/util/pmix_shmem.h
> Checkpoint gds shmem component work.

- src/mca/gds/shmem/Makefile.am
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
- src/util/pmix_shmem.c
- src/util/pmix_shmem.h
- src/util/pmix_vmem.c
- src/util/pmix_vmem.h
First cut at client/server rendezvous done.
> gds:shmem: Checkpoint client/server rendezvous.

- examples/dmodex.c
- Fence after the loop to prevent a hang if one rank fails.
- Fix check for a local rank.
- Make sure the namespace and rank is always copied in proc.
> examples/dmodex.c: Fix some bugs.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
> gds:shmem: Complete client/server rendezvous.

- src/mca/gds/shmem/gds_shmem.c
- src/util/pmix_shmem.c
> Silence Coverity warnings.

- src/class/pmix_object.h
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_utils.c
- src/util/pmix_shmem.h
Checkpoint mostly server-side work storing info objects into a
shared-memory backing store.
> gds:shmem: Checkpoint mostly server-side work.

- src/tools/wrapper/pmixcc.c
> Fix warning - compare of different signs

- src/tools/wrapper/pmixcc.c
> Fix signed comparison warning

- src/client/pmix_client_get.c
This rc isn't at this time in the loop, nor is it in the loop at all.
> Dmodex master

- src/client/pmix_client_get.c
Need to check for success prior to trying alternative storage
module.
> Minor correction to client-get logic

- examples/abi_no_init.c
- examples/abi_with_init.c
- src/common/pmix_query.c
> Fix picky-compiler and Coverity complaints

- include/pmix_deprecated.h
> Add error code for system limit on files

- examples/client.c
Need to discover which procs are local vs remote and
properly look for their posted data.
> Fix the "client" example

- config/pmix.m4
- examples/client.c
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_sendrecv.c
[Don't limit message size unless requested](https://github.com/openpmix/openpmix/commit/bd93ac0af480434a77b71d449ef55b810d5f16b3)[](https://github.com/rhc54)[](https://github.com/awlauria) 
[Fix the "client" example](https://github.com/openpmix/openpmix/commit/ccd6627fe57941e5dd7840a8beb166c156cca8e7)[](https://github.com/rhc54)[](https://github.com/awlauria) 
[Fix memcpy size in pmix_bfrops_base_copy_darray().](https://github.com/openpmix/openpmix/commit/d5e4e6dab040ac543c9b29748a18e635edfb0a0f)[](https://github.com/samuelkgutierrez)[](https://github.com/awlauria)
> v4.2: Bring in some updates from master.

- AUTHORS
- src/mca/gds/shmem/Makefile.am
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_fetch.h
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_store.h
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
- src/server/pmix_server.c
> Checkpoint data storage and retrieval work in gds/shmem.

- src/client/pmix_client.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
> Remove GDS envar disablement

- src/common/pmix_query.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server_ops.c
- src/util/pmix_hash.c
> Silence pedantic compiler warnings.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_fetch.h
- src/mca/gds/shmem/gds_shmem_store.h
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
> Checkpoint gds/shmem work.

- configure.ac
> configury: do look for sed

- src/mca/pfexec/linux/pfexec_linux.c
- src/util/pmix_fd.c
Signed-off-by: George Bosilca <bosilca@icl.utk.edu>
> Optimize the file descriptor cleanup on OSX

- examples/dmodex.c
- src/mca/bfrops/base/bfrop_base_print.c
> Some minor cleanups for picky compilers

- VERSION
> Fix the greek version

- VERSION
> Fix greek versioning

- src/mca/pcompress/zlib/compress_zlib.c
Fixes zlib usage during compression and decompression:
- API usage
- Data types
- Heap overflows
> Fix pcompress/zlib implementation

- src/mca/gds/shmem/gds_shmem_fetch.c
> Hide unused function

- src/mca/pnet/sshot/Makefile.am
> Add CPPFLAGS for pnet/sshot component

- src/mca/common/sse/Makefile.am
- src/mca/common/sse/sse.c
- src/mca/pnet/sshot/pnet_fabric.c
- src/mca/pnet/sshot/pnet_sshot.c
- src/mca/pnet/sshot/pnet_sshot_component.c
- test/sshot/Makefile.am
> Cleanup the pnet/sshot code for picky compilers

- examples/dmodex.c
> Update the dmodex example

- src/common/pmix_iof.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
Ensure we properly terminate the stream when the input
is complete
> Fix IOF of stdin

- src/mca/pnet/base/pnet_base_fns.c
> Return the correct code for register fabric

- src/mca/gds/hash/gds_hash.c
> Remove stale object release

- EXCEPTIONS
- NEWS
- VERSION
> Update the news, version, and exceptions for rc1

- src/common/pmix_iof.c
> Minor cleanup of timestamp output

- examples/hello.c
Useful to have a simple PMIx singleton test case
> Allow example to run as singleton

- include/pmix_common.h.in
> Add new attribute definitions to support display options

- src/mca/gds/hash/process_arrays.c
Thanks to @krempel-pt for the report
> Protect against NULL returned pointer

- include/pmix_common.h.in
> Add runtime options attribute

- bindings/python/pmix.pyx
Refs #2306 
Signed-off-by: Matt Baker <matthew@voltrondata.com>
(cherry picked from commit f5bb8d25c0d711cca5fb6ed890377503c15cffcb)
> Release GIL before registering event handler

- include/pmix_common.h.in
- src/util/pmix_cmd_line.h
Porting from PRRTE for more general use
> Add a couple more definitions

- EXCEPTIONS
- NEWS
- VERSION
> Final prep for release

- config/pmix_functions.m4
Change to utilize shell scripts - ported from https://github.com/open-mpi/ompi/pull/10785
> Enhance the performance of the var_scope_push/pop script

- .github/workflows/main.yml
- .github/workflows/run-special.yml
- .github/workflows/run-xversion.yml
Using https://github.com/marketplace/actions/checkout-submodules
> Update Github actions to use submodules

- autogen.pl
Ensure that the submodule is both present and
correct.
> Update autogen.pl to check for submodules

- src/client/pmix_client.c
> Stop-in-init applies to all procs in a job

- contrib/perf_tools/pmi_intra_perf.c
- contrib/perf_tools/pmix.c
> Fix perf_tools build, silence warnings.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
> Refactor, optimize shmem connection info exchange.

- src/mca/gds/shmem/Makefile.am
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
- src/mca/gds/shmem/help-gds-shmem.txt
> Address some TODO items, silence some Coverity warnings.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_store.h
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
- src/util/pmix_vmem.h
* make check now passes all tests on my machine
* Silence Coverity warnings
* Improve shared-memory segment sizing
* Remove dead code, refactor
> Harden gds/shmem

- bindings/python/pmix.pyx
> Remove debug print statements

- src/mca/gds/hash/gds_fetch.c
- src/mca/gds/hash/process_arrays.c
> Remove unused temporary values.

- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
Service more fetch requests using data stored in shared-memory.
> Improve pmix_gds_shmem_fetch().

- include/pmix.h
- src/common/pmix_strings.c
Enable easier debugging efforts.
> Add an API to pretty-print pmix_app_t structures

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_store.h
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
> gds/shmem: Store modex data in shared-memory.

- src/client/pmix_client_fence.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_store.h
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
> Checkpoint gds/shmem modex data retrieval.

- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/shmem/gds_shmem.c
- src/server/pmix_server.c
mark_modex_complete() now returns pmix_status_t.
> Change function signature of mark_modex_complete().

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
* Generalize segment attach code.
* Implement client-side attach for modex data.
> Improve shared-memory segment attach in gds/shmem.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
> Checkpoint gds/shmem work for remote debug help.

- src/mca/base/pmix_mca_base_var.c
Accept keywords of "true" and "false" in addition
to numbers.
Thanks to @s417-lama for the report
> Extend handling of bool MCA params

- src/mca/pfexec/base/pfexec_base_frame.c
- src/mca/pfexec/linux/pfexec_linux.c
Also shift the registration code from the pfexec framework open to the linux component as there is no need to register it until we actually spawn a process.
> Move SIGCHLD capture to aux event base

- src/server/pmix_server_ops.c
Properly handle purely local group construct and destruct. If the host supports group ops, then provide the host with an opportunity to know what happened, but mark the op as purely local so the host knows it doesn't need to do a global operation. If the host does not support group ops, then just locally complete it in the PMIx server.
Do NOT handle timeout in the PMIx server - let the host worry about it. Need to update this in the next iteration to handle timeout of purely local ops.
> Fix local group operations

- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_tma.h
Cleanup tma-integration code from prior commits, add TMA to pmix_bfrops_base_copy_payload() and pmix_bfrop_buffer_extend().
> tma-integration: Cleanup TMA infrastructure.

- include/pmix_common.h.in
> Add an attribute to request display of available cpus

- include/pmix_common.h.in
> Add attribute to stipulate parseable output for display info

- README.md
> Provide pointer to online security policy in README.md

- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
> gds/shmem: Cleanup before enabling component by default.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_utils.h
- src/util/pmix_shmem.c
- src/util/pmix_shmem.h
> Add reference counting to pmix_shmem.

- docs/exceptions.rst
Update exceptions doc
Thoroughly cover the exceptions, adding explanation
and usage documentation.
> Update exceptions doc

- src/mca/pif/solaris_ipv6/pif_solaris_ipv6.c
Cleanup a few things.
Fixes #2933 
> Handle some Solaris errors/warnings

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_utils.c
> gds:shmem Clean up before trying to enable again.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
> Enable gds/shmem by default take 2.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_utils.h
- src/util/pmix_shmem.c
* Multi-node async reinit now works
* Performance improvements
* Bug fixes
> Checkpoint gds/shmem revamp.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/util/pmix_shmem.c
> Plug memory leak in gds/shmem and other cleanup.

- config/pmix_setup_cc.m4
> Fix configure for __builtin_expect support.

- bindings/python/pmix.pyx
> Trim v5 crossover from the Python bindings

- docs/requirements.txt
Crossport of https://github.com/open-mpi/ompi/pull/11395
> Update sphinx requirements

- src/client/pmix_client.c
Need to acquire and post objects passed via the
thread handler. Some environments are more
sensitive about it.
> Add missing thread support to client functions

- src/mca/bfrops/base/bfrop_base_frame.c
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
Based on my testing things are looking promising.
> gds/shmem: Clean up code in revamp.

- src/mca/gds/shmem/gds_shmem.h
> Enable gds/shmem by default take 3.

- src/util/pmix_cmd_line.c
Deal with all the edge cases for cmd line parsing where we have just the cmd, cmd with no options but single executable, cmd with no options but multiple executables, cmd with options and single executable, and cmd with options and multiple executables.
> Fix handling of cmd line arguments

- src/mca/base/pmix_mca_base_components_open.c
> Plug memory leak.

- contrib/pmix.spec
Files changed a bit with move to Sphinx documentation
> Update rpm spec file

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_utils.c
* Remove stale comments
* Add missing comments
* Make internal coding errors easier to find
> Make code in gds/shmem more developer friendly.

- include/pmix_deprecated.h
- src/mca/bfrops/base/bfrop_base_macro_backers.c
- src/mca/bfrops/base/bfrop_base_tma.h
Plug memory leaks identified by memcheck on the prterun side.
> Plug memory leaks.

- .gitignore
- bindings/python/pmix.pyx
- config/pmix.m4
- include/pmix.h
- include/pmix_common.h.in
- include/pmix_server.h
- include/pmix_tool.h
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_connect.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/tool/pmix_tool.c
- src/tools/Makefile.include
- src/tools/palloc/Makefile.am
- src/tools/palloc/help-palloc.txt
- src/tools/palloc/palloc.c
- src/tools/pquery/pquery.c
- src/util/pmix_cmd_line.h
[Fix some Python bindings errors](https://github.com/openpmix/openpmix/commit/1712c6924ecad3bd1150eaef704dad8259cfb18b)
Ensure we return a proper status when calling the callback
functions. Fix a segfault in the 'toolconnected' function.
Add a PMIxScheduler class
[Add some allocation attributes and a new tool API](https://github.com/openpmix/openpmix/commit/81c28af192b32c1d3f04ac78bba8f41eac47d723)
Add attributes for specifying a resource allocation
to a little more detail. Add a tool API that allows
a tool to load the server function pointer module
in case the tool wants to service requests.
[Add a "palloc" tool to request resource allocations](https://github.com/openpmix/openpmix/commit/5c5ce0ea835e91 …
> Multiple commits

- src/client/pmix_client.c
- src/client/pmix_client_fence.c
- src/client/pmix_client_ops.h
- src/mca/gds/shmem/gds_shmem.c
- src/runtime/pmix_init.c
- src/runtime/pmix_params.c
- src/server/pmix_server.c
This reverts commit 20c4bfb0bf0a9b327917bd53c41391376665fda9.
> Revert "REVERT ME: add debug output for intermittent hang"

- contrib/Makefile.am
- contrib/check_compat.py
Check to see what has been added, removed, and/or modified. Provide simple output showing the results
> Provide tool for checking compatibility between two PMIx libraries

- src/client/pmix_client_group.c
Once group destruct has completed, remove the group from the client's tracking list.
Refs #3062
> Remove the group from client tracking when destruct is done

- .readthedocs.yaml
Signed-off-by: Luke Robison <lrbison@amazon.com>
(cherry picked from commit a602fb602d784cbcd8719ef43d14d5a4365a081f)
> [v4.2] RTD: Add .readthedocs.yaml file

- .readthedocs.yaml
Signed-off-by: Luke Robison <lrbison@amazon.com>
(cherry picked from commit a602fb602d784cbcd8719ef43d14d5a4365a081f)
> [v5.0] RTD: Add .readthedocs.yaml file

- src/include/pmix_stdint.h
Apply patch from George Bosilca to fix compilation error he reported.
> Fix compilation error.

- .github/workflows/main.yml
- .github/workflows/pr-target.yaml
- .github/workflows/run-xversion.yml
See individual commit messages for details.
> v5.0: require cherry picks and update github actions

- .github/workflows/main.yml
- .github/workflows/pr-target.yaml
- .github/workflows/run-xversion.yml
See individual commit messages for details.
> v4.2: require cherry picks and update github actions

- src/client/pmix_client.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
Tools and servers could (theoretically) join groups as well.
> Ensure client grp list gets initialized

- src/common/pmix_attributes.c
- src/common/pmix_query.c
- src/include/pmix_globals.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/tools/pattrs/help-pattrs.txt
- src/tools/pattrs/pattrs.c
Fix some bitrot in the attribute query support. Resolve inconsistency in passed structure type. Handle the case of returning an array of values vs returning a single string value. Improve formatting of output by adding spaces between function results.
> Repair the pattrs utility

- src/tools/plookup/plookup.c
Remove stale variable to prevent segfault
> Fix bitrot in plookup

- examples/Makefile.am
Needs a little more plumbing in the Makefile
> Properly support the "log" example

- docs/building-apps/index.rst
- docs/conf.py
- docs/exceptions.rst
- docs/installing-pmix/required-support-libraries.rst
See individual commit messages for details:
* s/Open MPI/PMIx/ in a few places that were missed
* Override some CSS to fix HTML table cell word wrapping, and remove the workarounds that we had to effect word wrapping.
> Fix Sphinx RTD theme HTML table cell word wrapping

- examples/group.c
The group construct returns at least two results
in this example: the group membership and the
requested context ID. Properly parse the returned
values.
> Update the "group" example

- .github/workflows/builds.yaml
Add a few build tests Github Actions:
* Ubuntu
* MacOS
Do both with non-vpath and vpath, and both of those with and without sphinx.
Also do a distcheck.
> Add a new Github Action

- config/pmix_setup_hwloc.m4
Append the extra libs to the proper global variable
> Touchup the OMPI integration

- VERSION
- docs/news/news-v4.x.rst
> Update VERSION and NEWS for release

- src/mca/ptl/base/ptl_base_fns.c
> Remove static version of global function

- test/simple/doubleget.c
Add an option to execute a group construct
in-between the two put/get operations. Thanks
to Sonja Happ for the example.
> Update the doubleget test

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem_utils.h
Implement realloc() for gds/shmem's shared-memory TMA.
> gds/shmem: Implement first cut of tma_realloc().

- src/server/pmix_server_get.c
Signed-off-by: HawkmoonEternal <domi.huber@tum.de>
(cherry picked from commit 5efb97ecff134440d5b49837bddd38df3ad5df0a)
> avoid loopback in resolve_nspace_requests

- src/mca/base/pmix_mca_base_var_enum.c
Only defined if PMIx built with --enable-debug
> Protect a variable

- config/pmix.m4
- config/pmix_setup_cc.m4
- src/include/pmix_stdatomic.h
Protect against it not being found
> Check for stdatomic.h

- src/mca/base/pmix_mca_base_open.c
- src/mca/ptl/base/ptl_base_listener.c
- src/util/pmix_os_dirpath.c
- src/util/pmix_os_dirpath.h
Unnecessary function that calls stat
> Remove pmix_osd_dirpath_access

- src/util/pmix_getcwd.c
Avoid use of the stat function
> Remove use of stat from pmix_getcwd

- src/mca/ptl/base/ptl_base_fns.c
Detect directory vs file by calling opendir
and checking for NULL return
> Remove use of stat

- src/include/pmix_globals.c
Don't use stat when executing the epilogs
> Remove use of stat in pmix_globals

- src/mca/ptl/base/ptl_base_listener.c
> Remove use of stat to check file existence

- src/mca/ptl/base/ptl_base_fns.c
> Test open a dir instead of using stat

- src/client/pmix_client_spawn.c
If someone passes a pmix_app_t struct to PMIx_Spawn that contains a field (e.g., argv or env) pointing to a stack location, then using PMIx_Argv_xxx commands to manipulate that field will fail. Painful as it is, at least for now we copy the pmix_app_t array to ensure everything is in heap memory.
Fixes #3244
> Resolve problem of stack variables and realloc

- config/pmix.m4
Leave things clean
Refs https://github.com/open-mpi/ompi/issues/12277
> Do not add no-unused-parameter for non-devel-check builds

- docs/Makefile.am
- docs/how-things-work/index.rst
- docs/how-things-work/session_dirs.rst
Explain relevant attributes, naming conventions for rendezvous files, and cleanup policy.
> Provide an explanation of session directories

- src/server/pmix_server_get.c
> Fix --enable-devel-check builds.

- src/mca/gds/shmem/gds_shmem.c
PMIX_GDS_SHMEM_DISABLE no longer exists.
> gds/shmem: fix build.

- docs/man/man1/index.rst
- docs/man/man1/palloc.1.rst
- docs/man/man1/pattrs.1.rst
- docs/man/man1/pevent.1.rst
- docs/man/man1/plookup.1.rst
- docs/man/man1/pmix_info.1.rst
- docs/man/man1/pmixcc.1.rst
- docs/man/man1/pps.1.rst
- docs/man/man1/pquery.1.rst
- src/tools/pmix_info/help-pmix-info.txt
Setup the infrastructure and add some initial drafts. Provide a complete page for "palloc".
> Begin to add man pages for PMIx commands

- docs/man/man1/palloc.1.rst
- docs/man/man1/pattrs.1.rst
- docs/man/man1/pevent.1.rst
- docs/man/man1/plookup.1.rst
- docs/man/man1/pmixcc.1.rst
- docs/man/man1/pps.1.rst
- docs/man/man1/pquery.1.rst
- src/tools/plookup/help-plookup.txt
- src/tools/pquery/pquery.c
Update content for the remaining man pages to track the current "help" output
> Continue work on tool man pages

- examples/group.c
Members that are being added to the group construct operation by one of the participants are notified
of their inclusion via PMIx event. Setup an event
handler to capture the invitation.
> Update the group example to handle add-members

- src/util/pmix_cmd_line.c
This reverts commit 3289b3fe172ac7fa211dc535daf857be4ab8340d.
> Revert "Adjust cmd line processor for special case"

- examples/group.c
- examples/group_dmodex.c
- src/client/pmix_client_group.c
Get devel-check to pass under a different compiler
> Cleanup a few warnings

- src/mca/gds/shmem2/gds_shmem2.c
Allocating memory for a pointer and then doing
PMIX_DESTRUCT on it causes the pointer memory
itself to be leaked. Probably also a bit of a
problem when the allocator is using a tma as
the "destruct" may not correctly release things.
Anyway, this change fixes the loop spawn issue.
Fixes #3309
> Fix memory leak in storing of modex data

- src/client/pmix_client_spawn.c
Ensure that the cmd field always gets set, or return an error if it wasn't provided and neither was argv. If cmd is not set, then take it from argv0.
Ensure that argv0 is always the basename of cmd so that the spawned app sees the expected name in
that location.
Fix a bug in the transferrence of the app's argv
to the internal structure.
Thanks to @krempel-pt and @sonjahapp for the report/questions.
Refs #3321
> Correctly set the app cmd and argv0 fields

- src/client/pmix_client_spawn.c
Standard requires we support it, so check for its
presence in either job-info or app-info during
PMIx_Spawn and adjust accordingly.
(cherry picked from commit 775839bbdd08d347e7c452a530c5a2ab676f007b)
> Implement support for PMIX_PREFIX attribute

- src/client/pmix_client_spawn.c
If we are handling any prefix provided by the caller, then remove that attribute and don't pass it up to the host to avoid them applying it a second time.
Thanks to @krempel-pt and @sonjahapp for their thoughtful questions and input.
Fixes https://github.com/openpmix/openpmix/issues/3321
> Do not include PMIX_PREFIX in spawn upcall

- .github/workflows/builds.yaml
- include/pmix_common.h.in
If provided by user or some other means, include
it in job info passed to applications. Also can
be used in queries by tools.
> Add new PMIX_MEM_ALLOC_KIND attribute

- src/mca/gds/base/gds_base_fns.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server_get.c
Cleanup a few formats. Primary focus is on updating the server get function to ensure that we provide the entire modex info for a proc upon first request.
> Perform some cleanup

- configure.ac
Refs https://github.com/open-mpi/ompi/issues/12540
> Update tar format to tar-pax

- .github/workflows/builds.yaml
Hit the commit button a tad too early.
> Fix yaml syntax error

- src/mca/pmdl/base/pmdl_base_stubs.c
Need to setup PRRTE frameworks
> Add missing function call

- contrib/construct_dictionary.py
- contrib/construct_event_strings.py
Ensure we mark that Python scripts to use Python
for execution.
> Add python directive

- contrib/Makefile.am
(cherry picked from commit 96742d10c425c3b2d595df817d98ae0126a656ca)
> add contrib/construct_event_strings.py to the dist tarball

- src/include/pmix_portable_platform.h
- src/include/pmix_portable_platform_real.h
See https://github.com/open-mpi/ompi/pull/12829 for an explanation
> Update pmix_portable_platform_real.h from upstream gasnet

- docs/news/news-v5.x.rst
Sync the news with the branch doc
> Update NEWS to include v5.0 branch

- VERSION
> Update VERSION for release

- src/mca/gds/base/gds_base_fns.c
- src/mca/gds/gds.h
- src/server/help-pmix-server.txt
- src/server/pmix_server.c
Get the order correct for unpacking the provided blob - it is a multi-layered object, so need to carefully coordinate the unpacking with the packing sequence.
> Fix the modex operation

- VERSION
- docs/news/news-v5.x.rst
> Update NEWS and VERSION for final release

- contrib/make_dist_tarball
Sometimes wind up with empty VERSION file.
> Correct git syntax in make_dist_tarball

- src/server/pmix_server.c
- src/server/pmix_server_group.c
- src/server/pmix_server_ops.h
Solidify the construct/destruct operation when all members participate with a full parameter list
> Cleanup basic group construct/destruct operation

- .gitignore
- examples/Makefile.am
- examples/pub2.c
Really more of a test, but conduct a tight loop around publish/lookup between two procs.
> Add another publish/lookup example

- VERSION
- docs/news/news-v5.x.rst
> Final update for release

- VERSION
> Roll VERSION for end of release branch

- examples/asyncgroup.c
- examples/group.c
- examples/group_bootstrap.c
- examples/group_dmodex.c
- examples/group_lcl_cid.c
> Ensure "group" examples return non-zero on error

- docs/news/news-v5.x.rst
> Update NEWS for release

- docs/how-things-work/sets_groups/group_construct.rst
- examples/group.c
Include details on all three construction modes. Cleanup group example
> Expand docs on group construct

- docs/how-things-work/sets_groups/group_construct.rst
- docs/news/index.rst
- docs/news/news-v6.x.rst
Provide an initial description of the v6 series.
> Add NEWS for v6.0 release series

- VERSION
Differentiate from the v6.0 release branch
> Rev the libtool triplet

- docs/Makefile.am
- docs/conf.py
- docs/how-things-work/sets_groups/asyncgroup.c
- docs/how-things-work/sets_groups/group.c
- docs/how-things-work/sets_groups/group_async_example.rst
- docs/how-things-work/sets_groups/group_bootstrap.c
- docs/how-things-work/sets_groups/group_bootstrap_example.rst
- docs/how-things-work/sets_groups/group_construct.rst
- docs/how-things-work/sets_groups/group_example.rst
to the GitHub repo locations
(cherry picked from commit 9f808b2dda1a2ba284eb32c0f2479d11a9bdfdcc)
> Directly add the example code instead of linking

- src/common/pmix_attributes.c
- src/common/pmix_control.c
- src/common/pmix_query.c
- src/server/pmix_server_ops.h
Include the returned results if the returned status is either "success" OR "partial success".
Refs #3499
> Transfer the query response for partial complete

- .github/workflows/group.yaml
- src/mca/gds/hash/gds_fetch.c
- src/server/pmix_server_get.c
We may have reserved keys that are pushed by the application.
> Correct the fetch procedure

- .github/workflows/prrte.yaml
- .gitignore
- examples/Makefile.am
- examples/hello.c
- examples/toolqry.c
- src/mca/gds/shmem2/gds_shmem2_fetch.c
Need to propagate recent fix to gds/hash to the shmem2 component. Add an example and CI test to ensure we catch any future breakage.
> Propagate shmem fix and add new example plus test

- src/util/pmix_fd.c
Cleanup some of the checks on return values
> Silence Coverity warning in fd support

- examples/hello.c
- examples/toolqry.c
> Silence some more Coverity nits

- .github/workflows/builds.yaml
- .github/workflows/group.yaml
- .github/workflows/prrte.yaml
- examples/dynamic.c
- examples/group_lcl_cid.c
- examples/multi_nspace_group.c
- examples/pub2.c
- examples/resolve.c
- examples/spawn_group.c
Add `--enable-devel-check` to all configure lines
> Update CI workflows

- VERSION
- docs/news/news-v5.x.rst
> Update NEWS and headers for release

- .gitignore
- examples/Makefile.am
- examples/pubstress.c
Try to more fully explore the publish-lookup race
condition
> Add new pub-lookup stress example

- src/mca/pmdl/ompi/pmdl_ompi.c
When we see the OPAL_PREFIX envar, we need to not only propagate it, but we also need to modify LD_LIBRARY_PATH accordingly so that the app can find its components.
> Properly handle OPAL_PREFIX

- .github/workflows/pmix_mpi4py.yaml
- .gitignore
- examples/Makefile.am
- examples/client4.c
Test fetch of PMIX_RANK, PMIX_NODEID, and PMIX_APPNUM
> Add new client example

- examples/client4.c
Cite the correct proc rank
Thanks to Felip Moll for pointing it out!
> Correct client4 error output

- examples/client2.c
- src/mca/psec/psec.h
- src/mca/ptl/base/ptl_base_connection_hdlr.c
The client_connected2 upcall provides a callback function, but the current code passed a NULL for it, thereby disabling that feature. Implement and provide a callback function for it.
> Provide callback function for client_connected2

- Makefile.openpmix-rules
We were missing several of the "PMIX_V_xxx" rules
> Add missing Makefile rules

- src/mca/pnet/opa/pnet_opa.c
When we pass local network data, we read until the buffer is exhausted, which means we have a PMIX_ERR_UNPACK_READ_PAST_END_OF_BUFFER status code. This isn't an error, it just indicates we hit the end of the data - so convert it to SUCCESS.
> Ensure we don't return an error when unpacking network data

- docs/news/news-v4.x.rst
- docs/news/news-v5.x.rst
- docs/news/news-v6.x.rst
> Update news from release branches

- src/tools/wrapper/help-pmixcc.txt
- src/tools/wrapper/pmixcc.c
- src/util/convert-help.py
Cannot use the cmd line parser as the wrapper compiler must accept all options for the underlying system compiler. Also cleanup a bunch of formatting crud
> Fix the wrapper compiler

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/server/pmix_server.c
Add threadshift to several more of the callbacks
> Continue work on threadshifting all upcall callbacks

- src/include/Makefile.am
> Delete built files on "make clean"

- src/client/pmix_client_spawn.c
- src/event/pmix_event_registration.c
- src/server/pmix_server_ops.c
Ensure they threadshift prior to processing any info that touches global values.
> Complete sweep of server upcall callback functions

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/server/pmix_server.c
This reverts commit 92c09e07c81bc92aec859b796bab994264b86140.
Not intended for the v5.0 release branch
> Revert "Ensure to threadshift callback functions"

- src/common/pmix_data.c
If we are a server and are packing/unpacking for a specific peer, then we need to threadshift the request as we are accessing global data.
> Update the Data pack/unpack functions

- contrib/construct_dictionary.py
- src/client/pmix_client.c
Check the return code to see if we need to wait
for thread release.
> Check return code for notify ready-for-debug

- src/mca/ptl/base/ptl_base_connection_hdlr.c
We added the client_connected2 server module upcall so we could pass information to the host about the connecting client. Use it to pass the uid and gid of the client. Terminate the connection attempt if the host rejects it.
> Pass the uid/gid for client connections

- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/util/pmix_os_dirpath.c
> Use the correct value for the number of info to unpack
