- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- test/test_v2/server_callbacks.c
The PMIx library can only test timeout for local completion - we
cannot continue the timer once we pass the operation to the host
as we would have conflicting timers running. Correctly have the
tracker (and not the individual proc entry's) event carry the
timeout. Fix reuse of a status variable to ensure that all
participants receive the "timeout" status code.
Fixes #2096 
> Fix fence timeout

- src/mca/pcompress/base/help-pcompress.txt
- src/mca/pcompress/base/pcompress_base_frame.c
- src/server/pmix_server_ops.c
Update the compression warning so it tells the user how to
turn it off, and ensure it only comes from non-clients. Correct
the "connect" code to use the operation tracker for timeoue.
> Improve compression warning and fix "connect" timeout

- config/Makefile.am
Fix place where maintainer-clean was removing files that were
under git control.  I think this was cruft from when get_version
was more complicated and shared code with a macro callable from
configure.  But now that it's a git-tracked file, don't clean
it.
> build: Fix maintainer-clean issue

- test/test_spawn.c
(cherry picked from commit 30f3ad75c829ae01b41fc35e1dac00bc3a7798cb)
> You have to at least spawn SOMETHING

- src/client/pmix_client_spawn.c
- src/server/pmix_server_ops.c
- src/util/Makefile.include
- src/util/pmix_getcwd.c
- src/util/pmix_getcwd.h
Ensure we wind up with an absolute path so our host can
find the executable as the daemon may not be in the same
wdir as the proc/client. Also ensure that the few required
fields are properly filled out.
> Spawn needs to do a little checking of the app

- config/Makefile.am
Add two files missing from dist tarballs which are needed for
autogen.pl to succeed when run in a dist tarball.
> build: Allow autogen.pl to be run from a tarball

- src/client/pmix_client.c
- src/mca/pcompress/base/pcompress_base_frame.c
- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_connect.c
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_handshake.h
- src/mca/ptl/client/ptl_client.c
- src/mca/ptl/ptl_types.h
- src/tools/pps/pps.c
Allow a singleton to act like a tool if a system server
is available. The singleton must pass authorization tests
as if it were a tool, including being approved by the
system server's host. This greatly simplifies singleton
comm_spawn and other dynamic operations in appropriate
environments (e.g., under PRRTE).
> Enable singletons to connect to system servers

- NEWS
- config/pmix.m4
- config/pmix_mca.m4
Default to a slightly nicer default on large systems of building MCA components into the base library, rather than having hundreds of stat/open calls during initialization.
Also, remove the unused direct all interface logic in pmix_mca.
> Enable static MCA components by default and remove unused MCA configure code

- src/client/pmix_client.c
- src/client/pmix_client_spawn.c
If a client spawns another job, then IO from that
job will automatically be forwarded to the parent.
Be prepare to properly output it
> Setup clients to output forwarded IO

- config/pmix_mca.m4
Some components should always be built as dso's to allow
for situations where the libs aren't present on the backend.
Default to supporting that situation, allowing a user to
override it if they want everything static.
> Set the default for enable-mca-dso

- src/tool/pmix_tool.c
* Found while debugging PRRTE's indirect.c
- PMIx_tool_init followed by a PMIx_Spawn
- PMIx_tool_set_server switches to the IL
- PMIx_tool_finalize will crash when destructing the
`pmix_globals.iof_requests` array because of a 0 ref count
on the `p->requestor` pointer.
* Determined that this is because when switching servers
we do not PMIX_RETAIN the peer pointer that becomes `myserver`
so it gets destructed in pmix_tool.c when it cleans up the
`pmix_server_globals.clients` list before calling `pmix_rte_finalize`.
- By retaining the object, it is then cleaned up properly in finalize.
> Tool finalize crash due to ref count issue

- src/mca/ptl/base/base.h
- src/mca/ptl/base/help-ptl-base.txt
- src/mca/ptl/base/ptl_base_connect.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/client/ptl_client.c
If a tool finds multiple servers that it could connect to, then it
shall return an error indicating that the user must provide more
information so a specific server can be selected. Otherwise, it can
be a somewhat random selection. Multiple connection files are permitted,
but we check to see if all point to the same server. If not, then
report the ambiguity and ask for clarification.
Fixes https://github.com/openpmix/prrte/issues/864
> Reject ambiguous connection options

- src/mca/ptl/base/ptl_base_connect.c
This fixes an assert failure in the memory allocator at `free(suri)`
when running:
pterm
There is a path from the start of that function to the free() that
leaves suri uninitialized: with none of the connection identifiers set,
through the clause
else if (1 < pmix_list_get_size(&connections))
Signed-off-by: Alexei Colin <acolin@isi.edu>
> ptl: prevent free of uninited suri variable

- src/mca/psec/munge/psec_munge.h
Fixes compile error:
In file included from psec_munge_component.c:33:
psec_munge.h:20:20: error: unknown type name
âpmix_psec_base_component_tâ
20 | PMIX_EXPORT extern pmix_psec_base_component_t
mca_psec_munge_component;
|                    ^~~~~~~~~~~~~~~~~~~~~~~~~~
> psec: include missing psec.h

- src/mca/ptl/base/help-ptl-base.txt
Otherwise, it can be mysterious why prun/pterm report this error,
when the user certainly has only one DVM running.
I haven't checked if saying `$TMPDIR` is accurate; perhaps it should say just `/tmp`.
Presumably garbage is left only in case of unclean shutdown (segfault, etc), but it happens.
```
$ prte  --report-pid $PWD/dvm.pid &
$ prun -n 2 hostname
--------------------------------------------------------------------------
PMIx has found multiple possible servers to which it could
connect. Further guidance is required to ensure the connection
is made to a desirable server. Guidance can be in the form
of the namespace or PID of a specific server, a directive to
connect to a system server, a specific URI to use, or the name
of a rendezvous file. …
```
> ptl: help on too-many-conns: mention conn handle files

- src/common/pmix_iof.c
The processing callback called as part of PMIx_IOF_deregister processing intermittently returns PMIX_ERR_UNPACK_READ_PAST_END_OF_BUFFER as completion status.
This seems to be caused by PMIx_IOF_deregister being called as PMIx processes are shutting down, resulting in partial or invalid buffers passed to the callback. When PMIX_BFROPS_UNPACK tries to unpack the buffer, this status is the result.
This change forces the returned status to PMIX_SUCCESS in this case.
There is a second problem that occurs when I run the PRRTE attach testcase, where the PMIx_IOF_deregister callback is intermittently returning an invalid status. The status is an apparently random number that is not a valid error status.
I think that there is a path thru the buffer unpack code where an error occurs but an …
> Ignore PMIX_ERR_UNPACK_READ_PAST_END_OF_BUFFER status in PMIx_IOF_deregister callback

- examples/client.c
- include/pmix_common.h.in
- include/pmix_deprecated.h
- src/client/pmix_client.c
- src/event/pmix_event_notification.c
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/process_arrays.c
- src/server/pmix_server.c
- src/util/error.c
The host/debugger needs a way to communicate which ranks are to
be debugged - eg., which are to be stopped on exec. We had been
assuming that it would be all of them as that is the typical
case, but that isn't a restriction. Modify the debugger attrs
to pass a rank (or an array of ranks) instead of just "bool".
Allow the app to indicate where they are stopped, should they
choose to do so. Replace `WAIT_FOR_NOTIFY` with `READY_FOR_DEBUG`
as release by notification is probably the least-used use-case.
> Some mods/cleanup of debugger definitions and handling

- src/Makefile.am
Change libpmix_la_DEPENDENCIES to explicitly list the internal
build artifacts that are included in libpmix_la_LIBADD, so that
Automake doesn't just ignore the indirection from
MCA_pmix_FRAMEWORK_LIBS.  This fixes an issue where changes in
a framework base or component were not causing a relink of
libpmix.
Fixes the PMIx part of https://github.com/openpmix/prrte/issues/897.
> build: Explicitly list libpmix dependencies

- include/pmix_server.h
- src/client/pmix_client_get.c
- src/server/pmix_server.c
Ensure we pass the desired scope on a PMIx_Get call.
Don't reinitialize nspace object on multiple calls to
PMIx_server_register_nspace
Allow the client to go up to the server when looking
for a newly assigned context ID
> Fix some minor errors

- src/atomics/sys/Makefile.include
A missing \ resulted in the gcc_builtins atomic file not ending
up in the tarball.  Ooops.
> atomics: Fix broken make dist

- include/pmix_common.h.in
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_unpack.c
We were missing support for a number of datatypes in the
PMIX_DATA_ARRAY_CONSTRUCT macro and in the darray copy function.
They were present at one time - not sure what happened to them.
Fixes #2159 
Fixes #2160 
> Add missing datatype support in darray macros

- include/pmix_common.h.in
Per pushback from the standards group, retain support for the
"bool" data type associated with the "stop" attributes, but
extend them by adding pmix_rank_t and pmix_data_array_t value
options. Define "bool" as equivalent to a rank of WILDCARD when
true.
> Update comments on debug attributes

- src/mca/ploc/hwloc/ploc_hwloc.c
> Remove stale envar settings in hwloc support

- config/pmix_check_curl.m4
- config/pmix_check_jansson.m4
Even if the libs are in standard locations, do not install
this support unless asked to do so. It is mainly targeting
future components.
> Do not include curl and jansson support unless requested

- src/mca/ploc/hwloc/ploc_hwloc.c
HWLOC v2.1.0 apparently introduces a change to the version
string that broke our support. Update how we check the
version string to accommodate the change.
Thanks to @RaymondMichael for the report and fix
Fixes #2173 
> Update hwloc support to handle revised version string

- src/class/pmix_hash_table.h
- src/mca/base/Makefile.am
- src/mca/base/pmix_mca_base_alias.c
- src/mca/base/pmix_mca_base_alias.h
- src/mca/pmdl/base/pmdl_base_frame.c
We unified the "ompix" plugins to be simply "ompi" as they
wound up being duplicative. However, as they were previously
included in at least one release and people might have set
MCA params accordingly, alias the two prior plugin names
to the new one. Port the MCA aliasing code to support it
> Register ompi5 and ompi4 as aliases for ompi plugin

- include/pmix.h
Should have been updated to "pmix_key_t key"
Fixes #2182 
> Correct the PMIx_Get signature

- include/pmix.h
- include/pmix_common.h.in
- src/client/pmix_client.c
- src/client/pmix_client_get.c
- src/server/pmix_server.c
It's a subtle point, but gcc11's warnings of potential
string overflows are technically valid. If someone were
to pass a string longer than PMIX_MAX_KEYLEN to one of
the four functions that took a pmix_key_t argument, then
that argument would overflow and impact the surrounding
memory. So go back to the v3.0 function prototypes as
they are technically safer.
> Silence some gcc11 warnings

- include/pmix_common.h.in
- src/client/pmix_client.c
Non-terminated strings can cause strlen to run wild,
so create a safe way of computing it for pmix_nspace_t.
> Protect against bad nspace input

- include/pmix_common.h.in
- src/mca/pmdl/ompi/pmdl_ompi.c
- src/mca/pmdl/oshmem/pmdl_oshmem.c
- src/mca/pnet/opa/pnet_opa.c
In the DVM use-case, we want prun to pickup the envars
as that is where the user is acting. We then need to tell
PRRTE _not_ to pick them up as that would overwrite the
user's settings.
> Protect against duplicate envar harvesting

- src/server/pmix_server.c
If we don't already know the nspace and thus create
a new nspace entry, then we won't know the GDS module
yet because a client from that nspace won't have
attached to us yet.
> Protect register_nspace against new entries

- include/pmix_common.h.in
- src/include/pmix_globals.h
Enable RM to indicate that the node is oversubscribed
> Add oversubscribed attribute

- include/pmix_common.h.in
- src/util/error.c
Better inform callers of "spawn" on what happened
> Add a few job error constants

- src/mca/plog/syslog/plog_syslog_component.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server_ops.c
Only deprecate nlocalprocs if the client dies without
finalizing. Cleanup one spot where MCA params weren't
being reinitialized.
Fixes https://github.com/openpmix/openpmix/issues/2202
> Enable re-init of clients

- src/mca/gds/hash/gds_fetch.c
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/gds_hash.h
- src/mca/gds/hash/gds_utils.c
- src/mca/gds/hash/process_arrays.c
- src/util/pif.c
- src/util/pif.h
In most cases, we will receive consistent names for hosts. Thus,
whenever we are checking the input name of a host against our
array of known nodes, first just check the given name against
the known name of the nodes. If we don't find a match, then go
back thru the array and check the given name against all aliases.
This way, only those who use multiple names for their nodes will
pay the performance penalty.
> Optimize check for nodes

- include/pmix_common.h.in
- src/client/pmix_client.c
- src/common/pmix_iof.c
- src/common/pmix_iof.h
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/process_arrays.c
- src/mca/plog/stdfd/plog_stdfd.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.h
- src/tool/pmix_tool.c
Transfer the PRRTE output formatting code to the PMIx library
so that tools can also provide a similar capability. This
includes the ability to output XML format, timestamps,
and tagged output as well as the ability to specify a
file format and/or directory where the output is to be
written.
Please see the OpenPMIx wiki page for explanation of
this feature and how to use it.
> Transfer stdout/err formatting to PMIx

- bindings/python/pmix.pyx
I was trying out the Python interface to PMIx and noticed this bug. It looks like if the `PMIx_Get()` code path encounters an error, than `val` never gets set and Python crashes with a 'use before assignment' error when trying to return `val`. This PR add an assignment to `val` so that it is always initialized before the return
> Initialize val before get in case get isn't successful

- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Ensure that the event notification chain stops when it should by
tracking the interim status returned by each handler. When the keepalive
pipe goes away, generate an event with a known named affected proc
so that the host can catch it.
> Some cleanups of the event notification and keepalive support

- src/mca/common/sse/Makefile.am
Unify on a single naming convention for the library produced for
the common/sse component, with libmca_common_sse.la.  Unlike
traditional components that are actual DSOs, common components
aren't dynamically loaded; they're dynamically linked by other
loaded components and are stand-alone shared libraries, so the
naming convention that is necessary for other components is
not necessary for common components.
This solves a bug with the common/sse component not being able
to find libcurl symbols when built as a static component.  The
*_LIBADD rule was only for the dynamic build mode and was missing
for the static build mode.
Refs #2142
> common/sse: Ensure library links against libcurl

- src/mca/common/dstore/Makefile.am
The Makefile.am for common/dstore was inconsistent in the
flags set for the static and dynamic build cases.  While
this was not causing any problems today, it could lead
to the problems seen with common/sse on the master branch.
This change is similar to 936bf79 on master, in that it
unifies on a single naming convention for the library produced
by common components.
At the same time, remove some unneeded flags, like the LTDLINC
CPPFLAGS, which are not used in this component.
> common/dstore: Fix inconsistent Makefile.am

- src/client/pmix_client.c
- test/simple/simptest.c
Do not call "exit" from within the function - just return an "unreachable" error if the PMIx server is no longer available. Retain the changes to the "simptest" program.
> Revert change to PMIx_Abort

- src/common/pmix_iof.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Don't close the send/recv socket for a client when it
finalizes - let the socket close upon client termination
and do the cleanup at that time. Be a little better
on setting the IOF output default for a server. Write
IOF output directly to stdout/stderr instead of pusing
into events to avoid potential loss of output upon
termination.
> Some cleanups for client finalize and IOF output

- test/test_v2/cli_stages.c
- test/test_v2/cli_stages.h
- test/test_v2/pmix_test.c
- test/test_v2/test_server.c
Needed for LANL-CI to proceed through timeouts without hard failure.
> Modified test_v2 status code return logic so timeouts can be propagated through to caller

- src/common/pmix_iof.c
- src/server/pmix_server.c
Do not let a server forward cached IOF to itself
as it leads to duplicate output
> Do not forward cached IOF to self

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
When using the Python bindings I noticed some strange behavior with namespaces and `PMIX_BYTE_OBJECT` values. I made some bug fixes to the Python bindings that makes my use case work, and it also seems to fix some of the tests. The `PMIX_BYTE_OBJECT` use case is fixed by leveraging Cython's type casting ability to convert C `char[]`'s into Python `bytes` classes and the namespace bug is fixed by similarly casting `char[]` into `bytes` and then decoding those into a Python `string`.
> Improved handling of C bytes to Python objects

- src/client/pmix_client_spawn.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Enable PMIx servers to call "spawn" so that the PMIx
server library can process directives - e.g., indicating
that IOF is to be sent to a particular target.
> Allow servers to use PMIx_Spawn

- src/mca/pinstalldirs/env/pmix_pinstalldirs_env.c
- src/tools/wrapper/pmixcc-wrapper-data.txt.in
- src/tools/wrapper/pmixcc.c
We standardixe on the envar of PMIX_PREFIX to relocate the installed
library, so use it in the installdirs component. Remove stale references
to MPI and Fortran as neither are relevant here.
> Correct the PMIX_PREFIX envar name and minor wrapper cleanups

- src/mca/ptl/base/ptl_base_sendrecv.c
Don't call client_finalized upon loss of connection.
Fixes #2236 
> Avoid calling client_finalized on abnormal term

- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server.c
Both clients and tools send the PMIX_FINALIZE_CMD to the server when
finalizing, but we don't want the server calling the host's
client_finalized function for tools. A host can only learn of a tool's
departure by receiving a "lost connection" event, so be sure to always
generate one when a tool departs.
> Do not call client_finalized for tools, report lost tool connections

- .github/actions/mlnx/Dockerfile
- src/mca/ploc/base/help-ploc.txt
- src/mca/ploc/base/ploc_base_frame.c
- src/mca/ploc/base/ploc_base_select.c
- src/mca/ploc/hwloc/configure.m4
- src/server/pmix_server.c
While we are setup to support alternatives, for now we must
require HWLOC.
> Require a hardware topology library at configure

- include/pmix_common.h.in
- include/pmix_deprecated.h
- src/common/pmix_iof.c
- src/include/pmix_globals.h
Deprecate some early ones in favor of collecting all the IOF-related
attributes under the "PMIX_IOF_" prefix. Add one to tag output solely
with the rank of the source.
> Cleanup some IOF attributes

- include/pmix_common.h.in
- src/common/pmix_iof.c
- src/include/pmix_globals.h
Extend IOF outputting format to cover Hydra options.
> Continue updates to support MPICH integration

- NEWS
- include/pmix_common.h.in
- include/pmix_deprecated.h
- src/common/pmix_iof.c
- src/include/pmix_globals.h
Cleanup some IOF attributes
Deprecate some early ones in favor of collecting all the IOF-related
attributes under the "PMIX_IOF_" prefix. Add one to tag output solely
with the rank of the source.
(cherry picked from commit f9e15e6)
Continue updates to support MPICH integration
Extend IOF outputting format to cover Hydra options.
(cherry picked from commit cb50b26)
> Track changes to IOF attributes and implementation

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
There are threeish different bugs being fixed here. One is string decoding, similar to several previous fixes.
One of the biggest changes is changing some instances of `PyMem_Malloc/PyMem_Free` with the system `malloc/free`. The reason for this is that in some code paths, such as called in `PMIx_Spawn()` will lead to PMIx internally calling the `realloc()` function. When the libc `realloc()` function sees a pointer from `PyMem_Malloc()` it crashes the program. So this change will use the system malloc when allocating data structures that will be given to PMIx rather than being given to Python. 
The last change is declare the `pyeventhandler()` cb function with the `with gil` clause. Without it the Python interpreter won't set up the Python thread state and won't be able to access the …
> Misc Python fixes

- include/pmix_common.h.in
- src/client/pmix_client_topology.c
- src/include/pmix_globals.h
- src/mca/ploc/base/ploc_base_frame.c
- src/mca/ploc/hwloc/ploc_hwloc.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Establish the relative roles of the client and server
in performing the calculation. Passing of NULL topology
indicates use of local topology. Passing of NULL cpuset
indicates use of local cpuset for proc.
> Cleanup the device distance computation

- include/pmix_common.h.in
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/bfrops/v41/bfrop_pmix41.c
Define and assign values to the PMIx storage types per the Standard.
> Add missing storage constants

- .github/actions/mlnx/entrypoint.sh
- src/common/pmix_iof.c
- src/common/pmix_iof.h
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/runtime/pmix_progress_threads.c
- src/server/pmix_server.c
No longer directly output stdout/stderr - add them to the event
list for output. This helps us deal with the case where the std
file descriptors are getting blocked/metered. Add a counter to
track the number of times we attempt to output to a given sink
and abort if we exceed that count - helps avoid deadlock where
we simply cannot get the output to go. Also, don't try to "join"
the progress thread when we stop it as this can hang if we are
in an event we cannot get out of.
(cherry picked from commit 5b1be8dbd1b60aea4983801d65b112116b8b2389)
> Some cleanup of IOF output

- .github/actions/mlnx/entrypoint.sh
- src/common/pmix_iof.c
There is a very tiny window of time where the host might be calling
down into the PMIx server library (which does a threadshift) and
the read handler attempts to call up into the host from within the
handler (which is in a PMIx progress thread event). If we hit that
window, the host may be blocked waiting for the PMIx progress thread
to make progress while the PMIx progress thread is waiting for the
host's progress thread to do something...and we threadlock.
So don't block in the read handler. In general, we don't want to
block anywhere in an event, so we probably need to review the code
to ensure this isn't happening elsewhere.
> Avoid blocking in the stdin read handler

- src/common/pmix_iof.c
- src/server/pmix_server.c
Append an event on the end of the event library in server finalize
and wait for that event to be executed before exiting.
> Ensure the server waits for all IOF and message events to complete

- include/pmix_common.h.in
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/server/ptl_server.c
- src/server/pmix_server.c
This can cause problems because PMIx will pick them up
and forward them to all daemons and app procs, resulting
in confusion.
> Avoid use of MCA params for singleton and report-uri

- src/hwloc/pmix_hwloc.c
Could be that a tool connected to a remote daemon
> Don't treat inability to open shmem file as fatal

- src/hwloc/pmix_hwloc_datatype.c
Even for ancient versions of hwloc
> Ensure we always copy the source field in pmix_topology_t

- src/common/pmix_iof.c
- src/include/pmix_globals.h
Track passing of IOF_LOCAL_OUTPUT separately from any
other option.
Refs https://github.com/open-mpi/ompi/issues/9365
> Default to using our local_output flag

- src/common/pmix_iof.c
- src/mca/pfexec/base/pfexec_base_default_fns.c
If a tool calls "spawn" while not connected, we will fork/exec
the specified app as a child of the PMIx library. In this case,
the library takes responsibility for reading, forwarding, and/or
outputting any stdout/err from that child.
> Properly read/output stdout/err from a fork/exec'd child

- VERSION
Since OpenPMIx is moving past the current official Standard,
begin tracking how far beyond it has gone by adding a simple
"std_extension" value to the current "std_major/minor"
values.
> Add a Standard extension value to the compliance version

- include/pmix_common.h.in
PMIX_TIMEOUT is operation-agnostic, but when passed to
PMIx_Spawn there is some confusion over whether it applies
to the spawn operation itself, or to the job being spawned.
Reduce the confusion by adding specific timeout attributes
for these two phases.
> Add some spawn-specific timeout attributes

- src/event/pmix_event.h
- src/mca/ptl/base/ptl_base_sendrecv.c
If at least one process starts a collective before another
local process dies, then the number of local procs has already
been set in the collective. If the process dies before entering
the collective, then it won't be in the local callback list.
Ensure we properly decrement nlocal procs so the collective
locally completes.
> Resolve race condition in lost condition

- EXCEPTIONS
- include/pmix_common.h.in
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/server/pmix_server_ops.c
- test/simple/simpdie.c
- test/simple/simptest.c
If a process fails during a collective, we want the collective
procedure to complete - but we really should return an error
and not success.
> Provide "partial_success" error when collectives not complete

- src/hwloc/pmix_hwloc.c
- src/hwloc/pmix_hwloc_datatype.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/gds/hash/gds_hash.c
Cleanup some problems when using hwloc v1.5.2
> Correctly copy stone age hwloc topologies

- bindings/python/pmix.pyx
In the `spawn()` function in in the Python bindings it will currently try and unconditionally decode nspace return value from the base `PMIx_Spawn()` function. On failure the output of nspace seems to be undefined, so the output looks to be random data and the `decode()` function in Python will usually raise an exception that it can't decode the string. This patch fixes this behavior by conditionally decoding the output string only when the return status is `PMIX_SUCCESS`
Signed-off-by: Matthew Baker <bakermb@ornl.gov>
> Conditionally decode the nspace return value in Python

- .gitignore
- config/pmix_check_os_flavors.m4
- test/test_v2/Makefile.am
- test/test_v2/test_common.c
- test/test_v2/test_common.h
Avoid multiple definitions of a couple of variables declared
in test_common.h by making them "extern", instancing them
in test_common.c. Silence warnings on Mac due to use of
"-no-install" option in Makefile - it is "no-fast-install"
on the Mac. Although cute, we don't support Windows so let's
avoid the warnings from the "sleep" function.
Update ignores as well.
Fixes #2300 
> Cleanup the test_v2 area

- config/pmix_check_tm.m4
Thanks to Moritz Kreutzer for pointing it out.
Fixes #2307 
> Expand the tm/pbs config to check for lib64

- config/pmix.m4
This is a port from the corresponding
https://github.com/open-mpi/ompi/pull/9398.
OpenPMIx does not compile with GCC 4.4.7 (the default GCC that ships
in RHEL 6).  Open PMIx *does* compile with GCC 4.8.5 (the default GCC
that ships with RHEL 7).  The Open MPI community regularly tests Open
MPI (including PMIx) with GCC 4.8.1, so we know that works, too.
Hence, abort configure if GCC is used and GCC is < v4.8.1.
> pmix.m4: abort if gcc is <= v4.8.1

- include/pmix_common.h.in
Make it easier for programs to initialize static
complex datatypes.
> Provide static initializers for all structures

- .gitignore
- config/pmix.m4
- config/pmix_check_curl.m4
- config/pmix_check_jansson.m4
- config/pmix_check_lustre.m4
- config/pmix_check_package.m4
- config/pmix_setup_hwloc.m4
- config/pmix_setup_libevent.m4
- src/mca/common/sse/configure.m4
- src/mca/pcompress/zlib/configure.m4
- src/mca/pstrg/lustre/configure.m4
- test/util/Makefile.am
- test/util/convert.c
- test/util/numa.c
Cleanup configuration logic
We still weren't dealing with the scenario where there is
a copy of HWLOC in the standard location, but we pass our
own path to a different HWLOC install that we want to use.
Problem turned out to be the common mistake we keep rolling
back to making - AC_CHECK_HEADERS _always_ looks in the default
paths in addition to whetever you may add. Ditto for its
AC_SEARCH_LIBS companion.
So you have to be more careful about handling this situation. We
periodically seem to forget and rollback the configure logic
into this error, so try to provide a big comment explaining
why you can't do it.
If I felt like taking the time to search for it, I could swear
I could just have copied that comment from prior times...
`<shrug>`
Also, cleanup a few of the summary lines at the end …
> Extend NUMA utility and cleanup configure logic errors

- config/pmix_check_package.m4
- config/pmix_functions.m4
- config/pmix_setup_hwloc.m4
- config/pmix_setup_libevent.m4
- config/pmix_summary.m4
Whatever locations we are told on the cmd line should
trump any correspnding envars.
> Ensure configure cmd line trumps environment

- src/include/pmix_config_bottom.h
Signed-off-by: Thomas Naughton <naughtont@ornl.gov>
> delete use of `PMIX_CHECK_BROKEN_QSORT` refs #2375

- src/include/pmix_config_bottom.h
Signed-off-by: Thomas Naughton <naughtont@ornl.gov>
> v4.2: remove `PMIX_CHECK_BROKEN_QSORT` refs #2375

- src/common/pmix_iof.c
- src/mca/bfrops/bfrops.h
Add a little debug info to a verbose output
Correct copy/paste error - use correct procID
Use the correct procID when creating directories and/or
file sinks.
> Cleanup procID on output to file/dir and add a little info to a verbose output

- config/pmix_mca.m4
- src/mca/bfrops/base/bfrop_base_frame.c
- src/mca/bfrops/bfrops_types.h
- src/mca/pgpu/amd/pgpu_amd.c
- src/mca/pgpu/intel/pgpu_intel.c
- src/mca/pgpu/nvd/pgpu_nvd.c
- src/mca/pnet/nvd/pnet_nvd.c
- src/mca/pnet/opa/pnet_opa.c
- src/mca/pnet/opa/pnet_opa_component.c
- src/mca/pnet/usnic/pnet_usnic.c
When we allocate information to support a particular fabric,
we pack that info into a buffer and then transport the "blob"
to the backend for unpacking and processing. During the unpack
operation, we tried to be clever and simply assign the blob
into the various buffer fields.
Bad idea - missed a critical one and that caused the unpack
to fail. Instead, define a suitable macro for this purpose
to ensure that ALL the required buffer fields get set.
Also, OPA fabric is device type 0x208 - correct the typo.
Thanks to Howard Pritchard and Michael Heinz for identifying
the problem.
> Fix the network support components

- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_listener.c
- src/tool/pmix_tool.c
- test/util/numa.c
Change processing for the --pmixmca ptl_base_if_include and --pmixmca ptl_base_if_exclude options so that all adapters that are within the specified subnet range are selected or excluded, respectively.
The changes to the split_and_resolve function create a list of unique adapter names selected for processing in the order they are seen, and that list is returned to the caller.
The use case here is: Given a system with three ethernet devices:
eth0: 192.168.1.10
eth1: 192.168.2.10
eth2: 9.10.11.10
All three interfaces can route to other nodes, but we only want to use eth0 and eth1 for TCP traffic for this job.
Currently, I need to specify either the individual devices or non-overlapping subnets: --pmixmca ptl_base_if_include 192.168.1.0/24,192.168.2.0/24 because if I specify --pmixmca …
> Select all adapters with IPV4 addresses within specified subnet ranges.

- src/runtime/help-pmix-runtime.txt
The actual name is `PMIX_PREFIX` https://github.com/openpmix/openpmix/issues/2405#issuecomment-981217180
fixes #2405
> Fix environment variable name in help-pmix-runtime

- test/test_v2/test_common.c
- test/test_v2/test_common.h
Mark that pmixt_exit does not return.
> Fix devel-check of test_v2

- maint/pmix.pc.in
PMIX's dependencies are only needed when static linking, so they
should be marked as .private dependencies.
(cherry picked from commit e2102a569873e476ee41e634382ac3c275b95932)
> Mark dependencies private in pkg-config file

- config/pmix.m4
- config/pmix_functions.m4
- config/pmix_mca.m4
- config/pmix_setup_wrappers.m4
- configure.ac
- maint/pmix.pc.in
Fix logic to figure out what libraries to link with an application.  In the dynamic case, no longer include dependent libraries, since the aren't needed (this was a missing macro expansion in the wrapper compiler).  In the dynamic case, we need to thread the MCA libraries into the wrapper compiler.  Finally, switch from using pkg-config package requires and list the libraries out explicitly, due to problems with libevent and the MCA system (details in the commit message).
> Fix library linking in static link cases

- config/pmix.m4
- config/pmix_check_cuda.m4
- config/pmix_check_psm2.m4
- config/pmix_setup_hwloc.m4
- src/mca/pgpu/amd/configure.m4
- src/mca/pgpu/intel/configure.m4
- src/mca/pgpu/nvd/configure.m4
- src/mca/pnet/nvd/configure.m4
- src/mca/pnet/opa/configure.m4
- src/mca/pnet/tcp/configure.m4
- src/mca/pnet/usnic/configure.m4
Don't build the components if we lack the corresponding
support. We may not use those libraries in the components
at this time, but no point in grabbing/moving envars and
allocating resources for non-existent things
> Add configure support for the pgpu and pnet components

- include/pmix_common.h.in
- test/test_v2/test_get_basic.c
the GET_NUMBER macro didn't know about this pmix type
> fix a problem using PMIX_RANK

- config/pmix_functions.m4
Fix two issues in OPAL_FLAGS_APPEND_MOVE, which impacted the static
library list in the wrapper compilers.  First, an assignment was
outside the conditional clause, resulting in the original array
being wiped out if the input did not contain any -l arguments.
Second, we did not have the default case to handle arguments that
did not begin with -I, -L, or -l.
> Fix two bugs in OPAL_FLAGS_APPEND_MOVE

- config/pmix.m4
- config/pmix_setup_libev.m4
- config/pmix_setup_libevent.m4
Regardless of what was specified, if anything.
> The PMIX_HAVE_LIBEV and PMIX_HAVE_LIBEVENT flags must always be defined

- test/test_v2/test_fence_wildcard.c
declare the parse_fence_client static for safety
> test_v2: use static declaration for client parser

- config/pmix_setup_hwloc.m4
- config/pmix_setup_libev.m4
- config/pmix_setup_libevent.m4
Add ability to both add additional libraries into the link
dependencies for libevent, libev, and hwloc (useful if they
have unexpected libraries for static linking) and to disable
library checks for places where we get it really wrong and
users resort to setting LIBS directly.
> build: Be more flexible in library handling

- .gitignore
- EXCEPTIONS
- include/pmix_common.h.in
- src/class/pmix_list.h
- src/common/pmix_iof.c
- src/common/pmix_iof.h
- src/include/pmix_globals.h
- src/server/pmix_server.c
- src/server/pmix_server_ops.h
- test/simple/asyncio.c
Output complete lines at a time to eliminate output from
different ranks stepping on each other. Provide a new
attribute PMIX_IOF_OUTPUT_RAW to turn this off since
sometimes users want the output to appear immediately
and not be internally cached while it waits for a newline
character to be output.
> Enable buffered IOF output

- config/pmix_setup_wrappers.m4
(cherry picked from commit d0609f1a7f322f02295eecf845644c21afd91fec)
> build: Fix escaping issue in pkg-config file

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
This fixes several bugs in the Python bindings. One is to release the GIL around the `PMIx_IOF_pull` function and adds GIL protection around the `pyiofhandler()` handler.
The next one is more tricky and may need to be broken out if controversial. Inside of the `pmix_pyshift_t` there is a `pmix_byte_object_t *` that never gets set up in the `pyiofhandler()` in the 'handle not found' code path and causes codes to crash when trying to initialize the bad memory. The change I made changed `pmix_byte_object_t` to not be a pointer anymore, then allocate the bytes element and initialize in the 'handle not found' code path and frees it after it retries. 
This fixes my bug in the short term, though longer term I want to take a closer look at the event loop in general.
> Python IOF pull fixes

- src/tools/wrapper/pmixcc.c
Regardless of name being used, the wrapper data txt file
remains pmixcc-wrapper-data.txt
> Fix the wrapper compiler txt file path

- src/client/pmix_client_get.c
* Make sure to remove the matching pending request from the list before
calling the client callback. Otherwise the client could race ahead and
determine that there is an outstanding pending request at the bottom of
the get operation. In which case it is putting the main thread to sleep
forever (hang) thinking that another request will be incoming which it
won't because it was already processed.
> Fix race condition when processing pending get requests

- src/client/pmix_client_get.c
- src/common/pmix_strings.c
- src/include/pmix_globals.h
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Prior to this PR, the users thread was penetrating down into
code that accessed global variables that are restricted to
access only from within a PMIx progress event. Refactor the
code to prevent that from happening.
Also add code to support the "refresh cache" request - this
hook was missing from the current code. Still need server-side
implementation.
> Fix the client-get function

- EXCEPTIONS
- config/pmix.m4
- include/pmix_common.h.in
- src/mca/psensor/base/psensor_base_frame.c
- src/runtime/pmix_init.c
- src/runtime/pmix_progress_threads.c
- src/runtime/pmix_progress_threads.h
- test/simple/simptest.c
In some scenarios, it is desirable to bind progress threads
to one or more specific cores - e.g., a core designated for
utility usage and not assigned application processes. Provide
an attribute by which the user can specify the core(s) to
which the internal PMIx progress thread is to be bound, and
to indicate if the binding is mandatory (i.e., return an
error if the thread cannot be bound).
> Enable ability to bind PMIx progress thread

- src/mca/psensor/base/psensor_base_frame.c
- src/runtime/pmix_init.c
- src/runtime/pmix_params.c
- src/runtime/pmix_progress_threads.c
- src/runtime/pmix_progress_threads.h
- src/runtime/pmix_rte.h
- test/simple/simptest.c
Allow it to be set via MCA parameter, override by
attribute passed to a PMIx init API.
> Tweak the progress thread bind support

- config/pmix_setup_hwloc.m4
Blacklist all HWLOC releases 2.5.0 and above
> Protect against HWLOC issues

- test/pmix_environ.c
Fix CID 375078, caused by ec0daf3, by checking that the return of
getenv() is not NULL before passing it to strcmp().
> test: Fix dereference issue in environ test

- src/common/pmix_iof.c
Found this when testing mpirun/prterun --output dir=/foo/bar/
option.
> pmix_iof.c: malloc buffer before memcpy().

- src/mca/base/pmix_base.h
- src/mca/base/pmix_mca_base_alias.h
- src/mca/base/pmix_mca_base_open.c
- src/mca/base/pmix_mca_base_var.c
- src/mca/base/pmix_mca_base_var.h
- src/runtime/pmix_init.c
- src/tools/pmix_info/support.c
- src/tools/wrapper/pmixcc.c
- src/util/pmix_cmd_line.h
Allow specification of additional paths to component libraries.
Make the MCA prefix (e.g., "PMIX_MCA_") be based on the project
name used to register the variable.
> Generalize MCA support

- include/pmix_common.h.in
- src/mca/base/pmix_mca_base_component_repository.c
- src/util/pmix_argv.h
We were declaring pmix_argv_split_with_empty but never instantiated
it - do so. Include the original dlopen error when reporting possible
reasons the library could not be loaded.
> Add missing function and improve error message

- Makefile.am
- config/pmix.m4
- config/pmix_setup_wrappers.m4
- src/Makefile.am
- src/mca/bfrops/Makefile.am
- src/mca/common/sse/Makefile.am
- src/mca/gds/Makefile.am
- src/mca/pcompress/Makefile.am
- src/mca/pdl/Makefile.am
- src/mca/pfexec/Makefile.am
- src/mca/pgpu/Makefile.am
- src/mca/pif/Makefile.am
- src/mca/pinstalldirs/Makefile.am
- src/mca/plog/Makefile.am
- src/mca/pmdl/Makefile.am
- src/mca/pnet/Makefile.am
- src/mca/preg/Makefile.am
- src/mca/prm/Makefile.am
- src/mca/psec/Makefile.am
- src/mca/psensor/Makefile.am
- src/mca/psquash/Makefile.am
- src/mca/pstat/Makefile.am
- src/mca/pstrg/Makefile.am
- src/mca/ptl/Makefile.am
Always install the headers as they are now required by PRRTE.
Fixes https://github.com/openpmix/prrte/issues/1219
> Ensure we always install the internal headers

- src/util/pmix_cmd_line.c
Otherwise, the parser will try to match command line
options for the application to prterun.
Refs open-mpi/ompi#10044
> pmix_cmd_line.c: Stop parsing at the executable.

- src/util/pmix_context_fns.c
CID 376572:  Null pointer dereferences  (FORWARD_NULL)
CID 376571:  Null pointer dereferences  (FORWARD_NULL)
> Silence Coverity warnings

- maint/pmix.pc.in
- src/tools/wrapper/pmixcc-wrapper-data.txt.in
With the changes to allow PRRTE to rely on PMIx's utilities, we
need extra include directories for packages to pull in those
dependencies.
> Push additional include in pkg-config/wrappers

- src/util/pmix_cmd_line.c
According to the getopt_long() docs, it should be reset on the
second invocation when parsing the same command line:
"A program that scans multiple argument vectors, or rescans the
same vector more than once, and wants to make use of GNU
extensions such as '+' and '-' at the start of optstring, or
changes the value of POSIXLY_CORRECT between scans, must
reinitialize getopt() by resetting optind to 0, rather than the
traditional value of 1. (Resetting to 0 forces the invocation of
an internal initialization routine that rechecks POSIXLY_CORRECT
and checks for GNU extensions in optstring.)"
https://man7.org/linux/man-pages/man3/getopt.3.html
Since prrte makes use of '-' at the start of opt-string - this seems
to apply. I made the mistake of resetting this to 1 to fix a different
bug, …
> Reset getopt() to 0, not 1.

- .github/workflows/run-special.yml
* These run in the same container as the cross-version checks
which are already running in OpenPMIx's GitHub Actions.
> Move the Special builds to GitHub Actions

- test/test_v2/test_clientapp_funcs.c
- test/test_v2/test_common.h
Silence "reading 512 bytes from a region of size X" warnings generated
by GCC 11.2.0. This may be a spurious warning, but once that is
generated nonetheless. The problem seems to come from a function
definition with a static length char buffer (pmix_key_t) with call-sites
passing string constants that are strictly shorter than the size of
pmix_key_t. This usage seems atypical in the codebase, so perhaps there
is a better way to silence these particular warnings.
A similar warning is generated at a call-site in
test/test_v2/server_callbacks.c at line 323 involving a call to
PMIx_server_register_nspace(), but this one is stickier, so someone else
should look into that one. Note: changing the string constant to a char*
variable does not silence this one. Pesky, pesky.
Signed-off-by: Samuel …
> Silence warnings in pmixt_validate_predefined().

- src/mca/pif/base/base.h
- src/mca/pif/pif.h
- src/runtime/Makefile.include
- src/runtime/pmix_init.c
- src/runtime/pmix_init_util.h
- src/util/pmix_if.h
Now that PRRTE directly depends on PMIx classes and frameworks,
we need to ensure that some small portion of PMIx is setup
prior to PRRTE attempting to use it. Create a new "pmix_init_util"
for this purpose. Need to isolate that prototype in its own
include header to avoid pulling in a bunch of other stuff.
The PMIx interface framework was the immediate problem as PRRTE
tried to traverse a list prior to it being constructed.
> Provide a "hook" for PRRTE to init a small amount of PMIx

- src/util/pmix_net.c
- src/util/pmix_net.h
Bring back _net_addr_isipv6linklocal(), removed from prrte master.
> Fix ipv6 build with prrte.

- src/hwloc/pmix_hwloc.c
- src/hwloc/pmix_hwloc.h
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/util/Makefile.am
- src/util/pmix_shmem.c
- src/util/pmix_shmem.h
- src/util/pmix_vmem.c
- src/util/pmix_vmem.h
Make public virtual memory utility functions previously found in
src/hwloc. In particular, find_hole() is now made public as
pmix_vmem_find_hole() in utils/pmix_vmem.c. Other infrastructure will
soon make use this capability, namely gds/shmem.
Additionally, this commit checkpoints insignificant changes to
gds/shmem and utils/pmix_shmem.
> Publicize virtual memory utility functions.

- src/runtime/pmix_init.c
- src/runtime/pmix_init_util.h
- src/tools/pattrs/pattrs.c
- src/tools/pevent/pevent.c
- src/tools/plookup/plookup.c
- src/tools/pmix_info/pmix_info.c
- src/tools/pps/pps.c
- src/tools/pquery/pquery.c
- src/tools/wrapper/pmixcc.c
- src/util/pmix_show_help.c
- src/util/pmix_show_help.h
This way prte help files can be added to the search path.
> Modify pmix_show_help_init() to take an addition helpdir.

- src/hwloc/pmix_hwloc.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/runtime/pmix_init.c
- src/runtime/pmix_init_util.h
Do it in pmix_init_util.h so upper levels can access it
without pulling in a bunch of extra stuff.
Also, fix unused function error.
> Expose the pmix_tool_basename param

- src/class/pmix_hotel.h
There's no consumers of it at this point, and likely is not needed.
See discussion in https://github.com/openpmix/prrte/pull/1265.
> pmix_hotel_recheck(): Remove this function. 

- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/mca/ptl/server/ptl_server.c
- src/mca/ptl/tool/ptl_tool.c
Don't automatically terminate if a connection is dropped
unless it is to the "active" server. Consolidate some of
the connection code between servers and tools to remove
duplication.
> Properly handle tools that have tools connected to them

- .gitignore
- include/pmix.h
- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/server/pmix_server_ops.c
- src/tools/pquery/pquery.c
Add a couple of print APIs and update pquery to use one
I'm tired of writing pretty-print code in every app, so
create two new APIs:
PMIx_Info_string - prints a pmix_info_t
PMIx_Value_string - prints a pmix_value_t
Update pquery to print out the results using the new
APIs. Also update ignores
(cherry picked from commit https://github.com/openpmix/openpmix/commit/b419abdd7232f01614e7bbc860d59935991fa6c6)
Minor cleanups for picky compiler settings
(cherry picked from commit https://github.com/openpmix/openpmix/commit/db6ddf74ae382d0d5992a2d57e226eb6e0cc1930)
> Add print APIs and update pquery to use them

- examples/hello.c
- src/common/pmix_query.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/tools/pmix_info/support.c
- src/tools/pquery/pquery.c
- test/simple/simptest.c
If a tool receives a query, it may (and is likely) not be able
to find the data being requested. For example, if a tool requests
the proc table for a job that another tool spawned, then that
request has to be relayed to the RM for an answer - and then the
answer has to be relayed back to the original requestor.
Fix a problem in simptest where a threadshift left a value on
the stack, which could subsequently be lost.
Fixes https://github.com/openpmix/prrte/issues/1253
> Properly handle queries of tools

- config/pmix.m4
- configure.ac
Cython takes issue with purely static builds, so error
out if the user requests the Python bindings but has
specified --disable-shared.
Also fix a problem with the "canonicalize_path" function
in configure - new versions of MacOS (i.e., starting with
Mojave) do _not_ have a /usr/bin/python, but do have
"readlink", so use it instead
Fixes https://github.com/openpmix/openpmix/issues/2482
> Prohibit Python bindings with non-shared lib builds

- src/runtime/pmix_init.c
- src/runtime/pmix_init_util.h
- src/util/pmix_cmd_line.c
To be used for --version and --help messages, instead
of always displaying "PMIx" and its compiled version for
all tools.
Refs: https://github.com/open-mpi/ompi/pull/10120
Refs: https://github.com/open-mpi/ompi/issues/10096
Refs: https://github.com/openpmix/prrte/pull/1287
> Runtime: Add tool version, org, and custom message.

- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/pcompress/zlib/compress_zlib.c
** CID 376628: (USE_AFTER_FREE)
** CID 365833: Error handling issues (CHECKED_RETURN)
> Fix Coverity warnings

- src/include/pmix_globals.c
- src/mca/ptl/base/ptl_base_fns.c
- Revert "Leak: Always free ns->jobbkt in pmix_nspace_caddy_t destructor."
This reverts commit https://github.com/openpmix/openpmix/commit/aeb4145563eb3ed48a5445009213b806df2ccbfa.
Not sure why I did this, ns->jobbkt is free'd in the ns
destructor, called two lines down. If it isn't getting released,
that is a leak somewhere else where its reference count is incremented.
This was the wrong fix.
FWIW - that leak elsewhere may have since been fixed, causing me
to see this bug now.
This corrects a crash with --enable-debug where remote daemons
will crash with an assert on jobbkt's ref count.
- Initialize size for getsockopt().
This parameter is technically an in and out
for getsockopt() calls. Reported as uninitialized
by valgrind.
> Fix a crash with --enable-debug

- config/pmix_check_curl.m4
- config/pmix_check_jansson.m4
385308 broke building the common/sse package because it hid the Jansson
and Curl happiness variables from the later common/sse check.  The
downside of trying to keep namespace pollution down.  Re-share those
two state variables and fix an issue where we were mis-setting the
Curl happiness variable.
> build: Fix common/sse check

- config/pmix_mca.m4
PMIX_MCA_STRIP_LAFILES was supposed to copy the non-.la files into the
first argument, rather than append the non-.la files into the first
argument.  The append behavior caused us to leak component's LDFLAGS
into their LIBS.  Usually, deduping cleaned everything up later,
but it still is a bug.
While we're here, use the recently added PMIX_APPEND instead of
implementing our own append.
> build: Fix leak of non-LIBS flags into LIBS

- src/client/pmix_client_get.c
- src/server/pmix_server_get.c
- test/simple/simpdmodex.c
Cannot release the "lg" object as it might be used again
in the loop. Object will be released when the caddy is
released.
Cleanup the simpdmodex test a bit so that all outputs are
properly clumped when run thru "sort" - makes it easier
to debug.
Refs https://github.com/openpmix/prrte/issues/1243
> Remove incorrect object release

- src/client/pmix_client_get.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- test/simple/simpdmodex.c
- test/test_fence.c
Current code only supported delayed "get" requests
(i.e., a request for data not yet received) from
remote procs. If a local proc requested data from
another local proc, and the posting hadn't already
been done, then we would wait - but the retrieval
after waiting was locked to PMIX_REMOTE scope, and
so the data would never be found.
Also fix the return code so that we get the original
issue ("timeout") and not a bogus "not found".
Increase the flexibility of the simpdmodex test to
allow passing timeout, sleep, and async flags on
the cmd line.
Adjust the tests to not error on timeout when expected
to fail
Refs https://github.com/openpmix/prrte/issues/1243
> Properly deal with delayed local get requests

- src/class/pmix_object.h
Fix a very subtle bug where it is
possible that another thread will win the race
and update obj_reference_count before its value is returned.
This can result in asserts being hit with debug builds.
Cache the updated value before the lock is let go and return it
seems to fix intermittent crashes in various MPI routines.
> Protect critical zone in pmix_obj_update().

- config/pmix_summary.m4
38530 introduced a bug where the summary section values were
sent to stdout instead of stderror like the rest of the summary.
This patch fixes that issue.
> build: Fix output stream bug in summary

- src/class/pmix_object.h
Fix a very subtle bug where it is
possible that another thread will win the race
and update obj_reference_count before its value is returned.
This can result in asserts being hit with debug builds.
Cache the updated value before the lock is let go and return it
seems to fix intermittent crashes in various MPI routines.
(cherry picked from commit 56a46caa737da90d934a902769315bf3e949d3fd)
> v4.2: Protect critical zone in pmix_obj_update().

- src/include/pmix_globals.c
- src/mca/ptl/base/ptl_base_fns.c
This parameter is technically an in and out
for getsockopt() calls. Reported as uninitialized
by valgrind.
(cherry picked from commit 5158ae3ef1ddd4977e10c7baf1bde5cb67d418e8)
Revert "Leak: Always free ns->jobbkt in pmix_nspace_caddy_t destructor."
This reverts commit https://github.com/openpmix/openpmix/commit/aeb4145563eb3ed48a5445009213b806df2ccbfa.
Not sure why I did this, ns->jobbkt is free'd in the ns
destructor, called two lines down. If it isn't getting released,
that is a leak somewhere else where its reference count is incremented.
This was the wrong fix.
FWIW - that leak elsewhere may have since been fixed, causing me
to see this bug now.
This corrects a crash with --enable-debug where remote daemons
will crash with an assert …
> v4.2: Initialize size for getsockopt() and revert bad free

- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
When resolving data requests that may have been delayed waiting
for the source to commit the requested data, be sure to check
both the server's _and_ the peer's GDS component for the data.
While master currently only has one component, that may not
be true in the future, and it is possible that the committed
data was stored on the peer's component (and not the server's).
> Ensure we check peer's gds for data

- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/tools/wrapper/pmixcc.c
- test/simple/simpdmodex.c
[Fix warning - compare of different signs](https://github.com/openpmix/openpmix/commit/32d405332dc23a7c6964267f2f863f1ba68f337e)
[Fix dmodex operation on local host](https://github.com/openpmix/openpmix/commit/b445b978834a3e19ea2cab87f4361300a3275b0e)
Pass the scope to pending_resolve so we check the local
scope when appropriate instead of having the function locked
to the remote scope case. This was a change that somehow didn't
get backported from master.
Also ensure that we check the peer's GDS component and not
just our own when looking for requested data. On master, there
currently is only one storage system, so it doesn't matter.
However, that isn't the case on prior release branches, and
data can be stored in the peer's component.
Update the simpdmodex test to track master …
> Minor cleanup plus fix dmodex operation on local host

- src/client/pmix_client_get.c
- test/test_fence.c
If the server returns an error status on a get request,
ensure we pass that status to any requestors.
> Ensure we get correct return status

- src/util/help-cli.txt
- src/util/pmix_cmd_line.c
It has been correctly pointed out that a number of the cmd line
options could accept "help" as an input value as opposed to
meaning a request for "help". Until we can figure out a way to
separate those instances out from legitimate requests for help,
let's remove that method.
We therefore only accept two methods for requesting help:
- a directive to the cmd itself: e.g., "prte --help"
- an option to the help cmd line option: e.g., "--help map-by"
Hopefully, we will someday come up with a solution - perhaps
need to take a closer look at how "hydra" currently supports it.
Closes https://github.com/openpmix/openpmix/pull/2544
> Remove the "<option> help" support

- config/pmix.m4
We use the DELAYED_LIBS for threading .la files through the build
system, but need to wait until after the wrapper compiler finalize
(which is the last place in configure that LIBS are tested) before
adding DELAYED_LIBS to LIBS.  Note that all users of DELAYED_LIBS
directly add the right -l<lib> arguments to the wrapper compilers.
> build: Delay adding DELAYED_LIBS even more

- src/util/pmix_cmd_line.c
- src/util/pmix_cmd_line.h
Seems to be pretty commonly used, so support it
as a special case.
> Support the common "-np" option

- .gitignore
- VERSION
- config/pmix.m4
- config/pmix_get_version.sh
- config/pmix_summary.m4
- examples/Makefile.am
- examples/abi_no_init.c
- examples/abi_with_init.c
- include/pmix_common.h.in
- src/client/pmix_client.c
- src/common/pmix_query.c
* `PMIx_Query_info` can now query the ABI level via the `PMIX_QUERY_ABI_VERSION` key
* The `PMIX_QUERY_ABI_VERSION` is only resolvable locally to the caller and should not be sent to the server. So add a mechanism to, when this situation is identified, strip out this key from the query sent to the server. When the server response comes back then add the locally resolved information before passing it back to the client.
* Add the PMIx Standard ABI version level to the `VERSION` file (similar to the PMIx Standard level)
* Since the PMIx Standard ABI is not yet finalized set it to `0.0` for now. I'm assuming that we will change that to `5.0` once the ABI is ratified.
* Ref
* PMIx Standard PR: https://github.com/pmix/pmix-standard/pull/397
* PMIx Standard ABI Discussion: …
> Add PMIX_QUERY_ABI_VERSION key for PMIx_Query_info

- include/pmix_common.h.in
- include/pmix_deprecated.h
- src/util/pmix_context_fns.c
- src/util/pmix_error.c
Provide an atomistic error code for the context check_app and check_cwd
functions so callers can better know exactly what went wrong.
> Add constants and support for atomistic reporting of context checks

- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_sendrecv.c
Only cap the client/server message size if requested to do
so by setting the limit using the MCA param.
> Don't limit message size unless requested

- src/mca/bfrops/base/bfrop_base_copy.c
Fix incorrect memcpy size for the PMIX_PROC_RANK case found in
pmix_bfrops_base_copy_darray().
> Fix memcpy size in pmix_bfrops_base_copy_darray().

- src/class/pmix_object.h
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
Please note that this commit reimplements---internally within the gds
shmem component---some core PMIx functionality. The reason for this
approach is to first prototype the infrastructure required to implement
this component, with the ultimate goal of eventually finding a
reasonable way to reintegrate the duplicated infrastructure. This
approach minimizes sweeping changes to core infrastructure used by other
components, while also supporting forward progress in gds/shmem development.
Don't panic :).
> Checkpoint gds/shmem work.

- config/pmix_config_asm.m4
If the user disables the built-in atomic support AND is using
a compiler that lacks C11 atomics, then we need to error out
with an explanation during configure.
Fixes #2561 
> Error out if no atomic support is available

- include/pmix.h
- include/pmix_deprecated.h
When moving the now-deprecated macros to pmix_deprecated.h, we
had those macros invoke their replacement APIs. However, those
APIs are defined in pmix.h (where they belong). This causes users
who included only "pmix_common.h" in their files to break if they
invoked one of the now-deprecated macros.
Resolve this by including the function prototypes in pmix_deprecated.h.
Since we want them to be seen as true APIs, also include them
(in a protected form) in pmix.h, with comments documenting their
use.
(cherry picked from commit 07ba28c66d94ffdc37854304dee624dc5ab6f05b)
> Make pmix_common.h stand alone

- include/pmix_deprecated.h
Needs to be prototyped there as the prototype in
pmix.h is hidden
> Include Value_compare in pmix_deprecated.h

- src/mca/gds/hash/gds_fetch.c
Remove an unnecessary call to pmix_gds_hash_get_tracker() in
pmix_gds_hash_fetch(). The job tracker had already been acquired
beforehand.
> Remove unnecessary function call in pmix_gds_hash_fetch().

- include/pmix_common.h.in
- src/client/pmix_client.c
- src/common/pmix_log.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/plog/base/plog_base_stubs.c
- src/runtime/pmix_params.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
- src/util/pmix_show_help.c
- src/util/pmix_show_help.h
- test/simple/simptest.c
This requires some changes in prrte for it to work, will post that shortly if this looks ok.
[Refactor show_help() to use the PMIx_Log() api.](https://github.com/openpmix/openpmix/commit/e2e7d1b44b6c69809c861b09439741a9a172dc90) 
- Port over the de-dupping code from prrte.
- Add some additional keys to support a request
to de-dup logging messages.
- Remove locks from the high level PMIx_Log() api's - they
don't seem necessary, and make it very easy to deadlock
when the current thread already holds the global lock.
- Likewise - use PMIx_Log_nb() instead of PMIx_Log() - the
non-blocking counterpart will allow libevent to trigger the
callbacks on its own time. Otherwise, in the case of a
show_help() message from prted that happens before the main thread
hits the event loop, it will hang …
> Use PMIx_log() for show_help()

- src/util/pmix_show_help.c
- src/util/pmix_show_help.h
It is true that pmix_status_t is an int, but we always
explicitly return pmix_status_t anyway (just in case it
someday changes, which would be hard to believe). Add a
"norender" API that PRRTE uses in only one place, but easier
than trying to figure out a way around it.
> Cleanup the show_help changes a bit

- include/pmix_common.h.in
- src/client/pmix_client.c
- src/common/pmix_log.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/plog/base/plog_base_stubs.c
- src/runtime/pmix_params.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
- src/util/show_help.c
- src/util/show_help.h
- test/simple/simptest.c
[Refactor show_help() to use the PMIx_Log() api.](https://github.com/openpmix/openpmix/commit/51e71155bb7af89382deb6ef6af7e17d8a6d900f) 
- Port over the de-dupping code from prrte.
- Add some additional keys to support a request
to de-dup logging messages.
- Remove locks from the high level PMIx_Log() api's - they
don't seem necessary, and make it very easy to deadlock
when the current thread already holds the global lock.
- Likewise - use PMIx_Log_nb() instead of PMIx_Log() - the
non-blocking counterpart will allow libevent to trigger the
callbacks on its own time. Otherwise, in the case of a
show_help() message from prted that happens before the main thread
hits the event loop, it will hang forever.
- We can avoid deadlock in show_help calls made prior to
completing client/server/tool …
> v4.2: Refactor show_help() to use the PMIx_Log() api. 

- .gitignore
- examples/group.c
- examples/group_lcl_cid.c
- src/include/pmix_globals.h
- src/server/pmix_server_ops.c
- src/util/pmix_hash.c
- test/simple/simptest.c
Allow processes to contribute information during calls to
PMIx_Group_construct that are shared with all construct
participants. The values are returned to the participants
as "qualified" values, each value qualified by the assigned
group context ID.
> Complete support for group-level info

- configure.ac
PMIX_CANONICALIZE_PATH broke on MacOS when `/usr/bin/python`
disappeared (in favor of `/usr/bin/python3`) in MacOS Monterrey.  Make
things simpler by not canonicalizing the path to begin with.
Specifically: just look at `pwd`, $srcdir, and $prefix.  Even if
$srcdir and/or $prefix are relative to the build dir, the union of all
the checks will ensure that none of the target paths will contain
spaces.
Back-ported from
https://github.com/open-mpi/ompi/commit/6992c642437af1135ccb6f159683853fe63c58cc
> configure.ac: update directory space check

- src/runtime/pmix_params.c
- src/runtime/pmix_rte.h
- src/util/pmix_fd.c
On some OS's (e.g., macOS), the value returned by
sysconf(_SC_OPEN_MAX) can be set by the user via "ulimit -n X", where
X can be -1 (unlimited) or a positive integer. On macOS in particular,
if the user does not set this value, it's unclear how the default
value is chosen.  Some users have reported seeing arbitrarily large
default values (in the billions), resulting in a very large loop over
close() that can take minutes/hours to complete, leading the user to
think that the app has hung.  To avoid this, ensure that we cap the
max FD that we'll try to close.  This is not a perfect scheme, and
there's uncertainty on how the macOS default value works, so we
provide the pmix_maxfd MCA var to allow the user to set the max FD
value if needed.
This commit is inspired by …
> pmix_fd: cap the max FD to try to close

- configure.ac
PMIX_CANONICALIZE_PATH broke on MacOS when `/usr/bin/python`
disappeared (in favor of `/usr/bin/python3`) in MacOS Monterrey.  Make
things simpler by not canonicalizing the path to begin with.
Specifically: just look at `pwd`, $srcdir, and $prefix.  Even if
$srcdir and/or $prefix are relative to the build dir, the union of all
the checks will ensure that none of the target paths will contain
spaces.
Back-ported from
https://github.com/open-mpi/ompi/commit/6992c642437af1135ccb6f159683853fe63c58cc
(cherry picked from commit 594303dfa704daf9b3dde8ee1448bed06d4196d5)
> v4.2: configure.ac: update directory space check

- configure.ac
PMIX_CANONICALIZE_PATH broke on MacOS when `/usr/bin/python`
disappeared (in favor of `/usr/bin/python3`) in MacOS Monterrey.  Make
things simpler by not canonicalizing the path to begin with.
Specifically: just look at `pwd`, $srcdir, and $prefix.  Even if
$srcdir and/or $prefix are relative to the build dir, the union of all
the checks will ensure that none of the target paths will contain
spaces.
Back-ported from
https://github.com/open-mpi/ompi/commit/6992c642437af1135ccb6f159683853fe63c58cc
(cherry picked from commit 594303dfa704daf9b3dde8ee1448bed06d4196d5)
> v4.0: configure.ac: update directory space check

- src/mca/gds/hash/gds_hash.c
Eliminate duplicated key/value storage for a PMIX_QUALIFIED_VALUE()
case in hash_cache_job_info().
> Deduplicate key/value storage for qualified values.

- src/mca/ptl/base/ptl_base_listener.c
Pre-v4.2 tools will be looking for the PMIX_SERVER_URI instead
of the new PMIX_MYSERVER_URI key, so let's store both.
> Save a legacy URI to support older tools

- src/mca/bfrops/base/bfrop_base_fns.c
* Leaving the `flags` variable uninitialized can cause it to take
a value that leads to misbehavior when handling PMIx_Get.
* Detected by running an IBM XL compiler build of PRRTE in which
sometimes the PMIx_Get would turns the value requested and sometimes
not depending on the memory placmeent of the allocated pmix_info_t.
> Initialize pmix_info_t flags when loading

- include/pmix_common.h.in
When spawning a new job, support the case where the user
wants to spawn the new procs at locations where current
procs are executing. Provide for both specification of
the number of new procs to start on each node where the
current procs are executing, or the number of new procs
to start for each current proc that is executing.
Note that these are not required to be daemons - they can
be any application code, and can have any desired ranking
and/or binding policy. Mapping policy, however, will be
ignored as it is overridden by the "colocate" directive.
> Support colocation of processes

- config/pmix.m4
- configure.ac
We currently require flex whenever we are in a Git clone, but that
really isn't the requirement. We need flex whenever the flex output
files are not present - otherwise, you can build just fine. So open
things up a bit by tying the flex requirement to the actual one
(i.e., that the flex output file exist).
This also patches the configure logic to fix a reported situation
where configure incorrectly reports that `flex` is not available.
Refs https://github.com/openpmix/openpmix/issues/2605
Refs https://github.com/openpmix/openpmix/issues/2599
> Require flex only when keyval_lex.c is not provided

- src/class/pmix_object.c
- src/class/pmix_object.h
- src/mca/gds/shmem/gds_shmem.c
This commit further integrates TMA infrastructure into the base object
system. Some key memory allocations there were outside a provided TMA's
purview; now they are captured.
> TMA: Integrate more custom memory allocator infrastructure.

- include/pmix.h
- include/pmix_common.h.in
- include/pmix_deprecated.h
- src/client/pmix_client_get.c
- src/client/pmix_client_topology.c
- src/hwloc/pmix_hwloc.c
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/v20/copy.c
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/gds_hash_component.c
- src/mca/gds/hash/process_arrays.c
- src/mca/preg/base/base.h
- src/mca/preg/base/preg_base_frame.c
- src/mca/preg/base/preg_base_stubs.c
- src/mca/preg/compress/preg_compress.c
- src/mca/preg/native/preg_native.c
- src/mca/preg/preg.h
- src/mca/preg/raw/preg_raw.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/runtime/pmix_rte.h
- src/threads/pmix_tsd.h
Finalize the MCA param subsystem to cleanup the
parameter storage. Provide a way to release the
pmix_value_t and pmix_data_array_t storage. Ensure
we release the pmix_job_t tracker in the gds/hash
component when the nspace is deleted.
Resolve memory corruption problem associated with passing
the HWLOC topology into the PMIx server from the host. This
was being copied during the "info_list" processing, and then
being deleted when the resulting data array was released - leaving
the server to continue accessing the free'd topology tree.
Remove an unnecessary "retain" - thanks to Artem Polyakov for
spotting it. Cleanup around that to avoid segfault of double
release while avoiding leak.
Add some missing utility finalize calls
> Some initial valgrind cleanup

- src/hwloc/pmix_hwloc.c
> Fix typo in setting hwloc verbosity

- config/pmix.m4
- configure.ac
- include/pmix_common.h.in
- src/hwloc/pmix_hwloc.c
- src/mca/gds/hash/gds_fetch.c
- src/mca/pfexec/linux/pfexec_linux.c
- src/runtime/pmix_params.c
- src/runtime/pmix_rte.h
- src/util/pmix_fd.c
[Remove unnecessary function call in pmix_gds_hash_fetch().](https://github.com/openpmix/openpmix/commit/78488f61a196634830b9abfc1428b16667740204)
Remove an unnecessary call to pmix_gds_hash_get_tracker() in
pmix_gds_hash_fetch(). The job tracker had already been acquired
beforehand.
(cherry picked from commit https://github.com/openpmix/openpmix/commit/69e6965c0660d3e8da15d217728df91cd551e832)
[pmix_fd: cap the max FD to try to close](https://github.com/openpmix/openpmix/commit/fdecf3074ae7c24bc46527434e5d89608de2218b)
On some OS's (e.g., macOS), the value returned by
sysconf(_SC_OPEN_MAX) can be set by the user via "ulimit -n X", where
X can be -1 (unlimited) or a positive integer. On macOS in particular,
if the user does not set this …
> Update from master branch

- .gitignore
- examples/Makefile.am
- examples/nodeinfo.c
- src/client/pmix_client.c
- src/client/pmix_client_get.c
- src/include/pmix_globals.h
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_fetch.c
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/gds_hash.h
- src/server/pmix_server.c
Per the Standard, one can retrieve information about a process
from the node/app/session realms in two ways:
(a) by passing the proc ID along with a key that belongs to
one of those realms. The PMIx library is responsible
for identifying such keys and retrieving the specified
info from the corresponding default realm. If the user
wishes the key to be retrieved from a non-default realm,
then they must include the attribute specifying that realm.
(b) by passing an invalid proc rank (e.g., wildcard or undef)
and including attributes that specify the realm from which
the given key is to be retrieved along with whatever
further identification is required - e.g., PMIX_NODE_INFO
combined with the hostname of the node whose information
is being fetched.
This commit fixes both methods and provides …
> Fix retrieval of node/app/session-realm info

- config/pmix.m4
- configure.ac
- src/hwloc/pmix_hwloc.c
- src/mca/pfexec/linux/pfexec_linux.c
- src/runtime/pmix_params.c
- src/runtime/pmix_rte.h
- src/util/pmix_fd.c
[Require flex only when keyval_lex.c is not provided](https://github.com/openpmix/openpmix/commit/0d5afda8e15f9a64e0c9f22b17976b93e60b8bda)
We currently require flex whenever we are in a Git clone, but that
really isn't the requirement. We need flex whenever the flex output
files are not present - otherwise, you can build just fine. So open
things up a bit by tying the flex requirement to the actual one
(i.e., that the flex output file exist).
(cherry picked from commit https://github.com/openpmix/openpmix/commit/1286709db150ea2540f8a1d20f286a858c7a07df)
[Optimize the file descriptor cleanup on OSX](https://github.com/openpmix/openpmix/commit/a2732f805d076408c8bacc4ddd79b44683292388)
Signed-off-by: George Bosilca <bosilca@icl.utk.edu> …
> Backport updates from master/v4.2

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_utils.c
Tested on a single node, multiple clients now appear to share static
job-level information via shared-memory. We still have plenty of work
ahead, but at least it doesn't crash now. We now cache a pointer to a
full-featured gds module and pass certain operations to it.
> gds/shmem: Support multiple local clients.

- src/util/pmix_cmd_line.c
Any time we ask for help or version info, we should
return an "operation succeeded" status when done so the
caller knows we did it.
> Return "succeeded" status when outputting help/version info

- config/pmix.m4
- examples/server.c
- src/include/pmix_stdint.h
- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/base/pmix_mca_base_open.c
- src/mca/gds/shmem/pmix_hash2.c
- src/mca/psec/munge/psec_munge.c
- src/util/pmix_hash.c
- test/util/numa.c
Just to avoid committing things that fail the
enable-devel-check builds
> Enable pickyness by default in Git repo builds

- src/server/pmix_server_get.c
The get_job_data function cannot destruct the buffer being
passed to it - the caller will do so in the event of a
returned error status.
Fixes https://github.com/openpmix/openpmix/issues/2632
> Remove bad destruct call

- include/pmix_common.h.in
According to the standard, `PMIX_INFO_PROCESSED(info)` is meant to set and `PMIX_INFO_WAS_PROCESSED(info)` is meant to test the processed flag.
Signed-off-by: Stephan Krempel <krempel@par-tec.com>
> Fix PMIX_INFO_*PROCESSED macros

- src/class/pmix_list.h
Technically, the object is a "struct pmix_list_item_t*" in
the pmix_list_t definition because the actual list item
object hasn't been defined yet when we defined the list
structure. So when we access it, we should cast to the
defined object.
> Properly cast the list_item_t

- include/pmix.h
- src/common/pmix_attributes.c
- src/common/pmix_attributes.h
- src/common/pmix_strings.c
- src/mca/bfrops/base/bfrop_base_print.c
We frequently pass "const" values to functions, and this
generates warnings when passing those values to print
them. No need for that, nor for having to cast the "const"
away - the print functions never alter the provided value.
> Add "const" qualifiers to some string print APIs

- src/client/pmix_client.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/server/pmix_server.c
Some places used client instead of server base output. Eliminate
some unnecessary malloc's in print statements (more to be done).
> Cleanup some debug output

- contrib/construct_dictionary.py
- src/include/Makefile.am
Ran across some minor build issues with the OpenPMIx master when building Open MPI's main branch on an old RHEL 6 machine (with Python 2).
See the commit messages in the 2 individual commits for details.
> Minor fixes to the build process

- include/pmix_common.h.in
- src/client/pmix_client.c
- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
It is possible for a tool to receive two copies
of a "debugger-release" event - one directly from
the source and another from the server to which it
is connected. This can create a race condition that
thread-locks the tool.
Add a new PMIX_EVENT_ONESHOT attribute by which a
process can request that an event handler be atomically
deregistered once handling of that event is complete.
Thus, even if a second event is received, the event
notification system will ignore it unless the process
re-registers a handler for it.
> Stop multiple invocations of debugger-release

- include/pmix_common.h.in
Passing zero for the number of objects to create
isn't explicitly forbidden, so protect the
macros from that use-case.
Fixes #2656 
> Protect "create" macros from zero entries

- src/client/pmix_client_spawn.c
- src/common/pmix_iof.c
- src/mca/pfexec/base/base.h
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/mca/pfexec/base/pfexec_base_frame.c
We allow tools to directly fork/exec intermediate
launchers via the PMIx library, so we need to support
forwarding of any stdin for those tools to the spawned
children.
> Forward stdin to apps directly fork/exec'd by PMIx

- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/mca/ptl/base/ptl_base_fns.c
- src/server/pmix_server.c
When a tool pfexec's a server, it needs to ensure
that the server is using the same psec module as
the tool in order for the server to connect back
to its parent.
Fixes #2573 
> Coordinate psec modules across pfexec child

- examples/Makefile.am
- examples/group_lcl_cid.c
- src/client/pmix_client_get.c
- src/client/pmix_client_group.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/base/gds_base_fns.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
Porting some logic requires significant changes from
current PMIx master, so modifications had to be made
to get things right. Include the group_lcl_cid.c
example that illustrates how to use it.
> Complete implementation of group info exchange

- examples/group_lcl_cid.c
- src/mca/gds/gds.h
- src/server/pmix_server_ops.c
- src/util/pmix_name_fns.c
- src/util/pmix_name_fns.h
[Add helper macro](https://github.com/openpmix/openpmix/commit/288418b8dd2d84c47bfefd7d62b45f8caefab562)
...for checking GDS component of a peer
[Sort proc arrays to remove order sensitivity and fix multi-node grp info](https://github.com/openpmix/openpmix/commit/2496ae8a43eb433c0c11767674ab4700aff2e43d)
Remove the ordering sensitivity when doing collective operations
across arrays of procs as this is causing problems for users.
Indeed, backends are sorting the arrays given to them precisely
for this reason - so let's do it as a service to avoid future
complications.
Group info needs to be stored as "global" scope so it can be
properly retrieved.
> Add helper macro, sort proc arrays, and fix multi-node group info

- examples/group_lcl_cid.c
- src/server/pmix_server_ops.c
- src/util/pmix_name_fns.c
- src/util/pmix_name_fns.h
Remove the ordering sensitivity when doing collective operations
across arrays of procs as this is causing problems for users.
Indeed, backends are sorting the arrays given to them precisely
for this reason - so let's do it as a service to avoid future
complications.
Group info needs to be stored as "global" scope so it can be
properly retrieved.
(cherry picked from commit caf1f4336112f41f7eb0fe046714fd2b81c0ae60)
> Sort proc arrays to remove order sensitivity and fix multi-node grp info

- include/pmix_common.h.in
- src/common/pmix_iof.c
- src/include/pmix_globals.h
Formats include:
* tag => prepend `[jobid,rank]<stream>:` to output. The "jobid"
is taken as the portion of the nspace after a `@` character.
As this is not a universal standard, the "jobid" will be
replaced by the full namespace if the `@` is not found.
* tag-fullname => prepend `[nspace,rank]<stream>:` to output
* tag-detailed => prepend `[jobid,rank][hostname:pid]<stream>:` to
output. The hostname and pid will be reported as "unknown" if
not found inside the PMIx local data of the server.
Combining tag-fullname with tag-detailed is supported.
* rank => prepend `[rank]<stream>` to output
* xml => output in a pseudo-xml format. This can be combined
with tag-fullname and/or tag-detailed
> Support broader range of output formats

- NEWS
- contrib/make_dist_tarball
- src/mca/base/pmix_mca_base_var_enum.c
make_tarball needs to explicitly --enable-devel-check as it
otherwise enables picky compiler settings without the "hide"
macro and fails.
> Fix make_tarball and remove unused variable

- src/common/pmix_iof.c
(cherry picked from commit ed205380c41fbdc978f0c913266b9b9d82b4b2c5)
> Minor cleanup of timestamp output

- config/pmix_check_tm.m4
Cherry-pick from ps://github.com/openpmix/prrte/pull/1430
> Fix the tm configure logic

- src/mca/pinstalldirs/Makefile.am
- src/mca/pinstalldirs/pinstalldirs.h
- src/mca/pinstalldirs/pinstalldirs_types.h
Move the pinstalldirs struct to a new pinstalldirs_types.h
file so it can be cleanly included from PRRTE.
Refs https://github.com/openpmix/prrte/issues/1435
> Separate out pinstalldirs for inclusion by PRRTE

- config/oac_check_package.m4
- config/pmix_setup_libevent.m4
Distros are now creating a symlink between /lib and /lib64, and
between /usr/lib and /usr/lib64, in accordance with recent
agreements on file system conventions. Thus, if we detect that
the package file exists in both places, check that the two
locations are not symlinks before declaring ambiguity and
exiting with an error.
Fixes https://github.com/openpmix/openpmix/issues/2676
> Do not error out if lib is symlinked to lib64

- src/server/pmix_server_ops.c
Replacing only the nspace leaves the group rank instead of
the proc's nspace rank, so we need to replace the entire
proc entry with the grp member's ID.
> Need to replace the entire proc in fence with group member

- examples/server.c
- test/simple/gwtest.c
- test/simple/simpfabric.c
- test/simple/simpsched.c
Just need to encapsulate nspace names in pmix_nspace_t. We
already were consistent in use of char* for keys.
> Silence the gcc12 complaints

- src/client/pmix_client.c
- src/util/pmix_cmd_line.c
When running as a singleton, setup to handle any IO from spawned
children. Do not identify an ampersand as a cmd line "tail" as
this falsely implies it is an application.
> Output IO as singleton, support background commands

- .gitignore
- examples/Makefile.am
- examples/group_dmodex.c
usage.
The current algorithm in Open MPI for supporting MPI 4 Sessions support
makes use of an extended CID (communicator ID) concept.  This approach
is leading to problems supporting Sessions for PMLs that can't handle
exCID information easily.
A much simpler approach to handing the exCID exchange mechanism is
demonstrated in this PR.  By making use of PMIx dmodex feature in
combination with PMIx Group functionality, it should be much
easier to support MPI Sessions in PMLs other than OB1.
> examples: add a test to simulate open mpi PMIx group usage

- src/client/pmix_client.c
Properly destruct the IOF-related lists used when in
singleton mode.
> Cleanup singletion IOF lists

- .gitignore
- examples/Makefile.am
- examples/group_dmodex.c
- src/client/pmix_client.c
[examples: add a test to simulate open mpi group usage.](https://github.com/openpmix/openpmix/commit/c277f7f5f73d8cd8e9ee89789c2b3bbc9aed394b)
The current algorithm in Open MPI for supporting MPI 4 Sessions support
makes use of an extended CID (communicator ID) concept.  This approach
is leading to problems supporting Sessions for PMLs that can't handle
exCID information easily.
A much simpler approach to handing the exCID exchange mechanism is
demonstrated in this PR.  By making use of PMIx dmodex feature in
combination with PMIx Group functionality, it should be much
easier to support MPI Sessions in PMLs other than OB1.
(cherry picked from commit https://github.com/openpmix/openpmix/commit/e161a5ee82294b9af07100d85d0a2d2a0e6b632d) …
> Update to track master branch

- contrib/buildrpm.sh
Current code never finds home directory RPMBUILD, so
simplify it so it works.
> Fix the buildrpm script

- src/mca/plog/base/plog_base_stubs.c
- src/mca/plog/stdfd/plog_stdfd.c
- src/util/pmix_show_help.c
Don't restrict the plog/stdfd component to only work
on gateways - it needs to also support tools.
Refs https://github.com/openpmix/prrte/issues/1442
> Enable show_help output on tools

- VERSION
- contrib/buildrpm.sh
- src/mca/plog/base/plog_base_stubs.c
- src/mca/plog/stdfd/plog_stdfd.c
- src/util/pmix_show_help.c
[Fix the buildrpm script](https://github.com/openpmix/openpmix/commit/3f9ee9d3f7afa74d24a8e641de0bf8faffee3a55)
Current code never finds home directory RPMBUILD, so
simplify it so it works.
(cherry picked from commit https://github.com/openpmix/openpmix/commit/df0280b1328eaa99f578c19c32bf2315cd6c57b8)
[Enable show_help output on tools](https://github.com/openpmix/openpmix/commit/2b561432c5f196d8b83fbfbebb868b901cf87784)
Don't restrict the plog/stdfd component to only work
on gateways - it needs to also support tools.
(cherry picked from commit https://github.com/openpmix/openpmix/commit/e3b925f82d2a59f58c60c7d7a7b5a71eda7d41ae)
[Bump VERSION to …
> Updates for upcoming v4.2.1

- configure.ac
Need to include the "src" level in the path to the
keyval.c file when verifying that flex is not required
Fixes #2701
> Fix flex detection

- src/common/pmix_iof.c
Also, make sure stderr/stdout are seperated when writing
to files.
> iof: Fix merging of stderr to stdout.

- src/client/pmix_client.c
Missed a couple of spots that reference the "proc" parameter in
PMIx_Init, which is allowed to be NULL. Use a different place
to get the desired data and avoid the issue.
Thanks to @krempel-pt for the report.
Fixes https://github.com/openpmix/openpmix/issues/2707
> Fix bad dereferences when passed a NULL parameter to PMIx_Init

- include/pmix_common.h.in
- src/client/pmix_client.c
- src/common/pmix_iof.c
- src/mca/gds/hash/process_arrays.c
[iof: Fix merging of stderr to stdout.](https://github.com/openpmix/openpmix/commit/f799291e2ac274e5a7ccc56d32c26776d3a764f5)
Also, make sure stderr/stdout are seperated when writing
to files.
(cherry picked from commit https://github.com/openpmix/openpmix/commit/1491f3e92d803dbd039f8c61a25c282964895753)
[Fix bad dereferences when passed a NULL parameter to PMIx_Init](https://github.com/openpmix/openpmix/commit/45a540285d70611618ada328e869c7479c708586)
Missed a couple of spots that reference the "proc" parameter in
PMIx_Init, which is allowed to be NULL. Use a different place
to get the desired data and avoid the issue.
Thanks to @krempel-pt for the report.
(cherry picked from commit …
> Catch v4.2 up with changes from master branch

- src/mca/pnet/sshot/pnet_fabric.c
- src/mca/pnet/sshot/pnet_sshot.c
- src/mca/pnet/sshot/pnet_sshot.h
- src/mca/pnet/sshot/pnet_sshot_component.c
This solution requires the HPE VNId daemon for correct operation.
This will enable RMs on Aurora to query the VNId and retreive
a topology map for each node (including the NICs) in the system.
> Adding support for HPE sshot, usable for RMs.

- include/pmix_common.h.in
- src/mca/pnet/sshot/Makefile.am
- src/mca/pnet/sshot/configure.m4
- src/mca/pnet/sshot/help-pnet-sshot.txt
- src/mca/pnet/sshot/pnet_fabric.c
- src/mca/pnet/sshot/pnet_sshot.c
- src/mca/pnet/sshot/pnet_sshot.h
- src/mca/pnet/sshot/pnet_sshot_component.c
[Adding support for HPE sshot, usable for RMs. (](https://github.com/openpmix/openpmix/commit/7f83b5b1cb8289f227d04a12e02ce6c3089fc487)https://github.com/openpmix/openpmix/pull/2714[)](https://github.com/openpmix/openpmix/commit/7f83b5b1cb8289f227d04a12e02ce6c3089fc487)
This solution requires the HPE VNId daemon for correct operation.
Signed-off-by: Jai Dayal <jai.dayal@intel.com>
(cherry picked from commit https://github.com/openpmix/openpmix/commit/44b075f44b625040331b0eef17489c0a4ec2daf3)
[Add runtime options attribute](https://github.com/openpmix/openpmix/commit/fab0551eb717a889b57e787bccdd1f7c4b58f124)
(cherry picked from commit https://github.com/openpmix/openpmix/commit/b6c3000afb32a4baf15f4cd4b419ced7fa42040e)
> More v4.2 updates from master branch

- bindings/python/pmix.pyx
Newfound bug can result in deadlocks in the Python bindings when calling `PMIx_Register_event_handler()`. Add change to drop GIL before registering a new event handler.
> Release GIL before registering event handler

- src/mca/bfrops/base/bfrop_base_print.c
Allow the PMIx_Info_string and PMIx_Value_string functions to
successfully complete prior to calling PMIx_Init (in whatever
form).
Fixes https://github.com/openpmix/openpmix/issues/2723
> Allow printing of info and value structs prior to init

- src/mca/gds/hash/gds_fetch.c
It is okay not to find session/node/app info when searching
for it as not every namespace will have them.
(cherry picked from commit 55b0647c15d6c2c55dc6fc68e94441aa3eb4483e)
> Don't return error on not found

- EXCEPTIONS
- NEWS
- VERSION
- include/pmix_common.h.in
[Add some attributes to support job launch](https://github.com/openpmix/openpmix/commit/94f93724beb8e3ac591d26402a2515853b12c50e)
Some directives aimed at controlling runtime behavior
in support of a spawned job.
(cherry picked from commit https://github.com/openpmix/openpmix/commit/da240c502a9bf1721229dabd056a494a15ae5e07)
[Update EXCEPTIONS, NEWS, VERSION for v4.2.1rc1](https://github.com/openpmix/openpmix/commit/db778865b189bc433a8571923c6bdea914351e91)
> Prep for v4.2.1rc1

- src/mca/bfrops/base/bfrop_base_frame.c
Need to let the first pack command set the buffer type
so it gets set to that of the remote side. Otherwise,
you get an error if the other side is different than that
of the sender.
Thanks to @david-edwards-arm for reporting the problem
> Do not set the buffer type in construct

- configure.ac
Ensure they know they need flex for GitHub-generated
tarballs (but not our offical ones).
> Add some detail to warning output by flex detector

- config/pmix.m4
- include/pmix_common.h.in
- src/mca/base/help-pmix-mca-base.txt
- src/mca/base/pmix_base.h
- src/mca/base/pmix_mca_base_close.c
- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/base/pmix_mca_base_components_open.c
- src/mca/base/pmix_mca_base_components_register.c
- src/mca/base/pmix_mca_base_open.c
- src/util/pmix_cmd_line.h
to be a flexible mechanism to specify when (and when not) to emit
warnings about errors when trying to load DSO components.
Port of https://github.com/open-mpi/ompi/pull/10763
> Convert the MCA parameter "pmix_mca_base_component_show_load_errors"

- config/pmix.m4
- examples/client.c
- include/pmix_common.h.in
- src/mca/base/help-pmix-mca-base.txt
- src/mca/base/pmix_base.h
- src/mca/base/pmix_mca_base_close.c
- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/base/pmix_mca_base_components_open.c
- src/mca/base/pmix_mca_base_components_register.c
- src/mca/base/pmix_mca_base_open.c
- src/util/pmix_cmd_line.h
[Consistently use PMIx_Error_string in client example](https://github.com/openpmix/openpmix/commit/896c081deb696b505fbfc004dc38c5fdd2c94d06)
Signed-off-by: Stephan Krempel <krempel@par-tec.com>
(cherry picked from commit https://github.com/openpmix/openpmix/commit/8465992fc88cd3e0e9315da488b2bafb0941d8ce)
[Convert the MCA parameter "pmix_mca_base_component_show_load_errors"](https://github.com/openpmix/openpmix/commit/a72c896be48ff5202f25cb75e5f1a27c051a8c4b)
to be a flexible mechanism to specify when (and when not) to emit
warnings about errors when trying to load DSO components.
Port of https://github.com/open-mpi/ompi/pull/10763
(cherry picked from commit https://github.com/openpmix/openpmix/commit/6927bc40c97151163bb49c76d1f0a73318b2f6ec)
> Multiple commits

- .gitignore
Clean up left over .gitignore entry after mca/common/* removal in 4f8a4bdc
> Clean up left over .gitignore entry after mca/common/* removal

- src/client/pmix_client_get.c
- src/client/pmix_client_group.c
- src/common/pmix_iof.c
- src/include/pmix_globals.h
- src/server/pmix_server_ops.c
- src/util/pmix_hash.c
- src/util/pmix_show_help.c
Ensure we release the pmix_dstor_t object itself
Fix Coverity CID #380553
It is just debug output, but ensure we free the character
string returned by PMIx_Value_string
Fix Coverity CID #380367
Protect against possible NULL list item
Fixes Coverity CID #379775
The list item removed from the list should never be NULL,
but silence Coverity anyway.
Fixes CID #379495
Protect against possible NULL pointer, even though that
pointer really can never be NULL
Fixes Coverity CID #379233
Fix check for zero-length string
Fixes Coverity CID …
> Fix Coverity CID #378400

- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/tool/pmix_tool.c
Tools can be chained from one tool to another, eventually connecting to a server. Events passed to a tool must be propagated along the chain to ensure all targets receive them.
Thanks to @david-edwards-arm for the report.
> Ensure tools relay events to their server

- etc/pmix-mca-params.conf
- src/mca/base/help-pmix-mca-var.txt
- src/mca/base/pmix_mca_base_component_find.c
- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/base/pmix_mca_base_components_open.c
- src/mca/base/pmix_mca_base_var.c
- src/runtime/pmix_init.c
The param passed to pmix_init_util is the libdir of the caller.
> Add improved debug and correct param passing to pmix_init_util

- src/util/pmix_output.h
Needs to be visible so PRRTE can use it
> Export the output_stream_t class declaration

- src/mca/pnet/nvd/configure.m4
Add an OAC_VAR_SCOPE_PUSH to protect the temp variable and fix escaping that was causing confusion on Autoconf's part (the VAR_SCOPE_POP was outside the macro body, so screwed up any AC_REQUIREs in OAC_VAR_SCOPE_POP).
> pnet/nvd: Fix macro escaping issue

- src/util/pmix_cmd_line.h
Need to account for '-' delimiters in both
provided parameters to ensure correct identification.
> Fix the check_cli_option code

- src/mca/bfrops/base/bfrop_base_frame.c
- src/threads/thread.c
- src/tools/pmix_info/support.c
- src/util/pmix_net.c
compliance at least as far as the LLVM on which the Intel OneAPI 2022 release is based (14).  LLVM is getting pickier about what it lets through in terms of ISO C99 compliance when using -Werror, etc.
Related to https://reviews.llvm.org/D122983
Without this patch and without disabling developer flags (which is very difficult when building within spack without adding yet another variant) one gets these sorts of errors at compile time.
pmix_net.c:168:22: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
threads/thread.c:109:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes] int pmix_tsd_keys_destruct()
^
void
base/bfrop_base_frame.c:68:13: error: variable …
> llvm/oneapi: fixes to bring pmix up to iso c99

- .github/workflows/pr-target.yaml
The action checks each commit in a pull request to see if
* the committer / author do not match bad patterns ("root@", "localhost", etc.)
* a "Signed-off-by:" line exists
* a "cherry picked from" message appears, if required by config inputs (not required by default)
* if the message exists, ensure the referenced commit exists
If all commit checks pass, the action successfully completes and the action check for the PR passes. If any commit check fails, the action check fails as well. Additionally, a comment is posted to the pull request, describing which commits failed which test and suggesting the user fix them.
Signed-off-by: Joe Downs <joe@dwns.dev>
-------
-------
@rhc54 Finally got the ompi commit checker moved to [its own repo](https://github.com/open-mpi/pr-git-commit-checker) as …
> Add action to check commits on pull requests

- contrib/pmix.spec
Without BuildRequires specified, pmix cannot be built with mock.
> Updated specfile BuildRequires

- include/pmix_common.h.in
- include/pmix_deprecated.h
- src/util/pmix_cmd_line.h
- src/util/pmix_error.c
Restore a couple of deprecated status codes and add a few relevant to process fault reporting.
Fix the cmd line option parser to better support multi-word directives.
> Provide more detailed process failure codes and fix CLI parsing

- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/runtime/pmix_init_util.h
I thought we had a CI test to check this but apparently it didn't detect this break. This is work using OMPI main at 14bc2ed496
Anway, without this patch, if one uses MPI Sessions with this sequence:
MPI_Session_init
MPI_Session_finalize
MPI_Session_init
the app will flame out with this type of traceback:
Starting second init
sessions_init_twice: pmix_pointer_array.c:234: pmix_pointer_array_add: Assertion `(table->addr != NULL) && (table->size > 0)' failed. [er-head:1794920] *** Process received signal ***
[er-head:1794920] Signal: Aborted (6)
[er-head:1794920] Signal code:  (-6)
[er-head:1794920] [ 0] /lib64/libpthread.so.0(+0x12c20)[0x7ffff7476c20] [er-head:1794920] [ 1] /lib64/libc.so.6(gsignal+0x10f)[0x7ffff70d637f] [er-head:1794920] [ 2] /lib64/libc.so.6(abort+0x127)[0x7ffff70c0db5] …
> pmix reinit: a fix to allow pmix to be reinitable

- contrib/pmix.spec
- Additional requirements for el8 support
- zlib as recommended
> Additional BuildRequires in spec

- src/client/pmix_client_get.c
Ensure we release the created info array if we successfully traverse the "fastpath" in pmix_client_get
Fixes https://github.com/openpmix/openpmix/issues/2572
> Plug a memory leak

- include/pmix_common.h.in
- src/mca/bfrops/base/bfrop_base_fns.c
Few places in value_destruct released the contents of data pointed to in the pmix_value_t, but did not release the underlying allocated memory.
Thanks to @darbyShaw for pointing it out
> Fix some memory leaks and cleanup macro defns

- include/pmix_common.h.in
- src/mca/bfrops/base/bfrop_base_fns.c
[Plug a memory leak](https://github.com/openpmix/openpmix/commit/5ea3b8bb8e5528a4c9297d456f54be4fbe13081e)
Ensure we release the data array which is allocated in
pmix_bfrops_base_copy_darray.
Signed-off-by: Heena Sirwani <heena.sirwani@itwm.fraunhofer.de>
(cherry picked from commit https://github.com/openpmix/openpmix/commit/dd7af8dcb198d871e263a18fdd47d315d8a8de1a)
[Fix some memory leaks and cleanup macro defns](https://github.com/openpmix/openpmix/commit/114ccd30a6f69a54715fb9f6e00a5ad95e6abfb7)
Few places in value_destruct released the contents of data
pointed to in the pmix_value_t, but did not release the
underlying allocated memory.
Thanks to @darbyShaw for pointing it out
(cherry picked from commit …
> Plug memory leaks

- src/class/pmix_object.h
- there is potential issue in PMIX object: GCC v4.8.5 may fail to compile static initializer used in PMIX (it seems compiler issue)
- minor redesign of initializer to better fit C99 standard allows to workaround issue
compiler reports issue:
```
make[3]: Entering directory `ompi/3rd-party/openpmix/src/include'
CC       pmix_globals.lo
pmix_globals.c:65:1: error: missing initializer for field ‘tma_realloc’ of ‘pmix_tma_t’ [-Werror=missing-field-initializers]
PMIX_EXPORT pmix_lock_t pmix_global_lock = {.mutex = PMIX_MUTEX_STATIC_INIT,
^
In file included from ompi/3rd-party/openpmix/src/util/pmix_output.h:76:0,
from ompi/3rd-party/openpmix/src/include/pmix_types.h:55,
from pmix_globals.c:26:
ompi/3rd-party/openpmix/src/class/pmix_object.h:221:13: note: ‘tma_realloc’ declared here
void …
```
> PMIX_OBJ_STATIC_INIT: fixed initialization

- src/include/pmix_globals.h
- src/util/pmix_hash.c
- src/util/pmix_hash.h
Add a global one for tracking keys, and another specifically for use in the pmix_hash.c functions.
> Add some debug macros for tracking key values

- src/mca/prm/tm/prm_tm.c
Newer gcc versions warn about unused-parameter - which results in compilation errors after 93bbaed5cd86b2b0245ace56cfeb99df6be3c30c.
This fixes this by applying __pmix_attribute_unused__ to the reported code part and parameters.
> Fix compiler error from unused function parameters

- src/util/help-cli.txt
- src/util/pmix_cmd_line.c
If you provide a cmd line directive that requires
an argument, but forget to include the argument, then
output a better error message.
> Provide a little more useful error output 

- src/include/pmix_globals.h
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/process_arrays.c
- src/server/pmix_server_get.c
Store my appnum and other values in the pmix_globals struct as they arrive. Define PMIX_PSET_MEMBERSHIP as an app-level info for retrieval purposes.
> Cleanup some store/retrieve issues

- src/util/keyval/keyval_lex.h
- src/util/pmix_keyval_parse.c
The icc compiler seems to believe that an enum is not an integer, thus generating a warning. Go figure.
> Silence complaint about enum vs int

- include/pmix_server.h
- src/server/pmix_server.c
Since pset_name in PMIx_server_define_process_set() is not to be modified by the function, it should be declared as const, especially to avoid compiler warnings about discarded qualifiers.
Signed-off-by: Stephan Krempel <krempel@par-tec.com>
> Add const qualifier to pset_name

- src/mca/psec/munge/psec_munge_component.c
that the intel oneapi will not compile.
This patch allows the file to successfully compile using intel oneapi 2022 series (and probabably llvm/clang 14 or newer).
> intel oneapi: fix a munge code error

- test/test_common.h
pmix tests to compile using icx, icpx, etc.
Without this patch intel oneapi 2022 series fails to compile openpmix if tests are built.
> Intel oneapi (and probably llvm): patch to allow

- test/test_common.h
pmix tests to compile using icx, icpx, etc.
Without this patch intel oneapi 2022 series fails to compile openpmix if tests are built.
(cherry picked from commit 7381e3d4cf3eebbfe4f88e2b643780704d4acb1b)
> oneapi (and probably llvm): patch to allow

- bindings/python/pmix.pxi
The PMIx Python bindings doesn't set the pmix_app_t env parameter correctly. Bug fix to properly set this up. 
Signed-off-by: Matthew Baker <matthew@voltrondata.com>
> Have python bindings properly setup the env

- bindings/python/pmix.pyx
If `PMIX_IOF_PUSH_STDIN` is set in the info object to a call to `PMIx_IOF_Push()` than the byte object parameter can be NULL. The Python bindings will try and do an allocation anyways, and in some cases this can result in a real pointer instead of a NULL, which will cause problems. This updates the iof_push() function to allow for this behavior.
Also use `malloc()` instead of `PyMem_Malloc()`.
Signed-off-by: Matthew Baker <matthew@voltrondata.com>
> Update Python iof_push() function to take null byte object

- src/class/pmix_list.c
Fix the bug that calls to pmix_list_insert() with idx=0 will make list->pmix_list_length increase twice.
Port of https://github.com/open-mpi/ompi/pull/11059
> pmix_list: fix a bug in pmix_list_insert()

- src/common/pmix_iof.c
- src/common/pmix_iof.h
- src/mca/pfexec/base/pfexec_base_default_fns.c
- src/mca/pfexec/linux/pfexec_linux.c
- src/mca/preg/native/preg_native.c
- src/mca/psensor/file/psensor_file.c
- src/mca/psensor/heartbeat/psensor_heartbeat.c
- src/util/pmix_output.c
- src/util/pmix_output.h
- src/util/pmix_path.c
Replace the PMIX_OUTPUT_VERBOSE macro with direct
calls to pmix_output_verbose so it always compiles, even in non-debug configurations. Inline the "check_verbosity" function to minimize the performance impact of calling that function - requires changing the "info" array into a properly-prefixed global array.
Retain the PMIX_OUTPUT_VERBOSE definition so that
legacy users (e.g., PRRTE v3.0.0) are not impacted, but direct that it always be compiled "in".
> Modify the pmix_output system

- src/server/pmix_server.c
PMIx_server_define_process_set and PMIx_server_delete_process_set both currently return incorrect (or uninitialized) status codes. Correct that so they always return "success" unless there is an error.
Thanks to @krempel-pt for the report.
Fixes #2818 
> Correct return codes for two APIs

- .gitignore
- bindings/python/Makefile.am
- bindings/python/setup.py
No picky compilers down there as Cython isn't prepared to handle them. Ensure we include the target destination in PYTHONPATH as it gets tested during install to ensure the target is present. Update install classifiers.
Update ignores
> Some cleanup of the Python bindings build system

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/tests/python/client.py
- bindings/python/tests/python/sched.py
- bindings/python/tests/python/server_upcalls.py
[Some repairs to the Python bindings](https://github.com/openpmix/openpmix/commit/892bd4a01de1dc1dcf2d66193355feb6dad17df6)
Correct the function signature for the Python "query" call. Add
some protection in a couple of places for data types.
[Fix the Python tests](https://github.com/openpmix/openpmix/commit/e1693833ac4f38474630c099f3ee66ee0f0159ac)
Correct a couple of function signatures. Properly initialize the
"flags" field of a couple of pmix_info_t dicts.
Update the sched.py test
> Some fixes to the Python bindings

- config/pmix_check_os_flavors.m4
Backport of https://github.com/open-mpi/ompi/pull/11081
> Minor correction to check_os_flavors

- bindings/python/pmix.pyx
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Provide a server entry point for passing callback functions. If connection is optional, then don't ask for job info as that causes the tool to hang. Fix some indenting.
> Allow Python tool to set server module functions

- src/mca/gds/gds.h
For a strict subset of gds module function pointers, allow for the use of NULL to indicate that another module should be used instead, namely hash.
The impacted functions here are: store, assemb_kvs_req, and accept_kvs_resp.
> Allow gds function fallback to hash take II.

- src/server/pmix_server.c
Give the local client's GDS module first chance to provide the connect info, but then try the server's module if that didn't work.
> Try both peer and server storage for connect info

- include/pmix_common.h.in
Returns an array of pmix_info_t describing the nodes known to the
server. Each array element will consist of the PMIX_NODE_INFO key containing
a pmix_data_array_t of pmix_info_t - the first element of the array must be
the hostname of that node, with additional info on the node in subsequent entries.
SUPPORTED_QUALIFIER: a PMIX_ALLOC_ID qualifier indicating the specific
allocation of interest
> Add attribute to query allocation info

- include/pmix_common.h.in
When reporting the allocation, the RTE must include topology information for each node. Rather than passing the topology itself repeatedly, pass an index for the topology in an array of topologies and then include that array in the report.
> Add attribute to report index of topology in storage array

- bindings/python/construct.py
Need the extended list of attributes
> Include deprecated definitions in Python bindings

- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- include/pmix.h
- include/pmix_common.h.in
- include/pmix_server.h
- src/server/pmix_server.c
* PMIx_Session_control[_nb] provides an entry point for requesting session-related operations. Schedulers use it to direct the RTE to instantiate a session. RTE's use it to notify schedulers of session completion.
* Attributes to support the above API
* A new server module upcall function pointer for passing session control requests
* Python binding implementations for both API and upcall
> Add some scheduler integration support

- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_handshake.h
- src/mca/ptl/ptl_types.h
The ptl connection handler wasn't unpacking any provided info keys, which led to loss of info about the type of "tool" connecting to the server. Add support for the "scheduler" proc type.
> Ensure the ptl connection handler includes the provided info

- src/server/pmix_server.c
When returning the modex complete signal, always allow the GDS to access the list of participating namespaces.
> Always allow the GDS to use the namespace list

- src/server/pmix_server.c
- src/server/pmix_server_get.c
Error path in server/get released the wrong
object type.
Construction of the list of unique nspaces did
an improper comparison - need to just look at
the nspace itself.
> Fix a couple of bugs in the modex/get path

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
Fixes crashes during shared modex information access.
* Don't directly unpack connection info into a pmix_shmem_t.
* Don't overwrite shared contents in server_store_modex().
* Do improve debug output.
> Address a few issues in gds/shmem.

- include/pmix.h
- include/pmix_common.h.in
- include/pmix_deprecated.h
- src/mca/base/pmix_mca_base_components_open.c
- src/mca/bfrops/base/bfrop_base_macro_backers.c
- src/mca/gds/hash/gds_fetch.c
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/pmix_hash2.c
- src/mca/ptl/base/ptl_base_fns.c
- src/util/pmix_hash.c
Cover another group. Discovered some memory corruption where PMIX_LOAD_KEY was being passed the address of the target key instead of the target key itself.
> Checkpoint work on macro conversion to functions

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
- src/mca/gds/shmem/pmix_hash2.c
- src/mca/gds/shmem/pmix_pointer_array2.c
> Cleanup error paths in gds/shmem, silence Coverity warning.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
* Expose an MCA parameter that influences the ultimate sizes of the shared-memory segments used to back gds/shmem data.
* Emit shared-memory usage statistics during job termination when appropriate.
* Incorporate other minor modifications that happened to be captured during this work.
> Address to-do items in gds/shmem.

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
> Silence some Coverity and valgrind warnings in gds/shmem.

- include/pmix_common.h.in
- src/common/pmix_iof.c
- src/include/pmix_globals.h
- src/runtime/pmix_init.c
- src/tool/pmix_tool.c
The PMIx library catches some signals to support things like IOF (e.g., start/stop of stdin forwarding). If the host has its own libevent or libev event base and is also using that base to trap signals, then this can cause confusion - neither libevent or libev handle the case of two event bases simultaneously trapping signals. So allow the host to pass in their event base for such purposes and have PMIx use it instead of its own base.
> Add an attribute for passing an auxiliary event base

- src/mca/bfrops/base/bfrop_base_macro_backers.c
Always initialize the pmix_info_t directive flags - we will mark them as "non-persistent" by default as that historically was the behavior. Remove a duplicate "else if" entry in the data array support.
> Silence a few Coverity complaints

- bindings/python/construct.py
- bindings/python/pmix.pyx
- include/pmix_deprecated.h
- src/mca/bfrops/base/bfrop_base_macro_backers.c
Check nspace incorrectly called check key. Add a stop point in deprecated .h to avoid having the macro backers show up twice in the Python binding defs.
Fix bad variable assignment in the Python binding
for "spawn"
> Fix a typo in the macro backers and add a "stop" pt in deprecated.h

- bindings/python/Makefile.am
- bindings/python/construct.py
- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/setup.py
Use pip to do the install, modifying the setup.py
to support that model.
Thanks to Sam Gutierrez for showing how to do it.
> Silence a warning during Python binding install

- src/mca/bfrops/base/Makefile.include
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_macro_backers.c
- src/mca/bfrops/base/bfrop_base_tma.h
- src/mca/gds/shmem/gds_shmem_tma.h
This commit is the first of several that introduces a new capability into bfrops: the ability to use non-standard (or custom) heap memory managers (aka TMAs). Please note that this process is not yet complete. If I didn't make a mistake, then all PMIx infrastructure should be unaffected by these changes (even in its unfinished state).
> tma-integration: Integrate some TMA infrastructure into bfrops.

- config/pmix.m4
When Python bindings are enabled, Cython becomes a required package - so report it there instead of as a "Binding"
> Correctly identify Cython as a required package

- src/runtime/pmix_params.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Internally support timeout for purely local group operations such as construct and destruct. Track group IDs of groups that fail to complete construct so that latecomers are rejected and don't hang. Ensure we notify all prior participants so they don't hang. Add a new verbose output channel solely for server-side group operations.
> Re-implement the timeout support for purely local grp ops

- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_tma.h
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_tma.h
- src/mca/gds/shmem/pmix_hash2.c
This commit is the third of several that introduces TMA into into bfrops. Please note that this process is not yet complete.  If I didn't make a mistake, then all PMIx infrastructure should be unaffected by these changes (even in its unfinished state).
> tma-integration: Integrate more TMA infrastructure into bfrops.

- src/mca/ptl/base/ptl_base_connect.c
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/mca/ptl/base/ptl_base_fns.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
Correct some issues in the connection handshake where the singleton client case wasn't being handled. Cleanup some formatting. Silence a Coverity warning.
> Fix singleton support

- src/hwloc/pmix_hwloc_datatype.c
Prior versions of PMIx have this protection, but it was lost when converting macros to functions.
Refs https://github.com/openpmix/prrte/issues/1624
> Protect against NULL topology when destructing pmix_topology_t

- .gitignore
- examples/Makefile.am
- examples/examples.h
- examples/pset.c
- src/client/pmix_client.c
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
- src/server/pmix_server.c
Cache proc-local events at the client as those don't go up to the server and therefore cannot be cached there. All other events are cached solely at the server to avoid duplicate deliveries.
Thanks to @krempel-pt and @sonjahapp for the detailed triage report!
Refs https://github.com/openpmix/openpmix/issues/2886
> Avoid double-caching of events

- include/pmix_deprecated.h
- src/mca/bfrops/base/bfrop_base_macro_backers.c
- src/mca/bfrops/base/bfrop_base_tma.h
Just adds some missing const qualifiers to avoid meaningless compiler warnings when using `PMIx_Proc_load` with const namespace string.
> Add const qualifier to nspace strings

- bindings/python/Makefile.am
- bindings/python/requirements.txt
- bindings/python/setup.py
- Separate build vs. install: the Python bindings will now be built during "make all", and installed during "make install" (vs. being built and installed during "make install").
- Fix regression introduced in 9cd0aa4f where the Python bindings were not actually installed in $prefix.
- Update from Python distutils to setuptools.  We still use setup.py instead of the newer setup.cfg or pyproject.toml, but that can be upgraded later.
- Suppress "setup.py" deprecated warnings during the installation.
- Fix keywords listing in the Python package
- Setup dependencies properly so that the Python bindings will properly re-build if any of its dependent header files change.
- Use a workaround to make Cython work properly in VPATH builds.
- Update "make uninstall" for the Python bindings to be a bit …
> python: updates for Python bindings

- bindings/python/Makefile.am
- bindings/python/requirements.txt
- bindings/python/setup.py
- Separate build vs. install: the Python bindings will now be built during "make all", and installed during "make install" (vs. being built and installed during "make install").
- Fix regression introduced in 9cd0aa4f where the Python bindings were not actually installed in $prefix.
- Update from Python distutils to setuptools.  We still use setup.py instead of the newer setup.cfg or pyproject.toml, but that can be upgraded later.
- Suppress "setup.py" deprecated warnings during the installation.
- Fix keywords listing in the Python package
- Setup dependencies properly so that the Python bindings will properly re-build if any of its dependent header files change.
- Use a workaround to make Cython work properly in VPATH builds.
- Update "make uninstall" for the Python bindings to be a bit …
> v4.2.x: python: updates for Python bindings

- include/pmix.h
- include/pmix_common.h.in
- include/pmix_deprecated.h
- src/hwloc/pmix_hwloc.h
- src/hwloc/pmix_hwloc_datatype.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/pcompress/base/pcompress_base_frame.c
- src/mca/pcompress/pcompress.h
Add a couple of new APIs for estimating the size of data held in pmix_value_t and pmix_info_t objects:
* PMIx_Value_get_size
* PMIx_Info_get_size
Since the objective is to estimate the size of data included in nspace registration and modex operations, and such arrays are often constructed using the PMIx_Info_list_xxx APIs, provide an API to help loop over the list:
* PMIx_Info_list_get_info - returns a pointer to the info in the current object and a pointer to the next object on the list
Add another API to allow prepending a value to the list, and the PMIX_SIZE_ESTIMATE attribute for communicating the overall size of the payload.
> Provide support for estimating the size of value objects

- src/server/pmix_server_ops.c
This commit fixes a segfault in the fence operation when fencing across a proc list that contains a group followed by a namespace.
Signed-off-by: Heena Sirwani <heena.sirwani@itwm.fraunhofer.de>
> Fix segfault in fence operation with groups.

- src/client/pmix_client.c
A number of APIs now utilize the topology, and the servers generally provide us with access to it - so let's have the client always set it up.
> Initialize client topology

- src/mca/bfrops/base/bfrop_base_unpack.c
Signed-off-by: Heena Sirwani <heena.sirwani@itwm.fraunhofer.de>
> Add malloc return check in bfrops for byte object unpack.

- src/util/pmix_hash.c
PMIX_BFROPS_COPY for PMIX_VALUE allocates memory for kv->value which is already allocated by PMIX_KVAL_NEW.
Signed-off-by: darbyShaw <heena.sirwani@itwm.fraunhofer.de>
> Fix memory leak in pmix_hash_fetch.

- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/pdl/pdlopen/pdl_pdlopen_module.c
- src/server/pmix_server.c
[No need to fetch info arrays for job info](https://github.com/openpmix/openpmix/pull/2914/commits/0b1b74a75f0eacd6767cfb092453873ec51f3835)
We no longer have GDS components that do not
understand info arrays, so we don't need to
worry about providing that info to the client's
"hash" component.
> No need to fetch info arrays for job info

- src/mca/ptl/base/ptl_base_connect.c
currently, pmix_ptl_base_recv_blocking() return
PMIX_ERR_TEMP_UNAVAILABLE when recv() encounter EAGAIN or EWOULDBLOCK.
This caused client to close socket, and re-establish connection in try_connect().
The close of socket caused server to receive the SIGPIPE signal, and got aborted.
To address the issue, this patch makes pmix_ptl_base_recv_blocking() to retry recv() when it encountered EAGAIN or EWOULDBLOCK
Signed-off-by: Wei Zhang <wzam@amazon.com>
> ptl/base: retry recv() when it encounter EAGAIN or EWOULDBLOCK

- VERSION
- config/pmix_mca.m4
- configure.ac
- src/mca/base/pmix_mca_base_component_find.c
- src/mca/base/pmix_mca_base_component_repository.c
- src/mca/common/dstore/Makefile.am
- src/mca/common/dstore/dstore_base.c
- src/mca/gds/ds12/Makefile.am
- src/mca/gds/ds12/gds_ds12_base.c
- src/mca/gds/ds21/Makefile.am
- src/mca/gds/ds21/gds_ds21_base.c
- src/mca/pdl/pdlopen/pdl_pdlopen_module.c
- src/mca/plog/default/plog_default.h
- src/mca/psec/none/psec_none.h
- src/server/pmix_server.c
The dstore components lacked some required entry points that caused the daemons to segfault. Also, correct the peer used to fetch info arrays when the client isn't using the "hash" GDS component.
> Fix some backport issues

- src/mca/ptl/base/ptl_base_connect.c
currently, pmix_ptl_base_recv_blocking() return
PMIX_ERR_TEMP_UNAVAILABLE when recv() encounter EAGAIN or EWOULDBLOCK.
This caused client to close socket, and re-establish connection in try_connect().
The close of socket caused server to receive the SIGPIPE signal, and got aborted.
To address the issue, this patch makes pmix_ptl_base_recv_blocking() to retry recv() when it encountered EAGAIN or EWOULDBLOCK
Signed-off-by: Wei Zhang <wzam@amazon.com>
(cherry picked from commit 58db08671fc3507b057bd0401837a5f2698e33b1)
> [v3.2] ptl/base: retry recv() when it encounter EAGAIN or EWOULDBLOCK

- src/mca/ptl/base/ptl_base_connect.c
currently, pmix_ptl_base_recv_blocking() return
PMIX_ERR_TEMP_UNAVAILABLE when recv() encounter EAGAIN or EWOULDBLOCK.
This caused client to close socket, and re-establish connection in try_connect().
The close of socket caused server to receive the SIGPIPE signal, and got aborted.
To address the issue, this patch makes pmix_ptl_base_recv_blocking() to retry recv() when it encountered EAGAIN or EWOULDBLOCK
Signed-off-by: Wei Zhang <wzam@amazon.com>
(cherry picked from commit 58db08671fc3507b057bd0401837a5f2698e33b1)
> [v4.2] ptl/base: retry recv() when it encounter EAGAIN or EWOULDBLOCK

- config/pmix.m4
OpenPMIX does not support 32-bit environments, so make configure fail early.
Signed-off-by: Joe Downs <joe@dwns.dev>
> configure: abort in 32-bit environments

- config/pmix_mca.m4
The library must be named pmix_mca_xxx in order
for the MCA system to pick it up.
> Fix static common library installs

- src/mca/base/pmix_base.h
- src/mca/base/pmix_mca_base_component_find.c
- src/mca/base/pmix_mca_base_open.c
If a specified component (i.e., PMIX_MCA_foo=a,b,c) cannot be found or refuses to load, provide an MCA param to indicate that we should error out. Otherwise, ignore the situation (reporting it if show_load_errors is set) - the framework itself will abort if none of the components are available.
(cherry picked from commit 4012cc8dbfec92662a7be96a1b9fe249d5d76f57)
> Add option to abort on component find failure

- src/util/pmix_shmem.c
Avoid potential for multiple reference decrements from a single attachment site in shmem_destruct() if pmix_shmem_segment_detach() was called beforehand.
> Avoid multiple reference decrements in pmix_shmem.

- src/util/pmix_getid.c
Deal with the case where multiple definitions
are not present.
Fixes #2932 
> Hide unused params

- config/pmix.m4
- src/include/pmix_config_bottom.h
Turn the "sentinel" attribute checking off when
under a Solaris environment to avoid some
oddities.
> Disable the "sentinel" attribute in Solaris

- src/include/pmix_config_bottom.h
According to the docs, this is the one that would
trigger complaints about NULL pointers in va_args, even though the error talks about the "sentinel"
attribute. Might as well swat them both.
> Turn off the "format" attribute on Solaris

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/mca/gds/shmem/gds_shmem_utils.c
- src/mca/gds/shmem/gds_shmem_utils.h
IBM's CI found an issue with how we were storing job and session data in shared-memory. This commit checkpoints our work toward fixing that issue. I still need to cleanup some code, but my initial tests look promising. The solution here that appears to work requires that session data be stored in distinct shared-memory segments.
> gds:shmem Decouple session and job data.

- src/server/pmix_server_ops.c
Fix an unitialized variable by initializing it to zero.
> Initialize the storage size

- include/pmix_common.h.in
- src/mca/bfrops/base/bfrop_base_fns.c
- src/server/pmix_server_ops.c
Include the size of the pmix_value_t itself and
the hash table struct that holds it. Also add in
the number of keys that were included in the
payload.
> Extend size computation

- src/mca/gds/shmem/gds_shmem.h
It looks like gds/shmem still needs some work, so disable it for now.
> Disable gds/shmem by default.

- src/util/pmix_hash.c
The two are tightly coupled, so let's use the same verbosity in the two code areas.
> Use the GDS verbosity in the util/hash functions

- src/event/pmix_event_notification.c
> Don't get evhdlr name unless we know it is valid.

- src/tool/pmix_tool.c
Move the release to after rte_finalize as it might be used.
Fixes https://github.com/openpmix/prrte/issues/1667
> Move release of pmix_client_globals.myserver to later

- src/class/pmix_object.h
- src/mca/gds/shmem/gds_shmem.c
Return NULL if TMA allocation request would extend past shared-memory backing store boundary.
> gds/shmem: Return NULL if TMA allocation should fail.

- config/pmix.m4
This reverts commit 8e0225280bd032948287ef0fa3e732370d0e2817.
We have at least one volunteer wishing to work on resolving the 32-bit support, so make it available.
> Revert "configure: abort in 32-bit environments"

- docs/exceptions.rst
- include/pmix_common.h.in
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
No longer required - ditto for PMIX_NUM_KEYS
> Remove the PMIX_SIZE_ESTIMATE attribute

- docs/exceptions.rst
- include/pmix_common.h.in
- src/mca/gds/ds12/gds_ds12_base.c
- src/mca/gds/ds21/gds_ds21_base.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_hash.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
[Remove the PMIX_SIZE_ESTIMATE attribute](https://github.com/openpmix/openpmix/commit/236e80a2d046f2e2d252994a0f09e9c04f52c98a)
No longer required - ditto for PMIX_NUM_KEYS
(cherry picked from commit https://github.com/openpmix/openpmix/commit/3b9d91d7f0e424982b0939556b5ef82f153a2ac9)
[Remove GDS "set_size" entry points](https://github.com/openpmix/openpmix/commit/4950351fcf5ba22ac79685ec56d62ad18b1e59ea)
(cherry picked from commit https://github.com/openpmix/openpmix/commit/ea531ef552395474bc32144db7fd17f0f52fa37b)
> Remove support for PMIX_SIZE_ESTIMATE

- docs/requirements.txt
Crossport of https://github.com/open-mpi/ompi/pull/11395
(cherry picked from commit eed8592eeca7a299a16b9adb943456dd2102ee0f)
> Update sphinx requirements

- src/util/pmix_cmd_line.c
Trivial case of `prterun app` - need to completely jump out of the getopt loop or else it will run
to the end and report no executable.
Refs https://github.com/open-mpi/ompi/issues/11402
> Handle the case where prterun is given no options

- src/util/pmix_shmem.c
If the shared-memory reference count reaches zero in the pmix_shmem_segment_detach() path, then also unlink the backing file.
> Add missing unlink in pmix_shmem_segment_detach().

- src/util/pmix_cmd_line.c
Used as separator between cmd directives
and application.
Fixes #2980 
> Skip a double-dash on cmd line

- src/util/pmix_cmd_line.c
Do the special casing _after_ we process the known single-dash options so we don't mistakenly ignore
them. We only want to ensure that we don't generate an incorrect "unknown option" error and exit out
of the cli parser when necessary.
> Fix processing of single dash cmd line options

- src/hwloc/pmix_hwloc_datatype.c
- src/mca/bfrops/base/bfrop_base_tma.h
A straightforward PMIx_Init() then PMIx_Finalize() program running on my computer is now Valgrind memcheck clean.
> Plug memory leak.

- src/client/pmix_client.c
- src/mca/base/pmix_mca_base_close.c
- src/runtime/pmix_finalize.c
A straightforward looping program over PMIx_Init(), PMIx_Fence(), and PMIx_Finalize() running on my computer is now Valgrind memcheck clean.
> Plug memory leaks in reinit paths.

- include/pmix_deprecated.h
- src/mca/bfrops/base/bfrop_base_tma.h
Convert the majority of PMIX_*_FREE() macros by moving (or adding) the frees into the underlying function calls. Also NULLify the incoming pointers after freeing the base pointers where appropriate.
More to come, but the marked FIXME locations need more thought.
> Convert the majority of PMIX_*_FREE() macros.

- src/mca/gds/hash/configure.m4
- src/mca/gds/shmem/configure.m4
gds/shmem relies on large virtual address spaces, so disable its use when on a 32-bit system. Also add a configure.m4 to the hash component for configure summary consistency, but hash is unconditionally enabled.
> Disable gds/shmem support on 32-bit architectures.

- src/util/pmix_show_help.c
It is being passed a pmix_shift_caddy_t, not a pmix_query_caddy_t
> Correct cbdata type in pmix_show_help callback function

- include/pmix_deprecated.h
- src/include/pmix_globals.h
- src/mca/bfrops/base/bfrop_base_macro_backers.c
- src/mca/bfrops/base/bfrop_base_tma.h
- src/mca/plog/base/plog_base_stubs.c
Begin cleanup of code style violations. Fix the way we perform bit checks for pmix_info_t directives - now that we have multiple bits being set at a time, we need to correctly ensure we are testing only the bit of immediate interest.
Restore the pmix_argv_xxx function definitions so codes using prior PMIx versions can still find them when compiling.
> Cleanup code style, fix bit checks, and fix backward compatibility

- src/client/pmix_client_get.c
Ensure we use the gds/hash component as the dstore components just hang when searching for globally
unique keys.
Thanks to @JiakunYan for the report and reproducer
Fixes #3006 
> Fix fetch of globally unique keys

- src/client/pmix_client_ops.h
- src/common/pmix_query.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/tool/pmix_tool.c
If a server executes a call to PMIx_Query_info, then we do not want that call to circle back into a request for its host to provide the info as that can lead
to a deadlock. Mark a tool as being a server if it registers a server module.
> Fix loop in query by a server

- src/mca/gds/shmem/configure.m4
The shmem mechanism is not supported on Mac, so no point in building the component.
> Disable gds/shmem component on Mac

- src/client/pmix_client.c
- src/client/pmix_client_get.c
- src/client/pmix_client_group.c
- src/client/pmix_client_ops.h
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/tool/pmix_tool.c
The following commit adds support for PMIx_Get operations on groups for realm (node, process) attributes that depend on the process rank. The support is only for PMIx reserved keys and for groups constructed with embedded barriers.
> Add initial support for PMIx_Get operations on groups.

- examples/group.c
- src/client/Makefile.include
- src/client/pmix_client_convert.c
- src/client/pmix_client_get.c
- src/client/pmix_client_group.c
- src/client/pmix_client_ops.h
- src/event/pmix_event_notification.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
It is possible that the group membership may have been altered during group_construct - e.g., if one or more participants adds members that are not visible to all. Ensure we pass back the actual final membership, and use that to define the group in the client's storage
> Return final group membership to client

- include/pmix.h
- src/common/pmix_strings.c
- src/util/pmix_name_fns.c
We have several special rank values defined in PMIx (e.g., PMIX_RANK_INVALID). Help users in their
print statements by providing a new "pretty-print" function for printing out pmix_proc_t structures
that includes recognizing the special rank values.
> Add pretty-print proc name API

- src/util/pmix_cmd_line.c
Reordering some parsing reintroduced problems with cmds that have no options and cmd lines that
use a '--' to indicate end of options. Plug those
corner cases.
> Fix a few corner cases in the cmd line parser

- src/util/pmix_if.c
- src/util/pmix_if.h
Remove unused functions. Attempt to resolve complaint about "reading 1 or more bytes from a region of size 0" by restricting the string comparison to the length of the fixed field.
Thanks to @tonycurtis for the report and help with the fix!
Fixes #3026
> Attempt to resolve gcc13 complaint

- include/pmix_deprecated.h
PMIX_TOPOLOGY_FREE() doesn close the while loop. Fixed.
> PMIX: Fix compile error in macro

- src/client/pmix_client.c
- src/client/pmix_client_fabric.c
- src/client/pmix_client_get.c
- src/client/pmix_client_spawn.c
- src/client/pmix_client_topology.c
- src/server/pmix_server_ops.c
Tools may register server module function pointers to allow them to handle certain requests. The Python bindings are an example were the pointers can be registered, even though the host tool doesn't support them. Ensure that tools only use those pointers for requests that come up to them from clients, and don't call themselves back for those operations.
> Ensure tools send requests to their server

- src/server/pmix_server_ops.c
Just in case different participants pass the array in a different order.
> Sort the procs for a fence operation

- src/mca/gds/shmem/.pmix_unignore
Appears to be causing a process to exit with zero status under certain (currently unclear) conditions during PMIx_Init.
> Disable GDS shmem component

- src/server/pmix_server.c
Silence the following static analysis warning generated by UBSan:
server/pmix_server.c:3528:5: runtime error: applying zero offset to null pointer
> Silence UBSan warning.

- src/include/Makefile.am
- src/include/pmix_stdatomic.h
- src/mca/ptl/base/base.h
- src/runtime/pmix_progress_threads.c
Use atomic types approach seen in PRRTE: use _Atomic when available.
> Silence TSan data race warnings.

- src/event/pmix_event_registration.c
If the event needs to be registered and the tool is connected, then the tool needs to send the registration to its server.
> Ensure tools always send their event registration to their servers

- configure.ac
Avoid having to explicitly include it in an autoreconf line.
> Include the OAC subdir in the autoconf make directories

- src/client/pmix_client.c
- src/hwloc/pmix_hwloc.c
Ensure the topology is available to singletons. Properly handle the cpuset case for unbound procs.
> Handle the case of unbound proc. Also ensure topology is available

- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem.h
- src/util/pmix_shmem.c
- src/util/pmix_shmem.h
...or at least try! This commit attempts to address failing client-side attachments caused by an eager unlinking of shared-memory backing files.
We also unignore gds/shmem to resume broader CI testing.
> Improve shared-memory reference counting.

- src/mca/gds/shmem/configure.m4
- src/util/pmix_shmem.c
gds/shmem's use of pmix_shmem currently requires C11 atomics for reference counting. Disqualify gds/shmem if C11 atomics are not available. Also update how we implement reference counting in anticipation of future modifications (e.g., explicit memory barriers).
> Disqualify gds/shmem if C11 atomics are not available.

- config/pmix_config_asm.m4
- src/include/pmix_atomic.h
- src/include/pmix_stdatomic.h
- src/mca/gds/shmem/configure.m4
- src/util/pmix_shmem.c
This commit contains the following updates:
* Update pmix_config_asm to more closely match Open MPI's opal_config_asm (modified from ompi @ f6674c0).
* Include some 32-bit __atomic_fetch_* and __atomic_*_fetch operations They are provided under the names pmix_atomic_fetch_*_32() and pmix_atomic_*_fetch_32().
* Update pmix_shmem reference counting to use newly added atomic fetch functions. The tests I conducted on some PPC and Intel machines with GCC and XL looked promising.
* Remove gds/shmem disqualification if C11 atomics are not available.
> Update asm config, shmem ref counting, atomic ops.

- src/client/pmix_client.c
The pmix_init_result variable contains the correct return status, so use it.
> Return the correct status from PMIx_Init

- src/include/pmix_atomic.h
- src/util/pmix_shmem.c
Define pmix atomic ops for c11 atomics
Previously these ops were only available when using GCC atomics, but now
they can be used when C11 atomics are selected.
> Define pmix atomic ops for c11 atomics

- src/mca/bfrops/base/bfrop_base_macro_backers.c
Macros had their frees removed in favor of putting the free in the PMIx function behind them. Maintain consistency with master branch by adding the frees to the backing functions.
> Add missing frees

- include/pmix_common.h.in
- src/mca/bfrops/base/bfrop_base_tma.h
Now that we have moved all those "static inline" functions in pmix_common.h into APIs, there is no longer a reason for the "extern char **environ" being in that file and it generates warnings in some environments.
> Remove environ from public header

- test/simple/Makefile.am
The simptest.h file in the test/simple directory
was missing from the tarball. This fix involves
no change in library source code - it is strictly
a change to a Makefile in the test area.
> Fix missing "simptest.h" file

- src/client/pmix_client.c
- test/simple/simptool.c
Destruct the list and not just the list object during client finalize. Simptool test should use PMIx_tool_finalize instead of client finalize.
> Fix a couple of typos

- .github/workflows/main.yml
Update Github-provided actions to newer versions. This will squelch warnings that we get about using outdated Node.js versions.
> v4.0: .github/workflows: update actions versions

- config/pmix_setup_hwloc.m4
We currently only support HWLOC v1.11-2.x, so
error out during configure if something higher
is provided.
> Protect against HWLOC v3 and above

- src/util/pmix_string_copy.c
- src/util/pmix_string_copy.h
We have been copying a "getline" utility across
both PMIx and PRRTE. Centralize it.
> Expose pmix_getline utility

- src/common/pmix_query.c
- src/tools/pquery/help-pquery.txt
- src/tools/pquery/pquery.c
Cleanup the help output. Ensure proper return of results when query is locally resolved. Allow pquery to run as tool, but sometimes unconnected if a server isn't available.
> Fix bitrot in pquery tool

- include/pmix.h
- src/tools/pevent/help-pevent.txt
- src/tools/pevent/pevent.c
- src/tools/pquery/pquery.c
- src/util/pmix_error.c
Add a new PMIx_Error_code that takes the string name of an error/event and returns the corresponding integer code. Utilize it in the pevent tool, and change the cmd line of that tool to support better server specification and for ease of use.
> Add new API and cleanup pevent tool

- docs/conf.py
Allow to override build date with `SOURCE_DATE_EPOCH` to make builds reproducible.
See https://reproducible-builds.org/ for why this is good and https://reproducible-builds.org/specs/source-date-epoch/ for the definition of this variable.
Without this patch, I got variations in our `openmpi5` package:
```diff
+++ new//usr/lib64/mpi/gcc/openmpi5/share/doc/pmix/html/developers/frameworks.html      2023-07-25 00:00:00.000000000 +0000
@@ -109,7 +109,7 @@
– most services and functionality are implemented through MCA
components.</p>
<p>Here is a list of all the component frameworks in PMIx as of
-this writing August-2023:</p>
+this writing September-2039:</p>
```
This patch was done while working on reproducible builds for openSUSE.
Signed-off-by: Bernhard M. Wiedemann bwiedemann suse de
> Allow to override build date with SOURCE_DATE_EPOCH

- config/pmix.m4
Disable the unused param check when not enabling the developer picky compiler setting. If not specifically requested, then disable the developer picky compiler setting unless (a) we are in a git repo, and (b) we enable debug.
> Enable building of tarball

- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/ptl_types.h
The "select" function has an inherent limitation on the number of file descriptors that can be open at any given time. In some environments, this can cause problems - so switch to using the event library for harvesting client-server connection requests.
Note: we were directly using "select" to avoid dropped connections due to an incoming connection flood at large scale. This was copied from an "mpirun" implementation. PMIx, however, doesn't have that flood problem - at most, one might see a few hundred local clients attempting to connect at the same time. Probably not an issue, but worth remembering.
> Switch to using event lib for connections

- contrib/construct_dictionary.py
- include/pmix_common.h.in
- src/hwloc/pmix_hwloc.c
- src/mca/ptl/ptl_types.h
- src/server/pmix_server.c
Identify the server acting as the system-wide controller and provide an attribute by which the scheduler can request to be connected to it.
> Define a new server type and connection flags

- src/server/pmix_server.c
This reverts commit 2c9c66a29271605027597ab737fedb32b6e087ea.
> Revert "Temp fix - disable gds/shmem component"

- bindings/python/pmix.pyx
- src/mca/pdl/pdlopen/configure.m4
- src/mca/pdl/plibltdl/configure.m4
We provide a backdoor way to disable dlopen, but
then ignored the option. Simplify the name of the
option a little bit.
> Minor cleanups for disable-dlopen

- config/pmix.m4
- examples/pset.c
- include/pmix.h
- include/pmix_common.h.in
- src/server/pmix_server_get.c
- src/tools/Makefile.include
- src/tools/pctrl/Makefile.am
- src/tools/pctrl/help-pctrl.txt
- src/tools/pctrl/pctrl.c
- src/util/pmix_cmd_line.h
Pset memberships are tracked in the server, so
check for such a request and process it there.
Thanks to @sonjahapp for the report.
Fixes #3140
> Retrieve pset names upon PMIx_Get request

- src/util/pmix_pty.c
- src/util/pmix_shmem.c
There is a potential issue with allowing a "chown" operation to follow user-created links, so let's limit any use of that function to "lchown" - which directs the "chown" operation to NOT follow a link.
> Do not follow links when doing "chown"

- src/hwloc/pmix_hwloc.c
See https://github.com/open-mpi/ompi/issues/10025
for an explanation of the problem.
Thanks to @bgoglin for the assistance.
> Blacklist the HWLOC GL component to avoid deadlock

- src/mca/gds/base/gds_base_fns.c
Lack of modex info doesn't represent an error, so silently proceed with the job.
Refs https://github.com/open-mpi/ompi/issues/11964
> Remove spurious "error log"

- .github/workflows/builds.yaml
- autogen.pl
- config/pmix_setup_hwloc.m4
- config/pmix_setup_libevent.m4
- src/hwloc/pmix_hwloc_datatype.c
We have two dependent libraries we care about, and minimum version requirements on both of them. Let's connect them to the min values in the VERSION file and "standardize" the check configure code to make it easier to understand and maintain.
Also, since we require a min HWLOC version of 1.11, there is no longer a need to check for at least 1.8 so we know we have hwloc_topology_dup.
> Make checking min versions consistent

- src/util/help-cli.txt
- src/util/pmix_cmd_line.c
Fix shadow variable use of loop counter. Fix incorrect format in help file (should be '%c' instead of '%s')
> Fix couple of bugs in cmd line parser

- include/pmix_common.h.in
- src/tools/palloc/palloc.c
Fix cmd line option declarations to match shorts list. Add event registration to allow termination upon loss of server.
Add support for "do not wait"
> Cleanups for palloc tool

- include/pmix.h
- include/pmix_common.h.in
- include/pmix_server.h
- src/common/pmix_query.c
- src/include/pmix_globals.h
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Provide a means for apps to define blocks of resources for use in allocation and spawn requests. Support modification and deletion of the blocks, as well as queries to discover named blocks and their contents.
Include query for minimum allocatable unit as some systems define a default resource block.
> Add support for blocks of resources

- src/util/pmix_cmd_line.c
Use correct loop index to store found result
> Fix typo in cmd line processor

- include/pmix_common.h.in
Instead of having individual attributes to specify a connection target and others to specify an order for each target, just have an attribute that allows one to specify an ordered list of targets.
> Add a new attribute to specify connection order

- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_connect.c
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_listener.c
- src/mca/ptl/base/ptl_base_sendrecv.c
- src/runtime/pmix_init.c
- src/runtime/pmix_init_util.h
- src/tools/palloc/help-palloc.txt
- src/tools/palloc/palloc.c
- src/tools/pattrs/help-pattrs.txt
- src/tools/pattrs/pattrs.c
- src/tools/pctrl/help-pctrl.txt
- src/tools/pctrl/pctrl.c
- src/tools/pevent/help-pevent.txt
- src/tools/pevent/pevent.c
- src/tools/plookup/help-plookup.txt
- src/tools/plookup/plookup.c
- src/tools/pquery/help-pquery.txt
- src/tools/pquery/pquery.c
- src/util/pmix_cmd_line.h
Rather than trying to define specific attributes for "first" vs
any other connection order, use an attribute that takes a comma-delimited
list of connection directives to process the order in which
server connections are to be attempted by tools.
Ensure that all PMIx tools include a "--pmixmca foo bar" cmd line option to set MCA params.
> Implement attribute to specify connection order and process MCA params 

- config/pmix.m4
PMIx has never supported 32-bit environments,
so let's not allow them to configure.
> Error out of attempts for 32-bit builds

- include/pmix.h
- include/pmix_common.h.in
- src/common/pmix_strings.c
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_cmp.c
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/bfrops/v51/bfrop_pmix51.c
Fill in all the pack/unpack/print/copy support for pmix_resource_block_directive_t.
> Implement data type support for resource blocks

- src/util/pmix_hash.c
- src/util/pmix_hash.h
This commit provides two new internal functions that allow callers to specify a target key index: pmix_hash_register_key_in_keyindex() and pmix_hash_lookup_key_in_keyindex(). The behavior of pmix_hash_register_key() and pmix_hash_lookup_key() remain unchanged.
> hash: Add internal APIs that specify target key index.

- src/common/pmix_attributes.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/gds/hash/gds_fetch.c
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/gds_hash_component.c
- src/mca/gds/hash/gds_utils.c
- src/mca/gds/shmem/gds_shmem.c
- src/mca/gds/shmem/gds_shmem_fetch.c
- src/mca/gds/shmem/gds_shmem_store.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/server/pmix_server_ops.c
- src/util/pmix_hash.c
- src/util/pmix_hash.h
Update all pmix_hash functions to include an extra parameter: a pmix_keyindex_t *. This provides the ability to have hash lookups across different key/index translation tables, not just pmix_globals.keyindex.
Provide a new pmix_keyindex_t data type that eases the embedding of key/index structures into shared-memory.
Remove all internal pmix_hash APIs of the form pmix_hash_*in_keyindex in favor of the new form provided here.
Note: this work is slated for use in gds/shmem. Specifically, we are aiming to fix a potential issue that may arise when using gds/shmem when key/index values differ between server and client versions.
> hash: Update pmix_hash functions to accept a pmix_keyindex_t*.

- src/mca/gds/shmem/gds_shmem.c
In tma_realloc(), provide an error message describing the current limitations of the gds/shmem's TMA and a solution.
> gds/shmem: Improve error message in tma_realloc().

- src/common/pmix_alloc.c
- src/common/pmix_control.c
- src/common/pmix_session.c
- src/common/pmix_strings.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_connect.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Relay to the server where available. Server passes requests to its host where appropriate, returning
response to requestor.
Fix a bug in ptl_base_connect
> Implement the allocate, resource block, and session control support

- include/pmix_common.h.in
- src/server/pmix_server.c
Define a new attribute for specifying the min
allocatable unit and communicating it to the
PMIx server. This makes it available to apps
via query.
> Initial support for min allocatable unit

- include/pmix.h
- include/pmix_common.h.in
- include/pmix_deprecated.h
- include/pmix_server.h
- src/common/pmix_alloc.c
- src/common/pmix_strings.c
- src/include/pmix_globals.h
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_cmp.c
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_fns.c
- src/mca/bfrops/base/bfrop_base_macro_backers.c
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_print.c
- src/mca/bfrops/base/bfrop_base_stubs.c
- src/mca/bfrops/base/bfrop_base_tma.h
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/bfrops/v51/bfrop_pmix51.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
When describing the resource units to be included
in a resource block, we really need a struct to
contain the description. We can't use pmix_device_t as that describes a specific device - instead, we need a device type and number, the scheduler will assign the specific device(s) later.
Change the signature of the "resource block" APIs to include an array of resource units. Update the data type handlers to accommodate it.
> Intro the pmix_resource_unit_t struct

- include/pmix_common.h.in
- src/common/pmix_strings.c
Resource units have device types, not data type field. Add a couple of missing device types.
> Fix incorrect print string

- src/util/pmix_cmd_line.c
Need to add everything after the double-dash to the results tail.
> Fix handling of "--" in cmd lines

- src/client/pmix_client_get.c
- src/server/pmix_server_ops.c
- src/util/pmix_hash.c
- test/simple/doubleget.c
If we are using the gds/shmem component, then modex data will automatically refreshed upon receipt. However, if we are using the gds/hash component, then the server "holds" the updated data until the client specifically requests it.
> Fully implement refresh cache support

- src/server/pmix_server.c
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- test/simple/doubleget.c
Correctly retrieve updated "put" keys. In this release series, the mechanism for executing "refresh" is done by direct modex, which while inefficient does at least retrieve the data. In order for it to work with refresh, we have to pass the key to the remove daemon so it can specifically retrieve it.
Not sure why the updated data isn't included in the "fence" that is being executed after the values have been changed. Nor why the insertion of a "group construct" call before updating the values should have any impact on the operation as the two are completely orthogonal.
However, I do note that simply disabling the dstore resolves all observed problems. So I suspect we are again running up against the limitations of that subsystem.
Note: this change requires a corresponding change on the …
> Resolve a problem with updated "put" key-value pairs

- src/mca/preg/native/preg_native_component.c
- src/mca/preg/raw/preg_raw_component.c
Pick the "raw" component over the "native" one if zlib isn't available. While it is unusual, there are cases where "native" seems to have problems with randomized lists of hostnames. Since those cases almost always involve small numbers of nodes, just default to the "raw" listing.
> Adjust preg component priorities

- src/mca/base/pmix_mca_base_var.c
- src/util/pmix_context_fns.c
- src/util/pmix_os_dirpath.c
- src/util/pmix_path.c
Instead of calling "stat" on a location and then
performing an operation (e.g., doing 'mkdir' after 'stat' says the path doesn't exit), jut try to
perform the operation and deal with the error.
> Begin work on removing use of "stat"

- src/common/pmix_alloc.c
If we are not the system controller, but are connected to a scheduler, then send it to the scheduler.
> Avoid loopbacks in alloc op in non-system controller daemons

- src/client/pmix_client_get.c
Use PMIX_RELEASE() instead of PMIX_DESTRUCT() for pmix_cb_t data allocated on the heap.
> Address accidental use of PMIX_DESTRUCT.

- src/include/pmix_globals.c
- src/runtime/pmix_init.c
Code cleanup: move pmix_pointer_array_init to pmix_keyindex_t constructor, as suggested in a recent review of code that allowed pmix_hash functions to accept a pmix_keyindex_t*.
See discussion in #3190 for more details.
> Move pmix_pointer_array_init to pmix_keyindex_t constructor.

- src/client/pmix_client_get.c
Don't require a NULL procID parameter to retrieve
the PMIx library version
> Retrieve version regardless of proc ID

- docs/news/news-v4.x.rst
- src/runtime/pmix_init.c
Need to give tools that use PMIx a chance to parse their cmd lines and push params into the environment before we register them.
(cherry picked from commit ebb60d9b974f47f6252df2148b1631141c7af0e6)
> Delay registering top-level MCA params

- src/tools/palloc/palloc.c
Need to shift the call to pmix_init_util so we ensure that the help directories get set.
> Ensure palloc gets setup correctly

- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_connect.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/client/ptl_client.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Regardless of which one (system controller or scheduler) is started first, enable the auto-connection of the pair when requested. Ensure we don't hang waiting for a connection file to appear if the host specifies that the connection is optional.
> Enable auto-connect of sys ctrlr and scheduler

- src/client/pmix_client_get.c
Need to return success instead of succeeded
> Fix backport issue in client get

- src/util/help-pmix-util.txt
- src/util/pmix_os_dirpath.c
Just respond to the unlink error.
> Remove stat call when destroying a dirpath

- src/server/pmix_server_get.c
There occurs a problem in the following situation:
1. Job A uses PMIx_Spawn with the PMIX_ADD_HOST option to spawn Job B on some added nodes
2. A process from Job B (running on an added node) requests job level data of Job A (i.e. using PMIX_RANK_WILDCARD in PMIx_Get)
This leads to a crash of the PRRTE daemon hosting the requesting process from Job B.
The root of this problem is a loopback in resolve_nspace_requests:
- As the PMIx servers on the added nodes do not host any processes from Job A, the namespace of Job A is not yet registered when processes from job B request the job level data.
- The request is then forwarded to PRRTE which registers the namespace of Job A in the direct_modex host function
- The PMIx_register_nspace implementation calls resolve_nspace_requests to resolve any …
> avoid loopback in resolve_nspace_requests when using PMIX_ADD_HOST

- src/hwloc/pmix_hwloc.c
Ensure that the cpuset bitmap field isn't left
pointing to free'd memory.
> Assign NULL to free'd pointer

- include/pmix.h
- include/pmix_version.h.in
Add some capability flags to PMIx.  This will allow PMIx clients to do build-time checking to see if the PMIx they are building with have specific capabiltiies or not (without having to rely on version range checking).
This commit adds 3 silly/demo capabilities, and should be edited before merging.
Additionally, it would be good to expose these capability flags at run time as well (perhaps as an uint64_t -- or even a variable-length array of unsigned bytes -- so that there are plenty of bits available for future expansion).  This is an exercise left for the reader.
> pmix.h: Add capability flags

- src/mca/ptl/base/ptl_base_frame.c
- src/server/pmix_server.c
- src/util/pmix_cmd_line.h
- src/util/pmix_os_dirpath.c
Ensure os_dirpath_destroy protects the system tmpdir from removal.
> Do not remove the system tmpdir during cleanup

- src/mca/ptl/base/ptl_base_connect.c
- src/tools/palloc/help-palloc.txt
- src/tools/palloc/palloc.c
Add the system controller to the list of connection candidates for palloc. Allow launchers to default
to picking up the local session daemon.
> Cleanup palloc and prun connections

- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_connect.c
- src/mca/ptl/base/ptl_base_fns.c
- src/util/pmix_os_dirpath.c
Remove debug output. Correctly use our own peer
(instead of the one passed to us) when constructing a connection handshake message.
> Cleanup a few typos and remove debug output

- include/pmix_deprecated.h
When we made the transition from macros to functions, we were forced to move things that went on the left side of an `=` sign to being addresses of params to the function call. Compilers are getting increasinly picky about matching parameter types, so cast a few that might cause trouble.
Refs https://github.com/open-mpi/ompi/issues/12169
> Cast a few parameters when translating macros to functions

- config/pmix.m4
If we are going to use the "git" command to check if we are in a git repo build, then first check that the cmd is available.
> Check for presence of git before using it in configure

- config/pmix.m4
This reverts commit 374aa0e1ece60f7b7585c682e509ec1519ff16d5.
Revert "Use git describe on a known PMIx commit sha instead of checking for .git directory"
This reverts commit 58126b8ea7c5e4c530b6b7e1d768a3dc71f24580.
> Revert "Check for presence of git before using it in configure"

- config/pmix.m4
- src/util/pmix_path.c
- src/util/pmix_path.h
Use new algorithm based on code provided by @bosilca to minimize impact on the file system. Detect identified shared file system types, reporting that the provided directory is on such a system.
> Restore support for detecting shared file systems

- src/util/pmix_os_dirpath.c
Linux doesn't follow POSIX when trying to "unlink" a directory - it returns a different "errno" value. Cover that case.
> Properly handle directories during cleanup

- src/mca/gds/shmem/gds_shmem.c
Since we maintain our own arena for the gds/shmem TMA, don't be so pedantic in tma_free(). Namely, do nothing in tma_free().
> gds/shmem: revert tma_free() strategy.

- src/mca/gds/shmem/gds_shmem.c
Fix potentially confusing error output by setting errno before calling perror().
> gds/shmem: fix potentially confusing error output.

- src/util/pmix_os_dirpath.c
- src/util/pmix_path.c
If the directory entry is itself a directory, make an immediate attempt to remove it. If it isn't empty and we are recursively removing things, then recurse downward.
When checking for network file systems, ensure that we provide a string for the fstype if we don't have the necessary support to detect fs types.
> Touchup the dirpath_destroy code

- include/pmix_common.h.in
Allow someone to query the number of slots available in a given session. Note that this is purely a point-in-time measurement as jobs may be working there way thru the state machine for mapping, and more jobs may be
submitted at any moment.
> Add a query attribute for number of available slots

- .gitignore
- src/client/pmix_client.c
- src/server/pmix_server.c
- src/server/pmix_server_get.c
- test/simple/Makefile.am
- test/simple/legacy.c
Users are allowed to request a key using
PMIX_RANK_UNDEF _if_ the key is globally
unique. In order to do this, the gds/hash
component in the client needs to know how
many procs are in the job, and we need to
return the requested data from the server
to the client so it can be found since
the dstore cannot handle undefined ranks.
Thanks to @RaymondMichael for the report.
Fixes https://github.com/openpmix/openpmix/issues/3259
> Fix "get" of key with undefined rank

- src/server/pmix_server.c
When dstore is available, the server is not breaking apart job info arrays when caching the job registration. Thus, the hash component may not have the job size - so check the other gds component if not found in hash.
Refs #3259 
> Fix one more spot for "get" from rank undefined

- .gitignore
- src/server/pmix_server_get.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- test/simple/Makefile.am
- test/simple/legacy.c
When caching get requests at the server level, we need to track what key they were asking about. When a proc later commits data, check outstanding requests to see if it arrived - this includes a check of any request for rank=PMIX_RANK_UNDEF since it could be a global key that was committed.
> Better support global keys

- src/common/pmix_query.c
there was a path through pmix_parse_localquery that ended up doing a PMIX_RELEASE on the caddy, but soon thereafter it was re-relesed in PMIx_Query_info, causing a
PMIx_Query_info: Assertion `PMIX_OBJ_MAGIC_ID == _obj->obj_magic_id' failed.
for this case.
Related to https://github.com/open-mpi/ompi/pull/12217 Related to https://github.com/open-mpi/ompi/pull/10886
> PMIx_Query_info: removed duplicated PMIX_RELEASE

- config/pmix.m4
- test/simple/legacy.c
Don't know how it happened, but let's restore the default to enable-devel-check when building in Git clones. Protect some unused params in a test program.
> Restore default to enable-devel-check in Git repos

- src/mca/base/pmix_mca_base_var.c
If someone defines the PMIX_MCA_mca_base_param_files or the PMIX_MCA_mca_base_override_param_file envar as NULL (i.e., they specify the envar "name=" with no value), then the envar will be found but have a NULL value. Current code doesn't protect against that contingency, so fix it.
> Protect against empty envar definition for mca_base_param_files

- test/simple/gwtest.c
- test/simple/quietclient.c
- test/simple/simpclient.c
- test/simple/simpcoord.c
- test/simple/simpcycle.c
- test/simple/simpdmodex.c
- test/simple/simptest.c
- test/simple/stability.c
Newer compilers don't accept the void cast of asprintf's return value, so address those sites in test code.
> Fix test builds with picky compiler options.

- docs/conf.py
Python no longer accepts escape sequences in the
regex - need to use raw strings.
> Update the Python regex for doc build

- src/mca/gds/shmem/gds_shmem.h
- src/mca/gds/shmem/gds_shmem_component.c
Still working on resolving the shmem xversion issue, but we need to release a new v5.0 version. So for now, let's just disable the component at runtime, thus allowing someone to work with it minus needing to recompile.
> Disable gds/shmem at runtime

- src/common/pmix_attributes.c
This commit is part of the current cross-version work. To avoid potential issues with how we are approaching a solution in gds/shmem, we consult pmix_globals.keyindex instead of pmix_dictionary for attribute lookup.
> Update how PMIx attributes are looked up.

- src/common/pmix_attributes.c
Break out of the lookup loops when we pass the end of table element occupancy.
> Improve PMIx attribute lookup efficiency.

- docs/Makefile.am
- docs/how-things-work/index.rst
- docs/how-things-work/schedulers/index.rst
- docs/how-things-work/schedulers/overview.rst
- include/pmix_common.h.in
Add new docs explaining how PMIx handles scheduler integration - still a work-in-progress. Add a few attributes indicating that an allocation and/or job is to be independent of its parent.
> Add scheduler integration "how-things-work" docs and few attributes

- src/mca/ptl/base/ptl_base_frame.c
- src/util/pmix_os_dirpath.c
We protect any file in the session directory tree
whose name starts with "output-" so as to preserve diagnostic output.
> Protect output files during cleanup

- src/hwloc/pmix_hwloc.c
- test/simple/simpdist.c
Ancient HWLOC does not provide version information, so we have to protect some areas against missing definitions.
> Restore support for HWLOC truly ancient

- src/mca/gds/shmem2/gds_shmem2.c
- src/mca/gds/shmem2/gds_shmem2_utils.h
- src/util/pmix_hash.c
Additionally, address some minor formatting issues and amend a comment regarding TMA's use in pmix_hash.
> gds/shmem2: provide a useful error message on memory allocation failure.

- config/pmix.m4
Update oac submodule pointer to pick up a stronger test for Sphinx. Also add (new) optional 3rd param to OAC_SETUP_SPHINX.
Refs https://github.com/open-mpi/ompi/issues/12333
> oac: strengthen Sphinx check

- .gitignore
- docs/Makefile.am
- docs/how-things-work/index.rst
- docs/how-things-work/sets_groups/index.rst
- docs/how-things-work/sets_groups/overview.rst
- docs/how-things-work/sets_groups/psets.rst
- examples/Makefile.am
- examples/asyncgroup.c
- examples/group_bootstrap.c
- include/pmix_common.h.in
- src/client/pmix_client_convert.c
- src/client/pmix_client_fence.c
- src/client/pmix_client_group.c
- src/include/pmix_globals.h
- src/server/Makefile.include
- src/server/pmix_server_group.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Sometimes participants wanting to form a group
have limited knowledge of their co-participants.
For example, two procs may know that they "lead"
their respective subgroups, but may not know the
members of the other "leaders" subgroup. In this
case, we need to let the two procs that know about their subgroups tell us what they know, and let
the other procs simply join the collection.
All we really require is that everyone know the
groupID for the group they are trying to form, and that each leader know how many leaders are going to participate. We can use events under-the-covers to notify non-leaders of the group formation.
This is a collaborative change with PRRTE.
>  Extend group operations to support bootstrap

- src/util/pmix_cmd_line.c
Handle the case of "tool foo -opt" - i.e., where
the executable immediately follows the tool name.
> Adjust cmd line processor for special case

- include/pmix_common.h.in
- src/client/pmix_client_group.c
- src/event/pmix_event_notification.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/server/pmix_server_group.c
Ensure that everyone gets the job-level info, including all add-member participants. Add a couple of attributes to help with that operation. Generate the event for add-member participants from the PMIx server instead of the host.
> Provide job-level info to all group construct members

- docs/developers/autogen.rst
- docs/installing-pmix/quickstart.rst
The installation docs didn't mention that PMIx now incorporates a submodule. Add appropriate words
about that so people realize they need to initialize the submodule before trying to build a Git clone.
> Include notes about submodules in docs

- include/pmix_common.h.in
- src/include/pmix_globals.h
- src/server/pmix_server.c
- src/server/pmix_server_group.c
- src/server/pmix_server_ops.c
Ensure we remove clients from the local client array when deregistered, and that all clients get cleaned up when the nspace is deregistered as some people may not have deregistered clients prior to the nspace.
Do not reuse the "hybrid" field of the tracker to track the group operation as it is used for other purposes and should not be overwritten. Add a new PMIX_GROUP_NONE operation tag for initializing the new tracker field - put it at the end of the enum to avoid causing errors with existing users.
> More cleanup of group operations and local client array

- src/server/pmix_server_group.c
Fix one more place where the "hybrid" field was used in the tracker. Ensure we cleanup the "nspaces" argv array.
> Few minor cleanups

- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_copy.c
- src/mca/bfrops/base/bfrop_base_tma.h
- src/server/pmix_server_ops.c
The loop to identify unique nspaces was unfortunately incorrect, thus resulting in not storing modex info that was needed, and sometimes duplicating storage for other nspaces. Ensure we provide the data only once for every nspace involved in the group.
(cherry picked from commit ce7a58fd423c706852f305ad3609b0786bfc9531)
> Correct group modex storage to avoid duplication

- autogen.pl
- docs/news/news-v5.x.rst
Based off of https://github.com/open-mpi/ompi/pull/12406. Modified to cover the case where the submodule's ".git" file exists, but the directory is actually unpopulated. Admittedly a "borked" installation, but surprisingly does happen.
(cherry picked from commit 528b4bc19febe3d2d58341042f664045adcbec39)
> Toughen the submodule checks in autogen.pl

- src/client/pmix_client_spawn.c
If the cmd provided to spawn doesn't match
argv0, then assume that the user may have put the argv for their cmd in the argv array, but not
started with the actual cmd - so add it
to the front of the array
> Don't overwrite user's args

- .gitignore
- examples/Makefile.am
- examples/client.c
- examples/client3.c
- src/client/pmix_client_get.c
- src/mca/gds/hash/gds_hash.c
Per the Standard, PMIx_Get of node and app info
is to ignore the procID argument. Ensure that we
correctly do so. Add a minor test in the client
example.
Thanks to Hessam Mirsadeghi for pointing it out.
> Correct error in retrieval of node and app info

- examples/dynamic.c
- examples/group_lcl_cid.c
- include/pmix.h
- src/client/pmix_client_group.c
- src/common/pmix_strings.c
- src/server/pmix_server_group.c
- src/server/pmix_server_ops.c
Group operations that are purely local go thru an
optimized path, but still need to return the
right set of info so the client can correctly
track the group.
Add a function to pretty-print the group operation.
Ensure that we get the communications between server and client correct so that all examples work.
> Fix local group operations and cleanup to pass all examples.

- src/client/pmix_client_group.c
- src/include/pmix_globals.c
PR 3329 introduced a regression which causes Open MPI's MPI_Intercomm_from_groups method to fail.
Related to https://github.com/open-mpi/ompi/pull/12449
> fixes for pr 3329

- src/util/pmix_net.c
We almost never encounter it, so this error has gone undetected for quite some time. When the system lacks a sockaddr structure, we have to provide a "no-op" function. What remains unclear is how that can compile when the function parameters include a sockaddr structure - but that mystery will have to remain unsolved.
> Fix function declaration

- src/client/pmix_client.c
Don't try to save the server URL if we are operating as a singleton since we won't have one.
> Fix singletons

- src/util/pmix_basename.c
Modify pmix_basename to handle single character filenames.
Ported from comment by @ggouaillardet in https://github.com/open-mpi/ompi/issues/12619
> Handle single character filenames

- src/util/pmix_cmd_line.c
We had problems in the past with quoted params, but stripping quotes also has consequences - not clear of the best solution. For now, let's try going the other way and see how many problems we encounter.
> Don't strip quotes from cmd line entries

- .github/workflows/builds.yaml
Fix the issues with the MacOS builds so that they work again in Github Action environments.
Port of https://github.com/openpmix/prrte/commit/4a682ef670d2582ffda2e990428446138f7c10d7
> Github action: bring back MacOS builds

- src/client/pmix_client.c
- src/mca/bfrops/base/bfrop_base_cmp.c
- src/mca/bfrops/base/bfrop_base_print.c
Protect a couple of places from NULL fields in pmix_proc_info_t
(cherry picked from commit 2a7d9e13dc4e88a661e42a633ff25f5898f20401)
[Fix singletons](https://github.com/openpmix/openpmix/pull/3363/commits/5599f9fcf059d9ba787a03e1117eddabe90745df)
Don't try to save the server URL if we are operating
as a singleton since we won't have one.
(cherry picked from commit 930d4bc5af1cbf7a2674ed51a88984c299824eea)
> Protect against NULL fields

- src/client/pmix_client_pub.c
If a host returns partial success on PMIx_Lookup, then we still need to transfer the results to the user's array for return.
Thanks to @dgloe-hpe for the report and triage!
Fixes #3364
> Transfer results from partial success of lookup

- .github/actions/mlnx/Dockerfile
- .github/actions/mlnx/entrypoint.sh
- docs/conf.py
- src/client/pmix_client_spawn.c
When applying a specified prefix, apply the change to the copy of the incoming app array and not the incoming array elements themselves in case they were statically defined.
Thanks to @dgloe-hpe for the report!
Fixes #3370
> Apply prefix to copied version of the app array

- docs/requirements.txt
Getting into an odd situation where Sphinx is spewing errors and warnings due to deprecated packages. Try to find a path to something workable - somewhat frustrating as the Sphinx site admits to the problems, but basically saids they don't care, just poke around until you find a "good" combination.
> Update the requirements for Sphinx

- src/mca/gds/shmem2/configure.m4
Some code which was only valid using GNU bash was included. Detected in Gentoo packaging via:
```
* QA Notice: Abnormal configure code
*
* ./configure: 40936: test: 0: unexpected operator
```
Bash provides the standard `test XXX = YYY` or `[ XXX = YYY ]` utilities. It also provides the ability to spell the equals sign as a double equals. This does nothing whatsoever -- it adds no new functionality to bash, it forbids nothing, it is *literally* an exact alias.
It should never be used under any circumstances. All developers must immediately forget that it exists. Using it is non-portable and does not work in /bin/sh scripts such as configure scripts, and it results in dangerous muscle memory when used in bash scripts because it makes people unthinkingly use the double equals even in /bin/sh …
> configure: fix broken bashisms resulting in logic failure

- contrib/make_dist_tarball
Building a tarball on MacOSX results in a
tarball that includes undesirable artifacts
when unpacked on Linux systems. We therefore
do not support this operation by default
Include an override path by passing --macosx on the cmd line
Fixes https://github.com/openpmix/openpmix/issues/3376
> Warn against building tarball on MacOSX

- docs/requirements.txt
Installing anaconda confused the system and led to the problems. Uninstalling it resolved things and
we can therefore fall back to letting Python deal
with selecting the right combination of versions.
> Revert Sphinx requirements

- config/pmix.m4
- config/pmix_check_cflags.m4
We currently do not support the LTO optimizer
as it is incompatible with our plugin component
architecture. So detect it has been specified
in configure and error out with an explanation.
> Protect against LTO optimizer

- src/mca/pmdl/base/pmdl_base_stubs.c
The length of the framework names match as well
as the characters - must check both to ensure we
correctly only match complete string name
Refs https://github.com/open-mpi/ompi/issues/12682
> Correctly check MCA params

- src/client/pmix_client_spawn.c
- src/mca/pfexec/Makefile.am
- src/mca/pfexec/base/base.h
- src/mca/pfexec/base/pfexec_base_frame.c
- src/mca/pfexec/linux/pfexec_linux.c
- src/mca/pfexec/pfexec.h
- src/mca/pfexec/pfexec_types.h
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
Ensure we don't release the created app array copy prior to processing it. Do a much better job of
memory cleanup as we were leaking like a sieve.
Ensure we properly process any IOF directives
associated with the local fork/exec operation.
Refs #3390
> Cleanup pfexec spawn operations

- src/mca/pif/linux_ipv6/configure.m4
This typo causes linux_ipv6 module to be skipped during configure. It has been replaced with the OAC equivalent.
Bug was introduced in https://github.com/openpmix/openpmix/pull/2946
Need to backport to v5.0
> mca/pif: fix pmix_found_linux typo

- src/include/pmix_config_bottom.h
Configure test for pmix_argv.h fails when pmix_config_bottom.h tries to include pmix_printf.h as it is missing part of its relative path
Thanks to @ksalerno99 for the patch!
Refs https://github.com/open-mpi/ompi/issues/12814
> Path must start with "src"

- config/pmix.m4
- config/pmix_mca.m4
- src/mca/pcompress/zlib/configure.m4
- src/mca/pcompress/zlibng/Makefile.am
- src/mca/pcompress/zlibng/compress_zlibng.c
- src/mca/pcompress/zlibng/compress_zlibng.h
- src/mca/pcompress/zlibng/compress_zlibng_component.c
- src/mca/pcompress/zlibng/configure.m4
- src/mca/pcompress/zlibng/owner.txt
People have created a "next-gen" version of libz that contains some enhancements and performance improvements based on features available in newer chipsets. If we see it present and/or are directed to it, preferentially use it over the traditional libz.
Fixes #3351
> Add support for libz-ng

- .github/workflows/builds.yaml
- VERSION
- config/pmix_setup_hwloc.m4
- src/hwloc/pmix_hwloc.c
- src/hwloc/pmix_hwloc.h
- test/util/Makefile.am
We no longer support all the way to pre-StoneAge
versions.
> Raise min required HWLOC version to 2.1.0

- src/client/pmix_client_get.c
When we already have a get request pending with the server, add the new request to the pending list and just return
Fixes https://github.com/openpmix/openpmix/issues/3406
> Fix delayed get

- include/pmix_common.h.in
Part of a separate commit for scheduler integration, these attributes have value beyond just that use.
> Add some missing attributes

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_sendrecv.c
The current ptl implementation assigns dynamic tags for sendrecvs using a single, global cur_tag counter from the range [PMIX_PTL_TAG_DYNAMIC, UINT32_MAX].
This can lead to collisions, e.g., when a tool acts simultaneously as a server.
The solution proposed in this pull request uses a per-peer counter and range for the current tag to be used for sendrecvs to this peer.
The range of valid tags for a particular peer is either [PMIX_PTL_TAG_DYNAMIC, (UINT32_MAX - PMIX_PTL_TAG_DYNAMIC)/2] when we first connected to the peer and  [(UINT32_MAX - PMIX_PTL_TAG_DYNAMIC)/2, UINT32_MAX] if the peer connected to us.
> ptl support for connection to multiple servers

- src/client/pmix_client_spawn.c
- src/common/pmix_iof.c
- src/common/pmix_iof.h
- src/common/pmix_pfexec.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/runtime/pmix_init.c
- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
When a tool starts a launcher and the launcher cmd line includes IO formatting requests, we want the tool to receive relayed output in the specified format. So ensure that formatting directives for a spawned job are not only applied to the direct output of the launcher, but also to all output forwarded to a requestor.
Fixes https://github.com/openpmix/openpmix/issues/3405
> Ensure IOF respects formatting requests

- bindings/python/construct.py
- bindings/python/pmix.pxi
- bindings/python/pmix.pyx
- bindings/python/tests/python/sched.py
- bindings/python/tests/python/server.py
- bindings/python/tests/python/server_upcalls.py
The definition of the server function pointers in the python bindings are defined as blocking functions.
This has some limitations in certain scenarios.
This pull request adds support for non-blocking server functions in the Python bindings:
- Adds the paramters **cbfunc** and **cbdata** to the server function definitions, where
**cbfunc**: is one of the following callables:
+pypmix_op_cbfunc_t              =   Callable[[int, dict], int]
+pypmix_info_cbfunc_t            =   Callable[[int, list, dict], int]
+pypmix_modex_cbfunc_t           =   Callable[[int, bytearray, dict], int]
+pypmix_lookup_cbfunc_t          =   Callable[[int, list, dict], int]
+pypmix_spawn_cbfunc_t           =   Callable[[int, str, dict], int]
+pypmix_tool_connection_cbfunc_t =   Callable[[int, dict, dict], None] …
> support for non-blocking server funcs + small fixes in python bindings

- src/event/pmix_event.h
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
The current implementation does not support tools registering event_handlers at different servers.
This is because the `_add_hdlr` in pmix_event_registration.c does not call `_send_to_server` if there was already a handler registered for the same code.
This pull request stores a pointer to the currently active server peer in the `pmix_active_code_t` struct when adding it to the list of active events. 
In subsequent registrations, the current server peer is compared against the peer stored in the active event to ensure `_send_to_server` is called if the tool switched to another server. 
Unfortunately, we cannot use a pmix_peer_t pointer here, as the peer struct is defined in pmix_globals.h:
```
/* define an object for tracking status codes we are actively registered to receive */
typedef …
```
> support event registration at multiple  servers

- src/mca/bfrops/base/Makefile.include
- src/mca/bfrops/base/base.h
- src/mca/bfrops/base/bfrop_base_pack.c
- src/mca/bfrops/base/bfrop_base_squash.c
- src/mca/bfrops/base/bfrop_base_unpack.c
- src/mca/bfrops/v21/bfrop_pmix21.c
- src/mca/bfrops/v3/bfrop_pmix3.c
- src/mca/bfrops/v4/bfrop_pmix4.c
- src/mca/bfrops/v41/bfrop_pmix41.c
- src/mca/bfrops/v51/bfrop_pmix51.c
Unfortunately, the implementation of the "psquash" framework violated the PMIx design rules - and was not caught at the time it was released. The code _assumes_ that both sides of the communication are using the same psquash component, which is definitely not guaranteed.
I've tried several remedies, but nothing is particularly satisfying. Adding the psquash active component to the connection handshake doesn't solve the backward compatibility issue and just further complicates an already complex operation. Simply defaulting to always using either psquash component breaks backward compatibility as prior releases will continue to dynamically select the active one.
Given the default settings in that framework, the least breakage results from defaulting to using the "squashed" component. Not …
> Reverse the default "squash" setting

- bindings/python/pmix.pyx
- examples/spawn_group.c
[Silence Cython warning](https://github.com/openpmix/openpmix/commit/ae47c349f61860ca24d7781c4893c348388b67d6)
Consistent performance warning about the need to always take
the gil if allowing exceptions to be generated by these
two functions since they don't return a value.
[Silence warnings](https://github.com/openpmix/openpmix/commit/1d2ae55cd5467e7b2ddbde44e6b6a1b583f35601)
> Silence some warnings

- src/client/pmix_client.c
- src/server/pmix_server_get.c
When calling PMIx_Resolve_peers, the client may not be able to find the job-level info for the specified nspace. In this case, it requests the info from the server. The server's copy of the info is sometimes stored as rank=UNDEF, but can also be stored as rank=WILDCARD (depending on the server's version). So the client has to check both rank values to ensure the data is found.
Fortunately, it only requires one exchange with the server regardless of which rank is being used.
> Fix resolve peers for other nspaces

- src/client/pmix_client_get.c
If a request was made with rank=UNDEF, then retry the search with rank=WILDCARD since the server may have returned the data under that rank (depending upon version).
> Retry fetch with wildcard rank

- .gitignore
The file "configure~" is generated when building OpenPMIx as part of Open MPI.  This causes an annoying git submodule "untracked content" notification.  So let's just add "configure~" to .gitignore so that it's properly ignored by git / git submodules.
> .gitignore: add configure~

- examples/asyncgroup.c
- src/event/pmix_event_notification.c
- src/event/pmix_event_registration.c
We need to catch the "group complete" event so we can add the group and its membership to the client's list of known groups. This enables the client to then reference the group for operations like "fence" instead of the individual procs.
> Fix the asyncgroup example

- docs/how-things-work/sets_groups/group_construct.rst
- examples/group_bootstrap.c
- src/class/pmix_list.h
- src/client/pmix_client_convert.c
- src/client/pmix_client_group.c
- src/server/pmix_server.c
- src/server/pmix_server_group.c
- test/group/run.sh
In some scenarios, a limited number of group members will know the processIDs of other group members - but some group members will not. In this case, we want to still construct a group from all the members, but cannot execute it with every member calling PMIx_Group_construct and passing a complete array of participants.
So reduce the constraints by allowing a "leader" to call group construct and pass (a) its own process ID as the sole entry in the "procs" array; (b) the number of "leaders" that will be participating; and (c) an optional attribute identifying additional processIDs for procs that want to join the group, but don't know anything about it beyond the group ID.
All "additional members" must call PMIx_Group_construct with the group ID and a NULL entry for the procs array.
Upon …
> Complete implementation of group construct "bootstrap"

- examples/resolve.c
> Correct exec name in example

- .github/workflows/prrte.yaml
- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_listener.c
- src/util/help-pmix-util.txt
- src/util/pmix_os_dirpath.c
We made some changes to the os_dirpath_create code a while back to resolve some of the "test-before-use" warnings and other things. However, this opened a hole in the logic of the PTL code that used it. Specifically, we weakened the connection between when a file and directory were being created by the tool itself, and when those things already existed. So we could inadvertently stomp on files.
Do a better job of tracking precisely which directories and files are being created by a given process...and then ONLY remove those that were created by it.
> Repair the file removal code

- src/server/pmix_server.c
- src/server/pmix_server_group.c
- src/server/pmix_server_ops.h
Simplify the code by removing the local completion optimization - it isn't clear that is a good thing to do anyway. The host still needs to know about it, and probably needs global knowledge of the group's existence, so it isn't clear that it was even feasible/good to do.
Remove some other cruft. Also, group proc array doesn't have to be in any particular order, which means we cannot require that all participants provide the array in the _same_ order.
> Debug group operations

- src/server/pmix_server_group.c
Need to aggregate the procs from the various participants and include those in the upcall to the server. Since bootstrap results in multiple "block" trackers for the same ID being put on the collective tracking list, be sure to scan the list for matches so everyone gets notified.
> Cleanup the server's group ops a bit

- docs/how-things-work/index.rst
- docs/how-things-work/resolve.rst
- examples/resolve.c
- src/client/pmix_client.c
- src/client/pmix_client_get.c
- src/mca/gds/hash/gds_fetch.c
- src/mca/gds/shmem2/gds_shmem2_fetch.c
We return an error (e.g., "not found") if the nspace or node are not found. However, if they _are_ found but there are no peers from that nspace on the specified node, then return "success" (instead of "not found") with NULL for the array of peers.
Add a docs page that walks thru the "resolve" procedure and explains the various return status codes.
> Modify the return from PMIx_Resolve_peers for clarity

- src/mca/ptl/base/ptl_base_fns.c
Need to construct the lock prior to using and then destructing it. No idea how that line got lost as we have traversed that code path many, many times in the past.
Thanks to @dgloe-hpe for the report and triage!
Refs #3504
> Add missing lock construct

- src/mca/ptl/base/help-ptl-base.txt
- src/mca/ptl/base/ptl_base_fns.c
When the specified server rendezvous file cannot be accessed, provide a nicer error message and reason.
> Provide a better error message to user

- src/mca/pmdl/ompi/pmdl_ompi_component.c
In SSH environment's app procs need to find the OMPI library, and so we need OPAL_PREFIX to be in their environment.
This avoids having to explicitely set OPAL_PREFIX with -x in OMPI.
> Add OPAL_* in the list of default envars

- src/mca/pmdl/ompi/pmdl_ompi_component.c
Signed-off-by: Tomislav Janjusic <tomislavj@nvidia.com>
(cherry picked from commit 1eb98ce241c13ec29d563b742f6f661fee0f304b)
> v5.0: Add OPAL_* in the list of default envars

- src/mca/pmdl/ompi/pmdl_ompi_component.c
Signed-off-by: Tomislav Janjusic <tomislavj@nvidia.com>
(cherry picked from commit 1eb98ce241c13ec29d563b742f6f661fee0f304b)
> v6.0: Add OPAL_* in the list of default envars

- src/mca/gds/shmem2/gds_shmem2_store.c
The shmem2 component incorrectly restricted use of data arrays to PMIx predefined keys. Anyone can pass a data array with a custom key - we just treat it as any other key. The hash component did this correctly, so there is a workaround - make the shmem2 component do it too.
> Allow arbitrary keys to use data arrays

- src/client/pmix_client_get.c
- src/mca/gds/hash/gds_fetch.c
- src/mca/gds/shmem2/gds_shmem2_fetch.c
- src/server/pmix_server_get.c
If a proc (e.g., a tool) wants to fetch a piece of job-level data for a namespace other than their own, then it is likely that the proc won't already have a copy of that data. If they have done a PMIx_Connect or PMIx_Group_construct operation that included the other namespace, then they should have it - but otherwise, they likely don't. This is normally the case for tools, as an example.
Ensure we flow the request up to the server for processing. Given that it is job-level info (i.e., it is a request for a reserved key), then we only want to flow thru the fetch process once. If it is found, then no need to search further in other scopes - if it isn't found in the initial "internal" scope, then it definitely won't be found on some other scope.
> Enable fetch of job-level data for another nspace

- include/pmix_common.h.in
- src/mca/bfrops/base/bfrop_base_tma.h
There apparently are some circumstances when an application can benefit from disabling the internal GPU support in one or more of its libraries. Let's assume that a library might also provide a mechanism by which that support can be defaulted to enabled or disabled.
Add a spawn attribute by which a user/launcher can specify whether to enable of disable such support. Also extend the "info true" utility to accept a broader range of common entries for designating "true" or "false".
Refs https://github.com/openpmix/prrte/pull/2134
> Add attribute to direct app library's GPU support

- src/tools/pctrl/pctrl.c
Update the "pctrl" tool so it correctly exits with zero status when asked for "help" or "version".
Thanks to @heylinn for the report!
> Exit with correct status after displaying help or version

- examples/abi_with_init.c
- examples/examples.h
- src/common/pmix_attributes.c
- src/common/pmix_attributes.h
- src/common/pmix_query.c
- src/server/pmix_server_ops.c
Resolve the hang in the blocking query API. Strip out the
unnecessary code. Cache results as we go so we don't lose
initial results when we go to the server and/or the host.
> Revamp the query implementation

- examples/toolqry.c
- src/mca/gds/gds.h
- src/mca/gds/hash/gds_fetch.c
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/gds_hash.h
- src/mca/gds/hash/process_arrays.c
- src/mca/gds/shmem2/gds_shmem2_fetch.c
- src/mca/gds/shmem2/gds_shmem2_fetch.h
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/mca/ptl/base/ptl_base_stubs.c
When a client asks the server for information, the server must format the response to match the PMIx version employed by the client. We were incorrectly formatting the response on the basis of the version declared by the process whose data was being requested - as opposed to the version of the _requestor_.
In the case of tools, this led to an incorrectly formatted response, particularly for node-level data where earlier PMIx versions didn't support the node-info array.
Looking at this also exposed that the client's version was defaulting to 0.0.0, and would remain that way if the client application did not call PMIx_Init. Needed to adjust the macro that checks for PMIx version level to deal with non-PMIx clients.
> Fix format of fetch response for peer's version

- examples/pub2.c
Ensure the two procs are off-cycle so that we get the data server to "hold" a lookup request pending receipt of the corresponding publish.
> Slight mod to the pub2 example

- src/server/pmix_server.c
- src/server/pmix_server_ops.c
- src/server/pmix_server_ops.h
- src/server/pmix_server_resolve.c
If the host supports the "query" upcall interface, they will return SUCCESS to mean that they are servicing the request. It does not mean that they will understand the key(s) being passed to them - in which case, they will issue the callback with some status other than SUCCESS.
Should that happen, we still want the server to attempt to resolve the request to the best of its ability. So provide a mechanism by which the server gets a second shot at providing the answer.
> Further cleanup of "resolve" functions

- examples/abi_with_init.c
- examples/client.c
- src/common/pmix_query.c
- src/mca/ptl/base/ptl_base_fns.c
When executed as a singleton, we automatically search for available connections, just like a tool would do. However, if they are not found, we should not emit an error message if we were not specifically directed to find one - e.g., a system-level server.
Also fix the query operation to return any partial results it was able to find when operating as
a singleton.
Fixes https://github.com/open-mpi/ompi/issues/13114
> Silence error output when running as singleton

- .github/workflows/prrte.yaml
- examples/pubstress.c
Check that we correctly unpublish data for given
persistence levels. Add the pubstress test to
the CI.
> Extend the pubstress test and add it to CI

- config/pmix.m4
- config/pmix_check_cflags.m4
Rather than exiting configure with an error, print a warning
if lto-based directives are detected and ignore those flags.
This may help resolve rpm problems.
> Just ignore any lto settings

- src/mca/gds/shmem2/gds_shmem2.c
- src/util/help-pmix-util.txt
- src/util/pmix_shmem.c
If someone mistakenly provides an incorrect path for the directory where we will be storing the shmem backing file (e.g., pass a relative directory and then change the working directory), then we segfault in shmem2 because of a stale job object in the tracking system. So ensure we cleanup the job object when that happens so we can cleanly fallover to "hash".
Remove a bunch of error logs when this happens since we are not going to fail, but instead continue running. Add some debug output to report which file was attempted to be opened.
Fixes #3560
> Fix segfault on error in shmem2

- src/mca/pinstalldirs/runtime/Makefile.am
- src/mca/pinstalldirs/runtime/configure.m4
- src/mca/pinstalldirs/runtime/pmix_pinstalldirs_runtime.c
This is part of a multi-project effort, a similar PR will be created in OpenPMIX and OMPI. The goal of each of these changes is the same: instead of using build-time generated prefix that ignore a project rebase, take the prefix from the shared library of each project and derive the necessary paths from it. The user can however overwrite this using the environment variables, and the configuration files.
> Extract the install prefix from the shared library.

- src/util/pmix_cmd_line.c
- src/util/pmix_cmd_line.h
PMIx supports forward/set, unset, append, and prepend of environmental variables. However, the cmd line processor wasn't setup to handle cmd line options for that purpose. Extend it to provide such support.
Forward (-x) of envars can be just the envar name (to pickup the local value and
forward it), or can be envar=value to set the envar to a specific value.
Unset (--unset) takes just the name of the envar.
Append (--append-env) takes two arguments:
* the name of the envar, appended with a "[c]" where the 'c' is the character
to be used as the separator between envar values
* the value to be appended So it looks like "--append-env FOO[:] 20"
Prepend (--prepend-env) behaves exactly like append except it prepends the
value to whatever current envar value it finds
Multiple instances of any …
> Extend cmd line processor to deal with envar ops

- src/util/Makefile.am
Run the convert-help.py script when the resulting
pmix_show_help_content.c file is missing.
> Only run the show-help converter when necessary

- src/util/pmix_cmd_line.c
If we see an error when processing the request, then output the error to stderr. Otherwise, output all other help requests to stdout.
> Use stdout instead of stderr for help output

- .github/workflows/run-xversion.yml
- VERSION
- autogen.pl
- config/pmix.m4
- configure.ac
- docs/conf.py
- docs/developers/prerequisites.rst
- docs/installing-pmix/quickstart.rst
PMIx now requires Python to build when:
* in a Git clone for building:
* the attribute dictionary (pmix_dictionary.h)
* the show-help in-memory text (pmix_show_help_content.c)
* Python bindings are requested
Check for an adequate Python version for these cases.
> Add explicit test for Python >= v3.7 in configure

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/server/pmix_server.c
The server's callback functions are expected to be executed in the host's progress thread. However, it is possible that the host could execute it in the server's upcall to them - we ask that they don't, but no guarantee. So in the interest of protecting against that scenario, and to minimize time spent in their progress thread, ensure we threadshift the callback function before processing it.
> Ensure to threadshift callback functions

- .github/workflows/run-xversion.yml
Transfer the xversion tests to GitHub actions, removing dependency on stale IBM docker support. Allows master branch to build/run.
> Update xversion CI

- src/include/pmix_globals.c
- src/include/pmix_globals.h
- src/server/pmix_server.c
- test/simple/simptool.c
Continue work on threadshifting all callbacks from the host. Note that even a cbfunc that just sends a message to a client must be threadshifted as the "send" routine appends the message to that peer's queue - which is a global value.
> Ensure more upcall cbfuncs threadshift

- VERSION
- config/pmix.m4
- src/util/Makefile.am
Decrease the minimum required Python version to 3.6. Ensure we cleanup the pmix_show_help_content.c file when executing "make clean".
> Decrease min Py version to 3.6

- src/event/pmix_event_notification.c
- src/include/pmix_globals.c
- src/include/pmix_globals.h
This is a non-blocking API, and it accesses
internal objects - so it must be threadshifted
prior to execution.
> Threadshift the PMIx_Notify_event API

- include/pmix_common.h.in
Used in spawn to request that the entire environment at the launcher be forwarded to all processes being spawned. Note that we don't take the client's environ because it probably contains a bunch of proc-specific envars and we don't want to create confusion.
> Add a PMIX_FWD_ENVIRONMENT attribute

- config/pmix.m4
- config/pmix_config_threads.m4
- src/runtime/pmix_progress_threads.c
We use the pthread_setaffinity_np function if it is found in the standard pthread library. Apparently, however, some folks split the definition of that function from pthreads.h into a separate header, even though they leave the function itself in the pthread library. Go figure.
> Check for pthread_np.h header

- src/client/pmix_client.c
- src/client/pmix_client_connect.c
- src/event/pmix_event_notification.c
Set a few more server fields when client is operating as a singleton. When the connect function is attempting to retrieve job-level info, check both the server and local GDS components if necessary. Calling PMIx_Notify_event with a NULL callback function indicates the user is requesting a blocking operation, so support that request.
> Provide better singleton support and support blocking event notify

- src/server/pmix_server.c
- src/tool/pmix_tool.c
The pmix_cb_t destructor will release the info
array if the infocopy field is set to true.
> Ensure cleanup of allocated pmix_info_t

- docs/how-things-work/sets_groups/group_construct.rst
- include/pmix_common.h.in
Correct the group bootstrap procedure descriptions to indicate that "add members" must call group_construct.
> Cleanup some group docs

- src/common/pmix_iof.c
- src/mca/plog/stdfd/plog_stdfd.c
- src/mca/ptl/base/ptl_base_connect.c
- src/tool/pmix_tool.c
- src/util/pmix_show_help.c
The show-help system is routed thru the IOF subsystem for local output. However, if a show-help is generated prior to the IOF being fully setup, then we need to output the message directly thru stderr. Manage the "enabled" flags to ensure that happens.
> Prevent show-help from using IOF too soon

- config/pmix.m4
We treat a NULL string as boolean "true", which means that the show-load-errors param was defaulting to "all". Change the default configuration option --with-show-load-errors to be "none" so we avoid that behavior.
Refs https://github.com/open-mpi/ompi/issues/13314
> Change default show-load-errors to "none"

- src/mca/base/pmix_mca_base_component_repository.c
Hide the warnings about bad prefixes behind a verbosity check - only active if show-load-errors is set as well.
> Only report bad prefix if verbose requested

- src/client/pmix_client.c
- src/server/pmix_server.c
Need to provide a callback function so that the notify procedure can correctly release the code for the next step in debugger rendezvous
> Correct client notify of ready for debugger

- config/pmix.m4
- include/pmix_common.h.in
- src/tool/pmix_tool.c
- src/util/Makefile.am
- src/util/pmix_fd.c
- src/util/pmix_fd.h
- src/util/pmix_pty.c
- src/util/pmix_tty.c
- src/util/pmix_tty.h
Add some common tty support functions for handling terminal attributes and window sizes. Expose atomistic utilities for pty creation. Add a dup2 abstracion to remove clutter elsewhere.
> Continue work on pty support

- src/client/pmix_client.c
- src/runtime/pmix_params.c
- src/runtime/pmix_rte.h
The length of time we wait for client finalize to be ack'd by the server is pretty arbitrary - the timeout is there just to avoid having a client "hang" forever if the server is stuck. So let the user adjust the time via MCA param in the case where they need a long time, and set the default to something higher (i.e., 10 sec) than what we were using just in case they have a heavily loaded server.
Refs: https://github.com/open-mpi/ompi/issues/13344
> Parameterize client finalize timeout

- src/common/pmix_iof.c
Currently, setting an output file successfully creates the directory on one process, but the rest then detect an already existing directory. PMIX reports the error and continues, but the output from those processes is lost (even to the standard shared output).
> Don't fail when PMIX_IOF_OUTPUT_TO_FILE directory exists

- src/include/pmix_globals.h
- src/mca/gds/hash/gds_hash.c
- src/mca/gds/hash/gds_utils.c
- src/mca/gds/hash/process_arrays.c
- src/runtime/pmix_finalize.c
- src/runtime/pmix_init.c
- src/runtime/pmix_params.c
- src/runtime/pmix_rte.h
- src/server/pmix_server_resolve.c
We strip FQDNs by default because of the inherent problem of interacting with users, who generally don't like typing all that extra stuff. However, that creates a problem when being provided FQDN input during things like nspace registration.
So add an MCA param to control the strip operation instead of only switching it on/off via info directing during init. Add logic to the nspace registration process to perform the strip and add aliases (for the case where the host failed to provide them).
Refs #3652
> Provide better FQDN support

- include/pmix_common.h.in
- src/client/pmix_client.c
- src/include/pmix_globals.c
- src/mca/ptl/base/base.h
- src/mca/ptl/base/ptl_base_connection_hdlr.c
- src/mca/ptl/base/ptl_base_fns.c
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_listener.c
- src/server/pmix_server.c
Provide the ability to include/exclude connections from tools whose user IDs are different from that of the server (i.e., "foreign" tools). Add an attribute to direct that behavior, default to "exclude". If we allow foreign tools, then modify the rendezvous file permissions to allow read by others. Track both the real user/group IDs vs the effective ones in case someone wants to check both. Pass more information up to the server client_connected2 and tool_connection upcalls so the server can make more informed decisions.
> Extend authentication support

- src/mca/ptl/base/base.h
- src/mca/ptl/base/help-ptl-base.txt
- src/mca/ptl/base/ptl_base_frame.c
- src/mca/ptl/base/ptl_base_listener.c
- src/server/pmix_server.c
- src/tool/pmix_tool.c
Default to using the loopback interface unless remote connections are specified - in which case, reject any loopback interfaces. Provide useful show-help messages when no valid interfaces are available. If no remote connection directive is given, and no loopback interfaces are available, then accept a non-loopback interface.
> Improve selection of interfaces

- src/common/pmix_pfexec.c
- src/mca/base/pmix_mca_base_var.c
A definition of `MAXPATHLEN` is not a mandatory part of the POSIX standard, and is not defined for [GNU hurd](https://www.gnu.org/software/hurd/) operating system, where `<sys/param.h>` is not available.
cf. https://www.gnu.org/software/hurd/community/gsoc/project_ideas/maxpath.html
for further context.
But it is difficult to use `getcwd` without `MAXPATHLEN`, so set a default value if it has not been defined in `<sys/param.h>`.
This allows openpmix to build for hurd.
The patch is taken from debian,
https://salsa.debian.org/science-team/pmix/-/blob/e29db6a5b8e523a3b5e0d80922d5958a0d8e0d07/debian/patches/hurd-fix.patch
and has been successfully tested in debian hurd builds, e.g.
https://buildd.debian.org/status/fetch.php?pkg=pmix&arch=hurd-amd64&ver=6.0.0-3&stamp=1756199722&raw=0
Closes: …
> define default MAXPATHLEN if not defined by system

- src/mca/pcompress/zlib/compress_zlib.c
- src/mca/pcompress/zlibng/compress_zlibng.c
We were mistakenly comparing the size of the working buffer to the input size and not compressing if the working buffer was larger. However, zlib _always_ uses a larger working buffer, and so this prevented us from actually compressing.
Compare the size of the resulting compressed data to the input data and don't use the compressed block if it isn't smaller - it can happen, though probably rare.
> Fix compression components
